FROM docker.io/cloudflare/sandbox:0.12.10-python

ENV COMMAND_TIMEOUT_MS=600000
ENV NODE_EXTRA_CA_CERTS=/etc/cloudflare/certs/cloudflare-containers-ca.crt
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

EXPOSE 3000
