import { composioToolkitCatalogueSchema } from "../src/schema.ts";

const PROVIDER_ID_PATTERN = /^[A-Za-z0-9_][A-Za-z0-9._-]*$/;
const TOOLKIT_FILE_NAME_PATTERN = /^[A-Za-z0-9_][A-Za-z0-9._-]*\.json$/;

export function assertSafeProviderId(providerId) {
  if (!PROVIDER_ID_PATTERN.test(providerId) || providerId.includes("..")) {
    throw new Error(`Unsafe Composio toolkit id "${providerId}"`);
  }
}

export function toolkitFileName(providerId) {
  assertSafeProviderId(providerId);

  return `${providerId}.json`;
}

export function validateManifest(manifest) {
  return composioToolkitCatalogueSchema.parse({ toolkits: manifest });
}

export function buildToolkitFiles(manifest) {
  const files = new Map();

  for (const providerId of Object.keys(manifest).sort()) {
    files.set(toolkitFileName(providerId), `${JSON.stringify(manifest[providerId], null, "\t")}\n`);
  }

  return files;
}

export function buildDataIndexSource(providerIds) {
  const lines = [
    "// Generated by scripts/sync-composio-toolkits.mjs. Do not edit by hand.",
    'import type { UnparsedComposioToolkitCatalogue } from "../schema.js";',
  ];

  providerIds.forEach((providerId, index) => {
    lines.push(
      `import toolkit${index} from "./toolkits/${toolkitFileName(providerId)}" with { type: "json" };`,
    );
  });

  lines.push("", "const catalogue: UnparsedComposioToolkitCatalogue = {", "  toolkits: {");

  providerIds.forEach((providerId, index) => {
    lines.push(`    ${JSON.stringify(providerId)}: toolkit${index},`);
  });

  lines.push("  },", "};", "", "export default catalogue;", "");

  return lines.join("\n");
}

export function buildProviderIdsSource(providerIds) {
  return `${JSON.stringify(providerIds, null, "\t")}\n`;
}

export function listStaleToolkitFiles(fileNames, manifest) {
  const expected = new Set(Object.keys(manifest).map(toolkitFileName));

  return fileNames
    .filter((fileName) => TOOLKIT_FILE_NAME_PATTERN.test(fileName) && !expected.has(fileName))
    .sort();
}
