packages:
  - packages/*
  - apps/*

allowBuilds:
  better-sqlite3: true
  core-js: false
  core-js-pure: false
  esbuild: false
  protobufjs: false
  sharp: false
  workerd: false

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@4.20260523.1'
  - '@scalar/client-side-rendering@0.1.12'
  - '@scalar/hono-api-reference@0.10.19'
  - '@scalar/schemas@0.3.2'
  - '@scalar/types@0.12.2'
  - '@tanstack/query-core@5.100.13'
  - '@tanstack/query-devtools@5.100.13'
  - '@tanstack/react-query-devtools@5.100.13'
  - '@tanstack/react-query@5.100.13'

onlyBuiltDependencies:
  - better-sqlite3
