packages:
  - packages/*
  - apps/*

allowBuilds:
  better-sqlite3: true
  core-js: false
  core-js-pure: false
  esbuild: false
  protobufjs: false
  sharp: false
  workerd: false

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@4.20260523.1'
  - '@scalar/client-side-rendering@0.1.12'
  - '@scalar/hono-api-reference@0.10.19'
  - '@scalar/schemas@0.3.2'
  - '@scalar/types@0.12.2'
  - '@tanstack/query-core@5.100.13'
  - '@tanstack/query-devtools@5.100.13'
  - '@tanstack/react-query-devtools@5.100.13'
  - '@tanstack/react-query@5.100.13'
  - '@aws-sdk/client-bedrock@3.1057.0'
  - '@aws-sdk/client-s3@3.1057.0'
  - '@aws-sdk/credential-provider-ini@3.972.46'
  - '@aws-sdk/credential-provider-node@3.972.47'
  - '@aws-sdk/s3-request-presigner@3.1057.0'
  - '@aws-sdk/token-providers@3.1057.0'
  - '@cloudflare/workers-types@4.20260530.1'

onlyBuiltDependencies:
  - better-sqlite3
