import type {
  HardwareOption,
  HostManifest,
  ProviderManifest,
  RegionOption,
  TrainerManifest,
} from "@ngriffin_uk/polychat-schemas";

export const HF_JOB_FLAVOURS: HardwareOption[] = [
  {
    id: "t4-medium",
    label: "T4 (16 GB)",
    accelerator: "nvidia-t4",
    count: 1,
    memoryGb: 16,
    hourlyUsd: 0.6,
  },
  {
    id: "a10g-large",
    label: "A10G (24 GB)",
    accelerator: "nvidia-a10g",
    count: 1,
    memoryGb: 24,
    hourlyUsd: 1.5,
  },
  {
    id: "a10g-largex4",
    label: "4× A10G (96 GB)",
    accelerator: "nvidia-a10g",
    count: 4,
    memoryGb: 96,
    hourlyUsd: 5,
  },
  {
    id: "l4x1",
    label: "L4 (24 GB)",
    accelerator: "nvidia-l4",
    count: 1,
    memoryGb: 24,
    hourlyUsd: 0.8,
  },
  {
    id: "l40sx1",
    label: "L40S (48 GB)",
    accelerator: "nvidia-l40s",
    count: 1,
    memoryGb: 48,
    hourlyUsd: 1.8,
  },
  {
    id: "l40sx4",
    label: "4× L40S (192 GB)",
    accelerator: "nvidia-l40s",
    count: 4,
    memoryGb: 192,
    hourlyUsd: 8.3,
  },
  {
    id: "a100-large",
    label: "A100 (80 GB)",
    accelerator: "nvidia-a100",
    count: 1,
    memoryGb: 80,
    hourlyUsd: 2.5,
  },
  {
    id: "a100x4",
    label: "4× A100 (320 GB)",
    accelerator: "nvidia-a100",
    count: 4,
    memoryGb: 320,
    hourlyUsd: 10,
  },
  {
    id: "a100x8",
    label: "8× A100 (640 GB)",
    accelerator: "nvidia-a100",
    count: 8,
    memoryGb: 640,
    hourlyUsd: 20,
  },
  {
    id: "rtx-pro-6000",
    label: "RTX PRO 6000 (96 GB)",
    accelerator: "nvidia-rtx-pro-6000",
    count: 1,
    memoryGb: 96,
    hourlyUsd: 2.75,
  },
  {
    id: "h200",
    label: "H200 (141 GB)",
    accelerator: "nvidia-h200",
    count: 1,
    memoryGb: 141,
    hourlyUsd: 5,
  },
  {
    id: "h200x4",
    label: "4× H200 (564 GB)",
    accelerator: "nvidia-h200",
    count: 4,
    memoryGb: 564,
    hourlyUsd: 20,
  },
  {
    id: "h200x8",
    label: "8× H200 (1128 GB)",
    accelerator: "nvidia-h200",
    count: 8,
    memoryGb: 1128,
    hourlyUsd: 40,
  },
];

export const HF_ENDPOINT_REGIONS: RegionOption[] = [
  { id: "aws:eu-west-1", label: "AWS Ireland", jurisdiction: "eu" },
  { id: "aws:us-east-1", label: "AWS N. Virginia", jurisdiction: "us" },
  { id: "gcp:europe-west4", label: "Google Cloud Netherlands", jurisdiction: "eu" },
  { id: "gcp:us-east4", label: "Google Cloud Virginia", jurisdiction: "us" },
  { id: "azure:eastus", label: "Azure East US", jurisdiction: "us" },
];

export const HF_ENDPOINT_INSTANCES: HardwareOption[] = [
  {
    id: "nvidia-t4:x1",
    label: "T4 (16 GB)",
    accelerator: "nvidia-t4",
    count: 1,
    memoryGb: 16,
    hourlyUsd: 0.5,
  },
  {
    id: "nvidia-l4:x1",
    label: "L4 (24 GB)",
    accelerator: "nvidia-l4",
    count: 1,
    memoryGb: 24,
    hourlyUsd: 0.8,
  },
  {
    id: "nvidia-a10g:x1",
    label: "A10G (24 GB)",
    accelerator: "nvidia-a10g",
    count: 1,
    memoryGb: 24,
    hourlyUsd: 1,
  },
  {
    id: "nvidia-l4:x4",
    label: "4× L4 (96 GB)",
    accelerator: "nvidia-l4",
    count: 4,
    memoryGb: 96,
    hourlyUsd: 3.8,
  },
  {
    id: "nvidia-l40s:x1",
    label: "L40S (48 GB)",
    accelerator: "nvidia-l40s",
    count: 1,
    memoryGb: 48,
    hourlyUsd: 1.8,
  },
  {
    id: "nvidia-l40s:x4",
    label: "4× L40S (192 GB)",
    accelerator: "nvidia-l40s",
    count: 4,
    memoryGb: 192,
    hourlyUsd: 8.3,
  },
  {
    id: "nvidia-a100:x1",
    label: "A100 (80 GB)",
    accelerator: "nvidia-a100",
    count: 1,
    memoryGb: 80,
    hourlyUsd: 2.5,
  },
  {
    id: "nvidia-a100:x4",
    label: "4× A100 (320 GB)",
    accelerator: "nvidia-a100",
    count: 4,
    memoryGb: 320,
    hourlyUsd: 10,
  },
  {
    id: "nvidia-h200:x1",
    label: "H200 (141 GB)",
    accelerator: "nvidia-h200",
    count: 1,
    memoryGb: 141,
    hourlyUsd: 5,
  },
  {
    id: "nvidia-h200:x8",
    label: "8× H200 (1128 GB)",
    accelerator: "nvidia-h200",
    count: 8,
    memoryGb: 1128,
    hourlyUsd: 40,
  },
];

export const HF_JOBS_TRAINER: TrainerManifest = {
  id: "huggingface-jobs",
  name: "Hugging Face Jobs",
  description:
    "Runs the Polychat TRL recipe on Hub GPUs, reading the base from its pinned commit and pushing results to a private repository in your organisation.",
  methods: [
    "sft",
    "dpo",
    "rft",
    "distillation",
    "continued_pretraining",
    "embedding",
    "vision_sft",
    "merge",
    "quantise",
  ],
  adaptations: ["lora", "qlora", "full"],
  datasetShapes: ["messages", "preference", "prompt_grader", "text", "retrieval", "image_text"],
  graderKinds: ["exact", "contains", "regex", "json_schema", "numeric"],
  bases: { kind: "hub", models: ["*"], maxParameters: null },
  hardware: HF_JOB_FLAVOURS,
  regions: [{ id: "us", label: "Hugging Face (US)", jurisdiction: "us" }],
  output: "hub",
  pricing: { unit: "gpu_hour", usd: null, note: "Per-second billing at the flavour's hourly rate" },
};

export const HF_ENDPOINTS_HOST: HostManifest = {
  id: "huggingface-endpoints",
  name: "Inference Endpoints",
  description:
    "Dedicated vLLM deployment of a pinned Hub commit on AWS, Google Cloud or Azure, with scale-to-zero and private access.",
  shapes: ["dedicated"],
  weights: "hub",
  adapters: false,
  scaleToZero: true,
  weightsVerified: true,
  retention: "zero",
  engines: ["vllm", "sglang"],
  quantisations: ["none", "fp8", "awq", "gptq"],
  hardware: HF_ENDPOINT_INSTANCES,
  regions: HF_ENDPOINT_REGIONS,
  architectures: ["*"],
  maxParameters: null,
  pricing: { unit: "gpu_hour", usd: null, note: "Per-minute billing while replicas run" },
};

export const HF_INFERENCE_HOST: HostManifest = {
  id: "huggingface-inference",
  name: "Inference Providers",
  description:
    "Serverless per-token routing to Together, Fireworks, Cerebras, SambaNova and others for models they already serve.",
  shapes: ["serverless"],
  weights: "catalogue",
  adapters: false,
  scaleToZero: true,
  weightsVerified: false,
  retention: "provider",
  engines: ["provider"],
  quantisations: ["none"],
  hardware: [],
  regions: [{ id: "global", label: "Routed by Hugging Face", jurisdiction: "global" }],
  architectures: ["*"],
  maxParameters: null,
  pricing: { unit: "million_tokens", usd: null, note: "Billed per token by the routed provider" },
};

export const HUGGINGFACE_MANIFEST: ProviderManifest = {
  id: "huggingface",
  name: "Hugging Face",
  vendor: "Hugging Face",
  description:
    "Source for open models and datasets, private repositories for your outputs, Jobs for training and Inference Endpoints for hosting.",
  docsUrl: "https://huggingface.co/docs/hub",
  connection: {
    fields: [
      {
        key: "token",
        label: "Access token",
        kind: "secret",
        required: true,
        help: "A write token, or a fine-grained token with write access to the organisation's repositories, Jobs and Inference Endpoints.",
      },
      {
        key: "namespace",
        label: "Organisation",
        kind: "text",
        required: true,
        help: "The account or organisation that owns and pays for jobs, output repositories and endpoints.",
      },
      {
        key: "endpointRegion",
        label: "Default endpoint location",
        kind: "select",
        required: false,
        options: HF_ENDPOINT_REGIONS.map((region) => ({ value: region.id, label: region.label })),
      },
    ],
  },
  source: true,
  store: { id: "huggingface-repo", name: "Private Hub repository", versioned: true },
  trainers: [HF_JOBS_TRAINER],
  hosts: [HF_ENDPOINTS_HOST, HF_INFERENCE_HOST],
};
