import type { CatalogRecipe } from "./shared";
import { RECIPE_CONNECTOR_TOOL, reviewInstructionsField } from "./shared";

export const configuredComposioRecipes: CatalogRecipe[] = [
	{
		id: "metabase-analytics",
		title: "Metabase Analytics",
		summary: "Find dashboards and questions, run queries, and explain business metrics.",
		description:
			"Uses Metabase search, metadata, dashboard, card, dataset, and query APIs for repeatable analysis without changing BI content.",
		kind: "integrate",
		category: "Productivity",
		featured: false,
		estimatedSetupMinutes: 4,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "metabase",
				providerId: "metabase",
				name: "Metabase",
				description: "Searches BI content and executes saved or ad-hoc analytics queries.",
				requiresConnection: true,
				operationIds: [
					"METABASE_GET_API_SEARCH",
					"METABASE_GET_API_ACTIVITY_POPULAR_ITEMS",
					"METABASE_GET_API_ACTIVITY_RECENT_VIEWS",
					"METABASE_GET_DASHBOARD_BY_ID",
					"METABASE_GET_DASHBOARD_RELATED",
					"METABASE_GET_API_CARD_ID",
					"METABASE_GET_CARD_QUERY_METADATA",
					"METABASE_CREATE_CARD_QUERY1",
					"METABASE_POST_DASHBOARD_QUERY",
					"METABASE_POST_API_DATASET",
					"METABASE_POST_API_DATASET_PIVOT",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Ask a business question",
				description: "Explore Metabase data from chat.",
			},
			{
				type: "schedule",
				label: "Recurring metric review",
				description: "Run a saved read-only analytics review.",
			},
		],
		actions: [
			"Discover relevant dashboards, cards, and collections",
			"Run saved card, dashboard, dataset, and pivot queries",
			"Explain results with source links and query context",
		],
		setupPrompt:
			"Set up Metabase Analytics. Ask which databases, collections, dashboards, cards, filters, metrics, and reporting cadence to use. Use only the enabled read and query operations; explain query assumptions and do not change Metabase content.",
		configurationFields: [
			{
				key: "collectionIds",
				label: "Collections",
				type: "string_list",
				placeholder: "Collection IDs or names",
			},
			{
				key: "dashboardIds",
				label: "Dashboards",
				type: "string_list",
				placeholder: "Dashboard IDs or names",
			},
			{
				key: "metricQuestions",
				label: "Metric questions",
				type: "textarea",
				placeholder: "Revenue, activation, retention, operations, or other KPIs",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "metabase-content-studio",
		title: "Metabase Content Studio",
		summary: "Create and maintain Metabase dashboards, cards, collections, and subscriptions.",
		description:
			"Uses Metabase content lifecycle APIs to create, copy, update, organise, subscribe, revert, and delete BI assets after review.",
		kind: "integrate",
		category: "Productivity",
		featured: false,
		estimatedSetupMinutes: 5,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "metabase",
				providerId: "metabase",
				name: "Metabase",
				description: "Manages dashboards, cards, collections, subscriptions, and revisions.",
				requiresConnection: true,
				operationIds: [
					"METABASE_POST_API_DASHBOARD",
					"METABASE_UPDATE_DASHBOARD",
					"METABASE_CREATE_DASHBOARD_COPY",
					"METABASE_DELETE_DASHBOARD",
					"METABASE_POST_API_CARD",
					"METABASE_PUT_API_CARD_ID",
					"METABASE_POST_API_CARD_ID_COPY",
					"METABASE_DELETE_CARD",
					"METABASE_POST_API_COLLECTION",
					"METABASE_PUT_API_COLLECTION_ID",
					"METABASE_POST_API_CARDS_MOVE",
					"METABASE_METABASE_POST_API_EE_METABOT_TOOLS_CREATE_DASH_SUB",
					"METABASE_POST_API_REVISION_REVERT",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Maintain BI content",
				description: "Create or update reviewed Metabase assets.",
			},
		],
		actions: [
			"Create, copy, update, move, and organise dashboards and cards",
			"Create dashboard subscriptions and manage collections",
			"Revert or delete assets only after exact confirmation",
		],
		setupPrompt:
			"Set up Metabase Content Studio. Ask for target collections, naming rules, owners, dashboard layout, card definitions, and subscription recipients. Preview every mutation. Require explicit confirmation before deleting or reverting anything.",
		configurationFields: [
			{
				key: "targetCollection",
				label: "Target collection",
				type: "text",
				placeholder: "Collection ID or name",
			},
			{
				key: "contentStandards",
				label: "Content standards",
				type: "textarea",
				placeholder: "Naming, descriptions, owners, filters, and layout rules",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "nasa-data-explorer",
		title: "NASA Data Explorer",
		summary:
			"Research astronomy, Earth events, space weather, missions, imagery, and scientific datasets.",
		description:
			"Combines NASA APOD, EONET, DONKI, EPIC, NEO, Mars, POWER, TechPort, OSDR, CMR, and publication search tools.",
		kind: "integrate",
		category: "Students",
		featured: false,
		estimatedSetupMinutes: 3,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "nasa",
				providerId: "nasa",
				name: "NASA",
				description:
					"Searches NASA science, Earth observation, mission, imagery, and publication data.",
				requiresConnection: true,
				operationIds: [
					"NASA_GET_APOD",
					"NASA_GET_EONET_EVENTS",
					"NASA_GET_EONET_EVENT",
					"NASA_GET_DONKI_NOTIFICATIONS",
					"NASA_GET_DONKI_SOLAR_FLARES",
					"NASA_GET_DONKI_GST",
					"NASA_BROWSE_NEO",
					"NASA_SEARCH_NEAR_EARTH_OBJECTS",
					"NASA_GET_NEO_LOOKUP",
					"NASA_GET_MARS_ROVER_PHOTOS",
					"NASA_GET_EPIC_NATURAL",
					"NASA_GET_POWER_DAILY",
					"NASA_QUERY_EXOPLANET_ARCHIVE",
					"NASA_SEARCH_OSDR",
					"NASA_QUERY_CMR_COLLECTIONS",
					"NASA_QUERY_CMR_GRANULES",
					"NASA_SEARCH_CITATIONS",
					"NASA_SEARCH_PUBSPACE_DOCUMENTS",
					"NASA_SEARCH_TECHTRANSFER_SOFTWARE",
					"NASA_GET_TECHPORT_PROJECT",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Explore NASA data",
				description: "Ask a scientific or space-data question.",
			},
			{
				type: "schedule",
				label: "Space and Earth watch",
				description: "Track selected read-only NASA feeds.",
			},
		],
		actions: [
			"Explore live Earth events, space weather, NEOs, imagery, and Mars data",
			"Search mission, biological, climate, exoplanet, and Earth-observation datasets",
			"Find publications, citations, projects, and technology-transfer software",
		],
		setupPrompt:
			"Set up NASA Data Explorer. Ask which subjects, locations, missions, date ranges, datasets, and alert thresholds matter. Cite dataset identifiers and timestamps, distinguish observations from interpretation, and use only the enabled read operations.",
		configurationFields: [
			{
				key: "researchTopics",
				label: "Research topics",
				type: "string_list",
				placeholder: "Space weather, wildfires, Mars, exoplanets, climate",
			},
			{
				key: "locations",
				label: "Locations",
				type: "string_list",
				placeholder: "Coordinates, regions, or observatories",
			},
			{
				key: "dateRange",
				label: "Date range",
				type: "text",
				placeholder: "Today, last 30 days, or an exact range",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "nasdaq-market-research",
		title: "Nasdaq Market Research",
		summary: "Research quotes, analyst ratings, dividends, and Nasdaq Data Link tables.",
		description:
			"Uses all configured Nasdaq tools for company price context, analyst sentiment, dividends, table metadata, filtered rows, and bulk data exports.",
		kind: "integrate",
		category: "Finance",
		featured: false,
		estimatedSetupMinutes: 3,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "nasdaq",
				providerId: "nasdaq",
				name: "Nasdaq Data Link",
				description: "Reads quotes, ratings, dividends, and tabular market datasets.",
				requiresConnection: true,
				operationIds: [
					"NASDAQ_GET_REAL_TIME_QUOTE",
					"NASDAQ_GET_ANALYST_RATINGS",
					"NASDAQ_GET_DIVIDEND_HISTORY",
					"NASDAQ_GET_DATATABLE_METADATA",
					"NASDAQ_GET_DATATABLE",
					"NASDAQ_GET_TABLE_ROW",
					"NASDAQ_GET_TABLES_BY_DATE",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Research a market",
				description: "Investigate a company or dataset.",
			},
			{
				type: "schedule",
				label: "Market watch",
				description: "Run a recurring read-only market review.",
			},
		],
		actions: [
			"Compare quote and analyst context",
			"Review dividend history",
			"Explore and export Nasdaq Data Link tables",
		],
		setupPrompt:
			"Set up Nasdaq Market Research. Ask for symbols, datasets, filters, comparison benchmarks, date ranges, and reporting cadence. State data timestamps and limitations. Provide research, not personalised financial advice.",
		configurationFields: [
			{ key: "symbols", label: "Symbols", type: "string_list", placeholder: "AAPL, MSFT, NVDA" },
			{
				key: "datasets",
				label: "Datasets",
				type: "string_list",
				placeholder: "Nasdaq Data Link table codes",
			},
			{
				key: "researchFocus",
				label: "Research focus",
				type: "textarea",
				placeholder: "Price, analyst targets, dividends, comparisons, or data exports",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "new-relic-incident-operations",
		title: "New Relic Incident Operations",
		summary:
			"Investigate telemetry and manage alert policies, channels, conditions, and entity metadata.",
		description:
			"Uses New Relic applications, NRQL, violations, entities, tags, golden signals, alert policies, channels, and condition lifecycle APIs.",
		kind: "integrate",
		category: "Developer",
		featured: false,
		estimatedSetupMinutes: 5,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "new_relic",
				providerId: "new_relic",
				name: "New Relic",
				description: "Investigates telemetry and manages alerting and entity configuration.",
				requiresConnection: true,
				operationIds: [
					"NEW_RELIC_GET_APPLICATIONS",
					"NEW_RELIC_GET_BROWSER_APPLICATIONS",
					"NEW_RELIC_EXECUTE_NRQL_QUERY",
					"NEW_RELIC_GET_ALERTS_VIOLATIONS_JSON",
					"NEW_RELIC_GET_ALERT_POLICIES",
					"NEW_RELIC_GET_ALERT_CHANNELS",
					"NEW_RELIC_GET_ALERT_CONDITIONS",
					"NEW_RELIC_LIST_NRQL_CONDITIONS",
					"NEW_RELIC_CREATE_ALERT_POLICY",
					"NEW_RELIC_UPDATE_ALERT_POLICY",
					"NEW_RELIC_DELETE_ALERT_POLICY",
					"NEW_RELIC_CREATE_ALERT_CHANNEL",
					"NEW_RELIC_UPDATE_ALERT_CHANNEL",
					"NEW_RELIC_DELETE_ALERT_CHANNEL",
					"NEW_RELIC_CREATE_NRQL_CONDITION",
					"NEW_RELIC_CREATE_NRQL_BASELINE_CONDITION",
					"NEW_RELIC_UPDATE_NRQL_CONDITION",
					"NEW_RELIC_UPDATE_NRQL_BASELINE_CONDITION",
					"NEW_RELIC_DELETE_NRQL_CONDITION",
					"NEW_RELIC_ADD_TAGS_TO_ENTITY",
					"NEW_RELIC_REPLACE_TAGS_ON_ENTITY",
					"NEW_RELIC_DELETE_TAG_VALUES_FROM_ENTITY",
					"NEW_RELIC_OVERRIDE_ENTITY_GOLDEN_METRICS",
					"NEW_RELIC_RESET_ENTITY_GOLDEN_METRICS",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Investigate or change observability",
				description: "Work an incident or maintain New Relic alerting.",
			},
		],
		actions: [
			"Query telemetry and correlate applications with active violations",
			"Create, update, and delete alert policies, channels, and NRQL conditions",
			"Maintain entity tags and golden metrics after review",
		],
		setupPrompt:
			"Set up New Relic Incident Operations. Ask for account IDs, applications, entity GUIDs, NRQL conventions, alert policy ownership, notification channels, and severity thresholds. Run investigations before proposing changes. Preview all mutations and require exact confirmation before deleting or replacing alerting configuration.",
		configurationFields: [
			{
				key: "accountIds",
				label: "Account IDs",
				type: "string_list",
				placeholder: "New Relic account IDs",
			},
			{
				key: "applications",
				label: "Applications",
				type: "string_list",
				placeholder: "API, web, worker, mobile",
			},
			{
				key: "alertStandards",
				label: "Alert standards",
				type: "textarea",
				placeholder: "Thresholds, naming, runbooks, channels, and ownership",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "npm-package-intelligence",
		title: "npm Package Intelligence",
		summary: "Research packages, versions, downloads, registry changes, and security advisories.",
		description:
			"Uses npm registry metadata, search, download statistics, change feeds, and bulk advisory APIs for dependency research.",
		kind: "integrate",
		category: "Developer",
		featured: false,
		estimatedSetupMinutes: 3,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "npm",
				providerId: "npm",
				name: "npm",
				description: "Searches registry metadata, download trends, change feeds, and advisories.",
				requiresConnection: true,
				operationIds: [
					"NPM_REGISTRY_SEARCH_PACKAGES",
					"NPM_REGISTRY_GET_PACKAGE",
					"NPM_REGISTRY_GET_ROOT",
					"NPM_GET_REGISTRY_META",
					"NPM_GET_REGISTRY_CHANGES",
					"NPM_GET_ALL_PACKAGES_DOWNLOAD_POINT",
					"NPM_GET_DOWNLOAD_COUNTS_POINT",
					"NPM_GET_DOWNLOAD_COUNTS_RANGE_PACKAGE",
					"NPM_GET_DOWNLOAD_RANGE_ALL",
					"NPM_GET_VERSION_DOWNLOADS",
					"NPM_QUERY_BULK_SECURITY_ADVISORIES",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Research a dependency",
				description: "Compare npm packages and versions.",
			},
			{
				type: "schedule",
				label: "Dependency watch",
				description: "Monitor package changes and advisories.",
			},
		],
		actions: [
			"Compare package metadata and adoption",
			"Analyse download trends by package and version",
			"Check dependencies against security advisories and registry changes",
		],
		setupPrompt:
			"Set up npm Package Intelligence. Ask for package names, versions, time windows, usage constraints, and security thresholds. Link findings to exact package versions and advisory identifiers. Do not delete npm tokens in this recipe.",
		configurationFields: [
			{ key: "packages", label: "Packages", type: "string_list", placeholder: "react, zod, hono" },
			{
				key: "versions",
				label: "Versions",
				type: "string_list",
				placeholder: "Pinned or candidate versions",
			},
			{
				key: "evaluationCriteria",
				label: "Evaluation criteria",
				type: "textarea",
				placeholder: "Security, maintenance, adoption, size, compatibility, or licence",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "openweather-briefing",
		title: "OpenWeather Briefing",
		summary: "Track current weather, forecasts, air quality, UV, maps, and weather triggers.",
		description:
			"Combines OpenWeather geocoding, current conditions, forecast, air pollution, UV, station, map, and trigger reads.",
		kind: "automate",
		category: "Home",
		featured: false,
		estimatedSetupMinutes: 3,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "openweather_api",
				providerId: "openweather_api",
				name: "OpenWeather",
				description: "Reads weather, air quality, UV, maps, stations, and configured triggers.",
				requiresConnection: true,
				operationIds: [
					"OPENWEATHER_API_GET_GEOCODING_DIRECT",
					"OPENWEATHER_API_GET_GEOCODING_REVERSE",
					"OPENWEATHER_API_GET_GEOCODING_BY_ZIP",
					"OPENWEATHER_API_GET_CURRENT_WEATHER",
					"OPENWEATHER_API_GET_CIRCLE_CITY_WEATHER",
					"OPENWEATHER_API_GET5_DAY_FORECAST",
					"OPENWEATHER_API_GET_AIR_POLLUTION_CURRENT",
					"OPENWEATHER_API_GET_AIR_POLLUTION_FORECAST",
					"OPENWEATHER_API_GET_AIR_POLLUTION_HISTORY",
					"OPENWEATHER_API_GET_UV_INDEX",
					"OPENWEATHER_API_GET_UV_INDEX_FORECAST",
					"OPENWEATHER_API_GET_UV_INDEX_HISTORY",
					"OPENWEATHER_API_GET_WEATHER_MAP_TILE",
					"OPENWEATHER_API_GET_WEATHER_STATIONS",
					"OPENWEATHER_API_GET_WEATHER_STATION",
					"OPENWEATHER_API_GET_STATION_MEASUREMENTS",
					"OPENWEATHER_API_GET_WEATHER_TRIGGERS",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Ask about conditions",
				description: "Get detailed environmental conditions.",
			},
			{
				type: "schedule",
				label: "Weather briefing",
				description: "Run a recurring weather and air-quality briefing.",
			},
		],
		actions: [
			"Resolve locations accurately",
			"Combine forecast, air-quality, and UV risks",
			"Inspect map, station, and trigger context",
		],
		setupPrompt:
			"Set up OpenWeather Briefing. Ask for locations or coordinates, units, forecast window, air-quality and UV thresholds, and delivery cadence. State observation and forecast timestamps and distinguish measured station data from model forecasts.",
		configurationFields: [
			{
				key: "locations",
				label: "Locations",
				type: "string_list",
				placeholder: "London, home coordinates, travel destinations",
			},
			{
				key: "units",
				label: "Units",
				type: "text",
				placeholder: "metric, imperial, or standard",
				defaultValue: "metric",
			},
			{
				key: "alertThresholds",
				label: "Alert thresholds",
				type: "textarea",
				placeholder: "Rain, wind, heat, cold, AQI, or UV thresholds",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "openweather-station-operations",
		title: "OpenWeather Station Operations",
		summary: "Register, update, inspect, submit measurements to, and remove weather stations.",
		description:
			"Uses the complete OpenWeather station lifecycle for owned stations and measurement submissions.",
		kind: "integrate",
		category: "Home",
		featured: false,
		estimatedSetupMinutes: 4,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "openweather_api",
				providerId: "openweather_api",
				name: "OpenWeather",
				description: "Manages stations and submits owned sensor measurements.",
				requiresConnection: true,
				operationIds: [
					"OPENWEATHER_API_GET_WEATHER_STATIONS",
					"OPENWEATHER_API_GET_WEATHER_STATION",
					"OPENWEATHER_API_GET_STATION_MEASUREMENTS",
					"OPENWEATHER_API_POST_ADD_WEATHER_STATION",
					"OPENWEATHER_API_UPDATE_WEATHER_STATION",
					"OPENWEATHER_API_POST_SUBMIT_STATION_MEASUREMENTS",
					"OPENWEATHER_API_DELETE_WEATHER_STATION",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Manage a station",
				description: "Maintain owned OpenWeather stations and measurements.",
			},
		],
		actions: [
			"Register and inspect stations",
			"Update station metadata and submit measurements",
			"Delete a station only after exact confirmation",
		],
		setupPrompt:
			"Set up OpenWeather Station Operations. Ask for station IDs, names, coordinates, altitude, sensor units, and data provenance. Validate timestamps and units before submitting measurements. Preview all changes and require explicit confirmation before deleting a station.",
		configurationFields: [
			{
				key: "stationIds",
				label: "Station IDs",
				type: "string_list",
				placeholder: "Owned OpenWeather station IDs",
			},
			{
				key: "measurementUnits",
				label: "Measurement units",
				type: "textarea",
				placeholder: "Temperature, pressure, wind, humidity, rain, and snow units",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "plausible-site-analytics",
		title: "Plausible Site Analytics",
		summary: "Analyse traffic, realtime visitors, goals, custom properties, audiences, and trends.",
		description:
			"Uses Plausible sites, teams, goals, custom properties, guests, realtime, aggregate, timeseries, and breakdown APIs.",
		kind: "automate",
		category: "Developer",
		featured: false,
		estimatedSetupMinutes: 3,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "plausible_analytics",
				providerId: "plausible_analytics",
				name: "Plausible Analytics",
				description:
					"Reads site configuration and product analytics across aggregate and time dimensions.",
				requiresConnection: true,
				operationIds: [
					"PLAUSIBLE_ANALYTICS_CHECK_HEALTH",
					"PLAUSIBLE_ANALYTICS_LIST_SITES",
					"PLAUSIBLE_ANALYTICS_GET_SITE",
					"PLAUSIBLE_ANALYTICS_LIST_TEAMS",
					"PLAUSIBLE_ANALYTICS_LIST_GOALS",
					"PLAUSIBLE_ANALYTICS_LIST_CUSTOM_PROPS",
					"PLAUSIBLE_ANALYTICS_LIST_GUESTS",
					"PLAUSIBLE_ANALYTICS_GET_REALTIME_VISITORS",
					"PLAUSIBLE_ANALYTICS_QUERY_STATS",
					"PLAUSIBLE_ANALYTICS_GET_TIMESERIES_STATS",
					"PLAUSIBLE_ANALYTICS_GET_BREAKDOWN_STATS",
					"PLAUSIBLE_ANALYTICS_GET_PLUGIN_CAPABILITIES",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Ask about site traffic",
				description: "Investigate Plausible analytics.",
			},
			{
				type: "schedule",
				label: "Traffic report",
				description: "Run a recurring read-only analytics report.",
			},
		],
		actions: [
			"Compare realtime and historical traffic",
			"Break down acquisition, content, geography, devices, goals, and properties",
			"Review sites, teams, guests, and analytics capabilities",
		],
		setupPrompt:
			"Set up Plausible Site Analytics. Ask for site IDs, goals, custom properties, segments, comparison period, and reporting cadence. Explain filters, metric definitions, and incomplete data. Do not record synthetic events in this analytics recipe.",
		configurationFields: [
			{ key: "siteIds", label: "Sites", type: "string_list", placeholder: "example.com" },
			{
				key: "goals",
				label: "Goals",
				type: "string_list",
				placeholder: "Signup, Purchase, Contact",
			},
			{
				key: "reportFocus",
				label: "Report focus",
				type: "textarea",
				placeholder: "Acquisition, content, conversion, geography, devices, or campaigns",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "plausible-event-recorder",
		title: "Plausible Event Recorder",
		summary: "Record reviewed pageview or custom analytics events in Plausible.",
		description:
			"Uses Plausible event ingestion with site, goal, and custom-property discovery for controlled analytics instrumentation tests.",
		kind: "integrate",
		category: "Developer",
		featured: false,
		estimatedSetupMinutes: 3,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "plausible_analytics",
				providerId: "plausible_analytics",
				name: "Plausible Analytics",
				description: "Validates site analytics configuration and records reviewed events.",
				requiresConnection: true,
				operationIds: [
					"PLAUSIBLE_ANALYTICS_GET_SITE",
					"PLAUSIBLE_ANALYTICS_LIST_GOALS",
					"PLAUSIBLE_ANALYTICS_LIST_CUSTOM_PROPS",
					"PLAUSIBLE_ANALYTICS_RECORD_EVENT",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Record a test event",
				description: "Send a reviewed event to Plausible.",
			},
		],
		actions: [
			"Validate the target site, goal, and properties",
			"Prepare an exact pageview or custom event payload",
			"Record the event only after confirmation",
		],
		setupPrompt:
			"Set up Plausible Event Recorder. Ask for the site domain, event name, page URL, referrer, user-agent context, and custom properties. Show the exact payload and explain its analytics effect before recording it. Never fabricate production user events.",
		configurationFields: [
			{ key: "siteId", label: "Site", type: "text", placeholder: "example.com" },
			{
				key: "eventDefaults",
				label: "Event defaults",
				type: "textarea",
				placeholder: "Allowed test event names, URLs, referrers, and properties",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "polymarket-trading-desk",
		title: "Polymarket Trading Desk",
		summary:
			"Research markets, inspect exposure, preview trades, and manage live orders and positions.",
		description:
			"Uses the complete Polymarket US discovery, market data, portfolio, preview, order placement, modification, cancellation, and position-closing surface.",
		kind: "integrate",
		category: "Finance",
		featured: false,
		estimatedSetupMinutes: 6,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "polymarket_us",
				providerId: "polymarket_us",
				name: "Polymarket US",
				description:
					"Discovers markets and manages the connected account's positions and live orders.",
				requiresConnection: true,
				operationIds: [
					"POLYMARKET_US_SEARCH_MARKETS_AND_EVENTS",
					"POLYMARKET_US_LIST_EVENTS",
					"POLYMARKET_US_GET_EVENT_BY_ID",
					"POLYMARKET_US_GET_EVENT_BY_SLUG",
					"POLYMARKET_US_LIST_MARKETS",
					"POLYMARKET_US_GET_MARKET_BY_ID",
					"POLYMARKET_US_GET_MARKET_BY_SLUG",
					"POLYMARKET_US_GET_MARKET_BBO",
					"POLYMARKET_US_GET_MARKET_BOOK",
					"POLYMARKET_US_GET_MARKET_SETTLEMENT",
					"POLYMARKET_US_LIST_TAGS",
					"POLYMARKET_US_GET_TAG_BY_ID",
					"POLYMARKET_US_GET_TAG_BY_SLUG",
					"POLYMARKET_US_LIST_FEATURED_TAGS",
					"POLYMARKET_US_LIST_SERIES",
					"POLYMARKET_US_GET_SERIES_BY_ID",
					"POLYMARKET_US_LIST_SUBJECTS",
					"POLYMARKET_US_GET_SUBJECT_BY_ID",
					"POLYMARKET_US_GET_SUBJECT_BY_SLUG",
					"POLYMARKET_US_GET_MARKETS_FOR_SUBJECT",
					"POLYMARKET_US_GET_MARKETS_FOR_SUBJECT_BY_SLUG",
					"POLYMARKET_US_LIST_SPORTS",
					"POLYMARKET_US_GET_SPORT_BY_SLUG",
					"POLYMARKET_US_LIST_LEAGUES",
					"POLYMARKET_US_GET_LEAGUE_BY_SLUG",
					"POLYMARKET_US_LIST_EVENTS_FOR_SPORT",
					"POLYMARKET_US_LIST_EVENTS_FOR_LEAGUE",
					"POLYMARKET_US_LIST_EVENTS_FOR_SERIES",
					"POLYMARKET_US_LIST_SPORTS_TEAMS",
					"POLYMARKET_US_LIST_SPORTS_TEAMS_FOR_PROVIDER",
					"POLYMARKET_US_GET_ACCOUNT_BALANCES",
					"POLYMARKET_US_GET_ACTIVITIES",
					"POLYMARKET_US_GET_USER_POSITIONS",
					"POLYMARKET_US_GET_OPEN_ORDERS",
					"POLYMARKET_US_GET_ORDER",
					"POLYMARKET_US_PREVIEW_ORDER",
					"POLYMARKET_US_CREATE_ORDER",
					"POLYMARKET_US_CREATE_MULTIPLE_ORDERS",
					"POLYMARKET_US_MODIFY_ORDER",
					"POLYMARKET_US_MODIFY_MULTIPLE_ORDERS",
					"POLYMARKET_US_CANCEL_ORDER",
					"POLYMARKET_US_CANCEL_MULTIPLE_ORDERS",
					"POLYMARKET_US_CANCEL_ALL_OPEN_ORDERS",
					"POLYMARKET_US_CLOSE_POSITION_ORDER",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Research or manage a market position",
				description: "Use discovery, portfolio, preview, and live order tools.",
			},
		],
		actions: [
			"Discover events, markets, subjects, series, tags, sports, and leagues",
			"Inspect live books, balances, activity, positions, and open orders",
			"Preview, create, modify, cancel, batch, and close orders after exact confirmation",
		],
		setupPrompt:
			"Set up Polymarket Trading Desk. Ask for market interests, maximum position and order sizes, price and slippage limits, time-in-force preferences, and prohibited markets. Always inspect live market data and account exposure, then preview the exact order before any placement. Require explicit confirmation for every create, modify, cancel, batch, or close action. Never imply guaranteed outcomes or provide personalised financial advice.",
		configurationFields: [
			{
				key: "marketInterests",
				label: "Market interests",
				type: "string_list",
				placeholder: "Sports, politics, economics, technology",
			},
			{
				key: "riskLimits",
				label: "Risk limits",
				type: "textarea",
				placeholder: "Maximum order, position, loss, slippage, and market restrictions",
			},
			{
				key: "orderDefaults",
				label: "Order defaults",
				type: "textarea",
				placeholder: "Time in force, maker-only preference, and confirmation format",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "postman-api-lifecycle",
		title: "Postman API Lifecycle",
		summary:
			"Build and maintain API workspaces, specifications, collections, environments, mocks, and monitors.",
		description:
			"Uses Postman's API design and testing lifecycle from workspace discovery through specs, collections, mocks, environments, monitors, and review workflows.",
		kind: "integrate",
		category: "Developer",
		featured: false,
		estimatedSetupMinutes: 6,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "postman",
				providerId: "postman",
				name: "Postman",
				description:
					"Manages API workspaces, definitions, collections, environments, mocks, and monitors.",
				requiresConnection: true,
				operationIds: [
					"POSTMAN_GET_ALL_WORKSPACES",
					"POSTMAN_GET_A_WORKSPACE",
					"POSTMAN_CREATE_A_WORKSPACE",
					"POSTMAN_UPDATE_A_WORKSPACE",
					"POSTMAN_DELETE_A_WORKSPACE",
					"POSTMAN_GET_ALL_APIS",
					"POSTMAN_GET_AN_API",
					"POSTMAN_CREATE_AN_API",
					"POSTMAN_UPDATE_AN_API",
					"POSTMAN_DELETE_AN_API",
					"POSTMAN_GET_ALL_SPECS",
					"POSTMAN_GET_A_SPEC",
					"POSTMAN_CREATE_A_SPEC",
					"POSTMAN_UPDATE_A_SPECS_PROPERTIES",
					"POSTMAN_DELETE_A_SPEC",
					"POSTMAN_IMPORT_OPENAPI",
					"POSTMAN_GENERATE_A_COLLECTION_FROM_SPEC",
					"POSTMAN_GENERATE_SPEC_FROM_COLLECTION",
					"POSTMAN_SYNC_COLLECTION_WITH_SPEC",
					"POSTMAN_SYNC_SPEC_WITH_COLLECTION",
					"POSTMAN_TRANSFORM_COLLECTION_TO_OPENAPI",
					"POSTMAN_GET_ALL_COLLECTIONS2",
					"POSTMAN_CREATE_A_COLLECTION",
					"POSTMAN_UPDATE_PART_OF_A_COLLECTION",
					"POSTMAN_DUPLICATE_A_COLLECTION",
					"POSTMAN_DELETE_A_COLLECTION",
					"POSTMAN_CREATE_A_REQUEST",
					"POSTMAN_UPDATE_A_REQUEST",
					"POSTMAN_CREATE_A_RESPONSE",
					"POSTMAN_UPDATE_A_RESPONSE",
					"POSTMAN_GET_ALL_ENVIRONMENTS",
					"POSTMAN_CREATE_AN_ENVIRONMENT",
					"POSTMAN_UPDATE_AN_ENVIRONMENT",
					"POSTMAN_REPLACE_AN_ENVIRONMENTS_DATA",
					"POSTMAN_DELETE_AN_ENVIRONMENT",
					"POSTMAN_GET_ALL_MOCK_SERVERS",
					"POSTMAN_CREATE_A_MOCK_SERVER",
					"POSTMAN_UPDATE_A_MOCK_SERVER",
					"POSTMAN_PUBLISH_A_MOCK_SERVER",
					"POSTMAN_GET_ALL_MONITORS",
					"POSTMAN_GET_A_MONITOR",
					"POSTMAN_CREATE_A_MONITOR",
					"POSTMAN_UPDATE_A_MONITOR",
					"POSTMAN_RUN_A_MONITOR",
					"POSTMAN_DELETE_MONITOR",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Design or operate an API",
				description: "Work across the Postman API lifecycle.",
			},
		],
		actions: [
			"Create and maintain workspaces, APIs, specifications, collections, requests, and examples",
			"Import, generate, transform, and synchronise OpenAPI and Postman definitions",
			"Manage environments, mocks, and monitors and run reviewed checks",
		],
		setupPrompt:
			"Set up Postman API Lifecycle. Ask for target workspace, API and spec identifiers, source-of-truth rules, environment variable policy, mock visibility, and monitor schedule. Inspect existing resources before changing them. Preview replacements, syncs, imports, and deletions, and require exact confirmation before destructive operations.",
		configurationFields: [
			{ key: "workspaceId", label: "Workspace", type: "text", placeholder: "Postman workspace ID" },
			{ key: "apiIds", label: "APIs", type: "string_list", placeholder: "API IDs or names" },
			{
				key: "sourceOfTruth",
				label: "Source of truth",
				type: "textarea",
				placeholder: "OpenAPI, collection, repository, ownership, and sync direction",
			},
			{
				key: "environmentPolicy",
				label: "Environment policy",
				type: "textarea",
				placeholder: "Variable names, secret handling, and allowed targets",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "postmark-delivery-operations",
		title: "Postmark Delivery Operations",
		summary:
			"Investigate deliverability, maintain templates and streams, and send reviewed templated batches.",
		description:
			"Uses Postmark delivery analytics, message search, bounces, suppressions, templates, message streams, webhooks, inbound rules, spam checks, and batch sending.",
		kind: "integrate",
		category: "Email",
		featured: false,
		estimatedSetupMinutes: 6,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "postmark",
				providerId: "postmark",
				name: "Postmark",
				description:
					"Operates transactional delivery, templates, streams, webhooks, suppressions, and sending.",
				requiresConnection: true,
				operationIds: [
					"POSTMARK_GET_SERVER",
					"POSTMARK_EDIT_SERVER",
					"POSTMARK_GET_DELIVERY_STATS",
					"POSTMARK_GET_OUTBOUND_OVERVIEW",
					"POSTMARK_GET_SENT_COUNTS",
					"POSTMARK_GET_BOUNCE_COUNTS",
					"POSTMARK_GET_BOUNCES",
					"POSTMARK_GET_SPAM_COMPLAINTS",
					"POSTMARK_SEARCH_OUTBOUND_MESSAGES",
					"POSTMARK_SEARCH_INBOUND_MESSAGES",
					"POSTMARK_GET_TRACKED_EMAIL_COUNTS",
					"POSTMARK_GET_EMAIL_OPEN_COUNTS",
					"POSTMARK_GET_CLICK_COUNTS",
					"POSTMARK_LIST_OUTBOUND_MESSAGE_OPENS",
					"POSTMARK_LIST_OUTBOUND_MESSAGE_CLICKS",
					"POSTMARK_GET_EMAIL_CLIENT_USAGE",
					"POSTMARK_GET_BROWSER_USAGE",
					"POSTMARK_GET_BROWSER_PLATFORM_USAGE",
					"POSTMARK_GET_CLICKS_BY_BROWSER_FAMILY",
					"POSTMARK_GET_CLICKS_BY_LOCATION",
					"POSTMARK_GET_OPENS_BY_PLATFORM",
					"POSTMARK_LIST_SUPPRESSIONS",
					"POSTMARK_CREATE_SUPPRESSIONS",
					"POSTMARK_DELETE_SUPPRESSIONS",
					"POSTMARK_LIST_TEMPLATES",
					"POSTMARK_GET_TEMPLATE",
					"POSTMARK_VALIDATE_TEMPLATE",
					"POSTMARK_CHECK_SPAM_SCORE",
					"POSTMARK_CREATE_TEMPLATE",
					"POSTMARK_EDIT_TEMPLATE",
					"POSTMARK_DELETE_TEMPLATE",
					"POSTMARK_LIST_MESSAGE_STREAMS",
					"POSTMARK_GET_MESSAGE_STREAM",
					"POSTMARK_CREATE_MESSAGE_STREAM",
					"POSTMARK_UPDATE_MESSAGE_STREAM",
					"POSTMARK_ARCHIVE_MESSAGE_STREAM",
					"POSTMARK_UNARCHIVE_MESSAGE_STREAM",
					"POSTMARK_LIST_WEBHOOKS",
					"POSTMARK_GET_WEBHOOK",
					"POSTMARK_CREATE_WEBHOOK",
					"POSTMARK_EDIT_WEBHOOK",
					"POSTMARK_DELETE_WEBHOOK",
					"POSTMARK_LIST_INBOUND_RULES",
					"POSTMARK_CREATE_INBOUND_RULE",
					"POSTMARK_DELETE_INBOUND_RULE",
					"POSTMARK_SEND_BATCH_WITH_TEMPLATES",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Investigate or operate transactional email",
				description: "Review delivery or maintain Postmark resources.",
			},
		],
		actions: [
			"Investigate delivery, bounces, complaints, opens, clicks, clients, and geography",
			"Manage suppressions, templates, streams, webhooks, inbound rules, and server settings",
			"Validate content and send reviewed templated batches after recipient confirmation",
		],
		setupPrompt:
			"Set up Postmark Delivery Operations. Ask for server, message streams, sender identities, templates, webhook endpoints, suppression policy, and reporting focus. Never send until the exact template, model data, recipient list, sender, stream, and batch size are shown and confirmed. Require confirmation before deleting, archiving, unsuppressing, or changing server configuration.",
		configurationFields: [
			{ key: "serverId", label: "Server", type: "text", placeholder: "Postmark server ID" },
			{
				key: "messageStreams",
				label: "Message streams",
				type: "string_list",
				placeholder: "outbound, broadcasts, transactional",
			},
			{
				key: "deliveryStandards",
				label: "Delivery standards",
				type: "textarea",
				placeholder: "Bounce, complaint, suppression, sender, and webhook rules",
			},
			{
				key: "sendPolicy",
				label: "Send policy",
				type: "textarea",
				placeholder: "Allowed templates, recipients, batch limits, and required approvals",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "ticketmaster-event-finder",
		title: "Ticketmaster Event Finder",
		summary: "Discover events, venues, attractions, classifications, images, and seating context.",
		description:
			"Uses the complete configured Ticketmaster discovery surface for event planning and comparison.",
		kind: "integrate",
		category: "Travel",
		featured: false,
		estimatedSetupMinutes: 3,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "ticketmaster",
				providerId: "ticketmaster",
				name: "Ticketmaster",
				description:
					"Searches events and resolves attraction, venue, category, imagery, and section-map details.",
				requiresConnection: true,
				operationIds: [
					"TICKETMASTER_GET_EVENTS",
					"TICKETMASTER_GET_EVENT_DETAILS",
					"TICKETMASTER_GET_EVENT_IMAGES",
					"TICKETMASTER_GET_ATTRACTIONS",
					"TICKETMASTER_GET_ATTRACTION_DETAILS2",
					"TICKETMASTER_GET_VENUES",
					"TICKETMASTER_GET_VENUE_DETAILS2",
					"TICKETMASTER_GET_CLASSIFICATIONS",
					"TICKETMASTER_GET_CLASSIFICATION_DETAILS",
					"TICKETMASTER_GET_SEGMENT_DETAILS",
					"TICKETMASTER_GET_GENRE_DETAILS",
					"TICKETMASTER_GET_SUBGENRE_DETAILS",
					"TICKETMASTER_GET_SUGGESTIONS2",
					"TICKETMASTER_GET_SECTION_MAP_IMAGE",
					"TICKETMASTER_EXECUTE_SEASON_TICKETING_COMMAND",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Find an event",
				description: "Search and compare Ticketmaster events.",
			},
		],
		actions: [
			"Search by place, date, performer, team, genre, and classification",
			"Inspect event, attraction, venue, imagery, and seating details",
			"Compare options while preserving source availability and pricing caveats",
		],
		setupPrompt:
			"Set up Ticketmaster Event Finder. Ask for locations, dates, radius, performers or teams, genres, accessibility needs, quantity, and budget. Compare exact event and venue details and state that availability and pricing can change. Do not claim that a ticket has been reserved or purchased.",
		configurationFields: [
			{
				key: "locations",
				label: "Locations",
				type: "string_list",
				placeholder: "London, Manchester, New York",
			},
			{
				key: "dateWindow",
				label: "Date window",
				type: "text",
				placeholder: "This weekend, next month, or exact dates",
			},
			{
				key: "eventInterests",
				label: "Event interests",
				type: "string_list",
				placeholder: "Artists, teams, theatre, comedy, festivals",
			},
			{
				key: "constraints",
				label: "Constraints",
				type: "textarea",
				placeholder: "Budget, accessibility, travel distance, age limits, or seating",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "ticktick-task-operations",
		title: "TickTick Task Operations",
		summary: "Manage TickTick projects and tasks across their complete lifecycle.",
		description:
			"Uses TickTick project and task list, detail, create, update, complete, and delete operations.",
		kind: "integrate",
		category: "To-dos",
		featured: false,
		estimatedSetupMinutes: 3,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "ticktick",
				providerId: "ticktick",
				name: "TickTick",
				description: "Reads and manages projects and tasks through completion or deletion.",
				requiresConnection: true,
				operationIds: [
					"TICKTICK_GET_USER_PROJECT",
					"TICKTICK_GET_PROJECT_BY_ID",
					"TICKTICK_GET_PROJECT_WITH_DATA",
					"TICKTICK_LIST_ALL_TASKS",
					"TICKTICK_GET_TASK_BY_PROJECT_AND_ID",
					"TICKTICK_CREATE_PROJECT",
					"TICKTICK_UPDATE_PROJECT",
					"TICKTICK_DELETE_PROJECT",
					"TICKTICK_CREATE_TASK",
					"TICKTICK_UPDATE_TASK",
					"TICKTICK_COMPLETE_TASK",
					"TICKTICK_DELETE_TASK",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Manage TickTick",
				description: "Review and change projects or tasks.",
			},
		],
		actions: [
			"Inspect projects with their task data",
			"Create, update, and complete projects and tasks",
			"Delete a project or task only after exact confirmation",
		],
		setupPrompt:
			"Set up TickTick Task Operations. Ask for default projects, lists, priorities, tags, due-date rules, reminders, and recurring-task conventions. Confirm exact task and project identifiers before updates. Require explicit confirmation before completing or deleting anything.",
		configurationFields: [
			{
				key: "defaultProjects",
				label: "Default projects",
				type: "string_list",
				placeholder: "Inbox, Work, Personal",
			},
			{
				key: "taskDefaults",
				label: "Task defaults",
				type: "textarea",
				placeholder: "Priority, tags, due dates, reminders, and recurrence",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "typeform-form-operations",
		title: "Typeform Form Operations",
		summary:
			"Build forms and themes, analyse responses, manage media, and operate webhooks and workspaces.",
		description:
			"Uses Typeform's complete configured form, response, file, image, video, theme, webhook, account, and workspace lifecycle.",
		kind: "integrate",
		category: "Productivity",
		featured: false,
		estimatedSetupMinutes: 6,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "typeform",
				providerId: "typeform",
				name: "Typeform",
				description:
					"Creates and maintains forms, responses, media, themes, webhooks, and workspaces.",
				requiresConnection: true,
				operationIds: [
					"TYPEFORM_GET_ABOUT_ME",
					"TYPEFORM_LIST_WORKSPACES",
					"TYPEFORM_GET_WORKSPACE",
					"TYPEFORM_CREATE_ACCOUNT_WORKSPACE",
					"TYPEFORM_CREATE_WORKSPACE",
					"TYPEFORM_UPDATE_WORKSPACE",
					"TYPEFORM_DELETE_WORKSPACE",
					"TYPEFORM_LIST_FORMS",
					"TYPEFORM_GET_FORM",
					"TYPEFORM_CREATE_FORM",
					"TYPEFORM_PATCH_FORM",
					"TYPEFORM_UPDATE_FORM",
					"TYPEFORM_DELETE_FORM",
					"TYPEFORM_GET_FORM_MESSAGES",
					"TYPEFORM_UPDATE_FORM_MESSAGES",
					"TYPEFORM_GET_FORM_RESPONSES",
					"TYPEFORM_GET_ALL_RESPONSE_FILES",
					"TYPEFORM_DELETE_RESPONSES",
					"TYPEFORM_LIST_IMAGES",
					"TYPEFORM_GET_IMAGE_BY_SIZE",
					"TYPEFORM_GET_BACKGROUND_BY_SIZE",
					"TYPEFORM_GET_CHOICE_IMAGE_BY_SIZE",
					"TYPEFORM_CREATE_IMAGE",
					"TYPEFORM_DELETE_IMAGE",
					"TYPEFORM_UPLOAD_VIDEO",
					"TYPEFORM_LIST_THEMES",
					"TYPEFORM_GET_THEME",
					"TYPEFORM_CREATE_THEME",
					"TYPEFORM_PATCH_THEME",
					"TYPEFORM_UPDATE_THEME",
					"TYPEFORM_DELETE_THEME",
					"TYPEFORM_LIST_WEBHOOKS",
					"TYPEFORM_GET_WEBHOOK",
					"TYPEFORM_CREATE_OR_UPDATE_WEBHOOK",
					"TYPEFORM_DELETE_WEBHOOK",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Build or operate a form",
				description: "Work across the Typeform lifecycle.",
			},
		],
		actions: [
			"Create, patch, update, and review forms and respondent messages",
			"Read response data and files and manage images, video, and themes",
			"Operate workspaces and webhooks and delete resources after exact confirmation",
		],
		setupPrompt:
			"Set up Typeform Form Operations. Ask for target workspace, audience, form purpose, questions, logic, branding, respondent messages, webhook targets, and response retention policy. Treat response content and files as potentially sensitive. Preview form, theme, workspace, and webhook changes. Require explicit confirmation before deleting forms, responses, files, themes, webhooks, or workspaces.",
		configurationFields: [
			{
				key: "workspaceId",
				label: "Workspace",
				type: "text",
				placeholder: "Typeform workspace ID",
			},
			{
				key: "formPurpose",
				label: "Form purpose",
				type: "textarea",
				placeholder: "Audience, goals, questions, logic, and completion criteria",
			},
			{
				key: "brandRules",
				label: "Brand rules",
				type: "textarea",
				placeholder: "Theme, imagery, tone, accessibility, and respondent messages",
			},
			{
				key: "dataPolicy",
				label: "Response data policy",
				type: "textarea",
				placeholder: "PII, retention, export, webhook, and deletion rules",
			},
			reviewInstructionsField,
		],
	},
	{
		id: "zeplin-design-handoff",
		title: "Zeplin Design Handoff",
		summary:
			"Review projects and screens, maintain annotations and versions, and manage design tokens and collaborators.",
		description:
			"Uses Zeplin project, connected component, screen, annotation, version, colour, text style, styleguide, and member operations.",
		kind: "integrate",
		category: "Developer",
		featured: false,
		estimatedSetupMinutes: 5,
		enabledTools: [RECIPE_CONNECTOR_TOOL],
		integrations: [
			{
				id: "zeplin",
				providerId: "zeplin",
				name: "Zeplin",
				description:
					"Reviews and maintains design handoff, annotations, versions, tokens, and members.",
				requiresConnection: true,
				operationIds: [
					"ZEPLIN_USERS_GET_PERSONAL_PROJECTS",
					"ZEPLIN_PROJECTS_GET",
					"ZEPLIN_CONNECTED_COMPONENTS_PROJECT_LIST",
					"ZEPLIN_PROJECT_COLORS_LIST",
					"ZEPLIN_PROJECT_COLOR_UPDATE",
					"ZEPLIN_PROJECT_TEXT_STYLES_LIST",
					"ZEPLIN_PROJECT_TEXT_STYLE_UPDATE",
					"ZEPLIN_PROJECTS_MEMBERS_INVITE",
					"ZEPLIN_SCREEN_SECTIONS_LIST",
					"ZEPLIN_SCREEN_SECTION_GET",
					"ZEPLIN_SCREEN_COMPONENTS_LIST",
					"ZEPLIN_SCREEN_VERSIONS_LIST",
					"ZEPLIN_SCREEN_VERSION_GET",
					"ZEPLIN_SCREEN_VERSIONS_CREATE",
					"ZEPLIN_SCREEN_ANNOTATIONS_LIST",
					"ZEPLIN_SCREEN_ANNOTATION_GET",
					"ZEPLIN_SCREEN_ANNOTATIONS_UPDATE",
					"ZEPLIN_SCREEN_ANNOTATION_DELETE",
					"ZEPLIN_STYLEGUIDE_COLORS_LIST",
					"ZEPLIN_STYLEGUIDE_COLOR_CREATE",
					"ZEPLIN_STYLEGUIDE_COLOR_UPDATE",
					"ZEPLIN_STYLEGUIDE_TEXT_STYLES_LIST",
					"ZEPLIN_STYLEGUIDE_TEXT_STYLE_UPDATE",
				],
			},
		],
		triggers: [
			{
				type: "message",
				label: "Review or update design handoff",
				description: "Work with Zeplin projects, screens, tokens, and annotations.",
			},
		],
		actions: [
			"Inspect projects, connected components, screen sections, versions, and annotations",
			"Create screen versions and maintain annotations after review",
			"Maintain colours and text styles and invite collaborators with confirmation",
		],
		setupPrompt:
			"Set up Zeplin Design Handoff. Ask for projects, screen sections, design-system sources, component conventions, annotation policy, token naming, and collaborator roles. Inspect the current version and token state before changes. Preview annotation, version, token, and member changes and require exact confirmation before deleting an annotation or inviting a member.",
		configurationFields: [
			{
				key: "projectIds",
				label: "Projects",
				type: "string_list",
				placeholder: "Zeplin project IDs",
			},
			{
				key: "handoffStandards",
				label: "Handoff standards",
				type: "textarea",
				placeholder: "Components, annotations, states, responsive rules, and versioning",
			},
			{
				key: "tokenStandards",
				label: "Token standards",
				type: "textarea",
				placeholder: "Colour and text-style naming, sources, and allowed changes",
			},
			reviewInstructionsField,
		],
	},
];
