import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("pages/home.tsx"),
  route("/chat", "pages/chat/layout.tsx", [
    route("capabilities", "pages/chat/capabilities.tsx"),
    route("experiences", "pages/chat/experiences.tsx"),
    route("experiences/:experienceId/*", "pages/chat/experience.tsx"),
    route("tools/:toolId", "pages/chat/tool.tsx"),
    route("agents/:agentId", "pages/chat/agent.tsx"),
    route(":completionId?", "pages/chat/index.tsx"),
  ]),
  route("/work", "pages/work/layout.tsx", [
    index("pages/work/index.tsx"),
    route("attention", "pages/work/attention.tsx"),
    route("invitations", "pages/work/invitations.tsx"),
    route(":workspaceId", "pages/work/workspace.tsx"),
    route(":workspaceId/members", "pages/work/members.tsx"),
    route(":workspaceId/governance", "pages/work/governance.tsx"),
    route(":workspaceId/projects/:projectId", "pages/work/project.tsx"),
    route(":workspaceId/projects/:projectId/chat", "pages/work/project-chat.tsx"),
    route(":workspaceId/projects/:projectId/experiences", "pages/work/project-experiences.tsx"),
    route(
      ":workspaceId/projects/:projectId/experiences/:experienceId/*",
      "pages/work/project-experience.tsx",
    ),
    route(":workspaceId/projects/:projectId/library", "pages/work/project-library.tsx"),
    route(":workspaceId/projects/:projectId/sources", "pages/work/project-sources.tsx"),
    route(":workspaceId/projects/:projectId/tasks", "pages/work/project-tasks.tsx"),
    route(":workspaceId/projects/:projectId/tasks/:taskId", "pages/work/project-task.tsx"),
    route(":workspaceId/projects/:projectId/activity", "pages/work/project-activity.tsx"),
    route(":workspaceId/projects/:projectId/outputs/*", "pages/work/project-outputs.tsx"),
    route(":workspaceId/projects/:projectId/tools/:toolId", "pages/work/project-tool.tsx"),
    route(":workspaceId/projects/:projectId/agents/:agentId", "pages/work/project-agent.tsx"),
  ]),
  route("/pets", "pages/pets.tsx"),
  route("/discover", "pages/discover.tsx"),
  route("/pricing", "pages/pricing.tsx"),
  route("/terms", "pages/terms.tsx"),
  route("/privacy", "pages/privacy.tsx"),
  route("/auth/callback", "pages/auth/callback.tsx"),
  route("/auth/verify-magic-link", "pages/auth/verify-magic-link.tsx"),
  route("/profile", "pages/profile.tsx"),
  route("/s/:share_id", "pages/shared/[share_id].tsx"),
  route("/o/:token", "pages/shared/output.tsx"),
  route("*?", "pages/catchall.tsx"),
] satisfies RouteConfig;
