import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("pages/home.tsx"),
  route("/chat", "pages/chat/layout.tsx", [
    route("attention", "pages/chat/attention.tsx"),
    route("files/*", "pages/chat/files.tsx"),
    route("teammates", "pages/chat/teammates.tsx"),
    route("teammates/:teammateId", "pages/chat/teammate.tsx"),
    route("apps/:appId/*", "pages/chat/app.tsx"),
    route("tools/:toolId", "pages/chat/tool.tsx"),
    route(":completionId?", "pages/chat/index.tsx"),
  ]),
  route("/work", "pages/work/layout.tsx", [
    index("pages/work/index.tsx"),
    route("attention", "pages/work/attention.tsx"),
    route("invitations", "pages/work/invitations.tsx"),
    route(":workspaceId", "pages/work/workspace.tsx"),
    route(":workspaceId/members", "pages/work/members.tsx"),
    route(":workspaceId/governance", "pages/work/governance.tsx"),
    route(":workspaceId/projects/:projectId", "pages/work/project.tsx"),
    route(":workspaceId/projects/:projectId/settings", "pages/work/project-settings.tsx"),
    route(":workspaceId/projects/:projectId/chat/:conversationId?", "pages/work/project-chat.tsx"),
    route(":workspaceId/projects/:projectId/teammates", "pages/work/project-teammates.tsx"),
    route(
      ":workspaceId/projects/:projectId/teammates/:teammateId",
      "pages/work/project-teammate.tsx",
    ),
    route(":workspaceId/projects/:projectId/apps/:appId/*", "pages/work/project-app.tsx"),
    route(":workspaceId/projects/:projectId/files/*", "pages/work/project-files.tsx"),
    route(":workspaceId/projects/:projectId/tasks", "pages/work/project-tasks.tsx"),
    route(":workspaceId/projects/:projectId/tasks/:taskId", "pages/work/project-task.tsx"),
    route(":workspaceId/projects/:projectId/activity", "pages/work/project-activity.tsx"),
    route(":workspaceId/projects/:projectId/tools/:toolId", "pages/work/project-tool.tsx"),
  ]),
  route("/pets", "pages/pets.tsx"),
  route("/discover", "pages/discover.tsx"),
  route("/models", "pages/models.tsx"),
  route("/capabilities", "pages/capabilities.tsx"),
  route("/apps", "pages/apps.tsx"),
  route("/pricing", "pages/pricing.tsx"),
  route("/terms", "pages/terms.tsx"),
  route("/privacy", "pages/privacy.tsx"),
  route("/auth/callback", "pages/auth/callback.tsx"),
  route("/auth/verify-magic-link", "pages/auth/verify-magic-link.tsx"),
  route("/profile", "pages/profile.tsx"),
  route("/s/:share_id", "pages/shared/[share_id].tsx"),
  route("/o/:token", "pages/shared/output.tsx"),
  route("*?", "pages/catchall.tsx"),
] satisfies RouteConfig;
