import { DATASET_SHAPE_LABELS, LAWFUL_BASIS_LABELS } from "@ngriffin_uk/polychat-component-models";
import {
  FileDropzone,
  FormDialog,
  FormGrid,
  FormInput,
  FormSection,
  FormSelect,
  FormTextarea,
  Switch,
} from "@ngriffin_uk/polychat-component-ui";
import {
  useEvalSuites,
  useModelPlatformMutations,
  useModelRoutes,
  useModelUpload,
  useUploadPreview,
} from "@ngriffin_uk/polychat-library-react";
import { DATASET_SHAPES, LAWFUL_BASES } from "@ngriffin_uk/polychat-schemas";
import { formatBytes, getErrorMessage } from "@ngriffin_uk/polychat-utility-core";
import { useCallback, useEffect, useState } from "react";

import { runWithToast } from "../../../utils/toast-action.js";
import { useModelsScope } from "../ModelsScope.js";
import {
  buildDatasetRequest,
  type DatasetDraft,
  datasetDraftProblem,
  type DatasetSource,
  EMPTY_DATASET_DRAFT,
} from "./datasetDraft.js";

const SOURCE_OPTIONS: ReadonlyArray<{ value: DatasetSource; label: string }> = [
  { value: "upload", label: "Upload a file" },
  { value: "hub", label: "Hugging Face dataset" },
  { value: "bucket", label: "File in a connected S3 bucket" },
  { value: "conversations", label: "Rated conversations in this scope" },
  { value: "synthetic", label: "Generated by a teacher model" },
];

type DraftUpdate = (patch: Partial<DatasetDraft>) => void;

function UploadSource({ draft, update }: { draft: DatasetDraft; update: DraftUpdate }) {
  const { workspaceId } = useModelsScope();
  const upload = useModelUpload(workspaceId);
  const [files, setFiles] = useState<File[]>([]);
  const preview = useUploadPreview(workspaceId, upload.isReady ? upload.session?.id : undefined);
  const suggested = preview.data?.mapping;
  const sessionId = upload.session?.id ?? null;
  const status = upload.isReady
    ? null
    : upload.session?.status === "hashing"
      ? "Checking the file"
      : upload.progress
        ? `Uploading ${formatBytes(upload.progress.uploadedBytes, 1)} of ${formatBytes(upload.progress.totalBytes, 1)}`
        : null;

  useEffect(() => {
    if (suggested && sessionId) {
      update({ uploadId: sessionId, mapping: suggested });
    }
  }, [suggested, sessionId, update]);

  const choose = (next: File[]) => {
    setFiles(next);
    upload.reset();
    update({ uploadId: null, mapping: null });

    const file = next[0];

    if (file) {
      upload.start({
        purpose: "dataset",
        name: draft.name || file.name,
        sources: [{ path: file.name, file }],
      });
    }
  };

  return (
    <div className="space-y-3">
      <FileDropzone
        label="File"
        hint="JSONL, JSON, CSV or Parquet, up to 512 MB"
        accept=".jsonl,.json,.csv,.parquet"
        files={files}
        disabled={upload.isUploading}
        onFilesChange={choose}
      />
      {status && <p className="text-xs text-muted-foreground">{status}</p>}
      {upload.error && (
        <p className="text-sm text-failure">{getErrorMessage(upload.error, "Upload failed")}</p>
      )}
      {draft.mapping && preview.data && (
        <div className="space-y-3 rounded-lg border border-border p-3">
          <FormSelect
            label="Rows are"
            value={draft.mapping.shape}
            onValueChange={(shape) =>
              update({ mapping: draft.mapping ? { ...draft.mapping, shape } : null })
            }
            options={DATASET_SHAPES.map((shape) => ({
              value: shape,
              label: DATASET_SHAPE_LABELS[shape],
            }))}
          />
          <div className="flex flex-wrap gap-1.5 text-xs">
            {Object.entries(draft.mapping.columns).length === 0 ? (
              <span className="text-muted-foreground">
                No columns matched; we will try again from the first row.
              </span>
            ) : (
              Object.entries(draft.mapping.columns).map(([role, column]) => (
                <span key={role} className="rounded bg-muted px-2 py-0.5 font-mono">
                  {role} ← {column}
                </span>
              ))
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function SourceFields({ draft, update }: { draft: DatasetDraft; update: DraftUpdate }) {
  const { workspaceId, projectId } = useModelsScope();
  const routes = useModelRoutes(workspaceId, projectId);

  switch (draft.source) {
    case "upload":
      return <UploadSource draft={draft} update={update} />;
    case "hub":
      return (
        <div className="space-y-3">
          <FormInput
            label="Repository"
            placeholder="owner/name"
            value={draft.repo}
            onChange={(event) => update({ repo: event.target.value })}
          />
          <FormGrid>
            <FormInput
              label="Config (optional)"
              placeholder="default"
              value={draft.hubConfig}
              onChange={(event) => update({ hubConfig: event.target.value })}
            />
            <FormInput
              label="Split"
              value={draft.hubSplit}
              onChange={(event) => update({ hubSplit: event.target.value })}
            />
          </FormGrid>
        </div>
      );
    case "bucket":
      return (
        <FormInput
          label="S3 URI"
          placeholder="s3://bucket/data/train.jsonl"
          description="Read with the AWS account connected under Governance."
          value={draft.uri}
          onChange={(event) => update({ uri: event.target.value })}
        />
      );
    case "conversations":
      return (
        <div className="space-y-3">
          <FormSelect
            label="Include replies rated"
            value={String(draft.minRating)}
            onValueChange={(value) => update({ minRating: Number(value) })}
            options={["3", "4", "5"].map((value) => ({ value, label: `${value} stars and up` }))}
          />
          <Switch
            label="Pair best and worst replies as preferences"
            description="Builds preference pairs for DPO instead of chat examples."
            checked={draft.preference}
            onChange={(event) => update({ preference: event.target.checked })}
          />
        </div>
      );
    default:
      return (
        <div className="space-y-3">
          <FormGrid>
            <FormSelect
              label="Teacher"
              value={draft.teacherRouteId}
              onValueChange={(teacherRouteId) => update({ teacherRouteId })}
              placeholder="Choose an approved route"
              options={(routes.data ?? [])
                .filter((route) => route.status === "active")
                .map((route) => ({
                  value: route.id,
                  label: `${route.displayName} · ${route.provider}`,
                }))}
            />
            <FormInput
              label="Samples"
              type="number"
              min={1}
              value={draft.sampleCount}
              onChange={(event) => update({ sampleCount: Number(event.target.value) || 1 })}
            />
          </FormGrid>
          <FormTextarea
            label="Seed prompts"
            description="One per line. Teachers whose terms forbid training competing models are blocked unless you record an exception."
            value={draft.seedPrompts}
            onChange={(event) => update({ seedPrompts: event.target.value })}
            className="min-h-28"
          />
        </div>
      );
  }
}

export function CreateDatasetDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const { workspaceId, projectId, open: openObject } = useModelsScope();
  const mutations = useModelPlatformMutations(workspaceId);
  const suites = useEvalSuites(workspaceId, projectId);
  const [draft, setDraft] = useState<DatasetDraft>(EMPTY_DATASET_DRAFT);
  const update = useCallback(
    (patch: Partial<DatasetDraft>) => setDraft((current) => ({ ...current, ...patch })),
    [],
  );
  const problem = datasetDraftProblem(draft);

  const submit = async () => {
    const dataset = await runWithToast("Dataset queued for processing", () =>
      mutations.createDataset.mutateAsync(buildDatasetRequest(draft, projectId ?? null)),
    );

    if (dataset) {
      setDraft(EMPTY_DATASET_DRAFT);
      onOpenChange(false);
      openObject("datasets", dataset.versionId);
    }
  };

  return (
    <FormDialog
      open={open}
      onOpenChange={onOpenChange}
      size="lg"
      title="New dataset"
      description="Rows are canonicalised, deduplicated, checked against your eval suites, redacted and split the same way every time."
      onSubmit={submit}
      submitText="Build dataset"
      isLoading={mutations.createDataset.isPending}
      submitDisabled={problem !== null}
    >
      <div className="space-y-5">
        <FormSection title="Source">
          <FormGrid>
            <FormInput
              label="Name"
              placeholder="Support conversations Q3"
              value={draft.name}
              onChange={(event) => update({ name: event.target.value })}
            />
            <FormSelect
              label="Comes from"
              value={draft.source}
              onValueChange={(source) => update({ source, uploadId: null, mapping: null })}
              options={SOURCE_OPTIONS}
            />
          </FormGrid>
          <SourceFields draft={draft} update={update} />
        </FormSection>

        <FormSection
          title="Governance"
          description="Recorded with every version and checked by policy before the data can train anything."
        >
          <FormGrid>
            <FormInput
              label="Licence"
              placeholder="cc-by-4.0"
              value={draft.licence}
              onChange={(event) => update({ licence: event.target.value })}
            />
            <FormSelect
              label="Lawful basis"
              value={draft.lawfulBasis}
              onValueChange={(lawfulBasis) => update({ lawfulBasis })}
              options={LAWFUL_BASES.map((basis) => ({
                value: basis,
                label: LAWFUL_BASIS_LABELS[basis],
              }))}
            />
            <FormInput
              label="Personal data categories"
              placeholder="names, emails"
              description="Comma separated. Leave blank if there are none."
              value={draft.personalData}
              onChange={(event) => update({ personalData: event.target.value })}
            />
            <FormInput
              label="Intended use"
              placeholder="Fine-tune the support assistant"
              value={draft.intendedUse}
              onChange={(event) => update({ intendedUse: event.target.value })}
            />
          </FormGrid>
          <Switch
            label="Contains customer data"
            description="Policy can require extra approval for models trained on it."
            checked={draft.customerData}
            onChange={(event) => update({ customerData: event.target.checked })}
          />
        </FormSection>

        <FormSection title="Processing">
          <div className="space-y-3">
            <Switch
              label="Redact personal data"
              description="Emails, phone numbers, card numbers and similar are masked before training."
              checked={draft.redactPii}
              onChange={(event) => update({ redactPii: event.target.checked })}
            />
            <Switch
              label="Remove duplicates"
              description="Exact and near-exact repeats are dropped."
              checked={draft.dedupe}
              onChange={(event) => update({ dedupe: event.target.checked })}
            />
            {(suites.data ?? []).map((suite) => (
              <Switch
                key={suite.id}
                label={`Drop rows that overlap “${suite.name}”`}
                description="Keeps the eval honest by removing anything it would test on."
                checked={draft.decontaminateSuiteIds.includes(suite.id)}
                onChange={(event) =>
                  update({
                    decontaminateSuiteIds: event.target.checked
                      ? [...draft.decontaminateSuiteIds, suite.id]
                      : draft.decontaminateSuiteIds.filter((id) => id !== suite.id),
                  })
                }
              />
            ))}
          </div>
          <FormGrid>
            <FormInput
              label="Held out for validation (%)"
              type="number"
              min={0}
              max={50}
              value={draft.validationPercent}
              onChange={(event) =>
                update({
                  validationPercent: Math.min(50, Math.max(0, Number(event.target.value) || 0)),
                })
              }
            />
          </FormGrid>
        </FormSection>

        {problem && <p className="text-right text-xs text-muted-foreground">{problem}</p>}
      </div>
    </FormDialog>
  );
}
