import type { ModelConfig } from "@ngriffin_uk/polychat-schemas";

import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "alibaba";

export const alibabaModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("qwen3-max", PROVIDER, {
		name: "Qwen3 Max",
		matchingModel: "qwen3-max",
		family: "qwen",
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["reasoning", "coding", "multilingual", "tool_use"],
		openWeights: false,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 23, 2025",
		lastUpdated: "September 23, 2025",
		supportsAttachments: false,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0012,
		costPer1kOutputTokens: 0.006,
	}),
	createModelConfig("qwen3-coder-plus", PROVIDER, {
		name: "Qwen3 Coder Plus",
		matchingModel: "qwen3-coder-plus",
		family: "qwen",
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["coding", "agents", "tool_use"],
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		supportsAttachments: false,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.005,
	}),
	createModelConfig("deepseek-v4-flash-0731", PROVIDER, {
		name: "DeepSeek V4 Flash 0731",
		matchingModel: "deepseek-v4-flash-0731",
		family: "deepseek-flash",
		openWeights: true,
		knowledgeCutoffDate: "May 2025",
		releaseDate: "July 31, 2026",
		lastUpdated: "July 31, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.2", PROVIDER, {
		name: "GLM-5.2",
		matchingModel: "glm-5.2",
		family: "glm",
		openWeights: true,
		releaseDate: "June 13, 2026",
		lastUpdated: "June 13, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qvq-max", PROVIDER, {
		name: "QVQ Max",
		matchingModel: "qvq-max",
		family: "qvq",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "March 25, 2025",
		lastUpdated: "March 25, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0012,
		costPer1kOutputTokens: 0.0048,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen-flash", PROVIDER, {
		name: "Qwen Flash",
		matchingModel: "qwen-flash",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen-max", PROVIDER, {
		name: "Qwen Max",
		matchingModel: "qwen-max",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 3, 2024",
		lastUpdated: "January 25, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 32768,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0016,
		costPer1kOutputTokens: 0.0064,
	}),

	createModelConfig("qwen-mt-plus", PROVIDER, {
		name: "Qwen-MT Plus",
		matchingModel: "qwen-mt-plus",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "January 2025",
		lastUpdated: "January 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 16384,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00246,
		costPer1kOutputTokens: 0.00737,
	}),

	createModelConfig("qwen-mt-turbo", PROVIDER, {
		name: "Qwen-MT Turbo",
		matchingModel: "qwen-mt-turbo",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "January 2025",
		lastUpdated: "January 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 16384,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00016,
		costPer1kOutputTokens: 0.00049,
	}),

	createModelConfig("qwen-omni-turbo", PROVIDER, {
		name: "Qwen-Omni Turbo",
		matchingModel: "qwen-omni-turbo",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "January 19, 2025",
		lastUpdated: "March 26, 2025",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text", "audio"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 32768,
		maxTokens: 2048,
		costPer1kInputTokens: 0.00007,
		costPer1kOutputTokens: 0.00027,
	}),

	createModelConfig("qwen-omni-turbo-realtime", PROVIDER, {
		name: "Qwen-Omni Turbo Realtime",
		matchingModel: "qwen-omni-turbo-realtime",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "May 8, 2025",
		lastUpdated: "May 8, 2025",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text", "audio"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 32768,
		maxTokens: 2048,
		costPer1kInputTokens: 0.00027,
		costPer1kOutputTokens: 0.00107,
	}),

	createModelConfig("qwen-plus", PROVIDER, {
		name: "Qwen Plus",
		matchingModel: "qwen-plus",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "January 25, 2024",
		lastUpdated: "September 11, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0012,
		costPer1kReasoningTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen-plus-character-ja", PROVIDER, {
		name: "Qwen Plus Character (Japanese)",
		matchingModel: "qwen-plus-character-ja",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "January 2024",
		lastUpdated: "January 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 8192,
		maxTokens: 512,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.0014,
	}),

	createModelConfig("qwen-turbo", PROVIDER, {
		name: "Qwen Turbo",
		matchingModel: "qwen-turbo",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "November 1, 2024",
		lastUpdated: "April 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0002,
		costPer1kReasoningTokens: 0.0005,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen-vl-max", PROVIDER, {
		name: "Qwen-VL Max",
		matchingModel: "qwen-vl-max",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 8, 2024",
		lastUpdated: "August 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0008,
		costPer1kOutputTokens: 0.0032,
	}),

	createModelConfig("qwen-vl-ocr", PROVIDER, {
		name: "Qwen-VL OCR",
		matchingModel: "qwen-vl-ocr",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "October 28, 2024",
		lastUpdated: "April 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 34096,
		maxTokens: 4096,
		costPer1kInputTokens: 0.00072,
		costPer1kOutputTokens: 0.00072,
	}),

	createModelConfig("qwen-vl-plus", PROVIDER, {
		name: "Qwen-VL Plus",
		matchingModel: "qwen-vl-plus",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "January 25, 2024",
		lastUpdated: "August 15, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00021,
		costPer1kOutputTokens: 0.00063,
	}),

	createModelConfig("qwen2-5-14b-instruct", PROVIDER, {
		name: "Qwen2.5 14B Instruct",
		matchingModel: "qwen2-5-14b-instruct",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "September 2024",
		lastUpdated: "September 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00035,
		costPer1kOutputTokens: 0.0014,
	}),

	createModelConfig("qwen2-5-32b-instruct", PROVIDER, {
		name: "Qwen2.5 32B Instruct",
		matchingModel: "qwen2-5-32b-instruct",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "September 2024",
		lastUpdated: "September 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0007,
		costPer1kOutputTokens: 0.0028,
	}),

	createModelConfig("qwen2-5-72b-instruct", PROVIDER, {
		name: "Qwen2.5 72B Instruct",
		matchingModel: "qwen2-5-72b-instruct",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "September 2024",
		lastUpdated: "September 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0056,
	}),

	createModelConfig("qwen2-5-7b-instruct", PROVIDER, {
		name: "Qwen2.5 7B Instruct",
		matchingModel: "qwen2-5-7b-instruct",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "September 2024",
		lastUpdated: "September 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.000175,
		costPer1kOutputTokens: 0.0007,
	}),

	createModelConfig("qwen2-5-omni-7b", PROVIDER, {
		name: "Qwen2.5-Omni 7B",
		matchingModel: "qwen2-5-omni-7b",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "December 2024",
		lastUpdated: "December 2024",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text", "audio"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 32768,
		maxTokens: 2048,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
	}),

	createModelConfig("qwen2-5-vl-72b-instruct", PROVIDER, {
		name: "Qwen2.5-VL 72B Instruct",
		matchingModel: "qwen2-5-vl-72b-instruct",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "September 2024",
		lastUpdated: "September 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0028,
		costPer1kOutputTokens: 0.0084,
	}),

	createModelConfig("qwen2-5-vl-7b-instruct", PROVIDER, {
		name: "Qwen2.5-VL 7B Instruct",
		matchingModel: "qwen2-5-vl-7b-instruct",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "September 2024",
		lastUpdated: "September 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00035,
		costPer1kOutputTokens: 0.00105,
	}),

	createModelConfig("qwen3-14b", PROVIDER, {
		name: "Qwen3 14B",
		matchingModel: "qwen3-14b",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2025",
		lastUpdated: "April 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00035,
		costPer1kOutputTokens: 0.0014,
		costPer1kReasoningTokens: 0.0042,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-235b-a22b", PROVIDER, {
		name: "Qwen3 235B-A22B",
		matchingModel: "qwen3-235b-a22b",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2025",
		lastUpdated: "April 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0007,
		costPer1kOutputTokens: 0.0028,
		costPer1kReasoningTokens: 0.0084,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-32b", PROVIDER, {
		name: "Qwen3 32B",
		matchingModel: "qwen3-32b",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2025",
		lastUpdated: "April 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0007,
		costPer1kOutputTokens: 0.0028,
		costPer1kReasoningTokens: 0.0084,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-8b", PROVIDER, {
		name: "Qwen3 8B",
		matchingModel: "qwen3-8b",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2025",
		lastUpdated: "April 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00018,
		costPer1kOutputTokens: 0.0007,
		costPer1kReasoningTokens: 0.0021,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-asr-flash", PROVIDER, {
		name: "Qwen3-ASR Flash",
		matchingModel: "qwen3-asr-flash",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "September 8, 2025",
		lastUpdated: "September 8, 2025",
		modalities: {
			input: ["audio"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 53248,
		maxTokens: 4096,
		costPer1kInputTokens: 0.000035,
		costPer1kOutputTokens: 0.000035,
	}),

	createModelConfig("qwen3-coder-30b-a3b-instruct", PROVIDER, {
		name: "Qwen3-Coder 30B-A3B Instruct",
		matchingModel: "qwen3-coder-30b-a3b-instruct",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2025",
		lastUpdated: "April 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00045,
		costPer1kOutputTokens: 0.00225,
	}),

	createModelConfig("qwen3-coder-480b-a35b-instruct", PROVIDER, {
		name: "Qwen3-Coder 480B-A35B Instruct",
		matchingModel: "qwen3-coder-480b-a35b-instruct",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2025",
		lastUpdated: "April 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.0075,
	}),

	createModelConfig("qwen3-coder-flash", PROVIDER, {
		name: "Qwen3 Coder Flash",
		matchingModel: "qwen3-coder-flash",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0015,
	}),

	createModelConfig("qwen3-livetranslate-flash-realtime", PROVIDER, {
		name: "Qwen3-LiveTranslate Flash Realtime",
		matchingModel: "qwen3-livetranslate-flash-realtime",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "September 22, 2025",
		lastUpdated: "September 22, 2025",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text", "audio"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 53248,
		maxTokens: 4096,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.01,
	}),

	createModelConfig("qwen3-next-80b-a3b-instruct", PROVIDER, {
		name: "Qwen3-Next 80B-A3B Instruct",
		matchingModel: "qwen3-next-80b-a3b-instruct",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 2025",
		lastUpdated: "September 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("qwen3-next-80b-a3b-thinking", PROVIDER, {
		name: "Qwen3-Next 80B-A3B (Thinking)",
		matchingModel: "qwen3-next-80b-a3b-thinking",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 2025",
		lastUpdated: "September 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.006,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-omni-flash", PROVIDER, {
		name: "Qwen3-Omni Flash",
		matchingModel: "qwen3-omni-flash",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "September 15, 2025",
		lastUpdated: "September 15, 2025",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text", "audio"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 65536,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00043,
		costPer1kOutputTokens: 0.00166,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-omni-flash-realtime", PROVIDER, {
		name: "Qwen3-Omni Flash Realtime",
		matchingModel: "qwen3-omni-flash-realtime",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "September 15, 2025",
		lastUpdated: "September 15, 2025",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text", "audio"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 65536,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00052,
		costPer1kOutputTokens: 0.00199,
	}),

	createModelConfig("qwen3-vl-235b-a22b", PROVIDER, {
		name: "Qwen3-VL 235B-A22B",
		matchingModel: "qwen3-vl-235b-a22b",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2025",
		lastUpdated: "April 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0007,
		costPer1kOutputTokens: 0.0028,
		costPer1kReasoningTokens: 0.0084,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-vl-30b-a3b", PROVIDER, {
		name: "Qwen3-VL 30B-A3B",
		matchingModel: "qwen3-vl-30b-a3b",
		family: "qwen",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2025",
		lastUpdated: "April 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0008,
		costPer1kReasoningTokens: 0.0024,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-vl-plus", PROVIDER, {
		name: "Qwen3-VL Plus",
		matchingModel: "qwen3-vl-plus",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 23, 2025",
		lastUpdated: "September 23, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0016,
		costPer1kReasoningTokens: 0.0048,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.5-122b-a10b", PROVIDER, {
		name: "Qwen3.5 122B-A10B",
		matchingModel: "qwen3.5-122b-a10b",
		family: "qwen",
		openWeights: true,
		releaseDate: "February 23, 2026",
		lastUpdated: "February 23, 2026",
		modalities: {
			input: ["text", "image", "video", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0032,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.5-27b", PROVIDER, {
		name: "Qwen3.5 27B",
		matchingModel: "qwen3.5-27b",
		family: "qwen",
		openWeights: true,
		releaseDate: "February 23, 2026",
		lastUpdated: "February 23, 2026",
		modalities: {
			input: ["text", "image", "video", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0024,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.5-35b-a3b", PROVIDER, {
		name: "Qwen3.5 35B-A3B",
		matchingModel: "qwen3.5-35b-a3b",
		family: "qwen",
		openWeights: true,
		releaseDate: "February 23, 2026",
		lastUpdated: "February 23, 2026",
		modalities: {
			input: ["text", "image", "video", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.5-397b-a17b", PROVIDER, {
		name: "Qwen3.5 397B-A17B",
		matchingModel: "qwen3.5-397b-a17b",
		family: "qwen",
		openWeights: true,
		releaseDate: "February 15, 2026",
		lastUpdated: "February 15, 2026",
		modalities: {
			input: ["text", "image", "video", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0036,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.5-plus", PROVIDER, {
		name: "Qwen3.5 Plus",
		matchingModel: "qwen3.5-plus",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "February 16, 2026",
		lastUpdated: "February 16, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0024,
		costPer1kReasoningTokens: 0.0024,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.6-27b", PROVIDER, {
		name: "Qwen3.6 27B",
		matchingModel: "qwen3.6-27b",
		family: "qwen",
		openWeights: true,
		releaseDate: "April 22, 2026",
		lastUpdated: "April 22, 2026",
		modalities: {
			input: ["text", "image", "video", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0036,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.6-35b-a3b", PROVIDER, {
		name: "Qwen3.6 35B-A3B",
		matchingModel: "qwen3.6-35b-a3b",
		family: "qwen",
		openWeights: true,
		releaseDate: "April 17, 2026",
		lastUpdated: "April 17, 2026",
		modalities: {
			input: ["text", "image", "video", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.000248,
		costPer1kOutputTokens: 0.001485,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.6-flash", PROVIDER, {
		name: "Qwen3.6 Flash",
		matchingModel: "qwen3.6-flash",
		family: "qwen3.6",
		openWeights: false,
		releaseDate: "April 27, 2026",
		lastUpdated: "April 27, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0001875,
		costPer1kOutputTokens: 0.001125,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.6-max-preview", PROVIDER, {
		name: "Qwen3.6 Max Preview",
		matchingModel: "qwen3.6-max-preview",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 20, 2026",
		lastUpdated: "April 20, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0013,
		costPer1kOutputTokens: 0.0078,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.6-plus", PROVIDER, {
		name: "Qwen3.6 Plus",
		matchingModel: "qwen3.6-plus",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2, 2026",
		lastUpdated: "April 2, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.7-max", PROVIDER, {
		name: "Qwen3.7 Max",
		matchingModel: "qwen3.7-max",
		family: "qwen",
		openWeights: false,
		releaseDate: "May 21, 2026",
		lastUpdated: "May 21, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.0075,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.7-plus", PROVIDER, {
		name: "Qwen3.7 Plus",
		matchingModel: "qwen3.7-plus",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "June 2, 2026",
		lastUpdated: "June 4, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.8-flash", PROVIDER, {
		name: "Qwen3.8 Flash",
		matchingModel: "qwen3.8-flash",
		family: "qwen",
		openWeights: false,
		releaseDate: "August 26, 2026",
		lastUpdated: "August 26, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.00047,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.8-max", PROVIDER, {
		name: "Qwen3.8 Max",
		matchingModel: "qwen3.8-max",
		family: "qwen",
		openWeights: false,
		releaseDate: "August 3, 2026",
		lastUpdated: "August 3, 2026",
		modalities: {
			input: ["text", "image", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.006,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwq-plus", PROVIDER, {
		name: "QwQ Plus",
		matchingModel: "qwq-plus",
		family: "qwen",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "March 5, 2025",
		lastUpdated: "March 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0008,
		costPer1kOutputTokens: 0.0024,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
]);
