import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";
import type { ModelConfig } from "~/types";

const PROVIDER = "anthropic";

export const anthropicModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("claude-4.5-opus", PROVIDER, {
		name: "Claude 4.5 Opus",
		matchingModel: "claude-opus-4-5-20251101",
		description:
			"The Claude 4.5 Opus is intelligent, efficient, and the best model in the world for coding, agents, and computer use.",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "November 1, 2025",
		lastUpdated: "November 1, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/claude-4.5-opus",
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.005, // $5.00 per million tokens
		costPer1kOutputTokens: 0.025, // $25.00 per million tokens
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"reasoning",
			"creative",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		supportsToolCalls: true,
		supportsSearchGrounding: true,
		supportsCodeExecution: true,
		supportsDocuments: true,
		supportsTokenCounting: true,
		supportsTopP: false,
	}),
	createModelConfig("claude-4-5-sonnet", PROVIDER, {
		name: "Claude 4.5 Sonnet",
		matchingModel: "claude-sonnet-4-5",
		description:
			"Combined with state-of-the-art coding, vision, and writing skills, you can use this model for a variety of use cases.",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/claude-sonnet-4-5",
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"coding",
			"reasoning",
			"creative",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		reasoningConfig: { enabled: false },
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsToolCalls: true,
		supportsSearchGrounding: true,
		supportsCodeExecution: true,
		supportsDocuments: true,
		supportsTokenCounting: true,
		restrictsCombinedTopPAndTemperature: true,
	}),

	createModelConfig("claude-4-5-sonnet-thinking", PROVIDER, {
		name: "Claude 4.5 Sonnet Thinking",
		matchingModel: "claude-sonnet-4-5-20250929",
		description:
			"Combined with state-of-the-art coding, vision, and writing skills, you can use this model for a variety of use cases.",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/claude-sonnet-4-5",
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"coding",
			"reasoning",
			"creative",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		reasoningConfig: { enabled: true },
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsToolCalls: true,
		supportsSearchGrounding: true,
		supportsCodeExecution: true,
		supportsDocuments: true,
		supportsTokenCounting: true,
		restrictsCombinedTopPAndTemperature: true,
	}),

	createModelConfig("claude-4-sonnet", PROVIDER, {
		name: "Claude 4 Sonnet",
		matchingModel: "claude-sonnet-4-0",
		description:
			"Combined with state-of-the-art coding, vision, and writing skills, you can use this model for a variety of use cases.",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/claude-sonnet-4",
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"coding",
			"reasoning",
			"creative",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		reasoningConfig: { enabled: false },
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsToolCalls: true,
		supportsSearchGrounding: true,
		supportsCodeExecution: true,
		supportsDocuments: true,
		supportsTokenCounting: true,
	}),

	createModelConfig("claude-4-sonnet-thinking", PROVIDER, {
		name: "Claude 4 Sonnet Thinking",
		matchingModel: "claude-sonnet-4-20250514",
		description:
			"Combined with state-of-the-art coding, vision, and writing skills, you can use this model for a variety of use cases.",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/claude-sonnet-4",
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"coding",
			"reasoning",
			"creative",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		reasoningConfig: { enabled: true },
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsToolCalls: true,
		supportsSearchGrounding: true,
		supportsCodeExecution: true,
		supportsDocuments: true,
		supportsTokenCounting: true,
	}),

	createModelConfig("claude-3.5-haiku", PROVIDER, {
		name: "Claude 3.5 Haiku",
		matchingModel: "claude-3-5-haiku-latest",
		description:
			"With fast speeds, improved instruction following, and more accurate tool use, Claude 3.5 Haiku is well suited for user-facing products, specialized sub-agent tasks, and generating personalized experiences from huge volumes of data.",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "October 22, 2024",
		lastUpdated: "October 22, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/claude-3-5-haiku",
		contextWindow: 80000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.005,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"reasoning",
			"creative",
		],
		contextComplexity: 3,
		reliability: 3,
		speed: 5,
		isFeatured: false,
		multimodal: true,
		supportsArtifacts: true,
		supportsToolCalls: true,
		supportsSearchGrounding: true,
		supportsCodeExecution: true,
		includedInRouter: true,
		supportsTokenCounting: true,
	}),

	createModelConfig("claude-4-opus", PROVIDER, {
		name: "Claude 4 Opus",
		matchingModel: "claude-opus-4-20250514",
		description:
			"The Claude 4 Opus is an advanced AI model by Anthropic designed for enterprise-level applications. It offers unmatched performance in handling complex tasks, making it an ideal solution for businesses requiring high-level data processing and analysis.",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/claude-4-opus",
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"reasoning",
			"creative",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		supportsToolCalls: true,
		supportsSearchGrounding: true,
		supportsCodeExecution: true,
		supportsDocuments: true,
		supportsTokenCounting: true,
	}),

	createModelConfig("claude-4.1-opus", PROVIDER, {
		name: "Claude 4.1 Opus",
		matchingModel: "claude-opus-4-1",
		description:
			"Enhanced Claude 4 Opus with improved reasoning and analysis capabilities.",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/claude-4-opus",
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"reasoning",
			"creative",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		reasoningConfig: { enabled: true },
		supportsArtifacts: true,
		supportsToolCalls: true,
		supportsTokenCounting: true,
	}),

	createModelConfig("claude-3.7-sonnet", PROVIDER, {
		name: "Claude 3.7 Sonnet",
		matchingModel: "claude-3-7-sonnet-20250219",
		description:
			"Advanced reasoning model with enhanced capabilities for complex analytical tasks.",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "February 19, 2025",
		lastUpdated: "February 19, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/claude-3-7-sonnet",
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"coding",
			"reasoning",
			"creative",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		reasoningConfig: { enabled: true },
		supportsArtifacts: true,
		supportsToolCalls: true,
		supportsTokenCounting: true,
	}),
]);
