import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "azure-openai";

export const azureModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("openai/gpt-4-turbo-vision", PROVIDER, {
		name: "GPT-4 Turbo Vision",
		matchingModel: "gpt-4-turbo-vision",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "November 2023",
		releaseDate: "November 6, 2023",
		lastUpdated: "April 9, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.03,
	}),

	createModelConfig("openai/gpt-4", PROVIDER, {
		name: "GPT-4",
		matchingModel: "gpt-4",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "November 2023",
		releaseDate: "March 14, 2023",
		lastUpdated: "March 14, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 8192,
		maxTokens: 8192,
		costPer1kInputTokens: 0.06,
		costPer1kOutputTokens: 0.12,
	}),

	createModelConfig("openai/gpt-3.5-turbo-0125", PROVIDER, {
		name: "GPT-3.5 Turbo 0125",
		matchingModel: "gpt-3.5-turbo-0125",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: false,
		knowledgeCutoffDate: "August 2021",
		releaseDate: "January 25, 2024",
		lastUpdated: "January 25, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 16384,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.0015,
	}),

	createModelConfig("openai/gpt-4.1-mini", PROVIDER, {
		name: "GPT-4.1 mini",
		matchingModel: "gpt-4.1-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
	}),

	createModelConfig("openai/o4-mini", PROVIDER, {
		name: "o4-mini",
		matchingModel: "o4-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
	}),

	createModelConfig("openai/gpt-3.5-turbo-0613", PROVIDER, {
		name: "GPT-3.5 Turbo 0613",
		matchingModel: "gpt-3.5-turbo-0613",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: false,
		knowledgeCutoffDate: "August 2021",
		releaseDate: "June 13, 2023",
		lastUpdated: "June 13, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 16384,
		maxTokens: 16384,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.004,
	}),

	createModelConfig("openai/o1-mini", PROVIDER, {
		name: "o1-mini",
		matchingModel: "o1-mini",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "September 12, 2024",
		lastUpdated: "September 12, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
	}),

	createModelConfig("openai/codex-mini", PROVIDER, {
		name: "Codex Mini",
		matchingModel: "codex-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "May 16, 2025",
		lastUpdated: "May 16, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.006,
	}),

	createModelConfig("openai/gpt-4.1-nano", PROVIDER, {
		name: "GPT-4.1 nano",
		matchingModel: "gpt-4.1-nano",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
	}),

	createModelConfig("openai/o1-preview", PROVIDER, {
		name: "o1-preview",
		matchingModel: "o1-preview",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "September 12, 2024",
		lastUpdated: "September 12, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0165,
		costPer1kOutputTokens: 0.066,
	}),

	createModelConfig("openai/gpt-3.5-turbo-1106", PROVIDER, {
		name: "GPT-3.5 Turbo 1106",
		matchingModel: "gpt-3.5-turbo-1106",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: false,
		knowledgeCutoffDate: "August 2021",
		releaseDate: "November 6, 2023",
		lastUpdated: "November 6, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 16384,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("openai/gpt-3.5-turbo-instruct", PROVIDER, {
		name: "GPT-3.5 Turbo Instruct",
		matchingModel: "gpt-3.5-turbo-instruct",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: false,
		knowledgeCutoffDate: "August 2021",
		releaseDate: "September 21, 2023",
		lastUpdated: "September 21, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 4096,
		maxTokens: 4096,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("openai/gpt-4o-mini", PROVIDER, {
		name: "GPT-4o mini",
		matchingModel: "gpt-4o-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
	}),

	createModelConfig("openai/gpt-4-turbo", PROVIDER, {
		name: "GPT-4 Turbo",
		matchingModel: "gpt-4-turbo",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "November 2023",
		releaseDate: "November 6, 2023",
		lastUpdated: "April 9, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.03,
	}),

	createModelConfig("openai/o3-mini", PROVIDER, {
		name: "o3-mini",
		matchingModel: "o3-mini",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "December 20, 2024",
		lastUpdated: "January 29, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
	}),

	createModelConfig("openai/gpt-3.5-turbo-0301", PROVIDER, {
		name: "GPT-3.5 Turbo 0301",
		matchingModel: "gpt-3.5-turbo-0301",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: false,
		knowledgeCutoffDate: "August 2021",
		releaseDate: "March 1, 2023",
		lastUpdated: "March 1, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 4096,
		maxTokens: 4096,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("openai/o1", PROVIDER, {
		name: "o1",
		matchingModel: "o1",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "December 5, 2024",
		lastUpdated: "December 5, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.06,
	}),

	createModelConfig("openai/gpt-4.1", PROVIDER, {
		name: "GPT-4.1",
		matchingModel: "gpt-4.1",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
	}),

	createModelConfig("openai/gpt-4o", PROVIDER, {
		name: "GPT-4o",
		matchingModel: "gpt-4o",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "May 13, 2024",
		lastUpdated: "May 13, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
	}),

	createModelConfig("openai/gpt-4-32k", PROVIDER, {
		name: "GPT-4 32K",
		matchingModel: "gpt-4-32k",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "November 2023",
		releaseDate: "March 14, 2023",
		lastUpdated: "March 14, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.06,
		costPer1kOutputTokens: 0.12,
	}),

	createModelConfig("openai/o3", PROVIDER, {
		name: "o3",
		matchingModel: "o3",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
	}),
	createModelConfig("anthropic/claude-haiku-4-5", PROVIDER, {
		name: "Claude Haiku 4.5",
		matchingModel: "claude-haiku-4-5",
		knowledgeCutoffDate: "February 31, 2025",
		releaseDate: "November 18, 2025",
		lastUpdated: "November 18, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.005,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("anthropic/claude-opus-4-1", PROVIDER, {
		name: "Claude Opus 4.1",
		matchingModel: "claude-opus-4-1",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "November 18, 2025",
		lastUpdated: "November 18, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("anthropic/claude-opus-4-5", PROVIDER, {
		name: "Claude Opus 4.5",
		matchingModel: "claude-opus-4-5",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "November 24, 2025",
		lastUpdated: "August 1, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("anthropic/claude-opus-4-6", PROVIDER, {
		name: "Claude Opus 4.6",
		matchingModel: "claude-opus-4-6",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "February 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("anthropic/claude-sonnet-4-5", PROVIDER, {
		name: "Claude Sonnet 4.5",
		matchingModel: "claude-sonnet-4-5",
		knowledgeCutoffDate: "July 31, 2025",
		releaseDate: "November 18, 2025",
		lastUpdated: "November 18, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("mistral/codestral-2501", PROVIDER, {
		name: "Codestral 25.01",
		matchingModel: "codestral-2501",
		knowledgeCutoffDate: "March 2024",
		releaseDate: "January 1, 2025",
		lastUpdated: "January 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0009,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("cohere/command-a", PROVIDER, {
		name: "Command A",
		matchingModel: "cohere-command-a",
		knowledgeCutoffDate: "June 1, 2024",
		releaseDate: "March 13, 2025",
		lastUpdated: "March 13, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 8000,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("cohere/command-r-08-2024", PROVIDER, {
		name: "Command R",
		matchingModel: "cohere-command-r-08-2024",
		knowledgeCutoffDate: "June 1, 2024",
		releaseDate: "August 30, 2024",
		lastUpdated: "August 30, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 4000,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("cohere/command-r-plus-08-2024", PROVIDER, {
		name: "Command R+",
		matchingModel: "cohere-command-r-plus-08-2024",
		knowledgeCutoffDate: "June 1, 2024",
		releaseDate: "August 30, 2024",
		lastUpdated: "August 30, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 4000,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("cohere/embed-v-4-0", PROVIDER, {
		name: "Embed v4",
		matchingModel: "cohere-embed-v-4-0",
		releaseDate: "April 15, 2025",
		lastUpdated: "April 15, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 1536,
		costPer1kInputTokens: 0.00012,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("cohere/embed-v3-english", PROVIDER, {
		name: "Embed v3 English",
		matchingModel: "cohere-embed-v3-english",
		releaseDate: "November 7, 2023",
		lastUpdated: "November 7, 2023",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 512,
		maxTokens: 1024,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("cohere/embed-v3-multilingual", PROVIDER, {
		name: "Embed v3 Multilingual",
		matchingModel: "cohere-embed-v3-multilingual",
		releaseDate: "November 7, 2023",
		lastUpdated: "November 7, 2023",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 512,
		maxTokens: 1024,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("deepseek/r1", PROVIDER, {
		name: "DeepSeek-R1",
		matchingModel: "deepseek-r1",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "January 20, 2025",
		lastUpdated: "January 20, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00135,
		costPer1kOutputTokens: 0.0054,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek/r1-0528", PROVIDER, {
		name: "DeepSeek-R1-0528",
		matchingModel: "deepseek-r1-0528",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "May 28, 2025",
		lastUpdated: "May 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00135,
		costPer1kOutputTokens: 0.0054,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek/v3-0324", PROVIDER, {
		name: "DeepSeek-V3-0324",
		matchingModel: "deepseek-v3-0324",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "March 24, 2025",
		lastUpdated: "March 24, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00114,
		costPer1kOutputTokens: 0.00456,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("deepseek/v3.1", PROVIDER, {
		name: "DeepSeek-V3.1",
		matchingModel: "deepseek-v3.1",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "August 21, 2025",
		lastUpdated: "August 21, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00056,
		costPer1kOutputTokens: 0.00168,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek/v3.2", PROVIDER, {
		name: "DeepSeek-V3.2",
		matchingModel: "deepseek-v3.2",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "December 1, 2025",
		lastUpdated: "December 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00058,
		costPer1kOutputTokens: 0.00168,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek/v3.2-speciale", PROVIDER, {
		name: "DeepSeek-V3.2-Speciale",
		matchingModel: "deepseek-v3.2-speciale",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "December 1, 2025",
		lastUpdated: "December 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00058,
		costPer1kOutputTokens: 0.00168,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5", PROVIDER, {
		name: "GPT-5",
		matchingModel: "gpt-5",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 272000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5-chat", PROVIDER, {
		name: "GPT-5 Chat",
		matchingModel: "gpt-5-chat",
		knowledgeCutoffDate: "October 24, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5-codex", PROVIDER, {
		name: "GPT-5-Codex",
		matchingModel: "gpt-5-codex",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "September 15, 2025",
		lastUpdated: "September 15, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5-mini", PROVIDER, {
		name: "GPT-5 Mini",
		matchingModel: "gpt-5-mini",
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 272000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5-nano", PROVIDER, {
		name: "GPT-5 Nano",
		matchingModel: "gpt-5-nano",
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 272000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5-pro", PROVIDER, {
		name: "GPT-5 Pro",
		matchingModel: "gpt-5-pro",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "October 6, 2025",
		lastUpdated: "October 6, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 272000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.12,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5.1", PROVIDER, {
		name: "GPT-5.1",
		matchingModel: "gpt-5.1",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 14, 2025",
		lastUpdated: "November 14, 2025",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text", "image", "audio"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 272000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5.1-chat", PROVIDER, {
		name: "GPT-5.1 Chat",
		matchingModel: "gpt-5.1-chat",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 14, 2025",
		lastUpdated: "November 14, 2025",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text", "image", "audio"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5.1-codex", PROVIDER, {
		name: "GPT-5.1 Codex",
		matchingModel: "gpt-5.1-codex",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 14, 2025",
		lastUpdated: "November 14, 2025",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text", "image", "audio"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5.1-codex-max", PROVIDER, {
		name: "GPT-5.1 Codex Max",
		matchingModel: "gpt-5.1-codex-max",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5.1-codex-mini", PROVIDER, {
		name: "GPT-5.1 Codex Mini",
		matchingModel: "gpt-5.1-codex-mini",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 14, 2025",
		lastUpdated: "November 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5.2", PROVIDER, {
		name: "GPT-5.2",
		matchingModel: "gpt-5.2",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5.2-chat", PROVIDER, {
		name: "GPT-5.2 Chat",
		matchingModel: "gpt-5.2-chat",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5.2-codex", PROVIDER, {
		name: "GPT-5.2 Codex",
		matchingModel: "gpt-5.2-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "January 14, 2026",
		lastUpdated: "January 14, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("xai/grok-3", PROVIDER, {
		name: "Grok 3",
		matchingModel: "grok-3",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("xai/grok-3-mini", PROVIDER, {
		name: "Grok 3 Mini",
		matchingModel: "grok-3-mini",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0005,
		costPer1kReasoningTokens: 0.0005,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("xai/grok-4", PROVIDER, {
		name: "Grok 4",
		matchingModel: "grok-4",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "July 9, 2025",
		lastUpdated: "July 9, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		costPer1kReasoningTokens: 0.015,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("xai/grok-4-fast-non-reasoning", PROVIDER, {
		name: "Grok 4 Fast (Non-Reasoning)",
		matchingModel: "grok-4-fast-non-reasoning",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "September 19, 2025",
		lastUpdated: "September 19, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 2000000,
		maxTokens: 30000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("xai/grok-4-fast-reasoning", PROVIDER, {
		name: "Grok 4 Fast (Reasoning)",
		matchingModel: "grok-4-fast-reasoning",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "September 19, 2025",
		lastUpdated: "September 19, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 2000000,
		maxTokens: 30000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("xai/grok-code-fast-1", PROVIDER, {
		name: "Grok Code Fast 1",
		matchingModel: "grok-code-fast-1",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "August 28, 2025",
		lastUpdated: "August 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 10000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0015,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("monshot/kimi-k2-thinking", PROVIDER, {
		name: "Kimi K2 Thinking",
		matchingModel: "kimi-k2-thinking",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "November 6, 2025",
		lastUpdated: "December 2, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0025,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("monshot/kimi-k2.5", PROVIDER, {
		name: "Kimi K2.5",
		matchingModel: "kimi-k2.5",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 6, 2026",
		lastUpdated: "February 6, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("meta/llama-3.2-11b-vision-instruct", PROVIDER, {
		name: "Llama-3.2-11B-Vision-Instruct",
		matchingModel: "llama-3.2-11b-vision-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "September 25, 2024",
		lastUpdated: "September 25, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00037,
		costPer1kOutputTokens: 0.00037,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("meta/llama-3.2-90b-vision-instruct", PROVIDER, {
		name: "Llama-3.2-90B-Vision-Instruct",
		matchingModel: "llama-3.2-90b-vision-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "September 25, 2024",
		lastUpdated: "September 25, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00204,
		costPer1kOutputTokens: 0.00204,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("meta/llama-3.3-70b-instruct", PROVIDER, {
		name: "Llama-3.3-70B-Instruct",
		matchingModel: "llama-3.3-70b-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "December 6, 2024",
		lastUpdated: "December 6, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00071,
		costPer1kOutputTokens: 0.00071,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("meta/llama-4-maverick-17b-128e-instruct-fp8", PROVIDER, {
		name: "Llama 4 Maverick 17B 128E Instruct FP8",
		matchingModel: "llama-4-maverick-17b-128e-instruct-fp8",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "April 5, 2025",
		lastUpdated: "April 5, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.001,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("meta/llama-4-scout-17b-16e-instruct", PROVIDER, {
		name: "Llama 4 Scout 17B 16E Instruct",
		matchingModel: "llama-4-scout-17b-16e-instruct",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "April 5, 2025",
		lastUpdated: "April 5, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.00078,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/mai-ds-r1", PROVIDER, {
		name: "MAI-DS-R1",
		matchingModel: "mai-ds-r1",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "January 20, 2025",
		lastUpdated: "January 20, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00135,
		costPer1kOutputTokens: 0.0054,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("meta/llama-3-70b-instruct", PROVIDER, {
		name: "Meta-Llama-3-70B-Instruct",
		matchingModel: "meta-llama-3-70b-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "April 18, 2024",
		lastUpdated: "April 18, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 8192,
		maxTokens: 2048,
		costPer1kInputTokens: 0.00268,
		costPer1kOutputTokens: 0.00354,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("meta/llama-3-8b-instruct", PROVIDER, {
		name: "Meta-Llama-3-8B-Instruct",
		matchingModel: "meta-llama-3-8b-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "April 18, 2024",
		lastUpdated: "April 18, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 8192,
		maxTokens: 2048,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.00061,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("meta/llama-3.1-405b-instruct", PROVIDER, {
		name: "Meta-Llama-3.1-405B-Instruct",
		matchingModel: "meta-llama-3.1-405b-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "July 23, 2024",
		lastUpdated: "July 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00533,
		costPer1kOutputTokens: 0.016,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("meta/llama-3.1-70b-instruct", PROVIDER, {
		name: "Meta-Llama-3.1-70B-Instruct",
		matchingModel: "meta-llama-3.1-70b-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "July 23, 2024",
		lastUpdated: "July 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00268,
		costPer1kOutputTokens: 0.00354,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("meta/llama-3.1-8b-instruct", PROVIDER, {
		name: "Meta-Llama-3.1-8B-Instruct",
		matchingModel: "meta-llama-3.1-8b-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "July 23, 2024",
		lastUpdated: "July 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.00061,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("mistral/ministral-3b", PROVIDER, {
		name: "Ministral 3B",
		matchingModel: "ministral-3b",
		knowledgeCutoffDate: "March 2024",
		releaseDate: "October 22, 2024",
		lastUpdated: "October 22, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00004,
		costPer1kOutputTokens: 0.00004,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("mistral/mistral-large-2411", PROVIDER, {
		name: "Mistral Large 24.11",
		matchingModel: "mistral-large-2411",
		knowledgeCutoffDate: "September 2024",
		releaseDate: "November 1, 2024",
		lastUpdated: "November 1, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.006,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("mistral/medium-2505", PROVIDER, {
		name: "Mistral Medium 3",
		matchingModel: "mistral-medium-2505",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "May 7, 2025",
		lastUpdated: "May 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("mistral/mistral-nemo", PROVIDER, {
		name: "Mistral Nemo",
		matchingModel: "mistral-nemo",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.00015,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("mistral/mistral-small-2503", PROVIDER, {
		name: "Mistral Small 3.1",
		matchingModel: "mistral-small-2503",
		knowledgeCutoffDate: "September 2024",
		releaseDate: "March 1, 2025",
		lastUpdated: "March 1, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("azure/model-router", PROVIDER, {
		name: "Model Router",
		matchingModel: "model-router",
		releaseDate: "May 19, 2025",
		lastUpdated: "November 18, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-3-medium-128k-instruct", PROVIDER, {
		name: "Phi-3-medium-instruct (128k)",
		matchingModel: "phi-3-medium-128k-instruct",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "April 23, 2024",
		lastUpdated: "April 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.00017,
		costPer1kOutputTokens: 0.00068,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-3-medium-4k-instruct", PROVIDER, {
		name: "Phi-3-medium-instruct (4k)",
		matchingModel: "phi-3-medium-4k-instruct",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "April 23, 2024",
		lastUpdated: "April 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 4096,
		maxTokens: 1024,
		costPer1kInputTokens: 0.00017,
		costPer1kOutputTokens: 0.00068,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-3-mini-128k-instruct", PROVIDER, {
		name: "Phi-3-mini-instruct (128k)",
		matchingModel: "phi-3-mini-128k-instruct",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "April 23, 2024",
		lastUpdated: "April 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.00013,
		costPer1kOutputTokens: 0.00052,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-3-mini-4k-instruct", PROVIDER, {
		name: "Phi-3-mini-instruct (4k)",
		matchingModel: "phi-3-mini-4k-instruct",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "April 23, 2024",
		lastUpdated: "April 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 4096,
		maxTokens: 1024,
		costPer1kInputTokens: 0.00013,
		costPer1kOutputTokens: 0.00052,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-3-small-128k-instruct", PROVIDER, {
		name: "Phi-3-small-instruct (128k)",
		matchingModel: "phi-3-small-128k-instruct",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "April 23, 2024",
		lastUpdated: "April 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-3-small-8k-instruct", PROVIDER, {
		name: "Phi-3-small-instruct (8k)",
		matchingModel: "phi-3-small-8k-instruct",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "April 23, 2024",
		lastUpdated: "April 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 8192,
		maxTokens: 2048,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-3.5-mini-instruct", PROVIDER, {
		name: "Phi-3.5-mini-instruct",
		matchingModel: "phi-3.5-mini-instruct",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "August 20, 2024",
		lastUpdated: "August 20, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.00013,
		costPer1kOutputTokens: 0.00052,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-3.5-moe-instruct", PROVIDER, {
		name: "Phi-3.5-MoE-instruct",
		matchingModel: "phi-3.5-moe-instruct",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "August 20, 2024",
		lastUpdated: "August 20, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.00016,
		costPer1kOutputTokens: 0.00064,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-4", PROVIDER, {
		name: "Phi-4",
		matchingModel: "phi-4",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "December 11, 2024",
		lastUpdated: "December 11, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.000125,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-4-mini", PROVIDER, {
		name: "Phi-4-mini",
		matchingModel: "phi-4-mini",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "December 11, 2024",
		lastUpdated: "December 11, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.000075,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-4-mini-reasoning", PROVIDER, {
		name: "Phi-4-mini-reasoning",
		matchingModel: "phi-4-mini-reasoning",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "December 11, 2024",
		lastUpdated: "December 11, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.000075,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("microsoft/phi-4-multimodal", PROVIDER, {
		name: "Phi-4-multimodal",
		matchingModel: "phi-4-multimodal",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "December 11, 2024",
		lastUpdated: "December 11, 2024",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.00008,
		costPer1kOutputTokens: 0.00032,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/phi-4-reasoning", PROVIDER, {
		name: "Phi-4-reasoning",
		matchingModel: "phi-4-reasoning",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "December 11, 2024",
		lastUpdated: "December 11, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.000125,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("microsoft/phi-4-reasoning-plus", PROVIDER, {
		name: "Phi-4-reasoning-plus",
		matchingModel: "phi-4-reasoning-plus",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "December 11, 2024",
		lastUpdated: "December 11, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.000125,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("microsoft/text-embedding-3-large", PROVIDER, {
		name: "text-embedding-3-large",
		matchingModel: "text-embedding-3-large",
		releaseDate: "January 25, 2024",
		lastUpdated: "January 25, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: false,
		contextWindow: 8191,
		maxTokens: 3072,
		costPer1kInputTokens: 0.00013,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/text-embedding-3-small", PROVIDER, {
		name: "text-embedding-3-small",
		matchingModel: "text-embedding-3-small",
		releaseDate: "January 25, 2024",
		lastUpdated: "January 25, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: false,
		contextWindow: 8191,
		maxTokens: 1536,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("microsoft/text-embedding-ada-002", PROVIDER, {
		name: "text-embedding-ada-002",
		matchingModel: "text-embedding-ada-002",
		releaseDate: "December 15, 2022",
		lastUpdated: "December 15, 2022",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: false,
		contextWindow: 8192,
		maxTokens: 1536,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	}),
]);
