import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "azure-openai";

export const azureModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("openai/gpt-4-turbo-vision", PROVIDER, {
		name: "GPT-4 Turbo Vision",
		matchingModel: "gpt-4-turbo-vision",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "November 2023",
		releaseDate: "November 6, 2023",
		lastUpdated: "April 9, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.03,
	}),

	createModelConfig("openai/gpt-4", PROVIDER, {
		name: "GPT-4",
		matchingModel: "gpt-4",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "November 2023",
		releaseDate: "March 14, 2023",
		lastUpdated: "March 14, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 8192,
		maxTokens: 8192,
		costPer1kInputTokens: 0.06,
		costPer1kOutputTokens: 0.12,
	}),

	createModelConfig("openai/gpt-3.5-turbo-0125", PROVIDER, {
		name: "GPT-3.5 Turbo 0125",
		matchingModel: "gpt-3.5-turbo-0125",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: false,
		knowledgeCutoffDate: "August 2021",
		releaseDate: "January 25, 2024",
		lastUpdated: "January 25, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 16384,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.0015,
	}),

	createModelConfig("openai/gpt-4.1-mini", PROVIDER, {
		name: "GPT-4.1 mini",
		matchingModel: "gpt-4.1-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
	}),

	createModelConfig("openai/o4-mini", PROVIDER, {
		name: "o4-mini",
		matchingModel: "o4-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
	}),

	createModelConfig("openai/gpt-3.5-turbo-0613", PROVIDER, {
		name: "GPT-3.5 Turbo 0613",
		matchingModel: "gpt-3.5-turbo-0613",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: false,
		knowledgeCutoffDate: "August 2021",
		releaseDate: "June 13, 2023",
		lastUpdated: "June 13, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 16384,
		maxTokens: 16384,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.004,
	}),

	createModelConfig("openai/o1-mini", PROVIDER, {
		name: "o1-mini",
		matchingModel: "o1-mini",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "September 12, 2024",
		lastUpdated: "September 12, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
	}),

	createModelConfig("openai/codex-mini", PROVIDER, {
		name: "Codex Mini",
		matchingModel: "codex-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "May 16, 2025",
		lastUpdated: "May 16, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.006,
	}),

	createModelConfig("openai/gpt-4.1-nano", PROVIDER, {
		name: "GPT-4.1 nano",
		matchingModel: "gpt-4.1-nano",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
	}),

	createModelConfig("openai/o1-preview", PROVIDER, {
		name: "o1-preview",
		matchingModel: "o1-preview",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "September 12, 2024",
		lastUpdated: "September 12, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0165,
		costPer1kOutputTokens: 0.066,
	}),

	createModelConfig("openai/gpt-3.5-turbo-1106", PROVIDER, {
		name: "GPT-3.5 Turbo 1106",
		matchingModel: "gpt-3.5-turbo-1106",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: false,
		knowledgeCutoffDate: "August 2021",
		releaseDate: "November 6, 2023",
		lastUpdated: "November 6, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 16384,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("openai/gpt-3.5-turbo-instruct", PROVIDER, {
		name: "GPT-3.5 Turbo Instruct",
		matchingModel: "gpt-3.5-turbo-instruct",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: false,
		knowledgeCutoffDate: "August 2021",
		releaseDate: "September 21, 2023",
		lastUpdated: "September 21, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 4096,
		maxTokens: 4096,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("openai/gpt-4o-mini", PROVIDER, {
		name: "GPT-4o mini",
		matchingModel: "gpt-4o-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
	}),

	createModelConfig("openai/gpt-4-turbo", PROVIDER, {
		name: "GPT-4 Turbo",
		matchingModel: "gpt-4-turbo",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "November 2023",
		releaseDate: "November 6, 2023",
		lastUpdated: "April 9, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.03,
	}),

	createModelConfig("openai/o3-mini", PROVIDER, {
		name: "o3-mini",
		matchingModel: "o3-mini",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "December 20, 2024",
		lastUpdated: "January 29, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
	}),

	createModelConfig("openai/gpt-3.5-turbo-0301", PROVIDER, {
		name: "GPT-3.5 Turbo 0301",
		matchingModel: "gpt-3.5-turbo-0301",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: false,
		knowledgeCutoffDate: "August 2021",
		releaseDate: "March 1, 2023",
		lastUpdated: "March 1, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 4096,
		maxTokens: 4096,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("openai/o1", PROVIDER, {
		name: "o1",
		matchingModel: "o1",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "December 5, 2024",
		lastUpdated: "December 5, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.06,
	}),

	createModelConfig("openai/gpt-4.1", PROVIDER, {
		name: "GPT-4.1",
		matchingModel: "gpt-4.1",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
	}),

	createModelConfig("openai/gpt-4o", PROVIDER, {
		name: "GPT-4o",
		matchingModel: "gpt-4o",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "May 13, 2024",
		lastUpdated: "May 13, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
	}),

	createModelConfig("openai/gpt-4-32k", PROVIDER, {
		name: "GPT-4 32K",
		matchingModel: "gpt-4-32k",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "November 2023",
		releaseDate: "March 14, 2023",
		lastUpdated: "March 14, 2023",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.06,
		costPer1kOutputTokens: 0.12,
	}),

	createModelConfig("openai/o3", PROVIDER, {
		name: "o3",
		matchingModel: "o3",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
	}),
]);
