import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "chutes";

export const chutesModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("chutesai/Devstral-Small-2505", PROVIDER, {
		name: "Devstral Small (2505)",
		matchingModel: "chutesai/Devstral-Small-2505",
		description:
			"Efficient small model optimized for fast text generation and tool use.",
		releaseDate: "May 21, 2025",
		lastUpdated: "May 21, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.00008,
	}),

	createModelConfig("chutesai/Mistral-Small-3.2-24B-Instruct-2506", PROVIDER, {
		name: "Mistral Small 3.2 24B Instruct 2506",
		matchingModel: "chutesai/Mistral-Small-3.2-24B-Instruct-2506",
		description:
			"Instruction-tuned 24B model for high-quality text tasks and tool calling.",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00006,
		costPer1kOutputTokens: 0.00018,
		supportsResponseFormat: true,
	}),

	createModelConfig("deepseek-ai/DeepSeek-V3-0324", PROVIDER, {
		name: "DeepSeek V3 (0324)",
		matchingModel: "deepseek-ai/DeepSeek-V3-0324",
		description: "Advanced DeepSeek V3 model hosted on Chutes.",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 75000,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00018,
		costPer1kOutputTokens: 0.00072,
	}),

	createModelConfig("deepseek-ai/DeepSeek-R1-0528", PROVIDER, {
		name: "DeepSeek R1 (0528)",
		matchingModel: "deepseek-ai/DeepSeek-R1-0528",
		description: "Reasoning-optimized DeepSeek R1 model.",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 75000,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00018,
		costPer1kOutputTokens: 0.00072,
	}),

	createModelConfig("deepseek-ai/DeepSeek-R1-Distill-Llama-70B", PROVIDER, {
		name: "DeepSeek R1 Distill Llama 70B",
		matchingModel: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
		description: "Reasoning-capable distilled Llama 70B model.",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00003,
		costPer1kOutputTokens: 0.00011,
		supportsResponseFormat: true,
	}),

	createModelConfig("deepseek-ai/DeepSeek-R1-0528-Qwen3-8B", PROVIDER, {
		name: "DeepSeek R1 0528 Qwen3 8B",
		matchingModel: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B",
		description: "Qwen3 8B distilled reasoning model hosted on Chutes.",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "May 29, 2025",
		lastUpdated: "May 29, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.00007,
	}),

	createModelConfig("moonshotai/Kimi-K2-Instruct-75k", PROVIDER, {
		name: "Kimi K2 Instruct",
		matchingModel: "moonshotai/Kimi-K2-Instruct-75k",
		description: "Kimi K2 instruction-tuned model with large context.",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 75000,
		maxTokens: 75000,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.00059,
	}),

	createModelConfig("Qwen/Qwen3-30B-A3B", PROVIDER, {
		name: "Qwen3 30B A3B",
		matchingModel: "Qwen/Qwen3-30B-A3B",
		description: "Qwen3 30B A3B model with reasoning support.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 40960,
		maxTokens: 40960,
		costPer1kInputTokens: 0.00006,
		costPer1kOutputTokens: 0.00022,
		supportsResponseFormat: true,
	}),

	createModelConfig("Qwen/Qwen3-235B-A22B-Instruct-2507", PROVIDER, {
		name: "Qwen3 235B A22B Instruct 2507",
		matchingModel: "Qwen/Qwen3-235B-A22B-Instruct-2507",
		description: "High-capacity instruction-tuned Qwen3 model.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 28, 2025",
		lastUpdated: "July 21, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 131072,
		costPer1kInputTokens: 0.000078,
		costPer1kOutputTokens: 0.000312,
	}),

	createModelConfig("Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct (FP8)",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8",
		description: "Large coder model with FP8 precision hosted on Chutes.",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0008,
	}),

	createModelConfig("Qwen/Qwen3-235B-A22B-Thinking-2507", PROVIDER, {
		name: "Qwen3 235B A22B Thinking 2507",
		matchingModel: "Qwen/Qwen3-235B-A22B-Thinking-2507",
		description: "Thinking-optimized Qwen3 model for complex reasoning tasks.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00011,
		costPer1kOutputTokens: 0.0006,
		supportsResponseFormat: true,
	}),

	createModelConfig("tngtech/DeepSeek-TNG-R1T2-Chimera", PROVIDER, {
		name: "DeepSeek TNG R1T2 Chimera",
		matchingModel: "tngtech/DeepSeek-TNG-R1T2-Chimera",
		description: "Hybrid reasoning Chimera model by TNGTech.",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.00085,
		supportsResponseFormat: true,
	}),

	createModelConfig("tngtech/DeepSeek-R1T-Chimera", PROVIDER, {
		name: "DeepSeek R1T Chimera",
		matchingModel: "tngtech/DeepSeek-R1T-Chimera",
		description: "Reasoning-focused R1T Chimera model by TNGTech.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: false,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		supportsResponseFormat: true,
	}),

	createModelConfig("zai-org/GLM-4.5-Air", PROVIDER, {
		name: "GLM 4.5 Air",
		matchingModel: "zai-org/GLM-4.5-Air",
		description: "GLM 4.5 Air hosted on Chutes.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.00022,
		supportsResponseFormat: true,
	}),

	createModelConfig("zai-org/GLM-4.5-FP8", PROVIDER, {
		name: "GLM 4.5 FP8",
		matchingModel: "zai-org/GLM-4.5-FP8",
		description: "GLM 4.5 FP8 hosted on Chutes.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		supportsResponseFormat: true,
	}),
	createModelConfig("chutesai/Mistral-Small-3.1-24B-Instruct-2503", PROVIDER, {
		name: "Mistral Small 3.1 24B Instruct 2503",
		matchingModel: "chutesai/Mistral-Small-3.1-24B-Instruct-2503",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00003,
		costPer1kOutputTokens: 0.00011,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("deepseek-ai/DeepSeek-R1-0528-TEE", PROVIDER, {
		name: "DeepSeek R1 0528 TEE",
		matchingModel: "deepseek-ai/DeepSeek-R1-0528-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 163840,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.00175,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek-ai/DeepSeek-R1-TEE", PROVIDER, {
		name: "DeepSeek R1 TEE",
		matchingModel: "deepseek-ai/DeepSeek-R1-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek-ai/DeepSeek-V3", PROVIDER, {
		name: "DeepSeek V3",
		matchingModel: "deepseek-ai/DeepSeek-V3",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("deepseek-ai/DeepSeek-V3-0324-TEE", PROVIDER, {
		name: "DeepSeek V3 0324 TEE",
		matchingModel: "deepseek-ai/DeepSeek-V3-0324-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 163840,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00019,
		costPer1kOutputTokens: 0.00087,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("deepseek-ai/DeepSeek-V3.1-TEE", PROVIDER, {
		name: "DeepSeek V3.1 TEE",
		matchingModel: "deepseek-ai/DeepSeek-V3.1-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 163840,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0008,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek-ai/DeepSeek-V3.1-Terminus-TEE", PROVIDER, {
		name: "DeepSeek V3.1 Terminus TEE",
		matchingModel: "deepseek-ai/DeepSeek-V3.1-Terminus-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 163840,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00023,
		costPer1kOutputTokens: 0.0009,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek-ai/DeepSeek-V3.2-Speciale-TEE", PROVIDER, {
		name: "DeepSeek V3.2 Speciale TEE",
		matchingModel: "deepseek-ai/DeepSeek-V3.2-Speciale-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 163840,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00027,
		costPer1kOutputTokens: 0.00041,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek-ai/DeepSeek-V3.2-TEE", PROVIDER, {
		name: "DeepSeek V3.2 TEE",
		matchingModel: "deepseek-ai/DeepSeek-V3.2-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 163840,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.00038,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("MiniMaxAI/MiniMax-M2.1-TEE", PROVIDER, {
		name: "MiniMax M2.1 TEE",
		matchingModel: "MiniMaxAI/MiniMax-M2.1-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 196608,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00027,
		costPer1kOutputTokens: 0.00112,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("miromind-ai/MiroThinker-v1.5-235B", PROVIDER, {
		name: "MiroThinker V1.5 235B",
		matchingModel: "miromind-ai/MiroThinker-v1.5-235B",
		releaseDate: "January 10, 2026",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: false,
		contextWindow: 32768,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("mistralai/Devstral-2-123B-Instruct-2512-TEE", PROVIDER, {
		name: "Devstral 2 123B Instruct 2512 TEE",
		matchingModel: "mistralai/Devstral-2-123B-Instruct-2512-TEE",
		releaseDate: "January 10, 2026",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.00022,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("moonshotai/Kimi-K2-Instruct-0905", PROVIDER, {
		name: "Kimi K2 Instruct 0905",
		matchingModel: "moonshotai/Kimi-K2-Instruct-0905",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00039,
		costPer1kOutputTokens: 0.0019,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("moonshotai/Kimi-K2-Thinking-TEE", PROVIDER, {
		name: "Kimi K2 Thinking TEE",
		matchingModel: "moonshotai/Kimi-K2-Thinking-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65535,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.00175,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("moonshotai/Kimi-K2.5-TEE", PROVIDER, {
		name: "Kimi K2.5 TEE",
		matchingModel: "moonshotai/Kimi-K2.5-TEE",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65535,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("NousResearch/DeepHermes-3-Mistral-24B-Preview", PROVIDER, {
		name: "DeepHermes 3 Mistral 24B Preview",
		matchingModel: "NousResearch/DeepHermes-3-Mistral-24B-Preview",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.0001,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("NousResearch/Hermes-4-14B", PROVIDER, {
		name: "Hermes 4 14B",
		matchingModel: "NousResearch/Hermes-4-14B",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 40960,
		maxTokens: 40960,
		costPer1kInputTokens: 0.00001,
		costPer1kOutputTokens: 0.00005,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("NousResearch/Hermes-4-405B-FP8-TEE", PROVIDER, {
		name: "Hermes 4 405B FP8 TEE",
		matchingModel: "NousResearch/Hermes-4-405B-FP8-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("NousResearch/Hermes-4-70B", PROVIDER, {
		name: "Hermes 4 70B",
		matchingModel: "NousResearch/Hermes-4-70B",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00011,
		costPer1kOutputTokens: 0.00038,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("NousResearch/Hermes-4.3-36B", PROVIDER, {
		name: "Hermes 4.3 36B",
		matchingModel: "NousResearch/Hermes-4.3-36B",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: false,
		contextWindow: 32768,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.00039,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16", PROVIDER, {
		name: "NVIDIA Nemotron 3 Nano 30B A3B BF16",
		matchingModel: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00006,
		costPer1kOutputTokens: 0.00024,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("openai/gpt-oss-120b-TEE", PROVIDER, {
		name: "gpt oss 120b TEE",
		matchingModel: "openai/gpt-oss-120b-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00004,
		costPer1kOutputTokens: 0.00018,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-oss-20b", PROVIDER, {
		name: "gpt oss 20b",
		matchingModel: "openai/gpt-oss-20b",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.0001,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("OpenGVLab/InternVL3-78B-TEE", PROVIDER, {
		name: "InternVL3 78B TEE",
		matchingModel: "OpenGVLab/InternVL3-78B-TEE",
		releaseDate: "January 6, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.00039,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen2.5-72B-Instruct", PROVIDER, {
		name: "Qwen2.5 72B Instruct",
		matchingModel: "Qwen/Qwen2.5-72B-Instruct",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00013,
		costPer1kOutputTokens: 0.00052,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen2.5-Coder-32B-Instruct", PROVIDER, {
		name: "Qwen2.5 Coder 32B Instruct",
		matchingModel: "Qwen/Qwen2.5-Coder-32B-Instruct",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00003,
		costPer1kOutputTokens: 0.00011,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen2.5-VL-32B-Instruct", PROVIDER, {
		name: "Qwen2.5 VL 32B Instruct",
		matchingModel: "Qwen/Qwen2.5-VL-32B-Instruct",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 16384,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.00022,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen2.5-VL-72B-Instruct-TEE", PROVIDER, {
		name: "Qwen2.5 VL 72B Instruct TEE",
		matchingModel: "Qwen/Qwen2.5-VL-72B-Instruct-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen3-14B", PROVIDER, {
		name: "Qwen3 14B",
		matchingModel: "Qwen/Qwen3-14B",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 40960,
		maxTokens: 40960,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.00022,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("Qwen/Qwen3-235B-A22B", PROVIDER, {
		name: "Qwen3 235B A22B",
		matchingModel: "Qwen/Qwen3-235B-A22B",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 40960,
		maxTokens: 40960,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("Qwen/Qwen3-235B-A22B-Instruct-2507-TEE", PROVIDER, {
		name: "Qwen3 235B A22B Instruct 2507 TEE",
		matchingModel: "Qwen/Qwen3-235B-A22B-Instruct-2507-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00008,
		costPer1kOutputTokens: 0.00055,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen3-30B-A3B-Instruct-2507", PROVIDER, {
		name: "Qwen3 30B A3B Instruct 2507",
		matchingModel: "Qwen/Qwen3-30B-A3B-Instruct-2507",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00008,
		costPer1kOutputTokens: 0.00033,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen3-32B", PROVIDER, {
		name: "Qwen3 32B",
		matchingModel: "Qwen/Qwen3-32B",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 40960,
		maxTokens: 40960,
		costPer1kInputTokens: 0.00008,
		costPer1kOutputTokens: 0.00024,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8-TEE", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct FP8 TEE",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00022,
		costPer1kOutputTokens: 0.00095,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen3-Coder-Next", PROVIDER, {
		name: "Qwen3 Coder Next",
		matchingModel: "Qwen/Qwen3-Coder-Next",
		releaseDate: "February 5, 2026",
		lastUpdated: "February 5, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00007,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen3-Next-80B-A3B-Instruct", PROVIDER, {
		name: "Qwen3 Next 80B A3B Instruct",
		matchingModel: "Qwen/Qwen3-Next-80B-A3B-Instruct",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0008,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen3-VL-235B-A22B-Instruct", PROVIDER, {
		name: "Qwen3 VL 235B A22B Instruct",
		matchingModel: "Qwen/Qwen3-VL-235B-A22B-Instruct",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("Qwen/Qwen3Guard-Gen-0.6B", PROVIDER, {
		name: "Qwen3Guard Gen 0.6B",
		matchingModel: "Qwen/Qwen3Guard-Gen-0.6B",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: false,
		contextWindow: 32768,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00001,
		costPer1kOutputTokens: 0.00001,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("rednote-hilab/dots.ocr", PROVIDER, {
		name: "dots.ocr",
		matchingModel: "rednote-hilab/dots.ocr",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00001,
		costPer1kOutputTokens: 0.00001,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("tngtech/TNG-R1T-Chimera-TEE", PROVIDER, {
		name: "TNG R1T Chimera TEE",
		matchingModel: "tngtech/TNG-R1T-Chimera-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 163840,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.00085,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("tngtech/TNG-R1T-Chimera-Turbo", PROVIDER, {
		name: "TNG R1T Chimera Turbo",
		matchingModel: "tngtech/TNG-R1T-Chimera-Turbo",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 163840,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00022,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("unsloth/gemma-3-12b-it", PROVIDER, {
		name: "gemma 3 12b it",
		matchingModel: "unsloth/gemma-3-12b-it",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00003,
		costPer1kOutputTokens: 0.0001,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("unsloth/gemma-3-27b-it", PROVIDER, {
		name: "gemma 3 27b it",
		matchingModel: "unsloth/gemma-3-27b-it",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 96000,
		maxTokens: 96000,
		costPer1kInputTokens: 0.00004,
		costPer1kOutputTokens: 0.00015,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("unsloth/gemma-3-4b-it", PROVIDER, {
		name: "gemma 3 4b it",
		matchingModel: "unsloth/gemma-3-4b-it",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 96000,
		maxTokens: 96000,
		costPer1kInputTokens: 0.00001,
		costPer1kOutputTokens: 0.00003,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("unsloth/Llama-3.2-1B-Instruct", PROVIDER, {
		name: "Llama 3.2 1B Instruct",
		matchingModel: "unsloth/Llama-3.2-1B-Instruct",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: false,
		contextWindow: 32768,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00001,
		costPer1kOutputTokens: 0.00001,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("unsloth/Mistral-Nemo-Instruct-2407", PROVIDER, {
		name: "Mistral Nemo Instruct 2407",
		matchingModel: "unsloth/Mistral-Nemo-Instruct-2407",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.00004,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("unsloth/Mistral-Small-24B-Instruct-2501", PROVIDER, {
		name: "Mistral Small 24B Instruct 2501",
		matchingModel: "unsloth/Mistral-Small-24B-Instruct-2501",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00003,
		costPer1kOutputTokens: 0.00011,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("XiaomiMiMo/MiMo-V2-Flash", PROVIDER, {
		name: "MiMo V2 Flash",
		matchingModel: "XiaomiMiMo/MiMo-V2-Flash",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: false,
		contextWindow: 32768,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00009,
		costPer1kOutputTokens: 0.00029,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("zai-org/GLM-4.5-TEE", PROVIDER, {
		name: "GLM 4.5 TEE",
		matchingModel: "zai-org/GLM-4.5-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00035,
		costPer1kOutputTokens: 0.00155,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("zai-org/GLM-4.6-FP8", PROVIDER, {
		name: "GLM 4.6 FP8",
		matchingModel: "zai-org/GLM-4.6-FP8",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 65535,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("zai-org/GLM-4.6-TEE", PROVIDER, {
		name: "GLM 4.6 TEE",
		matchingModel: "zai-org/GLM-4.6-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00035,
		costPer1kOutputTokens: 0.0015,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("zai-org/GLM-4.6V", PROVIDER, {
		name: "GLM 4.6V",
		matchingModel: "zai-org/GLM-4.6V",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0009,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("zai-org/GLM-4.7-Flash", PROVIDER, {
		name: "GLM 4.7 Flash",
		matchingModel: "zai-org/GLM-4.7-Flash",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 65535,
		costPer1kInputTokens: 0.00006,
		costPer1kOutputTokens: 0.00035,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("zai-org/GLM-4.7-FP8", PROVIDER, {
		name: "GLM 4.7 FP8",
		matchingModel: "zai-org/GLM-4.7-FP8",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 65535,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("zai-org/GLM-4.7-TEE", PROVIDER, {
		name: "GLM 4.7 TEE",
		matchingModel: "zai-org/GLM-4.7-TEE",
		releaseDate: "December 29, 2025",
		lastUpdated: "January 10, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 65535,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0015,
		reasoningConfig: {
			enabled: true,
		},
	}),
]);
