import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "chutes";

export const chutesModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("chutesai/Devstral-Small-2505", PROVIDER, {
		name: "Devstral Small (2505)",
		matchingModel: "chutesai/Devstral-Small-2505",
		description:
			"Efficient small model optimized for fast text generation and tool use.",
		releaseDate: "May 21, 2025",
		lastUpdated: "May 21, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.00008,
	}),

	createModelConfig("chutesai/Mistral-Small-3.2-24B-Instruct-2506", PROVIDER, {
		name: "Mistral Small 3.2 24B Instruct (2506)",
		matchingModel: "chutesai/Mistral-Small-3.2-24B-Instruct-2506",
		description:
			"Instruction-tuned 24B model for high-quality text tasks and tool calling.",
		releaseDate: "June 20, 2025",
		lastUpdated: "June 20, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.00008,
	}),

	createModelConfig("deepseek-ai/DeepSeek-V3-0324", PROVIDER, {
		name: "DeepSeek V3 (0324)",
		matchingModel: "deepseek-ai/DeepSeek-V3-0324",
		description: "Advanced DeepSeek V3 model hosted on Chutes.",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 75000,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00018,
		costPer1kOutputTokens: 0.00072,
	}),

	createModelConfig("deepseek-ai/DeepSeek-R1-0528", PROVIDER, {
		name: "DeepSeek R1 (0528)",
		matchingModel: "deepseek-ai/DeepSeek-R1-0528",
		description: "Reasoning-optimized DeepSeek R1 model.",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 75000,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00018,
		costPer1kOutputTokens: 0.00072,
	}),

	createModelConfig("deepseek-ai/DeepSeek-R1-Distill-Llama-70B", PROVIDER, {
		name: "DeepSeek R1 Distill Llama 70B",
		matchingModel: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
		description: "Reasoning-capable distilled Llama 70B model.",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "January 23, 2025",
		lastUpdated: "January 23, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: false,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00003,
		costPer1kOutputTokens: 0.00014,
	}),

	createModelConfig("deepseek-ai/DeepSeek-R1-0528-Qwen3-8B", PROVIDER, {
		name: "DeepSeek R1 0528 Qwen3 8B",
		matchingModel: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B",
		description: "Qwen3 8B distilled reasoning model hosted on Chutes.",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "May 29, 2025",
		lastUpdated: "May 29, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.00007,
	}),

	createModelConfig("moonshotai/Kimi-K2-Instruct-75k", PROVIDER, {
		name: "Kimi K2 Instruct",
		matchingModel: "moonshotai/Kimi-K2-Instruct-75k",
		description: "Kimi K2 instruction-tuned model with large context.",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 75000,
		maxTokens: 75000,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.00059,
	}),

	createModelConfig("Qwen/Qwen3-30B-A3B", PROVIDER, {
		name: "Qwen3 30B A3B",
		matchingModel: "Qwen/Qwen3-30B-A3B",
		description: "Qwen3 30B A3B model with reasoning support.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 28, 2025",
		lastUpdated: "April 28, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 40960,
		maxTokens: 40960,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.00008,
	}),

	createModelConfig("Qwen/Qwen3-235B-A22B-Instruct-2507", PROVIDER, {
		name: "Qwen3 235B A22B Instruct 2507",
		matchingModel: "Qwen/Qwen3-235B-A22B-Instruct-2507",
		description: "High-capacity instruction-tuned Qwen3 model.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 28, 2025",
		lastUpdated: "July 21, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 131072,
		costPer1kInputTokens: 0.000078,
		costPer1kOutputTokens: 0.000312,
	}),

	createModelConfig("Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct (FP8)",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8",
		description: "Large coder model with FP8 precision hosted on Chutes.",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0008,
	}),

	createModelConfig("Qwen/Qwen3-235B-A22B-Thinking-2507", PROVIDER, {
		name: "Qwen3-235B-A22B-Thinking-2507",
		matchingModel: "Qwen/Qwen3-235B-A22B-Thinking-2507",
		description: "Thinking-optimized Qwen3 model for complex reasoning tasks.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 25, 2025",
		lastUpdated: "July 25, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.000078,
		costPer1kOutputTokens: 0.000312,
	}),

	createModelConfig("tngtech/DeepSeek-TNG-R1T2-Chimera", PROVIDER, {
		name: "DeepSeek TNG R1T2 Chimera",
		matchingModel: "tngtech/DeepSeek-TNG-R1T2-Chimera",
		description: "Hybrid reasoning Chimera model by TNGTech.",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "July 8, 2025",
		lastUpdated: "July 8, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: false,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0008,
	}),

	createModelConfig("tngtech/DeepSeek-R1T-Chimera", PROVIDER, {
		name: "DeepSeek R1T Chimera",
		matchingModel: "tngtech/DeepSeek-R1T-Chimera",
		description: "Reasoning-focused R1T Chimera model by TNGTech.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 26, 2025",
		lastUpdated: "April 26, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: false,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00018,
		costPer1kOutputTokens: 0.00072,
	}),

	createModelConfig("zai-org/GLM-4.5-Air", PROVIDER, {
		name: "GLM 4.5 Air",
		matchingModel: "zai-org/GLM-4.5-Air",
		description: "GLM 4.5 Air hosted on Chutes.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 98304,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("zai-org/GLM-4.5-FP8", PROVIDER, {
		name: "GLM 4.5 FP8",
		matchingModel: "zai-org/GLM-4.5-FP8",
		description: "GLM 4.5 FP8 hosted on Chutes.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: { input: ["text"], output: ["text"] },
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),
]);
