import type { ModelConfig } from "~/types";
import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "cortecs";

export const cortecsModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("claude-4-5-sonnet", PROVIDER, {
		name: "Claude 4.5 Sonnet",
		matchingModel: "claude-4-5-sonnet",
		knowledgeCutoffDate: "July 31, 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.003259,
		costPer1kOutputTokens: 0.016296,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-4-6-sonnet", PROVIDER, {
		name: "Claude Sonnet 4.6",
		matchingModel: "claude-4-6-sonnet",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 17, 2026",
		lastUpdated: "March 13, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 1000000,
		costPer1kInputTokens: 0.00359,
		costPer1kOutputTokens: 0.01792,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-haiku-4-5", PROVIDER, {
		name: "Claude Haiku 4.5",
		matchingModel: "claude-haiku-4-5",
		knowledgeCutoffDate: "February 28, 2025",
		releaseDate: "October 15, 2025",
		lastUpdated: "October 15, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.00109,
		costPer1kOutputTokens: 0.00543,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus4-5", PROVIDER, {
		name: "Claude Opus 4.5",
		matchingModel: "claude-opus4-5",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "November 24, 2025",
		lastUpdated: "November 24, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.00598,
		costPer1kOutputTokens: 0.02989,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus4-6", PROVIDER, {
		name: "Claude Opus 4.6",
		matchingModel: "claude-opus4-6",
		knowledgeCutoffDate: "May 31, 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "March 13, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 1000000,
		costPer1kInputTokens: 0.00598,
		costPer1kOutputTokens: 0.02989,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus4-7", PROVIDER, {
		name: "Claude Opus 4.7",
		matchingModel: "claude-opus4-7",
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "April 16, 2026",
		lastUpdated: "April 16, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0056,
		costPer1kOutputTokens: 0.02799,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-sonnet-4", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "claude-sonnet-4",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003307,
		costPer1kOutputTokens: 0.016536,
	}),

	createModelConfig("codestral-2508", PROVIDER, {
		name: "Codestral 2508",
		matchingModel: "codestral-2508",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "July 30, 2025",
		lastUpdated: "July 30, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0009,
	}),

	createModelConfig("deepseek-r1-0528", PROVIDER, {
		name: "DeepSeek R1 0528",
		matchingModel: "deepseek-r1-0528",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "May 28, 2025",
		lastUpdated: "May 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 164000,
		maxTokens: 164000,
		costPer1kInputTokens: 0.000585,
		costPer1kOutputTokens: 0.002307,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("deepseek-v3-0324", PROVIDER, {
		name: "DeepSeek V3 0324",
		matchingModel: "deepseek-v3-0324",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "March 24, 2025",
		lastUpdated: "March 24, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000551,
		costPer1kOutputTokens: 0.001654,
	}),

	createModelConfig("deepseek-v3.2", PROVIDER, {
		name: "DeepSeek V3.2",
		matchingModel: "deepseek-v3.2",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "December 1, 2025",
		lastUpdated: "December 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.000266,
		costPer1kOutputTokens: 0.000444,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("deepseek-v4-flash", PROVIDER, {
		name: "DeepSeek V4 Flash",
		matchingModel: "deepseek-v4-flash",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 384000,
		costPer1kInputTokens: 0.000133,
		costPer1kOutputTokens: 0.000266,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("deepseek-v4-pro", PROVIDER, {
		name: "DeepSeek V4 Pro",
		matchingModel: "deepseek-v4-pro",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 384000,
		costPer1kInputTokens: 0.001553,
		costPer1kOutputTokens: 0.003106,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("devstral-2512", PROVIDER, {
		name: "Devstral 2 2512",
		matchingModel: "devstral-2512",
		knowledgeCutoffDate: "December 2025",
		releaseDate: "December 9, 2025",
		lastUpdated: "December 9, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("devstral-small-2512", PROVIDER, {
		name: "Devstral Small 2 2512",
		matchingModel: "devstral-small-2512",
		knowledgeCutoffDate: "December 2025",
		releaseDate: "December 9, 2025",
		lastUpdated: "December 9, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("gemini-2.5-pro", PROVIDER, {
		name: "Gemini 2.5 Pro",
		matchingModel: "gemini-2.5-pro",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "March 20, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65535,
		costPer1kInputTokens: 0.001654,
		costPer1kOutputTokens: 0.011024,
	}),

	createModelConfig("glm-4.5", PROVIDER, {
		name: "GLM 4.5",
		matchingModel: "glm-4.5",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 29, 2025",
		lastUpdated: "July 29, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00067,
		costPer1kOutputTokens: 0.00246,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.5-air", PROVIDER, {
		name: "GLM 4.5 Air",
		matchingModel: "glm-4.5-air",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00022,
		costPer1kOutputTokens: 0.00134,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.7", PROVIDER, {
		name: "GLM 4.7",
		matchingModel: "glm-4.7",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 22, 2025",
		lastUpdated: "December 22, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 198000,
		maxTokens: 198000,
		costPer1kInputTokens: 0.00045,
		costPer1kOutputTokens: 0.00223,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.7-flash", PROVIDER, {
		name: "GLM-4.7-Flash",
		matchingModel: "glm-4.7-flash",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "August 8, 2025",
		lastUpdated: "August 8, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 203000,
		maxTokens: 203000,
		costPer1kInputTokens: 0.00009,
		costPer1kOutputTokens: 0.00053,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5", PROVIDER, {
		name: "GLM 5",
		matchingModel: "glm-5",
		releaseDate: "February 11, 2026",
		lastUpdated: "February 11, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 202752,
		costPer1kInputTokens: 0.00108,
		costPer1kOutputTokens: 0.00344,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.1", PROVIDER, {
		name: "GLM-5.1",
		matchingModel: "glm-5.1",
		releaseDate: "April 14, 2026",
		lastUpdated: "April 14, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00131,
		costPer1kOutputTokens: 0.0041,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-4.1", PROVIDER, {
		name: "GPT 4.1",
		matchingModel: "gpt-4.1",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.002354,
		costPer1kOutputTokens: 0.009417,
	}),

	createModelConfig("gpt-oss-120b", PROVIDER, {
		name: "GPT Oss 120b",
		matchingModel: "gpt-oss-120b",
		knowledgeCutoffDate: "January 2024",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("hermes-4-70b", PROVIDER, {
		name: "Hermes 4 70B",
		matchingModel: "hermes-4-70b",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "August 26, 2025",
		lastUpdated: "August 26, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000116,
		costPer1kOutputTokens: 0.000358,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("intellect-3", PROVIDER, {
		name: "INTELLECT 3",
		matchingModel: "intellect-3",
		knowledgeCutoffDate: "November 2025",
		releaseDate: "November 26, 2025",
		lastUpdated: "November 26, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000219,
		costPer1kOutputTokens: 0.001202,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2-instruct", PROVIDER, {
		name: "Kimi K2 Instruct",
		matchingModel: "kimi-k2-instruct",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "July 11, 2025",
		lastUpdated: "September 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.000551,
		costPer1kOutputTokens: 0.002646,
	}),

	createModelConfig("kimi-k2-thinking", PROVIDER, {
		name: "Kimi K2 Thinking",
		matchingModel: "kimi-k2-thinking",
		knowledgeCutoffDate: "December 2025",
		releaseDate: "December 8, 2025",
		lastUpdated: "December 8, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000656,
		costPer1kOutputTokens: 0.002731,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2.5", PROVIDER, {
		name: "Kimi K2.5",
		matchingModel: "kimi-k2.5",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.00055,
		costPer1kOutputTokens: 0.00276,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2.6", PROVIDER, {
		name: "Kimi K2.6",
		matchingModel: "kimi-k2.6",
		releaseDate: "April 17, 2026",
		lastUpdated: "April 17, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.00081,
		costPer1kOutputTokens: 0.00354,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("llama-3.1-405b-instruct", PROVIDER, {
		name: "Llama 3.1 405B Instruct",
		matchingModel: "llama-3.1-405b-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "July 23, 2024",
		lastUpdated: "July 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("llama-3.3-70b-instruct", PROVIDER, {
		name: "Llama 3.3 70B Instruct",
		matchingModel: "llama-3.3-70b-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "December 6, 2024",
		lastUpdated: "December 6, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.000089,
		costPer1kOutputTokens: 0.000275,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m2", PROVIDER, {
		name: "MiniMax-M2",
		matchingModel: "minimax-m2",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "October 27, 2025",
		lastUpdated: "October 27, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 400000,
		costPer1kInputTokens: 0.00039,
		costPer1kOutputTokens: 0.00157,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m2.1", PROVIDER, {
		name: "MiniMax-M2.1",
		matchingModel: "minimax-m2.1",
		releaseDate: "December 23, 2025",
		lastUpdated: "December 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 196000,
		maxTokens: 196000,
		costPer1kInputTokens: 0.00034,
		costPer1kOutputTokens: 0.00134,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m2.5", PROVIDER, {
		name: "MiniMax-M2.5",
		matchingModel: "minimax-m2.5",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 196608,
		maxTokens: 196608,
		costPer1kInputTokens: 0.00032,
		costPer1kOutputTokens: 0.00118,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m2.7", PROVIDER, {
		name: "MiniMax-m2.7",
		matchingModel: "minimax-m2.7",
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 196072,
		costPer1kInputTokens: 0.00047,
		costPer1kOutputTokens: 0.0014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("mistral-large-2512", PROVIDER, {
		name: "Mistral Large 3 2512",
		matchingModel: "mistral-large-2512",
		knowledgeCutoffDate: "December 2025",
		releaseDate: "December 1, 2025",
		lastUpdated: "December 1, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.0015,
	}),

	createModelConfig("mixtral-8x7B-instruct-v0.1", PROVIDER, {
		name: "Mixtral 8x7B Instruct v0.1",
		matchingModel: "mixtral-8x7B-instruct-v0.1",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "December 11, 2023",
		lastUpdated: "December 11, 2023",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.000438,
		costPer1kOutputTokens: 0.00068,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("nemotron-3-super-120b-a12b", PROVIDER, {
		name: "Nemotron 3 Super 120B A12B",
		matchingModel: "nemotron-3-super-120b-a12b",
		knowledgeCutoffDate: "December 2025",
		releaseDate: "March 11, 2026",
		lastUpdated: "March 11, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.000266,
		costPer1kOutputTokens: 0.000799,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("nova-pro-v1", PROVIDER, {
		name: "Nova Pro 1.0",
		matchingModel: "nova-pro-v1",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "December 3, 2024",
		lastUpdated: "December 3, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 300000,
		maxTokens: 5000,
		costPer1kInputTokens: 0.001016,
		costPer1kOutputTokens: 0.004061,
	}),

	createModelConfig("qwen-2.5-72b-instruct", PROVIDER, {
		name: "Qwen2.5 72B Instruct",
		matchingModel: "qwen-2.5-72b-instruct",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "September 19, 2024",
		lastUpdated: "September 19, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 33000,
		maxTokens: 33000,
		costPer1kInputTokens: 0.000062,
		costPer1kOutputTokens: 0.000231,
	}),

	createModelConfig("qwen3-235b-a22b-instruct-2507", PROVIDER, {
		name: "Qwen3 235B A22B Instruct 2507",
		matchingModel: "qwen3-235b-a22b-instruct-2507",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.000062,
		costPer1kOutputTokens: 0.000408,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-32b", PROVIDER, {
		name: "Qwen3 32B",
		matchingModel: "qwen3-32b",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "April 29, 2025",
		lastUpdated: "April 29, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 16384,
		maxTokens: 16384,
		costPer1kInputTokens: 0.000099,
		costPer1kOutputTokens: 0.00033,
	}),

	createModelConfig("qwen3-coder-30b-a3b-instruct", PROVIDER, {
		name: "Qwen3 Coder 30B A3B Instruct",
		matchingModel: "qwen3-coder-30b-a3b-instruct",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 31, 2025",
		lastUpdated: "July 31, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000053,
		costPer1kOutputTokens: 0.000222,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-coder-480b-a35b-instruct", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct",
		matchingModel: "qwen3-coder-480b-a35b-instruct",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "July 25, 2025",
		lastUpdated: "July 25, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000441,
		costPer1kOutputTokens: 0.001984,
	}),

	createModelConfig("qwen3-coder-next", PROVIDER, {
		name: "Qwen3 Coder Next 80B",
		matchingModel: "qwen3-coder-next",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "February 4, 2026",
		lastUpdated: "February 4, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.000158,
		costPer1kOutputTokens: 0.00084,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-next-80b-a3b-thinking", PROVIDER, {
		name: "Qwen3 Next 80B A3B Thinking",
		matchingModel: "qwen3-next-80b-a3b-thinking",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 11, 2025",
		lastUpdated: "September 11, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000164,
		costPer1kOutputTokens: 0.001311,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.5-122b-a10b", PROVIDER, {
		name: "Qwen3.5 122B A10B",
		matchingModel: "qwen3.5-122b-a10b",
		knowledgeCutoffDate: "January 2026",
		releaseDate: "February 24, 2026",
		lastUpdated: "February 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.000444,
		costPer1kOutputTokens: 0.003106,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.5-397b-a17b", PROVIDER, {
		name: "Qwen3.5 397B A17B",
		matchingModel: "qwen3.5-397b-a17b",
		knowledgeCutoffDate: "January 2026",
		releaseDate: "February 16, 2026",
		lastUpdated: "February 16, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 250000,
		maxTokens: 250000,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0036,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
]);
