import type { ModelConfig } from "@assistant/schemas";
import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "cortecs";

export const cortecsModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("claude-4-5-sonnet", PROVIDER, {
		name: "Claude 4.5 Sonnet",
		matchingModel: "claude-4-5-sonnet",
		knowledgeCutoffDate: "July 31, 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.002989,
		costPer1kOutputTokens: 0.014945,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 29.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-sonnet",
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("claude-4-6-sonnet", PROVIDER, {
		name: "Claude Sonnet 4.6",
		matchingModel: "claude-4-6-sonnet",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 17, 2026",
		lastUpdated: "March 13, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 1000000,
		costPer1kInputTokens: 0.003196,
		costPer1kOutputTokens: 0.01594,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 47.2,
			codingIndex: 63,
			agenticIndex: 40.8,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-sonnet",
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("claude-haiku-4-5", PROVIDER, {
		name: "Claude Haiku 4.5",
		matchingModel: "claude-haiku-4-5",
		knowledgeCutoffDate: "February 28, 2025",
		releaseDate: "October 15, 2025",
		lastUpdated: "October 15, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.000996,
		costPer1kOutputTokens: 0.004982,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "claude-haiku",
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("claude-opus4-5", PROVIDER, {
		name: "Claude Opus 4.5",
		matchingModel: "claude-opus4-5",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "November 24, 2025",
		lastUpdated: "November 24, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.005313,
		costPer1kOutputTokens: 0.026568,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 34.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-opus",
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("claude-opus4-6", PROVIDER, {
		name: "Claude Opus 4.6",
		matchingModel: "claude-opus4-6",
		knowledgeCutoffDate: "May 31, 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "March 13, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 1000000,
		costPer1kInputTokens: 0.005313,
		costPer1kOutputTokens: 0.026561,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 43.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-opus",
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("claude-opus4-7", PROVIDER, {
		name: "Claude Opus 4.7",
		matchingModel: "claude-opus4-7",
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "April 16, 2026",
		lastUpdated: "April 16, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 1000000,
		costPer1kInputTokens: 0.005437,
		costPer1kOutputTokens: 0.027186,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 53.5,
			codingIndex: 73.6,
			agenticIndex: 44.4,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-opus",
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("claude-sonnet-4", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "claude-sonnet-4",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.002898,
		costPer1kOutputTokens: 0.014493,
		family: "claude-sonnet",
		openWeights: false,
		supportsResponseFormat: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("codestral-2508", PROVIDER, {
		name: "Codestral 2508",
		matchingModel: "codestral-2508",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "July 30, 2025",
		lastUpdated: "July 30, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.000334,
		costPer1kOutputTokens: 0.001003,
		family: "mistral",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("deepseek-r1-0528", PROVIDER, {
		name: "DeepSeek R1 0528",
		matchingModel: "deepseek-r1-0528",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "May 28, 2025",
		lastUpdated: "May 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 164000,
		maxTokens: 164000,
		costPer1kInputTokens: 0.000652,
		costPer1kOutputTokens: 0.00257,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 20.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek-thinking",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("deepseek-v3-0324", PROVIDER, {
		name: "DeepSeek V3 0324",
		matchingModel: "deepseek-v3-0324",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "March 24, 2025",
		lastUpdated: "March 24, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000551,
		costPer1kOutputTokens: 0.001654,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 15.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek",
		openWeights: true,
	}),

	createModelConfig("deepseek-v3.2", PROVIDER, {
		name: "DeepSeek V3.2",
		matchingModel: "deepseek-v3.2",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "December 1, 2025",
		lastUpdated: "December 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.000296,
		costPer1kOutputTokens: 0.000495,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 24.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("deepseek-v4-pro", PROVIDER, {
		name: "DeepSeek V4 Pro",
		matchingModel: "deepseek-v4-pro",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.00173,
		costPer1kOutputTokens: 0.00346,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 31.2,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek-thinking",
		openWeights: true,
	}),

	createModelConfig("devstral-2512", PROVIDER, {
		name: "Devstral 2 2512",
		matchingModel: "devstral-2512",
		knowledgeCutoffDate: "December 2025",
		releaseDate: "December 9, 2025",
		lastUpdated: "December 9, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000446,
		costPer1kOutputTokens: 0.002228,
		openWeights: true,
		family: "devstral",
		supportsResponseFormat: true,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 15.5,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("devstral-small-2512", PROVIDER, {
		name: "Devstral Small 2 2512",
		matchingModel: "devstral-small-2512",
		knowledgeCutoffDate: "December 2025",
		releaseDate: "December 9, 2025",
		lastUpdated: "December 9, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("gemini-2.5-pro", PROVIDER, {
		name: "Gemini 2.5 Pro",
		matchingModel: "gemini-2.5-pro",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65535,
		costPer1kInputTokens: 0.001495,
		costPer1kOutputTokens: 0.009964,
		strengths: ["vision", "tool_use", "document"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 27,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		speed: 3,
		family: "gemini-pro",
		openWeights: false,
		supportsResponseFormat: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.5", PROVIDER, {
		name: "GLM 4.5",
		matchingModel: "glm-4.5",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 29, 2025",
		lastUpdated: "July 29, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00067,
		costPer1kOutputTokens: 0.00246,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 19.5,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	}),

	createModelConfig("glm-4.5-air", PROVIDER, {
		name: "GLM 4.5 Air",
		matchingModel: "glm-4.5-air",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00022,
		costPer1kOutputTokens: 0.00134,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 16.5,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm-air",
		openWeights: true,
	}),

	createModelConfig("glm-4.7", PROVIDER, {
		name: "GLM 4.7",
		matchingModel: "glm-4.7",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 22, 2025",
		lastUpdated: "December 22, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 198000,
		costPer1kInputTokens: 0.00078,
		costPer1kOutputTokens: 0.002785,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 26.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("glm-4.7-flash", PROVIDER, {
		name: "GLM-4.7-Flash",
		matchingModel: "glm-4.7-flash",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "January 19, 2026",
		lastUpdated: "January 19, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 203000,
		maxTokens: 203000,
		costPer1kInputTokens: 0.00008,
		costPer1kOutputTokens: 0.000478,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 15.5,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm-flash",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("glm-5", PROVIDER, {
		name: "GLM 5",
		matchingModel: "glm-5",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 202752,
		costPer1kInputTokens: 0.000988,
		costPer1kOutputTokens: 0.003164,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 32.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("glm-5.1", PROVIDER, {
		name: "GLM-5.1",
		matchingModel: "glm-5.1",
		releaseDate: "April 7, 2026",
		lastUpdated: "April 7, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 202752,
		costPer1kInputTokens: 0.001384,
		costPer1kOutputTokens: 0.004348,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 35.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	}),

	createModelConfig("gpt-4.1", PROVIDER, {
		name: "GPT 4.1",
		matchingModel: "gpt-4.1",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1047576,
		maxTokens: 1047576,
		costPer1kInputTokens: 0.002192,
		costPer1kOutputTokens: 0.008769,
		strengths: ["vision", "tool_use", "document"],
		contextComplexity: 5,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 19.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
		supportsResponseFormat: false,
	}),

	createModelConfig("gpt-oss-120b", PROVIDER, {
		name: "GPT Oss 120b",
		matchingModel: "gpt-oss-120b",
		knowledgeCutoffDate: "January 2024",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000089,
		costPer1kOutputTokens: 0.000446,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 23.8,
			codingIndex: 30.4,
			agenticIndex: 13.2,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-oss",
		openWeights: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		supportsResponseFormat: true,
	}),

	createModelConfig("hermes-4-70b", PROVIDER, {
		name: "Hermes 4 70B",
		matchingModel: "hermes-4-70b",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "August 26, 2025",
		lastUpdated: "August 26, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000129,
		costPer1kOutputTokens: 0.000399,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("intellect-3", PROVIDER, {
		name: "INTELLECT 3",
		matchingModel: "intellect-3",
		knowledgeCutoffDate: "November 2025",
		releaseDate: "November 26, 2025",
		lastUpdated: "November 26, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000219,
		costPer1kOutputTokens: 0.001202,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 15.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		openWeights: true,
	}),

	createModelConfig("kimi-k2-instruct", PROVIDER, {
		name: "Kimi K2 Instruct",
		matchingModel: "kimi-k2-instruct",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "July 11, 2025",
		lastUpdated: "September 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.000551,
		costPer1kOutputTokens: 0.002646,
		family: "kimi-k2",
		openWeights: true,
	}),

	createModelConfig("kimi-k2-thinking", PROVIDER, {
		name: "Kimi K2 Thinking",
		matchingModel: "kimi-k2-thinking",
		knowledgeCutoffDate: "December 2025",
		releaseDate: "December 8, 2025",
		lastUpdated: "December 8, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000656,
		costPer1kOutputTokens: 0.002731,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 32.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		openWeights: true,
	}),

	createModelConfig("kimi-k2.5", PROVIDER, {
		name: "Kimi K2.5",
		matchingModel: "kimi-k2.5",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 2026",
		lastUpdated: "January 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 256000,
		costPer1kInputTokens: 0.000495,
		costPer1kOutputTokens: 0.002768,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "tool_use", "document"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 29.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-k2",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("kimi-k2.6", PROVIDER, {
		name: "Kimi K2.6",
		matchingModel: "kimi-k2.6",
		releaseDate: "April 21, 2026",
		lastUpdated: "April 21, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 256000,
		costPer1kInputTokens: 0.000773,
		costPer1kOutputTokens: 0.00338,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "tool_use", "document"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 42.8,
			codingIndex: 56,
			agenticIndex: 30.3,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-k2",
		openWeights: true,
		knowledgeCutoffDate: "January 2025",
		supportsResponseFormat: true,
	}),

	createModelConfig("llama-3.1-405b-instruct", PROVIDER, {
		name: "Llama 3.1 405B Instruct",
		matchingModel: "llama-3.1-405b-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "July 23, 2024",
		lastUpdated: "July 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00195,
		costPer1kOutputTokens: 0.00195,
		family: "llama",
		openWeights: true,
		supportsResponseFormat: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("llama-3.3-70b-instruct", PROVIDER, {
		name: "Llama 3.3 70B Instruct",
		matchingModel: "llama-3.3-70b-instruct",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "December 6, 2024",
		lastUpdated: "December 6, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.000129,
		costPer1kOutputTokens: 0.000399,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "llama",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("minimax-m2", PROVIDER, {
		name: "MiniMax-M2",
		matchingModel: "minimax-m2",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "October 27, 2025",
		lastUpdated: "October 27, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 400000,
		costPer1kInputTokens: 0.000349,
		costPer1kOutputTokens: 0.001405,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 28.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("minimax-m2.1", PROVIDER, {
		name: "MiniMax-M2.1",
		matchingModel: "minimax-m2.1",
		releaseDate: "December 23, 2025",
		lastUpdated: "December 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 196000,
		maxTokens: 196000,
		costPer1kInputTokens: 0.000359,
		costPer1kOutputTokens: 0.001435,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 31.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("minimax-m2.5", PROVIDER, {
		name: "MiniMax-M2.5",
		matchingModel: "minimax-m2.5",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 196680,
		maxTokens: 196608,
		costPer1kInputTokens: 0.000296,
		costPer1kOutputTokens: 0.001087,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 33.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("minimax-m2.7", PROVIDER, {
		name: "MiniMax-m2.7",
		matchingModel: "minimax-m2.7",
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 196608,
		maxTokens: 196072,
		costPer1kInputTokens: 0.000668,
		costPer1kOutputTokens: 0.002674,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 38.1,
			codingIndex: 52.6,
			agenticIndex: 25.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
	}),

	createModelConfig("mistral-large-2512", PROVIDER, {
		name: "Mistral Large 3 2512",
		matchingModel: "mistral-large-2512",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "November 1, 2024",
		lastUpdated: "December 2, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.000557,
		costPer1kOutputTokens: 0.001671,
		family: "mistral-large",
		openWeights: true,
		supportsResponseFormat: true,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 15.9,
			codingIndex: 20.1,
			agenticIndex: 5.5,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("mixtral-8x7B-instruct-v0.1", PROVIDER, {
		name: "Mixtral 8x7B Instruct v0.1",
		matchingModel: "mixtral-8x7B-instruct-v0.1",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "December 11, 2023",
		lastUpdated: "December 11, 2023",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.000488,
		costPer1kOutputTokens: 0.000758,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("nemotron-3-super-120b-a12b", PROVIDER, {
		name: "Nemotron 3 Super 120B A12B",
		matchingModel: "nemotron-3-super-120b-a12b",
		knowledgeCutoffDate: "December 2025",
		releaseDate: "March 11, 2026",
		lastUpdated: "March 11, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.000266,
		costPer1kOutputTokens: 0.000799,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "nemotron",
		openWeights: true,
	}),

	createModelConfig("nova-pro-v1", PROVIDER, {
		name: "Nova Pro 1.0",
		matchingModel: "nova-pro-v1",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "December 3, 2024",
		lastUpdated: "December 3, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 300000,
		maxTokens: 5000,
		costPer1kInputTokens: 0.000918,
		costPer1kOutputTokens: 0.003671,
		family: "nova-pro",
		openWeights: false,
		supportsResponseFormat: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen-2.5-72b-instruct", PROVIDER, {
		name: "Qwen2.5 72B Instruct",
		matchingModel: "qwen-2.5-72b-instruct",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "September 19, 2024",
		lastUpdated: "September 19, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 33000,
		maxTokens: 33000,
		costPer1kInputTokens: 0.000062,
		costPer1kOutputTokens: 0.000231,
		strengths: ["tool_use"],
		contextComplexity: 3,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 9.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
	}),

	createModelConfig("qwen3-235b-a22b-instruct-2507", PROVIDER, {
		name: "Qwen3 235B A22B Instruct 2507",
		matchingModel: "qwen3-235b-a22b-instruct-2507",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 21, 2025",
		lastUpdated: "July 21, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.000069,
		costPer1kOutputTokens: 0.000455,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 18.2,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("qwen3-32b", PROVIDER, {
		name: "Qwen3 32B",
		matchingModel: "qwen3-32b",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2025",
		lastUpdated: "April 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 40000,
		maxTokens: 40000,
		costPer1kInputTokens: 0.000099,
		costPer1kOutputTokens: 0.000299,
		strengths: ["tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 8.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
		supportsResponseFormat: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3-coder-30b-a3b-instruct", PROVIDER, {
		name: "Qwen3 Coder 30B A3B Instruct",
		matchingModel: "qwen3-coder-30b-a3b-instruct",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2025",
		lastUpdated: "April 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000067,
		costPer1kOutputTokens: 0.000245,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 13.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("qwen3-coder-480b-a35b-instruct", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct",
		matchingModel: "qwen3-coder-480b-a35b-instruct",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "July 25, 2025",
		lastUpdated: "July 25, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000441,
		costPer1kOutputTokens: 0.001984,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 18,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
	}),

	createModelConfig("qwen3-coder-next", PROVIDER, {
		name: "Qwen3 Coder Next 80B",
		matchingModel: "qwen3-coder-next",
		knowledgeCutoffDate: "September 2025",
		releaseDate: "February 3, 2026",
		lastUpdated: "February 3, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.000167,
		costPer1kOutputTokens: 0.000891,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 21.2,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("qwen3-next-80b-a3b-thinking", PROVIDER, {
		name: "Qwen3 Next 80B A3B Thinking",
		matchingModel: "qwen3-next-80b-a3b-thinking",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 2025",
		lastUpdated: "September 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000149,
		costPer1kOutputTokens: 0.001195,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: true,
		family: "qwen",
		supportsResponseFormat: true,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 19.8,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("qwen3.5-122b-a10b", PROVIDER, {
		name: "Qwen3.5 122B A10B",
		matchingModel: "qwen3.5-122b-a10b",
		knowledgeCutoffDate: "January 2026",
		releaseDate: "February 23, 2026",
		lastUpdated: "February 23, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.000495,
		costPer1kOutputTokens: 0.00346,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 28.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
	}),

	createModelConfig("qwen3.5-397b-a17b", PROVIDER, {
		name: "Qwen3.5 397B A17B",
		matchingModel: "qwen3.5-397b-a17b",
		knowledgeCutoffDate: "January 2026",
		releaseDate: "February 15, 2026",
		lastUpdated: "February 15, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 250000,
		costPer1kInputTokens: 0.000668,
		costPer1kOutputTokens: 0.00401,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 32,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
	}),

	createModelConfig("qwen3.6-27b", PROVIDER, {
		name: "Qwen3.6 27B",
		matchingModel: "qwen3.6-27b",
		releaseDate: "April 22, 2026",
		lastUpdated: "April 22, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000446,
		costPer1kOutputTokens: 0.003008,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 29.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("cosmos3-super-reasoner", PROVIDER, {
		name: "Cosmos3 Super Reasoner",
		matchingModel: "cosmos3-super-reasoner",
		releaseDate: "June 2, 2026",
		lastUpdated: "June 2, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.000099,
		costPer1kOutputTokens: 0.000296,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("minicpm-v-4.5", PROVIDER, {
		name: "Minicpm V 4.5",
		matchingModel: "minicpm-v-4.5",
		releaseDate: "June 2, 2026",
		lastUpdated: "June 2, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 32000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.000651,
		costPer1kOutputTokens: 0.001097,
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("claude-opus4-8", PROVIDER, {
		name: "Claude Opus4.8",
		matchingModel: "claude-opus4-8",
		releaseDate: "May 28, 2026",
		lastUpdated: "May 28, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 1000000,
		costPer1kInputTokens: 0.005437,
		costPer1kOutputTokens: 0.027186,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 55.7,
			codingIndex: 74.3,
			agenticIndex: 47.2,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "January 2026",
		supportsResponseFormat: true,
	}),

	createModelConfig("gemini-3.5-flash", PROVIDER, {
		name: "Gemini 3.5 Flash",
		matchingModel: "gemini-3.5-flash",
		releaseDate: "May 19, 2026",
		lastUpdated: "May 19, 2026",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.001483,
		costPer1kOutputTokens: 0.008898,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "audio", "document", "tool_use", "coding"],
		contextComplexity: 5,
		reliability: 3,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 50.2,
			codingIndex: 70.1,
			agenticIndex: 37.4,
			intelligenceIndexVersion: 4.1,
		},
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		supportsResponseFormat: true,
	}),

	createModelConfig("gemini-3.1-flash-lite", PROVIDER, {
		name: "Gemini 3.1 Flash Lite",
		matchingModel: "gemini-3.1-flash-lite",
		releaseDate: "May 7, 2026",
		lastUpdated: "May 7, 2026",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.000272,
		costPer1kOutputTokens: 0.001631,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "audio", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 25,
			codingIndex: 34.7,
			agenticIndex: 6.2,
			intelligenceIndexVersion: 4.1,
		},
		family: "gemini-flash-lite",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		supportsResponseFormat: true,
	}),

	createModelConfig("gemma-3-12b-it", PROVIDER, {
		name: "Gemma 3 12B IT",
		matchingModel: "gemma-3-12b-it",
		releaseDate: "18 May 2026",
		lastUpdated: "18 May 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.00035,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.6-35b-a3b", PROVIDER, {
		name: "Qwen3.6 35B A3B",
		matchingModel: "qwen3.6-35b-a3b",
		releaseDate: "April 17, 2026",
		lastUpdated: "April 17, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000167,
		costPer1kOutputTokens: 0.000557,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 24.2,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("glm-5v-turbo", PROVIDER, {
		name: "GLM 5V Turbo",
		matchingModel: "glm-5v-turbo",
		releaseDate: "April 1, 2026",
		lastUpdated: "April 1, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 202752,
		costPer1kInputTokens: 0.001186,
		costPer1kOutputTokens: 0.003955,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 34.5,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("glm-5-turbo", PROVIDER, {
		name: "GLM 5 Turbo",
		matchingModel: "glm-5-turbo",
		releaseDate: "March 16, 2026",
		lastUpdated: "March 16, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 202752,
		costPer1kInputTokens: 0.001186,
		costPer1kOutputTokens: 0.003955,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		supportsResponseFormat: true,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		artificialAnalysis: {
			intelligenceIndex: 38.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: false,
	}),

	createModelConfig("gemma-4-26b-a4b-it", PROVIDER, {
		name: "Gemma 4 26B A4B IT",
		matchingModel: "gemma-4-26b-a4b-it",
		releaseDate: "April 2, 2026",
		lastUpdated: "April 2, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000111,
		costPer1kOutputTokens: 0.000557,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gemma",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("mistral-medium-3.5", PROVIDER, {
		name: "Mistral Medium 3.5",
		matchingModel: "mistral-medium-3.5",
		releaseDate: "April 30, 2026",
		lastUpdated: "April 30, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.001671,
		costPer1kOutputTokens: 0.00557,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 29.9,
			codingIndex: 46.9,
			agenticIndex: 19,
			intelligenceIndexVersion: 4.1,
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("nvidia-nemotron-3-nano-omni", PROVIDER, {
		name: "Nvidia Nemotron 3 Nano Omni",
		matchingModel: "nvidia-nemotron-3-nano-omni",
		releaseDate: "April 29, 2026",
		lastUpdated: "April 29, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 300000,
		maxTokens: 300000,
		costPer1kInputTokens: 0.000059,
		costPer1kOutputTokens: 0.000237,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("gpt-5.4", PROVIDER, {
		name: "GPT 5.4",
		matchingModel: "gpt-5.4",
		releaseDate: "March 5, 2026",
		lastUpdated: "March 5, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1050000,
		maxTokens: 1050000,
		costPer1kInputTokens: 0.002898,
		costPer1kOutputTokens: 0.015453,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		knowledgeCutoffDate: "August 31, 2025",
		supportsResponseFormat: true,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 27.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("qwen3.5-9b", PROVIDER, {
		name: "Qwen3.5 9B",
		matchingModel: "qwen3.5-9b",
		releaseDate: "February 23, 2026",
		lastUpdated: "February 23, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.000111,
		costPer1kOutputTokens: 0.000167,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use", "document"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 20.3,
			codingIndex: 23.5,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("glm-4.6", PROVIDER, {
		name: "GLM 4.6",
		matchingModel: "glm-4.6",
		releaseDate: "26 March 2026",
		lastUpdated: "26 March 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 203000,
		maxTokens: 203000,
		costPer1kInputTokens: 0.000355,
		costPer1kOutputTokens: 0.001553,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 23,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("deepseek-chat-v3.1", PROVIDER, {
		name: "Deepseek Chat V3.1",
		matchingModel: "deepseek-chat-v3.1",
		releaseDate: "26 March 2026",
		lastUpdated: "26 March 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 164000,
		maxTokens: 164000,
		costPer1kInputTokens: 0.000177,
		costPer1kOutputTokens: 0.00071,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("mistral-small-2603", PROVIDER, {
		name: "Mistral Small 2603",
		matchingModel: "mistral-small-2603",
		releaseDate: "March 16, 2026",
		lastUpdated: "March 16, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.000143,
		costPer1kOutputTokens: 0.000568,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "mistral-small",
		openWeights: true,
		knowledgeCutoffDate: "June 2025",
		supportsResponseFormat: true,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 12.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("qwen3guard-gen-8b", PROVIDER, {
		name: "Qwen3guard Gen 8B",
		matchingModel: "qwen3guard-gen-8b",
		releaseDate: "February 4, 2026",
		lastUpdated: "February 4, 2026",
		modalities: {
			input: ["text"],
			output: ["guardrails"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 32000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		openWeights: false,
		supportsResponseFormat: false,
	}),

	createModelConfig("qwen3guard-gen-0.6b", PROVIDER, {
		name: "Qwen3guard Gen 0.6b",
		matchingModel: "qwen3guard-gen-0.6b",
		releaseDate: "February 4, 2026",
		lastUpdated: "February 4, 2026",
		modalities: {
			input: ["text"],
			output: ["guardrails"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 32000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		openWeights: false,
		supportsResponseFormat: false,
	}),

	createModelConfig("voxtral-small-2507", PROVIDER, {
		name: "Voxtral Small 2507",
		matchingModel: "voxtral-small-2507",
		releaseDate: "February 2, 2026",
		lastUpdated: "February 2, 2026",
		modalities: {
			input: ["text", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 32000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.000111,
		costPer1kOutputTokens: 0.000334,
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("qwen3-vl-235b-a22b", PROVIDER, {
		name: "Qwen3 VL 235B A22B",
		matchingModel: "qwen3-vl-235b-a22b",
		releaseDate: "January 13, 2026",
		lastUpdated: "January 13, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.000617,
		costPer1kOutputTokens: 0.003119,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 20.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("nvidia-nemotron-3-nano-30b-a3b", PROVIDER, {
		name: "Nvidia Nemotron 3 Nano 30B A3B",
		matchingModel: "nvidia-nemotron-3-nano-30b-a3b",
		releaseDate: "January 12, 2026",
		lastUpdated: "January 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.00006,
		costPer1kOutputTokens: 0.00024,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 7.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("holo2-30b-a3b", PROVIDER, {
		name: "Holo2 30B A3B",
		matchingModel: "holo2-30b-a3b",
		releaseDate: "December 10, 2025",
		lastUpdated: "December 10, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 22000,
		maxTokens: 22000,
		costPer1kInputTokens: 0.000334,
		costPer1kOutputTokens: 0.00078,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("nova-2-lite", PROVIDER, {
		name: "Nova 2 Lite",
		matchingModel: "nova-2-lite",
		releaseDate: "December 4, 2025",
		lastUpdated: "December 4, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 1000000,
		costPer1kInputTokens: 0.000373,
		costPer1kOutputTokens: 0.003144,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("gpt-oss-safeguard-120b", PROVIDER, {
		name: "GPT OSS Safeguard 120B",
		matchingModel: "gpt-oss-safeguard-120b",
		releaseDate: "October 29, 2025",
		lastUpdated: "October 29, 2025",
		modalities: {
			input: ["text"],
			output: ["guardrails"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000179,
		costPer1kOutputTokens: 0.000697,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gpt-oss",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("ministral-8b-2512", PROVIDER, {
		name: "Ministral 8B 2512",
		matchingModel: "ministral-8b-2512",
		releaseDate: "December 3, 2025",
		lastUpdated: "December 3, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.000167,
		costPer1kOutputTokens: 0.000167,
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("ministral-3b-2512", PROVIDER, {
		name: "Ministral 3B 2512",
		matchingModel: "ministral-3b-2512",
		releaseDate: "December 3, 2025",
		lastUpdated: "December 3, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.000111,
		costPer1kOutputTokens: 0.000111,
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("ministral-14b-2512", PROVIDER, {
		name: "Ministral 14B 2512",
		matchingModel: "ministral-14b-2512",
		releaseDate: "December 3, 2025",
		lastUpdated: "December 3, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.000223,
		costPer1kOutputTokens: 0.000223,
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("gpt-5.1", PROVIDER, {
		name: "GPT 5.1",
		matchingModel: "gpt-5.1",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 400000,
		costPer1kInputTokens: 0.001375,
		costPer1kOutputTokens: 0.01096,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 20.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
		knowledgeCutoffDate: "September 30, 2024",
		supportsResponseFormat: false,
	}),

	createModelConfig("nemotron-nano-v2-12b", PROVIDER, {
		name: "Nemotron Nano V2 12B",
		matchingModel: "nemotron-nano-v2-12b",
		releaseDate: "October 31, 2025",
		lastUpdated: "October 31, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00024,
		costPer1kOutputTokens: 0.000707,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("magistral-medium-2509", PROVIDER, {
		name: "Magistral Medium 2509",
		matchingModel: "magistral-medium-2509",
		releaseDate: "18 September 2025",
		lastUpdated: "18 September 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.005,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 20.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("magistral-small-2509", PROVIDER, {
		name: "Magistral Small 2509",
		matchingModel: "magistral-small-2509",
		releaseDate: "18 September 2025",
		lastUpdated: "18 September 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.0015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 11.9,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-5", PROVIDER, {
		name: "GPT 5",
		matchingModel: "gpt-5",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 400000,
		costPer1kInputTokens: 0.001375,
		costPer1kOutputTokens: 0.01096,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 15.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
		knowledgeCutoffDate: "September 30, 2024",
		supportsResponseFormat: false,
	}),

	createModelConfig("qwen3-30b-a3b-instruct-2507", PROVIDER, {
		name: "Qwen3 30B A3B Instruct 2507",
		matchingModel: "qwen3-30b-a3b-instruct-2507",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000099,
		costPer1kOutputTokens: 0.000299,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("gpt-oss-20b", PROVIDER, {
		name: "GPT OSS 20B",
		matchingModel: "gpt-oss-20b",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.000045,
		costPer1kOutputTokens: 0.000167,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 14.9,
			codingIndex: 20.7,
			agenticIndex: 3.1,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-oss",
		openWeights: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("mistral-7b-instruct-v0.3", PROVIDER, {
		name: "Mistral 7B Instruct V0.3",
		matchingModel: "mistral-7b-instruct-v0.3",
		releaseDate: "May 26, 2025",
		lastUpdated: "May 26, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 127000,
		maxTokens: 127000,
		costPer1kInputTokens: 0.000111,
		costPer1kOutputTokens: 0.000111,
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("mistral-7b-instruct-v0.2", PROVIDER, {
		name: "Mistral 7B Instruct V0.2",
		matchingModel: "mistral-7b-instruct-v0.2",
		releaseDate: "May 26, 2025",
		lastUpdated: "May 26, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.000159,
		costPer1kOutputTokens: 0.000219,
		openWeights: false,
		supportsResponseFormat: false,
	}),

	createModelConfig("pixtral-large-2502", PROVIDER, {
		name: "Pixtral Large 2502",
		matchingModel: "pixtral-large-2502",
		releaseDate: "May 26, 2025",
		lastUpdated: "May 26, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.001993,
		costPer1kOutputTokens: 0.005978,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("mistral-small-3.2-24b-instruct-2506", PROVIDER, {
		name: "Mistral Small 3.2 24B Instruct 2506",
		matchingModel: "mistral-small-3.2-24b-instruct-2506",
		releaseDate: "May 26, 2025",
		lastUpdated: "May 26, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 131000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.000312,
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("gpt-4.1-mini", PROVIDER, {
		name: "GPT 4.1 Mini",
		matchingModel: "gpt-4.1-mini",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1047576,
		maxTokens: 1047576,
		costPer1kInputTokens: 0.000434,
		costPer1kOutputTokens: 0.001704,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 16.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-mini",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		supportsResponseFormat: false,
	}),

	createModelConfig("gpt-4.1-nano", PROVIDER, {
		name: "GPT 4.1 Nano",
		matchingModel: "gpt-4.1-nano",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1047576,
		maxTokens: 1047576,
		costPer1kInputTokens: 0.000111,
		costPer1kOutputTokens: 0.000434,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 7.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-nano",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		supportsResponseFormat: false,
	}),

	createModelConfig("nova-micro-v1", PROVIDER, {
		name: "Nova Micro V1",
		matchingModel: "nova-micro-v1",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00004,
		costPer1kOutputTokens: 0.000159,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("nova-lite-v1", PROVIDER, {
		name: "Nova Lite V1",
		matchingModel: "nova-lite-v1",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 300000,
		maxTokens: 300000,
		costPer1kInputTokens: 0.000069,
		costPer1kOutputTokens: 0.000275,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("llama-3.1-nemotron-ultra-253b-v1", PROVIDER, {
		name: "Llama 3.1 Nemotron Ultra 253B V1",
		matchingModel: "llama-3.1-nemotron-ultra-253b-v1",
		releaseDate: "April 7, 2025",
		lastUpdated: "April 7, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000598,
		costPer1kOutputTokens: 0.001794,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 9.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("llama-4-maverick", PROVIDER, {
		name: "Llama 4 Maverick",
		matchingModel: "llama-4-maverick",
		releaseDate: "April 5, 2025",
		lastUpdated: "April 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.000124,
		costPer1kOutputTokens: 0.000603,
		knowledgeCutoffDate: "August 2024",
		strengths: ["document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 14.3,
			codingIndex: 16.3,
			agenticIndex: 1.3,
			intelligenceIndexVersion: 4.1,
		},
		family: "llama",
		openWeights: true,
	}),

	createModelConfig("gemini-2.0-flash-001", PROVIDER, {
		name: "Gemini 2.0 Flash 001",
		matchingModel: "gemini-2.0-flash-001",
		releaseDate: "16 March 2025",
		lastUpdated: "16 March 2025",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.000134,
		costPer1kOutputTokens: 0.000537,
	}),

	createModelConfig("gemini-2.0-flash-lite-001", PROVIDER, {
		name: "Gemini 2.0 Flash Lite 001",
		matchingModel: "gemini-2.0-flash-lite-001",
		releaseDate: "16 March 2025",
		lastUpdated: "16 March 2025",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.000067,
		costPer1kOutputTokens: 0.000268,
		strengths: ["vision", "audio", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 8.8,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gemini-2.5-flash", PROVIDER, {
		name: "Gemini 2.5 Flash",
		matchingModel: "gemini-2.5-flash",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.000299,
		costPer1kOutputTokens: 0.002491,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "audio", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 14.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		supportsResponseFormat: true,
	}),

	createModelConfig("gemma-3-27b-it", PROVIDER, {
		name: "Gemma 3 27B IT",
		matchingModel: "gemma-3-27b-it",
		releaseDate: "March 12, 2025",
		lastUpdated: "March 12, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 131000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.000099,
		costPer1kOutputTokens: 0.000299,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("qwen2.5-vl-72b-instruct", PROVIDER, {
		name: "Qwen2.5 VL 72B Instruct",
		matchingModel: "qwen2.5-vl-72b-instruct",
		releaseDate: "January 27, 2025",
		lastUpdated: "January 27, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.000747,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("gpt-4o", PROVIDER, {
		name: "GPT 4O",
		matchingModel: "gpt-4o",
		releaseDate: "May 13, 2024",
		lastUpdated: "August 6, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.002659,
		costPer1kOutputTokens: 0.010635,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 9.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
		knowledgeCutoffDate: "September 2023",
		supportsResponseFormat: false,
	}),

	createModelConfig("gpt-5-mini", PROVIDER, {
		name: "GPT 5 Mini",
		matchingModel: "gpt-5-mini",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 400000,
		costPer1kInputTokens: 0.000279,
		costPer1kOutputTokens: 0.002192,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 33,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-mini",
		openWeights: false,
		knowledgeCutoffDate: "May 30, 2024",
		supportsResponseFormat: false,
	}),

	createModelConfig("gpt-5-nano", PROVIDER, {
		name: "GPT 5 Nano",
		matchingModel: "gpt-5-nano",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 400000,
		costPer1kInputTokens: 0.00006,
		costPer1kOutputTokens: 0.000439,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 19.9,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-nano",
		openWeights: false,
		knowledgeCutoffDate: "May 30, 2024",
		supportsResponseFormat: false,
	}),

	createModelConfig("pixtral-12b-2409", PROVIDER, {
		name: "Pixtral 12B 2409",
		matchingModel: "pixtral-12b-2409",
		releaseDate: "November 9, 2024",
		lastUpdated: "November 9, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000223,
		costPer1kOutputTokens: 0.000223,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("hermes-4-405b", PROVIDER, {
		name: "Hermes 4 405B",
		matchingModel: "hermes-4-405b",
		releaseDate: "August 13, 2024",
		lastUpdated: "August 13, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000996,
		costPer1kOutputTokens: 0.002989,
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("mistral-nemo-instruct-2407", PROVIDER, {
		name: "Mistral Nemo Instruct 2407",
		matchingModel: "mistral-nemo-instruct-2407",
		releaseDate: "August 7, 2024",
		lastUpdated: "August 7, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.000145,
		costPer1kOutputTokens: 0.000145,
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("mistral-medium-2508", PROVIDER, {
		name: "Mistral Medium 2508",
		matchingModel: "mistral-medium-2508",
		releaseDate: "August 7, 2024",
		lastUpdated: "August 7, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000446,
		costPer1kOutputTokens: 0.002228,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),

	createModelConfig("gpt-4o-mini", PROVIDER, {
		name: "GPT 4O Mini",
		matchingModel: "gpt-4o-mini",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000159,
		costPer1kOutputTokens: 0.000638,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 6.9,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-mini",
		openWeights: false,
		knowledgeCutoffDate: "September 2023",
		supportsResponseFormat: false,
	}),

	createModelConfig("llama-3.1-8b-instruct", PROVIDER, {
		name: "Llama 3.1 8B Instruct",
		matchingModel: "llama-3.1-8b-instruct",
		releaseDate: "April 9, 2024",
		lastUpdated: "April 9, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000167,
		costPer1kOutputTokens: 0.000167,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		openWeights: false,
		supportsResponseFormat: true,
	}),
	createModelConfig("minimax-m3", PROVIDER, {
		name: "MiniMax-M3",
		matchingModel: "minimax-m3",
		releaseDate: "June 1, 2026",
		lastUpdated: "June 1, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.000395,
		costPer1kOutputTokens: 0.001977,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 44.4,
			codingIndex: 58.6,
			agenticIndex: 35.4,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
		supportsResponseFormat: true,
	}),
	createModelConfig("glm-5.2", PROVIDER, {
		name: "GLM-5.2",
		matchingModel: "glm-5.2",
		releaseDate: "June 13, 2026",
		lastUpdated: "June 13, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.0012,
		costPer1kOutputTokens: 0.0042,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 51.1,
			codingIndex: 68.8,
			agenticIndex: 43.1,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	}),

	createModelConfig("kimi-k2.7-code", PROVIDER, {
		name: "Kimi K2.7 Code",
		matchingModel: "kimi-k2.7-code",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 12, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00075,
		costPer1kOutputTokens: 0.0035,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 41.9,
			codingIndex: 60.8,
			agenticIndex: 29.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-k2",
		openWeights: true,
	}),
	createModelConfig("hy3", PROVIDER, {
		name: "Hy3",
		matchingModel: "hy3",
		family: "Hy",
		openWeights: true,
		releaseDate: "July 6, 2026",
		lastUpdated: "July 6, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 64000,
		costPer1kInputTokens: 0.00041,
		costPer1kOutputTokens: 0.001025,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 33.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),
	createModelConfig("kimi-k3", PROVIDER, {
		name: "Kimi K3",
		matchingModel: "kimi-k3",
		family: "kimi-k3",
		openWeights: true,
		releaseDate: "July 16, 2026",
		lastUpdated: "July 16, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.014999,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("apertus-70b", PROVIDER, {
		name: "apertus-70b",
		matchingModel: "apertus-70b",
		openWeights: true,
		releaseDate: "September 2, 2025",
		lastUpdated: "September 2, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: false,
		contextWindow: 65536,
		maxTokens: 65536,
		costPer1kInputTokens: 0.001393,
		costPer1kOutputTokens: 0.002228,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		knowledgeCutoffDate: "September 2025",
	}),

	createModelConfig("claude-opus-5", PROVIDER, {
		name: "Claude Opus 5",
		matchingModel: "claude-opus-5",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "May 2026",
		releaseDate: "July 24, 2026",
		lastUpdated: "July 24, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 1000000,
		costPer1kInputTokens: 0.0055,
		costPer1kOutputTokens: 0.027498,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-sonnet-5", PROVIDER, {
		name: "Claude Sonnet 5",
		matchingModel: "claude-sonnet-5",
		family: "claude-sonnet",
		openWeights: false,
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "June 30, 2026",
		lastUpdated: "June 30, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 1000000,
		costPer1kInputTokens: 0.0022,
		costPer1kOutputTokens: 0.011,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gemma-4-31b-it", PROVIDER, {
		name: "Gemma 4 31B IT",
		matchingModel: "gemma-4-31b-it",
		family: "gemma",
		openWeights: true,
		releaseDate: "April 2, 2026",
		lastUpdated: "April 2, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.000223,
		costPer1kOutputTokens: 0.00039,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.6-luna", PROVIDER, {
		name: "GPT-5.6 Luna",
		matchingModel: "gpt-5.6-luna",
		family: "gpt-luna",
		openWeights: false,
		knowledgeCutoffDate: "February 16, 2026",
		releaseDate: "July 9, 2026",
		lastUpdated: "July 9, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 1050000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.006599,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.6-sol", PROVIDER, {
		name: "GPT-5.6 Sol",
		matchingModel: "gpt-5.6-sol",
		family: "gpt-sol",
		openWeights: false,
		knowledgeCutoffDate: "February 16, 2026",
		releaseDate: "July 9, 2026",
		lastUpdated: "July 9, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 1050000,
		costPer1kInputTokens: 0.0055,
		costPer1kOutputTokens: 0.032998,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.6-terra", PROVIDER, {
		name: "GPT-5.6 Terra",
		matchingModel: "gpt-5.6-terra",
		family: "gpt-terra",
		openWeights: false,
		knowledgeCutoffDate: "February 16, 2026",
		releaseDate: "July 9, 2026",
		lastUpdated: "July 9, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 1050000,
		costPer1kInputTokens: 0.002749,
		costPer1kOutputTokens: 0.016498,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("gemini-3.5-flash-lite", PROVIDER, {
		name: "Gemini 3.5 Flash Lite",
		matchingModel: "gemini-3.5-flash-lite",
		family: "gemini-flash-lite",
		openWeights: false,
		knowledgeCutoffDate: "March 2026",
		releaseDate: "July 21, 2026",
		lastUpdated: "July 21, 2026",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.00033,
		costPer1kOutputTokens: 0.002749,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("deepseek-v4-flash-0731", PROVIDER, {
		name: "DeepSeek V4 Flash 0731",
		matchingModel: "deepseek-v4-flash-0731",
		family: "deepseek-flash",
		openWeights: true,
		knowledgeCutoffDate: "May 2025",
		releaseDate: "July 31, 2026",
		lastUpdated: "July 31, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
]);
