import type { ModelConfig } from "~/types";
import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "deepinfra";

export const deepinfraModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("moonshotai/Kimi-K2-Instruct", PROVIDER, {
		name: "Kimi K2",
		matchingModel: "moonshotai/Kimi-K2-Instruct",
		description:
			"Kimi K2 is a powerful open-weights model with advanced text capabilities and tool calling support.",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 11, 2025",
		lastUpdated: "July 11, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.002,
		strengths: ["chat", "general_knowledge", "analysis", "tool_use"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct Turbo",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo",
		description:
			"Qwen3 Coder Turbo model optimized for coding tasks with fast inference and extensive context window.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 66536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		strengths: ["coding", "analysis", "instruction", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 5,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("Qwen/Qwen3-Coder-480B-A35B-Instruct", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
		description:
			"Qwen3 Coder model with advanced coding capabilities and extensive context window.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 66536,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
		strengths: ["coding", "analysis", "instruction", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 4,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("anthropic/claude-3-7-sonnet-latest", PROVIDER, {
		name: "Claude Sonnet 3.7 (Latest)",
		matchingModel: "anthropic/claude-3-7-sonnet-latest",
		knowledgeCutoffDate: "October 31, 2024",
		releaseDate: "March 13, 2025",
		lastUpdated: "March 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.0033,
		costPer1kOutputTokens: 0.0165,
	}),

	createModelConfig("anthropic/claude-4-opus", PROVIDER, {
		name: "Claude Opus 4",
		matchingModel: "anthropic/claude-4-opus",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "June 12, 2025",
		lastUpdated: "June 12, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.0165,
		costPer1kOutputTokens: 0.0825,
	}),

	createModelConfig("deepseek-ai/DeepSeek-R1-0528", PROVIDER, {
		name: "DeepSeek-R1-0528",
		matchingModel: "deepseek-ai/DeepSeek-R1-0528",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "May 28, 2025",
		lastUpdated: "May 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 163840,
		maxTokens: 64000,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.00215,
	}),

	createModelConfig("deepseek-ai/DeepSeek-V3.2", PROVIDER, {
		name: "DeepSeek-V3.2",
		matchingModel: "deepseek-ai/DeepSeek-V3.2",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "December 2, 2025",
		lastUpdated: "December 2, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 64000,
		costPer1kInputTokens: 0.00026,
		costPer1kOutputTokens: 0.00038,
	}),

	createModelConfig("MiniMaxAI/MiniMax-M2", PROVIDER, {
		name: "MiniMax M2",
		matchingModel: "MiniMaxAI/MiniMax-M2",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 32768,
		costPer1kInputTokens: 0.000254,
		costPer1kOutputTokens: 0.00102,
	}),

	createModelConfig("MiniMaxAI/MiniMax-M2.1", PROVIDER, {
		name: "MiniMax M2.1",
		matchingModel: "MiniMaxAI/MiniMax-M2.1",
		knowledgeCutoffDate: "June 2025",
		releaseDate: "December 23, 2025",
		lastUpdated: "December 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 196608,
		maxTokens: 196608,
		costPer1kInputTokens: 0.00028,
		costPer1kOutputTokens: 0.0012,
	}),

	createModelConfig("moonshotai/Kimi-K2-Thinking", PROVIDER, {
		name: "Kimi K2 Thinking",
		matchingModel: "moonshotai/Kimi-K2-Thinking",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "November 6, 2025",
		lastUpdated: "November 7, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00047,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("moonshotai/Kimi-K2.5", PROVIDER, {
		name: "Kimi K2.5",
		matchingModel: "moonshotai/Kimi-K2.5",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.0028,
	}),

	createModelConfig("openai/gpt-oss-120b", PROVIDER, {
		name: "GPT OSS 120B",
		matchingModel: "openai/gpt-oss-120b",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.00024,
	}),

	createModelConfig("openai/gpt-oss-20b", PROVIDER, {
		name: "GPT OSS 20B",
		matchingModel: "openai/gpt-oss-20b",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00003,
		costPer1kOutputTokens: 0.00014,
	}),

	createModelConfig("zai-org/GLM-4.7", PROVIDER, {
		name: "GLM-4.7",
		matchingModel: "zai-org/GLM-4.7",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 22, 2025",
		lastUpdated: "December 22, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00043,
		costPer1kOutputTokens: 0.00175,
	}),

	createModelConfig("zai-org/GLM-4.7-Flash", PROVIDER, {
		name: "GLM-4.7-Flash",
		matchingModel: "zai-org/GLM-4.7-Flash",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "January 19, 2026",
		lastUpdated: "January 19, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00006,
		costPer1kOutputTokens: 0.0004,
	}),
	createModelConfig("deepseek-ai/DeepSeek-V4-Flash", PROVIDER, {
		name: "DeepSeek V4 Flash",
		matchingModel: "deepseek-ai/DeepSeek-V4-Flash",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
	}),

	createModelConfig("deepseek-ai/DeepSeek-V4-Pro", PROVIDER, {
		name: "DeepSeek V4 Pro",
		matchingModel: "deepseek-ai/DeepSeek-V4-Pro",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 65536,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00348,
	}),

	createModelConfig("google/gemma-4-26B-A4B-it", PROVIDER, {
		name: "Gemma 4 26B",
		matchingModel: "google/gemma-4-26B-A4B-it",
		releaseDate: "April 2, 2026",
		lastUpdated: "April 2, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00007,
		costPer1kOutputTokens: 0.00034,
	}),

	createModelConfig("google/gemma-4-31B-it", PROVIDER, {
		name: "Gemma 4 31B",
		matchingModel: "google/gemma-4-31B-it",
		releaseDate: "April 2, 2026",
		lastUpdated: "April 2, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00013,
		costPer1kOutputTokens: 0.00038,
	}),

	createModelConfig("meta-llama/Llama-3.1-70B-Instruct", PROVIDER, {
		name: "Llama 3.1 70B",
		matchingModel: "meta-llama/Llama-3.1-70B-Instruct",
		releaseDate: "July 23, 2024",
		lastUpdated: "July 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0004,
	}),

	createModelConfig("meta-llama/Llama-3.1-70B-Instruct-Turbo", PROVIDER, {
		name: "Llama 3.1 70B Turbo",
		matchingModel: "meta-llama/Llama-3.1-70B-Instruct-Turbo",
		releaseDate: "July 23, 2024",
		lastUpdated: "July 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0004,
	}),

	createModelConfig("meta-llama/Llama-3.1-8B-Instruct", PROVIDER, {
		name: "Llama 3.1 8B",
		matchingModel: "meta-llama/Llama-3.1-8B-Instruct",
		releaseDate: "July 23, 2024",
		lastUpdated: "July 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.00005,
	}),

	createModelConfig("meta-llama/Llama-3.1-8B-Instruct-Turbo", PROVIDER, {
		name: "Llama 3.1 8B Turbo",
		matchingModel: "meta-llama/Llama-3.1-8B-Instruct-Turbo",
		releaseDate: "July 23, 2024",
		lastUpdated: "July 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0.00003,
	}),

	createModelConfig("meta-llama/Llama-3.3-70B-Instruct-Turbo", PROVIDER, {
		name: "Llama 3.3 70B Turbo",
		matchingModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
		releaseDate: "December 6, 2024",
		lastUpdated: "December 6, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.00032,
	}),

	createModelConfig("meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", PROVIDER, {
		name: "Llama 4 Maverick 17B FP8",
		matchingModel: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
		releaseDate: "April 5, 2025",
		lastUpdated: "April 5, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
	}),

	createModelConfig("meta-llama/Llama-4-Scout-17B-16E-Instruct", PROVIDER, {
		name: "Llama 4 Scout 17B",
		matchingModel: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
		releaseDate: "April 5, 2025",
		lastUpdated: "April 5, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 10000000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00008,
		costPer1kOutputTokens: 0.0003,
	}),

	createModelConfig("MiniMaxAI/MiniMax-M2.5", PROVIDER, {
		name: "MiniMax M2.5",
		matchingModel: "MiniMaxAI/MiniMax-M2.5",
		knowledgeCutoffDate: "June 2025",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00027,
		costPer1kOutputTokens: 0.00095,
	}),

	createModelConfig("moonshotai/Kimi-K2-Instruct-0905", PROVIDER, {
		name: "Kimi K2 0905",
		matchingModel: "moonshotai/Kimi-K2-Instruct-0905",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "September 5, 2025",
		lastUpdated: "September 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("moonshotai/Kimi-K2.6", PROVIDER, {
		name: "Kimi K2.6",
		matchingModel: "moonshotai/Kimi-K2.6",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 21, 2026",
		lastUpdated: "April 21, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00075,
		costPer1kOutputTokens: 0.0035,
	}),

	createModelConfig("Qwen/Qwen3.5-35B-A3B", PROVIDER, {
		name: "Qwen 3.5 35B A3B",
		matchingModel: "Qwen/Qwen3.5-35B-A3B",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 1, 2026",
		lastUpdated: "April 20, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 81920,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.00095,
	}),

	createModelConfig("Qwen/Qwen3.5-397B-A17B", PROVIDER, {
		name: "Qwen 3.5 397B A17B",
		matchingModel: "Qwen/Qwen3.5-397B-A17B",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 1, 2026",
		lastUpdated: "April 20, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 81920,
		costPer1kInputTokens: 0.00054,
		costPer1kOutputTokens: 0.0034,
	}),

	createModelConfig("Qwen/Qwen3.6-35B-A3B", PROVIDER, {
		name: "Qwen3.6 35B A3B",
		matchingModel: "Qwen/Qwen3.6-35B-A3B",
		releaseDate: "April 1, 2026",
		lastUpdated: "April 1, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 81920,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.001,
	}),

	createModelConfig("xiaomi/mimo-v2.5", PROVIDER, {
		name: "MiMo-V2.5",
		matchingModel: "xiaomi/mimo-v2.5",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "April 22, 2026",
		lastUpdated: "April 22, 2026",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("xiaomi/mimo-v2.5-pro", PROVIDER, {
		name: "MiMo-V2.5-Pro",
		matchingModel: "xiaomi/mimo-v2.5-pro",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "April 22, 2026",
		lastUpdated: "April 22, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.003,
	}),

	createModelConfig("zai-org/GLM-4.6", PROVIDER, {
		name: "GLM-4.6",
		matchingModel: "zai-org/GLM-4.6",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 30, 2025",
		lastUpdated: "September 30, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00043,
		costPer1kOutputTokens: 0.00174,
	}),

	createModelConfig("zai-org/GLM-4.6V", PROVIDER, {
		name: "GLM-4.6V",
		matchingModel: "zai-org/GLM-4.6V",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 30, 2025",
		lastUpdated: "September 30, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0009,
	}),

	createModelConfig("zai-org/GLM-5", PROVIDER, {
		name: "GLM-5",
		matchingModel: "zai-org/GLM-5",
		knowledgeCutoffDate: "December 2025",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0008,
		costPer1kOutputTokens: 0.00256,
	}),

	createModelConfig("zai-org/GLM-5.1", PROVIDER, {
		name: "GLM-5.1",
		matchingModel: "zai-org/GLM-5.1",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 7, 2026",
		lastUpdated: "April 7, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
	}),
]);
