import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "deepinfra";

export const deepinfraModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("moonshotai/Kimi-K2-Instruct", PROVIDER, {
		name: "Kimi K2",
		matchingModel: "moonshotai/Kimi-K2-Instruct",
		description:
			"Kimi K2 is a powerful open-weights model with advanced text capabilities and tool calling support.",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 11, 2025",
		lastUpdated: "July 11, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.002,
		strengths: ["chat", "general_knowledge", "analysis", "tool_use"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct Turbo",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo",
		description:
			"Qwen3 Coder Turbo model optimized for coding tasks with fast inference and extensive context window.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 66536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		strengths: ["coding", "analysis", "instruction", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 5,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("Qwen/Qwen3-Coder-480B-A35B-Instruct", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
		description:
			"Qwen3 Coder model with advanced coding capabilities and extensive context window.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 66536,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
		strengths: ["coding", "analysis", "instruction", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 4,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("zai-org/GLM-4.5", PROVIDER, {
		name: "GLM-4.5",
		matchingModel: "zai-org/GLM-4.5",
		description:
			"GLM-4.5 is a powerful open-weights model with advanced text generation and tool calling capabilities.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 98304,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"tool_use",
			"multilingual",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	}),
]);
