import type { ModelConfig } from "~/types";

export const deepseekModelConfig: ModelConfig = {
	"deepseek-chat": {
		name: "DeepSeek Chat",
		matchingModel: "deepseek-chat",
		description:
			"DeepSeek's latest model optimized for coding, analysis, and mathematical tasks with strong reasoning capabilities.",
		provider: "deepseek",
		knowledgeCutoffDate: "September 2025",
		releaseDate: "December 1, 2025",
		lastUpdated: "February 28, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		card: "https://www.prompthub.us/models/deepseek-v3",
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		strengths: ["multilingual", "coding", "analysis"],
		contextComplexity: 4,
		reliability: 5,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		isFree: true,
	},
	"deepseek-reasoner": {
		name: "DeepSeek Reasoner",
		matchingModel: "deepseek-reasoner",
		provider: "deepseek",
		knowledgeCutoffDate: "September 2025",
		releaseDate: "December 1, 2025",
		lastUpdated: "February 28, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		card: "https://www.prompthub.us/models/deepseek-reasoner-r1",
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		strengths: ["reasoning", "multilingual", "coding", "analysis"],
		contextComplexity: 4,
		reliability: 5,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		isFree: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	},
	"deepseek-v4-flash": {
		name: "DeepSeek V4 Flash",
		matchingModel: "deepseek-v4-flash",
		provider: "deepseek",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		isFeatured: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	},

	"deepseek-v4-pro": {
		name: "DeepSeek V4 Pro",
		matchingModel: "deepseek-v4-pro",
		provider: "deepseek",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		isFeatured: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00348,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	},
};
