import type { ModelConfig } from "~/types";

export const deepseekModelConfig: ModelConfig = {
	"deepseek-chat": {
		name: "DeepSeek Chat",
		matchingModel: "deepseek-chat",
		description:
			"DeepSeek's latest model optimized for coding, analysis, and mathematical tasks with strong reasoning capabilities.",
		provider: "deepseek",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "December 26, 2024",
		lastUpdated: "March 24, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		card: "https://www.prompthub.us/models/deepseek-v3",
		contextWindow: 64000,
		maxTokens: 8000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		strengths: ["multilingual", "coding", "analysis"],
		contextComplexity: 4,
		reliability: 5,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		isFree: true,
	},
	"deepseek-reasoner": {
		name: "DeepSeek Reasoner",
		matchingModel: "deepseek-reasoner",
		provider: "deepseek",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "January 20, 2025",
		lastUpdated: "May 29, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		card: "https://www.prompthub.us/models/deepseek-reasoner-r1",
		contextWindow: 64000,
		maxTokens: 8000,
		costPer1kInputTokens: 0.00055,
		costPer1kOutputTokens: 0.00219,
		strengths: ["reasoning", "multilingual", "coding", "analysis"],
		contextComplexity: 4,
		reliability: 5,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		isFree: true,
	},
};
