import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "deepinfra";

export const deepinfraModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("moonshotai/Kimi-K2-Instruct", PROVIDER, {
		name: "Kimi K2",
		matchingModel: "moonshotai/Kimi-K2-Instruct",
		description:
			"Kimi K2 is a powerful open-weights model with advanced text capabilities and tool calling support.",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 11, 2025",
		lastUpdated: "July 11, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.002,
		strengths: ["chat", "general_knowledge", "analysis", "tool_use"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct Turbo",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo",
		description:
			"Qwen3 Coder Turbo model optimized for coding tasks with fast inference and extensive context window.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 66536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		strengths: ["coding", "analysis", "instruction", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 5,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("Qwen/Qwen3-Coder-480B-A35B-Instruct", PROVIDER, {
		name: "Qwen3 Coder 480B A35B Instruct",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
		description:
			"Qwen3 Coder model with advanced coding capabilities and extensive context window.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 66536,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
		strengths: ["coding", "analysis", "instruction", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 4,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("zai-org/GLM-4.5", PROVIDER, {
		name: "GLM-4.5",
		matchingModel: "zai-org/GLM-4.5",
		description:
			"GLM-4.5 is a powerful open-weights model with advanced text generation and tool calling capabilities.",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 98304,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"tool_use",
			"multilingual",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	}),
	createModelConfig("anthropic/claude-3-7-sonnet-latest", PROVIDER, {
		name: "Claude Sonnet 3.7 (Latest)",
		matchingModel: "anthropic/claude-3-7-sonnet-latest",
		knowledgeCutoffDate: "October 31, 2024",
		releaseDate: "March 13, 2025",
		lastUpdated: "March 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.0033,
		costPer1kOutputTokens: 0.0165,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("anthropic/claude-4-opus", PROVIDER, {
		name: "Claude Opus 4",
		matchingModel: "anthropic/claude-4-opus",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "June 12, 2025",
		lastUpdated: "June 12, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.0165,
		costPer1kOutputTokens: 0.0825,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek-ai/DeepSeek-R1-0528", PROVIDER, {
		name: "DeepSeek-R1-0528",
		matchingModel: "deepseek-ai/DeepSeek-R1-0528",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "May 28, 2025",
		lastUpdated: "May 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 163840,
		maxTokens: 64000,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.00215,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("deepseek-ai/DeepSeek-V3.2", PROVIDER, {
		name: "DeepSeek-V3.2",
		matchingModel: "deepseek-ai/DeepSeek-V3.2",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "December 2, 2025",
		lastUpdated: "December 2, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 64000,
		costPer1kInputTokens: 0.00026,
		costPer1kOutputTokens: 0.00038,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("MiniMaxAI/MiniMax-M2", PROVIDER, {
		name: "MiniMax M2",
		matchingModel: "MiniMaxAI/MiniMax-M2",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 32768,
		costPer1kInputTokens: 0.000254,
		costPer1kOutputTokens: 0.00102,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("MiniMaxAI/MiniMax-M2.1", PROVIDER, {
		name: "MiniMax M2.1",
		matchingModel: "MiniMaxAI/MiniMax-M2.1",
		knowledgeCutoffDate: "June 2025",
		releaseDate: "December 23, 2025",
		lastUpdated: "December 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 196608,
		maxTokens: 196608,
		costPer1kInputTokens: 0.00028,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("moonshotai/Kimi-K2-Thinking", PROVIDER, {
		name: "Kimi K2 Thinking",
		matchingModel: "moonshotai/Kimi-K2-Thinking",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "November 6, 2025",
		lastUpdated: "November 7, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00047,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("moonshotai/Kimi-K2.5", PROVIDER, {
		name: "Kimi K2.5",
		matchingModel: "moonshotai/Kimi-K2.5",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.0028,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-oss-120b", PROVIDER, {
		name: "GPT OSS 120B",
		matchingModel: "openai/gpt-oss-120b",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.00024,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-oss-20b", PROVIDER, {
		name: "GPT OSS 20B",
		matchingModel: "openai/gpt-oss-20b",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00003,
		costPer1kOutputTokens: 0.00014,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("zai-org/GLM-4.7", PROVIDER, {
		name: "GLM-4.7",
		matchingModel: "zai-org/GLM-4.7",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 22, 2025",
		lastUpdated: "December 22, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00043,
		costPer1kOutputTokens: 0.00175,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("zai-org/GLM-4.7-Flash", PROVIDER, {
		name: "GLM-4.7-Flash",
		matchingModel: "zai-org/GLM-4.7-Flash",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "January 19, 2026",
		lastUpdated: "January 19, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00006,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			enabled: true,
		},
	}),
]);
