import type { ModelConfig } from "~/types";

export const fireworksModelConfig: ModelConfig = {
	"openai/gpt-oss-120b": {
		name: "GPT OSS 120B",
		matchingModel: "accounts/fireworks/gpt-oss-120b",
		description:
			"Large 120B parameter open-source GPT model optimized for reasoning and complex tasks.",
		provider: "fireworks",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: ["reasoning", "analysis", "coding", "multilingual"],
		contextComplexity: 5,
		reliability: 4,
		speed: 2,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"openai/gpt-oss-20b": {
		name: "GPT OSS 20B",
		matchingModel: "accounts/fireworks/gpt-oss-20b",
		description:
			"Efficient 20B parameter open-source GPT model for fast reasoning and general tasks.",
		provider: "fireworks",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0002,
		strengths: ["reasoning", "analysis", "coding"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"deepseek/deepseek-r1": {
		name: "Deepseek R1 05/28",
		matchingModel: "accounts/fireworks/models/deepseek-r1-0528",
		description:
			"Advanced DeepSeek R1 reasoning model hosted on Fireworks with enhanced mathematical and logical capabilities.",
		provider: "fireworks",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "May 28, 2025",
		lastUpdated: "May 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 160000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.008,
		strengths: ["reasoning", "math", "analysis", "coding"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"qwen/qwen3-235b-a22b": {
		name: "Qwen3 235B-A22B",
		matchingModel: "accounts/fireworks/models/qwen3-235b-a22b",
		description:
			"Large-scale Qwen3 model with 235B parameters, offering strong reasoning and language understanding.",
		provider: "fireworks",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 29, 2025",
		lastUpdated: "April 29, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00022,
		costPer1kOutputTokens: 0.00088,
		strengths: ["reasoning", "analysis", "multilingual", "coding"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"deepseek/deepseek-v3-0324": {
		name: "Deepseek V3 03-24",
		matchingModel: "accounts/fireworks/models/deepseek-v3-0324",
		description:
			"DeepSeek V3 model hosted on Fireworks, optimized for coding and analytical tasks.",
		provider: "fireworks",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "March 24, 2025",
		lastUpdated: "March 24, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 160000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0009,
		costPer1kOutputTokens: 0.0009,
		strengths: ["coding", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"moonshotai/kimi-k2-instruct": {
		name: "Kimi K2 Instruct",
		matchingModel: "accounts/fireworks/models/kimi-k2-instruct",
		description:
			"Kimi K2 instruction-following model optimized for conversational AI and task completion.",
		provider: "fireworks",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 11, 2025",
		lastUpdated: "July 11, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.003,
		strengths: ["chat", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"accounts/fireworks/models/deepseek-v3p1": {
		name: "DeepSeek V3.1",
		matchingModel: "accounts/fireworks/models/deepseek-v3p1",
		provider: "fireworks",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "August 21, 2025",
		lastUpdated: "August 21, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00056,
		costPer1kOutputTokens: 0.00168,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/deepseek-v3p2": {
		name: "DeepSeek V3.2",
		matchingModel: "accounts/fireworks/models/deepseek-v3p2",
		provider: "fireworks",
		knowledgeCutoffDate: "September 2025",
		releaseDate: "December 1, 2025",
		lastUpdated: "December 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 160000,
		maxTokens: 160000,
		costPer1kInputTokens: 0.00056,
		costPer1kOutputTokens: 0.00168,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/glm-4p5": {
		name: "GLM 4.5",
		matchingModel: "accounts/fireworks/models/glm-4p5",
		provider: "fireworks",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 29, 2025",
		lastUpdated: "July 29, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00055,
		costPer1kOutputTokens: 0.00219,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/glm-4p5-air": {
		name: "GLM 4.5 Air",
		matchingModel: "accounts/fireworks/models/glm-4p5-air",
		provider: "fireworks",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00022,
		costPer1kOutputTokens: 0.00088,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/glm-4p6": {
		name: "GLM 4.6",
		matchingModel: "accounts/fireworks/models/glm-4p6",
		provider: "fireworks",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "October 1, 2025",
		lastUpdated: "October 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 198000,
		maxTokens: 198000,
		costPer1kInputTokens: 0.00055,
		costPer1kOutputTokens: 0.00219,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/glm-4p7": {
		name: "GLM 4.7",
		matchingModel: "accounts/fireworks/models/glm-4p7",
		provider: "fireworks",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 22, 2025",
		lastUpdated: "December 22, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 198000,
		maxTokens: 198000,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/gpt-oss-120b": {
		name: "GPT OSS 120B",
		matchingModel: "accounts/fireworks/models/gpt-oss-120b",
		provider: "fireworks",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/gpt-oss-20b": {
		name: "GPT OSS 20B",
		matchingModel: "accounts/fireworks/models/gpt-oss-20b",
		provider: "fireworks",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0002,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/kimi-k2-thinking": {
		name: "Kimi K2 Thinking",
		matchingModel: "accounts/fireworks/models/kimi-k2-thinking",
		provider: "fireworks",
		releaseDate: "November 6, 2025",
		lastUpdated: "November 6, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0025,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/kimi-k2p5": {
		name: "Kimi K2.5",
		matchingModel: "accounts/fireworks/models/kimi-k2p5",
		provider: "fireworks",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/minimax-m2": {
		name: "MiniMax-M2",
		matchingModel: "accounts/fireworks/models/minimax-m2",
		provider: "fireworks",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "October 27, 2025",
		lastUpdated: "October 27, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 192000,
		maxTokens: 192000,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/minimax-m2p1": {
		name: "MiniMax-M2.1",
		matchingModel: "accounts/fireworks/models/minimax-m2p1",
		provider: "fireworks",
		releaseDate: "December 23, 2025",
		lastUpdated: "December 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			enabled: true,
		},
	},

	"accounts/fireworks/models/qwen3-coder-480b-a35b-instruct": {
		name: "Qwen3 Coder 480B A35B Instruct",
		matchingModel: "accounts/fireworks/models/qwen3-coder-480b-a35b-instruct",
		provider: "fireworks",
		releaseDate: "July 22, 2025",
		lastUpdated: "July 22, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00045,
		costPer1kOutputTokens: 0.0018,
		reasoningConfig: {
			enabled: false,
		},
	},
};
