import type { ModelConfig } from "@assistant/schemas";

export const fireworksModelConfig: ModelConfig = {
	"openai/gpt-oss-120b": {
		name: "GPT OSS 120B",
		matchingModel: "accounts/fireworks/gpt-oss-120b",
		description:
			"Large 120B parameter open-source GPT model optimized for reasoning and complex tasks.",
		provider: "fireworks",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: ["reasoning", "analysis", "coding", "multilingual", "tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 5,
		supportsArtifacts: true,
		artificialAnalysis: {
			intelligenceIndex: 23.8,
			codingIndex: 30.4,
			agenticIndex: 13.2,
			intelligenceIndexVersion: 4.1,
		},
	},

	"openai/gpt-oss-20b": {
		name: "GPT OSS 20B",
		matchingModel: "accounts/fireworks/gpt-oss-20b",
		description:
			"Efficient 20B parameter open-source GPT model for fast reasoning and general tasks.",
		provider: "fireworks",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0002,
		strengths: ["reasoning", "analysis", "coding", "tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 5,
		supportsArtifacts: true,
		artificialAnalysis: {
			intelligenceIndex: 14.9,
			codingIndex: 20.7,
			agenticIndex: 3.1,
			intelligenceIndexVersion: 4.1,
		},
	},

	"deepseek/deepseek-r1": {
		name: "Deepseek R1 05/28",
		matchingModel: "accounts/fireworks/models/deepseek-r1-0528",
		description:
			"Advanced DeepSeek R1 reasoning model hosted on Fireworks with enhanced mathematical and logical capabilities.",
		provider: "fireworks",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "May 28, 2025",
		lastUpdated: "May 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 160000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.008,
		strengths: ["reasoning", "math", "analysis", "coding", "tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 3,
		supportsArtifacts: true,
		artificialAnalysis: {
			intelligenceIndex: 12.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"qwen/qwen3-235b-a22b": {
		name: "Qwen3 235B-A22B",
		matchingModel: "accounts/fireworks/models/qwen3-235b-a22b",
		description:
			"Large-scale Qwen3 model with 235B parameters, offering strong reasoning and language understanding.",
		provider: "fireworks",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 29, 2025",
		lastUpdated: "April 29, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00022,
		costPer1kOutputTokens: 0.00088,
		strengths: ["reasoning", "analysis", "multilingual", "coding", "tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 3,
		supportsArtifacts: true,
		artificialAnalysis: {
			intelligenceIndex: 10.9,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"deepseek/deepseek-v3-0324": {
		name: "Deepseek V3 03-24",
		matchingModel: "accounts/fireworks/models/deepseek-v3-0324",
		description:
			"DeepSeek V3 model hosted on Fireworks, optimized for coding and analytical tasks.",
		provider: "fireworks",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "March 24, 2025",
		lastUpdated: "March 24, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 160000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0009,
		costPer1kOutputTokens: 0.0009,
		strengths: ["coding", "analysis", "multilingual", "tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 3,
		supportsArtifacts: true,
		artificialAnalysis: {
			intelligenceIndex: 15.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"moonshotai/kimi-k2-instruct": {
		name: "Kimi K2 Instruct",
		matchingModel: "accounts/fireworks/models/kimi-k2-instruct",
		description:
			"Kimi K2 instruction-following model optimized for conversational AI and task completion.",
		provider: "fireworks",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 11, 2025",
		lastUpdated: "July 11, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.003,
		strengths: ["chat", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		supportsArtifacts: true,
	},
	"accounts/fireworks/models/deepseek-v3p1": {
		name: "DeepSeek V3.1",
		matchingModel: "accounts/fireworks/models/deepseek-v3p1",
		provider: "fireworks",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "August 21, 2025",
		lastUpdated: "August 21, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00056,
		costPer1kOutputTokens: 0.00168,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 21,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/deepseek-v3p2": {
		name: "DeepSeek V3.2",
		matchingModel: "accounts/fireworks/models/deepseek-v3p2",
		provider: "fireworks",
		knowledgeCutoffDate: "September 2025",
		releaseDate: "December 1, 2025",
		lastUpdated: "December 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 160000,
		maxTokens: 160000,
		costPer1kInputTokens: 0.00056,
		costPer1kOutputTokens: 0.00168,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 24.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/glm-4p5": {
		name: "GLM 4.5",
		matchingModel: "accounts/fireworks/models/glm-4p5",
		provider: "fireworks",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 29, 2025",
		lastUpdated: "July 29, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00055,
		costPer1kOutputTokens: 0.00219,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 19.5,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/glm-4p5-air": {
		name: "GLM 4.5 Air",
		matchingModel: "accounts/fireworks/models/glm-4p5-air",
		provider: "fireworks",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "August 1, 2025",
		lastUpdated: "August 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00022,
		costPer1kOutputTokens: 0.00088,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 16.5,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/glm-4p6": {
		name: "GLM 4.6",
		matchingModel: "accounts/fireworks/models/glm-4p6",
		provider: "fireworks",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "October 1, 2025",
		lastUpdated: "October 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 198000,
		maxTokens: 198000,
		costPer1kInputTokens: 0.00055,
		costPer1kOutputTokens: 0.00219,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 23,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/glm-4p7": {
		name: "GLM 4.7",
		matchingModel: "accounts/fireworks/models/glm-4p7",
		provider: "fireworks",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 22, 2025",
		lastUpdated: "December 22, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 198000,
		maxTokens: 198000,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 26.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/gpt-oss-120b": {
		name: "GPT OSS 120B",
		matchingModel: "accounts/fireworks/models/gpt-oss-120b",
		provider: "fireworks",
		releaseDate: "August 5, 2025",
		lastUpdated: "June 16, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 23.8,
			codingIndex: 30.4,
			agenticIndex: 13.2,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-oss",
		openWeights: true,
	},

	"accounts/fireworks/models/gpt-oss-20b": {
		name: "GPT OSS 20B",
		matchingModel: "accounts/fireworks/models/gpt-oss-20b",
		provider: "fireworks",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00007,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 14.9,
			codingIndex: 20.7,
			agenticIndex: 3.1,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-oss",
		openWeights: true,
	},

	"accounts/fireworks/models/kimi-k2-thinking": {
		name: "Kimi K2 Thinking",
		matchingModel: "accounts/fireworks/models/kimi-k2-thinking",
		provider: "fireworks",
		releaseDate: "November 6, 2025",
		lastUpdated: "November 6, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0025,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 32.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/kimi-k2p5": {
		name: "Kimi K2.5",
		matchingModel: "accounts/fireworks/models/kimi-k2p5",
		provider: "fireworks",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 29.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/minimax-m2": {
		name: "MiniMax-M2",
		matchingModel: "accounts/fireworks/models/minimax-m2",
		provider: "fireworks",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "October 27, 2025",
		lastUpdated: "October 27, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 192000,
		maxTokens: 192000,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 28.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/minimax-m2p1": {
		name: "MiniMax-M2.1",
		matchingModel: "accounts/fireworks/models/minimax-m2p1",
		provider: "fireworks",
		releaseDate: "December 23, 2025",
		lastUpdated: "December 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 31.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/qwen3-coder-480b-a35b-instruct": {
		name: "Qwen3 Coder 480B A35B Instruct",
		matchingModel: "accounts/fireworks/models/qwen3-coder-480b-a35b-instruct",
		provider: "fireworks",
		releaseDate: "July 22, 2025",
		lastUpdated: "July 22, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00045,
		costPer1kOutputTokens: 0.0018,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 18,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},
	"accounts/fireworks/models/deepseek-v4-pro": {
		name: "DeepSeek V4 Pro",
		matchingModel: "accounts/fireworks/models/deepseek-v4-pro",
		provider: "fireworks",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00348,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 31.2,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek-thinking",
		openWeights: true,
	},

	"accounts/fireworks/models/glm-5": {
		name: "GLM 5",
		matchingModel: "accounts/fireworks/models/glm-5",
		provider: "fireworks",
		releaseDate: "February 11, 2026",
		lastUpdated: "February 11, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 131072,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.0032,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 32.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/glm-5p1": {
		name: "GLM 5.1",
		matchingModel: "accounts/fireworks/models/glm-5p1",
		provider: "fireworks",
		releaseDate: "April 1, 2026",
		lastUpdated: "April 1, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 35.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	},

	"accounts/fireworks/models/kimi-k2p6": {
		name: "Kimi K2.6",
		matchingModel: "accounts/fireworks/models/kimi-k2p6",
		provider: "fireworks",
		releaseDate: "April 17, 2026",
		lastUpdated: "April 17, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 42.8,
			codingIndex: 56,
			agenticIndex: 30.3,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-thinking",
		openWeights: true,
	},

	"accounts/fireworks/models/minimax-m2p5": {
		name: "MiniMax-M2.5",
		matchingModel: "accounts/fireworks/models/minimax-m2p5",
		provider: "fireworks",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 196608,
		maxTokens: 196608,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 33.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"accounts/fireworks/models/minimax-m2p7": {
		name: "MiniMax-M2.7",
		matchingModel: "accounts/fireworks/models/minimax-m2p7",
		provider: "fireworks",
		releaseDate: "April 12, 2026",
		lastUpdated: "April 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 196608,
		maxTokens: 196608,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 38.1,
			codingIndex: 52.6,
			agenticIndex: 25.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
	},

	"accounts/fireworks/models/qwen3p6-plus": {
		name: "Qwen 3.6 Plus",
		matchingModel: "accounts/fireworks/models/qwen3p6-plus",
		provider: "fireworks",
		releaseDate: "April 4, 2026",
		lastUpdated: "April 4, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	},

	"accounts/fireworks/routers/kimi-k2p5-turbo": {
		name: "Kimi K2.5 Turbo",
		matchingModel: "accounts/fireworks/routers/kimi-k2p5-turbo",
		provider: "fireworks",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	},
	"accounts/fireworks/models/deepseek-v4-flash": {
		name: "DeepSeek V4 Flash",
		matchingModel: "accounts/fireworks/models/deepseek-v4-flash",
		provider: "fireworks",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "June 16, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 28.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek-flash",
		openWeights: true,
	},
	"accounts/fireworks/routers/glm-5p1-fast": {
		name: "GLM 5.1 Fast",
		matchingModel: "accounts/fireworks/routers/glm-5p1-fast",
		provider: "fireworks",
		releaseDate: "April 1, 2026",
		lastUpdated: "April 1, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0028,
		costPer1kOutputTokens: 0.0088,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "glm",
		openWeights: true,
	},

	"accounts/fireworks/routers/kimi-k2p6-turbo": {
		name: "Kimi K2.6 Turbo",
		matchingModel: "accounts/fireworks/routers/kimi-k2p6-turbo",
		provider: "fireworks",
		releaseDate: "April 17, 2026",
		lastUpdated: "April 17, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "kimi-thinking",
		openWeights: true,
	},
	"accounts/fireworks/routers/kimi-k2p6-fast": {
		name: "Kimi K2.6 Fast",
		matchingModel: "accounts/fireworks/routers/kimi-k2p6-fast",
		provider: "fireworks",
		releaseDate: "April 17, 2026",
		lastUpdated: "June 5, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "kimi-thinking",
		openWeights: true,
	},
	"accounts/fireworks/models/kimi-k2p7-code": {
		name: "Kimi K2.7 Code",
		matchingModel: "accounts/fireworks/models/kimi-k2p7-code",
		provider: "fireworks",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 16, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		knowledgeCutoffDate: "January 2025",
		supportsResponseFormat: true,
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 41.9,
			codingIndex: 60.8,
			agenticIndex: 29.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-k2",
		openWeights: true,
	},

	"accounts/fireworks/models/minimax-m3": {
		name: "MiniMax-M3",
		matchingModel: "accounts/fireworks/models/minimax-m3",
		provider: "fireworks",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 512000,
		maxTokens: 512000,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 44.4,
			codingIndex: 58.6,
			agenticIndex: 35.4,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
	},

	"accounts/fireworks/models/qwen3p7-plus": {
		name: "Qwen 3.7 Plus",
		matchingModel: "accounts/fireworks/models/qwen3p7-plus",
		provider: "fireworks",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 12, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "qwen",
		openWeights: false,
	},

	"accounts/fireworks/routers/kimi-k2p7-code-fast": {
		name: "Kimi K2.7 Code Fast",
		matchingModel: "accounts/fireworks/routers/kimi-k2p7-code-fast",
		provider: "fireworks",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 16, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262000,
		maxTokens: 262000,
		costPer1kInputTokens: 0.0019,
		costPer1kOutputTokens: 0.008,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		knowledgeCutoffDate: "January 2025",
		supportsResponseFormat: true,
		family: "kimi-k2",
		openWeights: true,
	},
	"accounts/fireworks/models/glm-5p2": {
		name: "GLM 5.2",
		matchingModel: "accounts/fireworks/models/glm-5p2",
		provider: "fireworks",
		releaseDate: "June 16, 2026",
		lastUpdated: "June 16, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048575,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 51.1,
			codingIndex: 68.8,
			agenticIndex: 43.1,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	},
	"accounts/fireworks/routers/glm-5p2-fast": {
		name: "GLM 5.2 Fast",
		matchingModel: "accounts/fireworks/routers/glm-5p2-fast",
		provider: "fireworks",
		family: "glm",
		openWeights: true,
		releaseDate: "June 26, 2026",
		lastUpdated: "June 26, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048575,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0021,
		costPer1kOutputTokens: 0.0066,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	},
};
