import type { ModelConfig } from "~/types";
import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "github-copilot";

export const githubCopilotModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("ghcopilot/openai/o4-mini", PROVIDER, {
		name: "o4-mini (Preview)",
		matchingModel: "o4-mini",
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 65536,
	}),

	createModelConfig("ghcopilot/anthropic/claude-3.5-sonnet", PROVIDER, {
		name: "Claude Sonnet 3.5",
		matchingModel: "claude-3.5-sonnet",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "October 22, 2024",
		lastUpdated: "October 22, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 8192,
	}),

	createModelConfig("ghcopilot/google/gemini-2.0-flash-001", PROVIDER, {
		name: "Gemini 2.0 Flash",
		matchingModel: "gemini-2.0-flash-001",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "June 2024",
		releaseDate: "December 11, 2024",
		lastUpdated: "December 11, 2024",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		contextWindow: 1000000,
		maxTokens: 8192,
	}),

	createModelConfig("ghcopilot/anthropic/claude-opus-4.1", PROVIDER, {
		name: "Claude Opus 4.1",
		matchingModel: "claude-opus-4.1",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "March 2025",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 32000,
	}),

	createModelConfig("ghcopilot/anthropic/claude-3.7-sonnet-thought", PROVIDER, {
		name: "Claude Sonnet 3.7 Thinking",
		matchingModel: "claude-3.7-sonnet-thought",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "February 19, 2025",
		lastUpdated: "February 19, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 8192,
	}),

	createModelConfig("ghcopilot/anthropic/claude-3.7-sonnet", PROVIDER, {
		name: "Claude Sonnet 3.7",
		matchingModel: "claude-3.7-sonnet",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "February 19, 2025",
		lastUpdated: "February 19, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 8192,
	}),

	createModelConfig("ghcopilot/google/gemini-2.5-pro", PROVIDER, {
		name: "Gemini 2.5 Pro",
		matchingModel: "gemini-2.5-pro",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "March 20, 2025",
		lastUpdated: "June 5, 2025",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		contextWindow: 128000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/anthropic/claude-opus-4", PROVIDER, {
		name: "Claude Opus 4",
		matchingModel: "claude-opus-4",
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: false,
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 80000,
		maxTokens: 16000,
	}),

	createModelConfig("ghcopilot/openai/o3-mini", PROVIDER, {
		name: "o3-mini",
		matchingModel: "o3-mini",
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "December 20, 2024",
		lastUpdated: "January 29, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 65536,
	}),

	createModelConfig("ghcopilot/openai/gpt-4.1", PROVIDER, {
		name: "GPT-4.1",
		matchingModel: "gpt-4.1",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/openai/gpt-4o", PROVIDER, {
		name: "GPT-4o",
		matchingModel: "gpt-4o",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "May 13, 2024",
		lastUpdated: "May 13, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/openai/o3", PROVIDER, {
		name: "o3 (Preview)",
		matchingModel: "o3",
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
	}),
	createModelConfig("ghcopilot/anthropic/claude-haiku-4.5", PROVIDER, {
		name: "Claude Haiku 4.5",
		matchingModel: "claude-haiku-4.5",
		knowledgeCutoffDate: "February 28, 2025",
		releaseDate: "October 15, 2025",
		lastUpdated: "October 15, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 144000,
		maxTokens: 32000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/anthropic/claude-opus-4.5", PROVIDER, {
		name: "Claude Opus 4.5",
		matchingModel: "claude-opus-4.5",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "November 24, 2025",
		lastUpdated: "August 1, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 160000,
		maxTokens: 32000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/anthropic/claude-opus-4.6", PROVIDER, {
		name: "Claude Opus 4.6",
		matchingModel: "claude-opus-4.6",
		knowledgeCutoffDate: "May 31, 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "February 5, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 144000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/anthropic/claude-sonnet-4.5", PROVIDER, {
		name: "Claude Sonnet 4.5",
		matchingModel: "claude-sonnet-4.5",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 144000,
		maxTokens: 32000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/google/gemini-3-flash-preview", PROVIDER, {
		name: "Gemini 3 Flash",
		matchingModel: "gemini-3-flash-preview",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "December 17, 2025",
		lastUpdated: "December 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/openai/gpt-5-mini", PROVIDER, {
		name: "GPT-5-mini",
		matchingModel: "gpt-5-mini",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "August 13, 2025",
		lastUpdated: "August 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 264000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/openai/gpt-5.2", PROVIDER, {
		name: "GPT-5.2",
		matchingModel: "gpt-5.2",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 264000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/openai/gpt-5.2-codex", PROVIDER, {
		name: "GPT-5.2-Codex",
		matchingModel: "gpt-5.2-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("ghcopilot/xai/grok-code-fast-1", PROVIDER, {
		name: "Grok Code Fast 1",
		matchingModel: "grok-code-fast-1",
		knowledgeCutoffDate: "August 2025",
		releaseDate: "August 27, 2025",
		lastUpdated: "August 27, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),
	createModelConfig("claude-opus-4.7", PROVIDER, {
		name: "Claude Opus 4.7",
		matchingModel: "claude-opus-4.7",
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "April 16, 2026",
		lastUpdated: "April 16, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 144000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("claude-sonnet-4.6", PROVIDER, {
		name: "Claude Sonnet 4.6",
		matchingModel: "claude-sonnet-4.6",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 17, 2026",
		lastUpdated: "February 17, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("gemini-3.1-pro-preview", PROVIDER, {
		name: "Gemini 3.1 Pro Preview",
		matchingModel: "gemini-3.1-pro-preview",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 19, 2026",
		lastUpdated: "February 19, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("gpt-5.3-codex", PROVIDER, {
		name: "GPT-5.3-Codex",
		matchingModel: "gpt-5.3-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 24, 2026",
		lastUpdated: "February 24, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("gpt-5.4", PROVIDER, {
		name: "GPT-5.4",
		matchingModel: "gpt-5.4",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 5, 2026",
		lastUpdated: "March 5, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("gpt-5.4-mini", PROVIDER, {
		name: "GPT-5.4 Mini",
		matchingModel: "gpt-5.4-mini",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 17, 2026",
		lastUpdated: "March 17, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("gpt-5.5", PROVIDER, {
		name: "GPT-5.5",
		matchingModel: "gpt-5.5",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "April 22, 2026",
		lastUpdated: "April 22, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	}),
]);
