import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "github-copilot";

export const githubCopilotModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("ghcopilot/anthropic/claude-sonnet-4", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "claude-sonnet-4",
		supportsAttachments: true,
		supportsReasoning: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 8192,
	}),

	createModelConfig("ghcopilot/openai/o4-mini", PROVIDER, {
		name: "o4-mini (Preview)",
		matchingModel: "o4-mini",
		supportsAttachments: false,
		supportsReasoning: true,
		supportsTemperature: false,
		supportsToolCalls: false,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 65536,
	}),

	createModelConfig("ghcopilot/anthropic/claude-3.5-sonnet", PROVIDER, {
		name: "Claude Sonnet 3.5",
		matchingModel: "claude-3.5-sonnet",
		supportsAttachments: true,
		supportsReasoning: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "October 22, 2024",
		lastUpdated: "October 22, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 8192,
	}),

	createModelConfig("ghcopilot/google/gemini-2.0-flash-001", PROVIDER, {
		name: "Gemini 2.0 Flash",
		matchingModel: "gemini-2.0-flash-001",
		supportsAttachments: true,
		supportsReasoning: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "June 2024",
		releaseDate: "December 11, 2024",
		lastUpdated: "December 11, 2024",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		contextWindow: 1000000,
		maxTokens: 8192,
	}),

	createModelConfig("ghcopilot/anthropic/claude-opus-4.1", PROVIDER, {
		name: "Claude Opus 4.1",
		matchingModel: "claude-opus-4.1",
		supportsAttachments: true,
		supportsReasoning: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "March 2025",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 32000,
	}),

	createModelConfig("ghcopilot/anthropic/claude-3.7-sonnet-thought", PROVIDER, {
		name: "Claude Sonnet 3.7 Thinking",
		matchingModel: "claude-3.7-sonnet-thought",
		supportsAttachments: true,
		supportsReasoning: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "February 19, 2025",
		lastUpdated: "February 19, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 8192,
	}),

	createModelConfig("ghcopilot/anthropic/claude-3.7-sonnet", PROVIDER, {
		name: "Claude Sonnet 3.7",
		matchingModel: "claude-3.7-sonnet",
		supportsAttachments: true,
		supportsReasoning: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "February 19, 2025",
		lastUpdated: "February 19, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 8192,
	}),

	createModelConfig("ghcopilot/google/gemini-2.5-pro", PROVIDER, {
		name: "Gemini 2.5 Pro (Preview)",
		matchingModel: "gemini-2.5-pro",
		supportsAttachments: true,
		supportsReasoning: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "March 20, 2025",
		lastUpdated: "June 5, 2025",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		contextWindow: 1048576,
		maxTokens: 65536,
	}),

	createModelConfig("ghcopilot/anthropic/claude-opus-4", PROVIDER, {
		name: "Claude Opus 4",
		matchingModel: "claude-opus-4",
		supportsAttachments: true,
		supportsReasoning: true,
		supportsTemperature: false,
		supportsToolCalls: false,
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 80000,
		maxTokens: 16000,
	}),

	createModelConfig("ghcopilot/openai/o3-mini", PROVIDER, {
		name: "o3-mini",
		matchingModel: "o3-mini",
		supportsAttachments: false,
		supportsReasoning: true,
		supportsTemperature: false,
		supportsToolCalls: false,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "December 20, 2024",
		lastUpdated: "January 29, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 65536,
	}),

	createModelConfig("ghcopilot/openai/gpt-4.1", PROVIDER, {
		name: "GPT-4.1",
		matchingModel: "gpt-4.1",
		supportsAttachments: true,
		supportsReasoning: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
	}),

	createModelConfig("ghcopilot/openai/gpt-4o", PROVIDER, {
		name: "GPT-4o",
		matchingModel: "gpt-4o",
		supportsAttachments: true,
		supportsReasoning: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "May 13, 2024",
		lastUpdated: "May 13, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
	}),

	createModelConfig("openai/o3", PROVIDER, {
		name: "o3 (Preview)",
		matchingModel: "o3",
		supportsAttachments: true,
		supportsReasoning: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
	}),
]);
