import type { ModelConfig } from "~/types";

export const googleAiStudioModelConfig: ModelConfig = {
	"gemini-3-pro-preview": {
		name: "Gemini 3 Pro",
		matchingModel: "gemini-3-pro-preview",
		description:
			"Gemini 3 Pro is our state-of-the-art thinking model, capable of reasoning over complex problems in code, math, and STEM, as well as analyzing large datasets, codebases, and documents using long context.",
		provider: "google-ai-studio",
		strengths: ["coding", "analysis", "math", "multilingual"],
		multimodal: true,
		supportsToolCalls: true,
		supportsSearchGrounding: true,
		supportsCodeExecution: true,
		reasoningConfig: { enabled: true },
		supportsAttachments: true,
		supportsTemperature: true,
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		knowledgeCutoffDate: "January 2025",
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.004,
		costPer1kOutputTokens: 0.012,
		supportsArtifacts: true,
		isFeatured: true,
		isFree: true,
		includedInRouter: true,
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
	},
	"gemini-flash-latest": {
		name: "Gemini Flash",
		matchingModel: "gemini-flash-latest",
		description:
			"Gemini Flash delivers next-gen features and improved capabilities, including superior speed, native tool use, multimodal generation, and a 1M token context window.",
		provider: "google-ai-studio",
		strengths: ["coding", "analysis", "math", "multilingual"],
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		supportsCodeExecution: true,
		supportsSearchGrounding: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: true,
		multimodal: true,
		knowledgeCutoffDate: "January 2025",
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		isFree: true,
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
	},
	"gemini-flash-lite-latest": {
		name: "Gemini Flash Lite",
		matchingModel: "gemini-flash-lite-latest",
		description:
			"A Gemini Flash model optimized for cost efficiency and low latency.",
		provider: "google-ai-studio",
		strengths: ["coding", "analysis", "math", "multilingual"],
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		supportsTemperature: true,
		multimodal: true,
		knowledgeCutoffDate: "January 2025",
		contextWindow: 1048576,
		maxTokens: 8192,
		costPer1kInputTokens: 0.000075,
		costPer1kOutputTokens: 0.0003,
		supportsArtifacts: true,
		isFree: true,
		contextComplexity: 3,
		reliability: 3,
		speed: 2,
	},
};
