import type { ModelConfig } from "@ngriffin_uk/polychat-schemas";

import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "google-vertex";

export const googleVertexModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("gemini-2.5-pro", PROVIDER, {
		name: "Gemini 2.5 Pro",
		matchingModel: "gemini-2.5-pro",
		family: "gemini-pro",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["reasoning", "coding", "analysis", "multilingual", "tool_use", "vision", "document", "audio", "video"],
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 27,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),
	createModelConfig("gemini-2.5-flash", PROVIDER, {
		name: "Gemini 2.5 Flash",
		matchingModel: "gemini-2.5-flash",
		family: "gemini-flash",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["summarization", "coding", "tool_use", "vision", "document", "audio", "video"],
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		contextComplexity: 4,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 14.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),
	createModelConfig("gemini-2.5-flash-image", PROVIDER, {
		name: "Nano Banana",
		matchingModel: "gemini-2.5-flash-image",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "June 2024",
		releaseDate: "August 26, 2025",
		lastUpdated: "August 26, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text", "image"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.03,
		strengths: ["vision", "document", "image", "creative"],
		contextComplexity: 3,
		reliability: 4,
		artificialAnalysis: {
			intelligenceIndex: null,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: null,
			mediaScores: [{
				key: "text_to_imageElo",
				label: "Text-to-image arena",
				value: 1159,
				min: 800,
				max: 1400,
				confidenceInterval95: 8,
			}],
		},
	}),

	createModelConfig("gemini-2.5-flash-lite", PROVIDER, {
		name: "Gemini 2.5 Flash-Lite",
		matchingModel: "gemini-2.5-flash-lite",
		family: "gemini-flash-lite",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["audio", "vision", "document", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 3,
		artificialAnalysis: {
			intelligenceIndex: null,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: null,
			mediaScores: [{
				key: "text_to_speechElo",
				label: "Text-to-speech arena",
				value: 1088,
				min: 800,
				max: 1400,
				confidenceInterval95: 12,
			}],
		},
	}),

	createModelConfig("gemini-2.5-flash-tts", PROVIDER, {
		name: "Gemini 2.5 Flash TTS",
		matchingModel: "gemini-2.5-flash-tts",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "September 30, 2025",
		lastUpdated: "December 10, 2025",
		modalities: {
			input: ["text"],
			output: ["audio"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 32768,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.01,
		strengths: ["audio"],
		contextComplexity: 2,
		reliability: 2,
		artificialAnalysis: {
			intelligenceIndex: null,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: null,
			mediaScores: [{
				key: "text_to_speechElo",
				label: "Text-to-speech arena",
				value: 1036,
				min: 800,
				max: 1400,
				confidenceInterval95: 12,
			}],
		},
	}),

	createModelConfig("gemini-2.5-pro-tts", PROVIDER, {
		name: "Gemini 2.5 Pro TTS",
		matchingModel: "gemini-2.5-pro-tts",
		family: "gemini-pro",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "September 30, 2025",
		lastUpdated: "December 10, 2025",
		modalities: {
			input: ["text"],
			output: ["audio"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 32768,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.02,
	}),

	createModelConfig("gemini-3-flash-preview", PROVIDER, {
		name: "Gemini 3 Flash Preview",
		matchingModel: "gemini-3-flash-preview",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "December 17, 2025",
		lastUpdated: "December 17, 2025",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["minimal", "low", "medium", "high"],
			defaultEffort: "minimal",
		},
		strengths: ["vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 27.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gemini-3-pro-image", PROVIDER, {
		name: "Nano Banana Pro",
		matchingModel: "gemini-3-pro-image",
		family: "gemini-pro",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 28, 2026",
		lastUpdated: "May 28, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text", "image"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 65536,
		maxTokens: 32768,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.12,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "image", "creative"],
		contextComplexity: 3,
		reliability: 4,
		artificialAnalysis: {
			intelligenceIndex: null,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: null,
			mediaScores: [{
				key: "text_to_imageElo",
				label: "Text-to-image arena",
				value: 1219,
				min: 800,
				max: 1400,
				confidenceInterval95: 9,
			}],
		},
	}),

	createModelConfig("gemini-3.1-flash-image", PROVIDER, {
		name: "Nano Banana 2",
		matchingModel: "gemini-3.1-flash-image",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 28, 2026",
		lastUpdated: "May 28, 2026",
		modalities: {
			input: ["text", "image", "video", "pdf"],
			output: ["text", "image"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.06,
		reasoningConfig: {
			supportedEffortLevels: ["minimal", "high"],
			defaultEffort: "minimal",
		},
		strengths: ["vision", "document", "video", "image", "creative"],
		contextComplexity: 3,
		reliability: 5,
		artificialAnalysis: {
			intelligenceIndex: null,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: null,
			mediaScores: [{
				key: "text_to_imageElo",
				label: "Text-to-image arena",
				value: 1254,
				min: 800,
				max: 1400,
				confidenceInterval95: 9,
			}],
		},
	}),

	createModelConfig("gemini-3.1-flash-lite", PROVIDER, {
		name: "Gemini 3.1 Flash Lite",
		matchingModel: "gemini-3.1-flash-lite",
		family: "gemini-flash-lite",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 7, 2026",
		lastUpdated: "May 7, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.0015,
		reasoningConfig: {
			supportedEffortLevels: ["minimal", "low", "medium", "high"],
			defaultEffort: "minimal",
		},
		strengths: ["vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 25,
			codingIndex: 34.7,
			agenticIndex: 6.2,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gemini-3.1-pro-preview", PROVIDER, {
		name: "Gemini 3.1 Pro Preview",
		matchingModel: "gemini-3.1-pro-preview",
		family: "gemini-pro",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 19, 2026",
		lastUpdated: "February 19, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.012,
		reasoningConfig: {
			supportedEffortLevels: ["low", "medium", "high"],
			defaultEffort: "low",
		},
		strengths: ["coding", "vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 46.5,
			codingIndex: 68.8,
			agenticIndex: 21.4,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gemini-3.1-pro-preview-customtools", PROVIDER, {
		name: "Gemini 3.1 Pro Preview Custom Tools",
		matchingModel: "gemini-3.1-pro-preview-customtools",
		family: "gemini-pro",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 19, 2026",
		lastUpdated: "February 19, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.012,
		reasoningConfig: {
			supportedEffortLevels: ["low", "medium", "high"],
			defaultEffort: "low",
		},
	}),

	createModelConfig("gemini-3.5-flash", PROVIDER, {
		name: "Gemini 3.5 Flash",
		matchingModel: "gemini-3.5-flash",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 19, 2026",
		lastUpdated: "May 19, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.009,
		reasoningConfig: {
			supportedEffortLevels: ["minimal", "low", "medium", "high"],
			defaultEffort: "minimal",
		},
		strengths: ["coding", "vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 3,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 50.2,
			codingIndex: 70.1,
			agenticIndex: 37.4,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gemini-3.5-flash-lite", PROVIDER, {
		name: "Gemini 3.5 Flash Lite",
		matchingModel: "gemini-3.5-flash-lite",
		family: "gemini-flash-lite",
		openWeights: false,
		knowledgeCutoffDate: "March 2026",
		releaseDate: "July 21, 2026",
		lastUpdated: "July 21, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		reasoningConfig: {
			supportedEffortLevels: ["minimal", "low", "medium", "high"],
			defaultEffort: "minimal",
		},
	}),

	createModelConfig("gemini-3.6-flash", PROVIDER, {
		name: "Gemini 3.6 Flash",
		matchingModel: "gemini-3.6-flash",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "March 2026",
		releaseDate: "July 21, 2026",
		lastUpdated: "July 21, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00075,
		costPer1kOutputTokens: 0.00375,
		reasoningConfig: {
			supportedEffortLevels: ["minimal", "low", "medium", "high"],
			defaultEffort: "minimal",
		},
	}),

	createModelConfig("gemini-3.7-flash", PROVIDER, {
		name: "Gemini 3.7 Flash",
		matchingModel: "gemini-3.7-flash",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "March 2026",
		releaseDate: "August 13, 2026",
		lastUpdated: "August 13, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00075,
		costPer1kOutputTokens: 0.00375,
		reasoningConfig: {
			supportedEffortLevels: ["low", "medium", "high"],
			defaultEffort: "low",
		},
	}),

	createModelConfig("gemini-embedding-001", PROVIDER, {
		name: "Gemini Embedding 001",
		matchingModel: "gemini-embedding-001",
		family: "gemini",
		openWeights: false,
		knowledgeCutoffDate: "May 2025",
		releaseDate: "May 20, 2025",
		lastUpdated: "May 20, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 2048,
		maxTokens: 1,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0,
	}),

	createModelConfig("gemini-flash-latest", PROVIDER, {
		name: "Gemini Flash Latest",
		matchingModel: "gemini-flash-latest",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "March 2026",
		releaseDate: "August 13, 2026",
		lastUpdated: "August 13, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.009,
		reasoningConfig: {
			supportedEffortLevels: ["minimal", "low", "medium", "high"],
			defaultEffort: "minimal",
		},
	}),

	createModelConfig("gemini-flash-lite-latest", PROVIDER, {
		name: "Gemini Flash-Lite Latest",
		matchingModel: "gemini-flash-lite-latest",
		family: "gemini-flash-lite",
		openWeights: false,
		knowledgeCutoffDate: "March 2026",
		releaseDate: "July 21, 2026",
		lastUpdated: "July 21, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.0015,
		reasoningConfig: {
			supportedEffortLevels: ["minimal", "low", "medium", "high"],
			defaultEffort: "minimal",
		},
	}),
	createModelConfig("gemini-3.8-flash", PROVIDER, {
		name: "Gemini 3.8 Flash",
		matchingModel: "gemini-3.8-flash",
		family: "gemini-flash",
		openWeights: false,
		releaseDate: "September 2, 2026",
		lastUpdated: "September 2, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00075,
		costPer1kOutputTokens: 0.00375,
		reasoningConfig: {
			supportedEffortLevels: ["low", "medium", "high"],
			defaultEffort: "low",
		},
	}),
]);
