import type { ModelConfig } from "~/types";

export const googleAiStudioModelConfig: ModelConfig = {
	"gemini-3-pro-preview": {
		name: "Gemini 3 Pro Preview",
		matchingModel: "gemini-3-pro-preview",
		description:
			"Gemini 3 Pro is our state-of-the-art thinking model, capable of reasoning over complex problems in code, math, and STEM, as well as analyzing large datasets, codebases, and documents using long context.",
		provider: "google-ai-studio",
		strengths: ["coding", "analysis", "math", "multilingual"],
		multimodal: true,
		supportsToolCalls: true,
		supportsSearchGrounding: true,
		supportsCodeExecution: true,
		reasoningConfig: { enabled: true },
		supportsAttachments: true,
		supportsTemperature: true,
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		knowledgeCutoffDate: "January 2025",
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.012,
		supportsArtifacts: true,
		isFeatured: true,
		isFree: true,
		includedInRouter: true,
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		releaseDate: "November 18, 2025",
		lastUpdated: "November 18, 2025",
		supportsResponseFormat: true,
	},
	"gemini-3-flash-preview": {
		name: "Gemini 3 Flash Preview",
		matchingModel: "gemini-3-flash-preview",
		description:
			"Gemini Flash delivers next-gen features and improved capabilities, including superior speed, native tool use, multimodal generation, and a 1M token context window.",
		provider: "google-ai-studio",
		strengths: ["coding", "analysis", "math", "multilingual"],
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		supportsCodeExecution: true,
		supportsSearchGrounding: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: true,
		multimodal: true,
		knowledgeCutoffDate: "January 2025",
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		isFree: true,
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		releaseDate: "December 17, 2025",
		lastUpdated: "December 17, 2025",
		supportsResponseFormat: true,
	},
	"gemini-flash-lite-latest": {
		name: "Gemini Flash-Lite Latest",
		matchingModel: "gemini-flash-lite-latest",
		description:
			"A Gemini Flash model optimized for cost efficiency and low latency.",
		provider: "google-ai-studio",
		strengths: ["coding", "analysis", "math", "multilingual"],
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		supportsTemperature: true,
		multimodal: true,
		knowledgeCutoffDate: "January 2025",
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
		supportsArtifacts: true,
		isFree: true,
		contextComplexity: 3,
		reliability: 3,
		speed: 2,
		releaseDate: "September 25, 2025",
		lastUpdated: "September 25, 2025",
		supportsResponseFormat: true,
		reasoningConfig: {
			enabled: true,
		},
	},
	"gemini-1.5-flash": {
		name: "Gemini 1.5 Flash",
		matchingModel: "gemini-1.5-flash",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "May 14, 2024",
		lastUpdated: "May 14, 2024",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.000075,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			enabled: false,
		},
	},

	"gemini-1.5-flash-8b": {
		name: "Gemini 1.5 Flash-8B",
		matchingModel: "gemini-1.5-flash-8b",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "October 3, 2024",
		lastUpdated: "October 3, 2024",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0000375,
		costPer1kOutputTokens: 0.00015,
		reasoningConfig: {
			enabled: false,
		},
	},

	"gemini-1.5-pro": {
		name: "Gemini 1.5 Pro",
		matchingModel: "gemini-1.5-pro",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "February 15, 2024",
		lastUpdated: "February 15, 2024",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.005,
		reasoningConfig: {
			enabled: false,
		},
	},

	"gemini-2.0-flash": {
		name: "Gemini 2.0 Flash",
		matchingModel: "gemini-2.0-flash",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "December 11, 2024",
		lastUpdated: "December 11, 2024",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			enabled: false,
		},
	},

	"gemini-2.0-flash-lite": {
		name: "Gemini 2.0 Flash Lite",
		matchingModel: "gemini-2.0-flash-lite",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "December 11, 2024",
		lastUpdated: "December 11, 2024",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 8192,
		costPer1kInputTokens: 0.000075,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			enabled: false,
		},
	},

	"gemini-2.5-flash": {
		name: "Gemini 2.5 Flash",
		matchingModel: "gemini-2.5-flash",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "March 20, 2025",
		lastUpdated: "June 5, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-flash-image": {
		name: "Gemini 2.5 Flash Image",
		matchingModel: "gemini-2.5-flash-image",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "June 2025",
		releaseDate: "August 26, 2025",
		lastUpdated: "August 26, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text", "image"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.03,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-flash-image-preview": {
		name: "Gemini 2.5 Flash Image (Preview)",
		matchingModel: "gemini-2.5-flash-image-preview",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "June 2025",
		releaseDate: "August 26, 2025",
		lastUpdated: "August 26, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text", "image"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.03,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-flash-lite": {
		name: "Gemini 2.5 Flash Lite",
		matchingModel: "gemini-2.5-flash-lite",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-flash-lite-preview-06-17": {
		name: "Gemini 2.5 Flash Lite Preview 06-17",
		matchingModel: "gemini-2.5-flash-lite-preview-06-17",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-flash-lite-preview-09-2025": {
		name: "Gemini 2.5 Flash Lite Preview 09-25",
		matchingModel: "gemini-2.5-flash-lite-preview-09-2025",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "September 25, 2025",
		lastUpdated: "September 25, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-flash-preview-04-17": {
		name: "Gemini 2.5 Flash Preview 04-17",
		matchingModel: "gemini-2.5-flash-preview-04-17",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "April 17, 2025",
		lastUpdated: "April 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-flash-preview-05-20": {
		name: "Gemini 2.5 Flash Preview 05-20",
		matchingModel: "gemini-2.5-flash-preview-05-20",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 20, 2025",
		lastUpdated: "May 20, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-flash-preview-09-2025": {
		name: "Gemini 2.5 Flash Preview 09-25",
		matchingModel: "gemini-2.5-flash-preview-09-2025",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "September 25, 2025",
		lastUpdated: "September 25, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-flash-preview-tts": {
		name: "Gemini 2.5 Flash Preview TTS",
		matchingModel: "gemini-2.5-flash-preview-tts",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 1, 2025",
		lastUpdated: "May 1, 2025",
		modalities: {
			input: ["text"],
			output: ["audio"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 8000,
		maxTokens: 16000,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: false,
		},
	},

	"gemini-2.5-pro": {
		name: "Gemini 2.5 Pro",
		matchingModel: "gemini-2.5-pro",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "March 20, 2025",
		lastUpdated: "June 5, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-pro-preview-05-06": {
		name: "Gemini 2.5 Pro Preview 05-06",
		matchingModel: "gemini-2.5-pro-preview-05-06",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 6, 2025",
		lastUpdated: "May 6, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-pro-preview-06-05": {
		name: "Gemini 2.5 Pro Preview 06-05",
		matchingModel: "gemini-2.5-pro-preview-06-05",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 5, 2025",
		lastUpdated: "June 5, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-2.5-pro-preview-tts": {
		name: "Gemini 2.5 Pro Preview TTS",
		matchingModel: "gemini-2.5-pro-preview-tts",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 1, 2025",
		lastUpdated: "May 1, 2025",
		modalities: {
			input: ["text"],
			output: ["audio"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 8000,
		maxTokens: 16000,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.02,
		reasoningConfig: {
			enabled: false,
		},
	},

	"gemini-embedding-001": {
		name: "Gemini Embedding 001",
		matchingModel: "gemini-embedding-001",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "May 20, 2025",
		lastUpdated: "May 20, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 2048,
		maxTokens: 3072,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"gemini-flash-latest": {
		name: "Gemini Flash Latest",
		matchingModel: "gemini-flash-latest",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "September 25, 2025",
		lastUpdated: "September 25, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-live-2.5-flash": {
		name: "Gemini Live 2.5 Flash",
		matchingModel: "gemini-live-2.5-flash",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "September 1, 2025",
		lastUpdated: "September 1, 2025",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text", "audio"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 8000,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			enabled: true,
		},
	},

	"gemini-live-2.5-flash-preview-native-audio": {
		name: "Gemini Live 2.5 Flash Preview Native Audio",
		matchingModel: "gemini-live-2.5-flash-preview-native-audio",
		provider: "google-ai-studio",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "September 18, 2025",
		modalities: {
			input: ["text", "audio", "video"],
			output: ["text", "audio"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			enabled: true,
		},
	},
};
