import type { ModelConfig } from "@ngriffin_uk/polychat-schemas";

import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "greenpt";

export const greenPtModelConfig: ModelConfig = createModelConfigObject([
  createModelConfig("green-l-raw", PROVIDER, {
    name: "Green L Raw",
    matchingModel: "green-l-raw",
    modalities: { input: ["text"], output: ["text"] },
    supportsTemperature: true,
    supportsToolCalls: true,
  	family: "mistral-small",
  	openWeights: true,
  	knowledgeCutoffDate: "March 2025",
  	releaseDate: "June 20, 2025",
  	lastUpdated: "June 20, 2025",
  	supportsAttachments: true,
  	contextWindow: 128000,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.000285,
  	costPer1kOutputTokens: 0.000912,
  }),
  createModelConfig("green-s", PROVIDER, {
    name: "Green S",
    matchingModel: "green-s",
    modalities: { input: ["text"], output: ["text"] },
    supportsTemperature: false,
    supportsToolCalls: false,
  	openWeights: false,
  	releaseDate: "January 2025",
  	lastUpdated: "January 2025",
  	supportsAttachments: false,
  	contextWindow: 0,
  	maxTokens: 8192,
  	costPer1kInputTokens: 0.00000437,
  	costPer1kOutputTokens: 0,
  }),
  createModelConfig("deepseek-v4-flash-0731", PROVIDER, {
  	name: "DeepSeek V4 Flash 0731",
  	matchingModel: "deepseek-v4-flash-0731",
  	family: "deepseek-flash",
  	openWeights: true,
  	knowledgeCutoffDate: "May 2025",
  	releaseDate: "July 31, 2026",
  	lastUpdated: "July 31, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 384000,
  	costPer1kInputTokens: 0.0001596,
  	costPer1kOutputTokens: 0.000399,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("devstral-2-123b-instruct-2512", PROVIDER, {
  	name: "Devstral 2",
  	matchingModel: "devstral-2-123b-instruct-2512",
  	family: "devstral",
  	openWeights: true,
  	knowledgeCutoffDate: "December 2025",
  	releaseDate: "December 9, 2025",
  	lastUpdated: "December 9, 2025",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 200000,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.00057,
  	costPer1kOutputTokens: 0.002736,
  	strengths: ["tool_use"],
  	contextComplexity: 3,
  	reliability: 1,
  	speed: 2,
  	artificialAnalysis: {
  		intelligenceIndex: 15.5,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("gemma-3-27b-it", PROVIDER, {
  	name: "Gemma 3 27B",
  	matchingModel: "gemma-3-27b-it",
  	family: "gemma",
  	openWeights: true,
  	knowledgeCutoffDate: "August 2024",
  	releaseDate: "March 12, 2025",
  	lastUpdated: "March 12, 2025",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 40000,
  	maxTokens: 8192,
  	costPer1kInputTokens: 0.000342,
  	costPer1kOutputTokens: 0.000684,
  	strengths: ["vision", "document", "tool_use"],
  	contextComplexity: 3,
  	reliability: 1,
  	artificialAnalysis: {
  		intelligenceIndex: 4.8,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("gemma4", PROVIDER, {
  	name: "gemma4",
  	matchingModel: "gemma4",
  	family: "gemma",
  	openWeights: true,
  	releaseDate: "April 2, 2026",
  	lastUpdated: "April 2, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.00057,
  	costPer1kOutputTokens: 0.00171,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("glm-5.2", PROVIDER, {
  	name: "GLM-5.2",
  	matchingModel: "glm-5.2",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.005016,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["coding", "tool_use"],
  	contextComplexity: 5,
  	reliability: 3,
  	speed: 4,
  	artificialAnalysis: {
  		intelligenceIndex: 51.1,
  		codingIndex: 68.8,
  		agenticIndex: 43.1,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("glm-5.2-caveman", PROVIDER, {
  	name: "GLM-5.2 Caveman",
  	matchingModel: "glm-5.2-caveman",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.005016,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("glm-5.2-caveman-lite", PROVIDER, {
  	name: "GLM-5.2 Caveman Lite",
  	matchingModel: "glm-5.2-caveman-lite",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.005016,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("glm-5.2-caveman-ultra", PROVIDER, {
  	name: "GLM-5.2 Caveman Ultra",
  	matchingModel: "glm-5.2-caveman-ultra",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.005016,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("glm-5.2-honey", PROVIDER, {
  	name: "GLM-5.2 Honey",
  	matchingModel: "glm-5.2-honey",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.005016,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("glm-5.2-honey-lite", PROVIDER, {
  	name: "GLM-5.2 Honey Lite",
  	matchingModel: "glm-5.2-honey-lite",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.005016,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("glm-5.2-honey-ultra", PROVIDER, {
  	name: "GLM-5.2 Honey Ultra",
  	matchingModel: "glm-5.2-honey-ultra",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.005016,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("glm-5.2-ponytail", PROVIDER, {
  	name: "GLM-5.2 Ponytail",
  	matchingModel: "glm-5.2-ponytail",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.005016,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("glm-5.2-ponytail-lite", PROVIDER, {
  	name: "GLM-5.2 Ponytail Lite",
  	matchingModel: "glm-5.2-ponytail-lite",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.005016,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("glm-5.2-ponytail-ultra", PROVIDER, {
  	name: "GLM-5.2 Ponytail Ultra",
  	matchingModel: "glm-5.2-ponytail-ultra",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1000000,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.005016,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("gpt-oss-120b", PROVIDER, {
  	name: "GPT OSS 120B",
  	matchingModel: "gpt-oss-120b",
  	family: "gpt-oss",
  	openWeights: true,
  	releaseDate: "August 5, 2025",
  	lastUpdated: "August 5, 2025",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 131072,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.000228,
  	costPer1kOutputTokens: 0.000798,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["vision", "document", "tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	speed: 5,
  	artificialAnalysis: {
  		intelligenceIndex: 23.8,
  		codingIndex: 30.4,
  		agenticIndex: 13.2,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("green-l", PROVIDER, {
  	name: "Green L",
  	matchingModel: "green-l",
  	family: "mistral-small",
  	openWeights: true,
  	knowledgeCutoffDate: "March 2025",
  	releaseDate: "June 20, 2025",
  	lastUpdated: "June 20, 2025",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 128000,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.000285,
  	costPer1kOutputTokens: 0.000912,
  }),

  createModelConfig("green-r", PROVIDER, {
  	name: "Green R",
  	matchingModel: "green-r",
  	family: "gpt-oss",
  	openWeights: true,
  	releaseDate: "August 5, 2025",
  	lastUpdated: "August 5, 2025",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 131072,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.000399,
  	costPer1kOutputTokens: 0.001083,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("green-r-raw", PROVIDER, {
  	name: "Green R Raw",
  	matchingModel: "green-r-raw",
  	family: "gpt-oss",
  	openWeights: true,
  	releaseDate: "August 5, 2025",
  	lastUpdated: "August 5, 2025",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 131072,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.000399,
  	costPer1kOutputTokens: 0.001083,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("green-s-pro", PROVIDER, {
  	name: "Green S Pro",
  	matchingModel: "green-s-pro",
  	openWeights: false,
  	releaseDate: "February 2025",
  	lastUpdated: "February 2025",
  	modalities: {
  		input: ["audio"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: false,
  	supportsToolCalls: false,
  	contextWindow: 0,
  	maxTokens: 8192,
  	costPer1kInputTokens: 0.00000437,
  	costPer1kOutputTokens: 0,
  }),

  createModelConfig("holo2-30b-a3b", PROVIDER, {
  	name: "Holo2 30B A3B",
  	matchingModel: "holo2-30b-a3b",
  	openWeights: true,
  	releaseDate: "November 2025",
  	lastUpdated: "November 2025",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: false,
  	contextWindow: 22016,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.000399,
  	costPer1kOutputTokens: 0.000969,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("kimi-k2.6", PROVIDER, {
  	name: "Kimi K2.6",
  	matchingModel: "kimi-k2.6",
  	family: "kimi-k2",
  	openWeights: true,
  	knowledgeCutoffDate: "January 2025",
  	releaseDate: "April 21, 2026",
  	lastUpdated: "April 21, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 262144,
  	costPer1kInputTokens: 0.0007524,
  	costPer1kOutputTokens: 0.004275,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["vision", "document", "tool_use"],
  	contextComplexity: 4,
  	reliability: 2,
  	speed: 3,
  	artificialAnalysis: {
  		intelligenceIndex: 42.8,
  		codingIndex: 56,
  		agenticIndex: 30.3,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("kimi-k2.7-code", PROVIDER, {
  	name: "Kimi K2.7 Code",
  	matchingModel: "kimi-k2.7-code",
  	family: "kimi-k2",
  	openWeights: true,
  	knowledgeCutoffDate: "January 2025",
  	releaseDate: "June 12, 2026",
  	lastUpdated: "June 12, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: false,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 262144,
  	costPer1kInputTokens: 0.0009006,
  	costPer1kOutputTokens: 0.004389,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["tool_use", "coding"],
  	contextComplexity: 4,
  	reliability: 2,
  	speed: 3,
  	artificialAnalysis: {
  		intelligenceIndex: 41.9,
  		codingIndex: 60.8,
  		agenticIndex: 29.6,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("kimi-k3", PROVIDER, {
  	name: "Kimi K3",
  	matchingModel: "kimi-k3",
  	family: "kimi-k3",
  	openWeights: true,
  	releaseDate: "July 16, 2026",
  	lastUpdated: "July 16, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: false,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 1048576,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.003762,
  	costPer1kOutputTokens: 0.01881,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("llama-3.3-70b-instruct", PROVIDER, {
  	name: "Llama-3.3-70B-Instruct",
  	matchingModel: "llama-3.3-70b-instruct",
  	family: "llama",
  	openWeights: true,
  	knowledgeCutoffDate: "December 2023",
  	releaseDate: "December 6, 2024",
  	lastUpdated: "December 6, 2024",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 100000,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.001254,
  	costPer1kOutputTokens: 0.001254,
  }),

  createModelConfig("minimax-m2.5", PROVIDER, {
  	name: "MiniMax-M2.5",
  	matchingModel: "minimax-m2.5",
  	family: "minimax",
  	openWeights: true,
  	releaseDate: "February 12, 2026",
  	lastUpdated: "February 12, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 204800,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.0001938,
  	costPer1kOutputTokens: 0.001129,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	speed: 4,
  	artificialAnalysis: {
  		intelligenceIndex: 33.7,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("mistral-medium-3.5-128b", PROVIDER, {
  	name: "Mistral Medium 3.5",
  	matchingModel: "mistral-medium-3.5-128b",
  	family: "mistral-medium",
  	openWeights: true,
  	releaseDate: "April 29, 2026",
  	lastUpdated: "April 29, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.002052,
  	costPer1kOutputTokens: 0.01026,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["vision", "document", "tool_use"],
  	contextComplexity: 4,
  	reliability: 2,
  	speed: 4,
  	artificialAnalysis: {
  		intelligenceIndex: 29.9,
  		codingIndex: 46.9,
  		agenticIndex: 19,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("mistral-small-3.2-24b-instruct-2506", PROVIDER, {
  	name: "Mistral Small 3.2",
  	matchingModel: "mistral-small-3.2-24b-instruct-2506",
  	family: "mistral-small",
  	openWeights: true,
  	knowledgeCutoffDate: "March 2025",
  	releaseDate: "June 20, 2025",
  	lastUpdated: "June 20, 2025",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 128000,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.000228,
  	costPer1kOutputTokens: 0.000456,
  	strengths: ["vision", "document", "tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	speed: 4,
  	artificialAnalysis: {
  		intelligenceIndex: 9.1,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("pixtral-12b-2409", PROVIDER, {
  	name: "Pixtral 12B",
  	matchingModel: "pixtral-12b-2409",
  	family: "pixtral",
  	openWeights: true,
  	knowledgeCutoffDate: "September 2024",
  	releaseDate: "September 1, 2024",
  	lastUpdated: "September 1, 2024",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 128000,
  	maxTokens: 4096,
  	costPer1kInputTokens: 0.000285,
  	costPer1kOutputTokens: 0.000285,
  }),

  createModelConfig("qwen3-235b-a22b-instruct-2507", PROVIDER, {
  	name: "Qwen3 235B A22B Instruct 2507",
  	matchingModel: "qwen3-235b-a22b-instruct-2507",
  	family: "qwen",
  	openWeights: true,
  	knowledgeCutoffDate: "April 2025",
  	releaseDate: "July 21, 2025",
  	lastUpdated: "July 21, 2025",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.001026,
  	costPer1kOutputTokens: 0.003078,
  	strengths: ["tool_use"],
  	contextComplexity: 3,
  	reliability: 1,
  	speed: 3,
  	artificialAnalysis: {
  		intelligenceIndex: 18.2,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("qwen3-coder-30b-a3b-instruct", PROVIDER, {
  	name: "Qwen3-Coder 30B-A3B Instruct",
  	matchingModel: "qwen3-coder-30b-a3b-instruct",
  	family: "qwen",
  	openWeights: true,
  	knowledgeCutoffDate: "April 2025",
  	releaseDate: "April 2025",
  	lastUpdated: "April 2025",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 128000,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.000285,
  	costPer1kOutputTokens: 0.001083,
  	strengths: ["tool_use"],
  	contextComplexity: 3,
  	reliability: 1,
  	speed: 4,
  	artificialAnalysis: {
  		intelligenceIndex: 13.6,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("qwen3.5-397b-a17b", PROVIDER, {
  	name: "Qwen3.5 397B-A17B",
  	matchingModel: "qwen3.5-397b-a17b",
  	family: "qwen",
  	openWeights: true,
  	releaseDate: "February 15, 2026",
  	lastUpdated: "February 15, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.000798,
  	costPer1kOutputTokens: 0.004959,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["tool_use"],
  	contextComplexity: 3,
  	reliability: 1,
  	speed: 2,
  	artificialAnalysis: {
  		intelligenceIndex: 32,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("qwen3.6-35b-a3b", PROVIDER, {
  	name: "Qwen3.6 35B-A3B",
  	matchingModel: "qwen3.6-35b-a3b",
  	family: "qwen",
  	openWeights: true,
  	releaseDate: "April 17, 2026",
  	lastUpdated: "April 17, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.000342,
  	costPer1kOutputTokens: 0.002052,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["vision", "document", "tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	speed: 4,
  	artificialAnalysis: {
  		intelligenceIndex: 24.2,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("voxtral-small-24b-2507", PROVIDER, {
  	name: "Voxtral Small 24B",
  	matchingModel: "voxtral-small-24b-2507",
  	family: "mistral",
  	openWeights: true,
  	knowledgeCutoffDate: "July 2025",
  	releaseDate: "July 15, 2025",
  	lastUpdated: "July 15, 2025",
  	modalities: {
  		input: ["text", "audio"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: false,
  	contextWindow: 32768,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.000228,
  	costPer1kOutputTokens: 0.000513,
  }),
]);
