import type { ModelConfig } from "~/types";

export const groqModelConfig: ModelConfig = {
	"deepseek-r1-distill-qwen-32b": {
		name: "Groq DeepSeek R1 Distill Qwen 32B",
		matchingModel: "deepseek-r1-distill-qwen-32b",
		provider: "groq",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "January 20, 2025",
		lastUpdated: "January 20, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		contextWindow: 128000,
		maxTokens: 16384,
		card: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
		reasoningConfig: { enabled: true },
		includedInRouter: true,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0003,
		speed: 4,
		strengths: ["reasoning", "analysis"],
		contextComplexity: 4,
		reliability: 4,
		supportsArtifacts: true,
		supportsToolCalls: true,
	},
	"deepseek-r1-distill-llama-70b-specdec": {
		name: "Groq DeepSeek R1 Distill Llama 70B SpecDec",
		matchingModel: "deepseek-r1-distill-llama-70b-specdec",
		provider: "groq",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "January 20, 2025",
		lastUpdated: "January 20, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		contextWindow: 128000,
		maxTokens: 16384,
		card: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
		reasoningConfig: { enabled: true },
		includedInRouter: true,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0004,
		speed: 4,
		strengths: ["reasoning", "analysis"],
		contextComplexity: 4,
		reliability: 4,
		supportsArtifacts: true,
		supportsToolCalls: true,
	},
	"llama3-70b": {
		name: "Groq Llama 3 70B",
		matchingModel: "llama3-70b-8192-tool-use-preview",
		provider: "groq",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "April 18, 2024",
		lastUpdated: "April 18, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		includedInRouter: true,
		contextWindow: 8192,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0006,
		speed: 5,
		strengths: ["chat", "analysis", "creative", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		supportsArtifacts: true,
	},
	"llama3-8b": {
		name: "Groq Llama 3 8B",
		matchingModel: "llama3-8b-8192-tool-use-preview",
		provider: "groq",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "April 18, 2024",
		lastUpdated: "April 18, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		includedInRouter: true,
		contextWindow: 8192,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0003,
		speed: 5,
		strengths: ["chat", "general_knowledge"],
		contextComplexity: 3,
		reliability: 3,
		supportsArtifacts: true,
	},
	"llama-3.3-70b-versatile": {
		name: "Llama 3.3 70B Versatile",
		matchingModel: "llama-3.3-70b-versatile",
		provider: "groq",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "December 6, 2024",
		lastUpdated: "December 6, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		card: "https://www.prompthub.us/models/llama-3-3-70b",
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00059,
		costPer1kOutputTokens: 0.00079,
		strengths: ["chat", "general_knowledge", "analysis", "creative", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 5,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},
	"groq-llama-4-scout-17b": {
		name: "Llama 4 Scout 17B",
		matchingModel: "meta-llama/llama-4-scout-17b-16e-instruct",
		provider: "groq",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "April 5, 2025",
		lastUpdated: "April 5, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		isFeatured: true,
		includedInRouter: true,
		multimodal: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00011,
		costPer1kOutputTokens: 0.00034,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"creative",
			"multilingual",
			"coding",
			"vision",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 5,
		supportsArtifacts: true,
		supportsResponseFormat: true,
	},
	"llama-3.1-8b-instant": {
		name: "Llama 3.1 8B Instant",
		matchingModel: "llama-3.1-8b-instant",
		provider: "groq",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "July 23, 2024",
		lastUpdated: "July 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.00008,
		speed: 5,
		strengths: ["chat", "general_knowledge", "multilingual"],
		contextComplexity: 3,
		reliability: 3,
		includedInRouter: true,
		supportsArtifacts: true,
	},
	"mixtral-8x7b-32768": {
		name: "Mixtral 8x7B Instruct",
		matchingModel: "mixtral-8x7b-32768",
		provider: "groq",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "December 11, 2023",
		lastUpdated: "December 11, 2023",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00024,
		costPer1kOutputTokens: 0.00024,
		speed: 4,
		strengths: ["reasoning", "analysis", "multilingual", "coding"],
		contextComplexity: 4,
		reliability: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	},
	"gemma-2-2b-it": {
		name: "Gemma 2 2B IT",
		matchingModel: "gemma-2-2b-it",
		provider: "groq",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "June 27, 2024",
		lastUpdated: "June 27, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 8192,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0001,
		speed: 5,
		strengths: ["chat", "general_knowledge"],
		contextComplexity: 2,
		reliability: 3,
		includedInRouter: true,
		supportsArtifacts: true,
	},
	"gemma-2-27b-it": {
		name: "Gemma 2 27B IT",
		matchingModel: "gemma-2-27b-it",
		provider: "groq",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "June 27, 2024",
		lastUpdated: "June 27, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 8192,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0002,
		speed: 4,
		strengths: ["reasoning", "analysis", "multilingual"],
		contextComplexity: 3,
		reliability: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	},
	"groq-openai-gpt-oss-20b": {
		name: "GPT OSS 20B",
		matchingModel: "openai/gpt-oss-20b",
		description:
			"Efficient 20B parameter open-source GPT model for fast reasoning and general tasks.",
		provider: "groq",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 65536,
		costPer1kInputTokens: 0.000075,
		costPer1kOutputTokens: 0.0003,
		strengths: ["reasoning", "analysis", "coding"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsResponseFormat: true,
	},
	"groq-openai-gpt-oss-120b": {
		name: "GPT OSS 120B",
		matchingModel: "openai/gpt-oss-120b",
		description:
			"Large 120B parameter open-source GPT model optimized for reasoning and complex tasks.",
		provider: "groq",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: ["reasoning", "analysis", "coding", "multilingual"],
		contextComplexity: 5,
		reliability: 4,
		speed: 2,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsResponseFormat: true,
	},
	"moonshotai/kimi-k2-instruct-0905": {
		name: "Kimi K2 Instruct 0905",
		matchingModel: "moonshotai/kimi-k2-instruct-0905",
		provider: "groq",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "September 5, 2025",
		lastUpdated: "September 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			enabled: false,
		},
	},

	"qwen/qwen3-32b": {
		name: "Qwen3 32B",
		matchingModel: "qwen/qwen3-32b",
		provider: "groq",
		knowledgeCutoffDate: "November 8, 2024",
		releaseDate: "December 23, 2024",
		lastUpdated: "December 23, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 40960,
		costPer1kInputTokens: 0.00029,
		costPer1kOutputTokens: 0.00059,
		reasoningConfig: {
			enabled: true,
		},
	},
	"allam-2-7b": {
		name: "ALLaM-2-7b",
		matchingModel: "allam-2-7b",
		provider: "groq",
		knowledgeCutoffDate: "September 2024",
		releaseDate: "September 2024",
		lastUpdated: "September 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 4096,
		maxTokens: 4096,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"canopylabs/orpheus-arabic-saudi": {
		name: "Orpheus Arabic Saudi",
		matchingModel: "canopylabs/orpheus-arabic-saudi",
		provider: "groq",
		knowledgeCutoffDate: "December 16, 2025",
		releaseDate: "December 16, 2025",
		lastUpdated: "December 16, 2025",
		modalities: {
			input: ["text"],
			output: ["audio"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 4000,
		maxTokens: 50000,
		costPer1kInputTokens: 0.04,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"canopylabs/orpheus-v1-english": {
		name: "Orpheus V1 English",
		matchingModel: "canopylabs/orpheus-v1-english",
		provider: "groq",
		knowledgeCutoffDate: "December 19, 2025",
		releaseDate: "December 19, 2025",
		lastUpdated: "December 19, 2025",
		modalities: {
			input: ["text"],
			output: ["audio"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 4000,
		maxTokens: 50000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"groq/compound": {
		name: "Compound",
		matchingModel: "groq/compound",
		provider: "groq",
		knowledgeCutoffDate: "September 4, 2025",
		releaseDate: "September 4, 2025",
		lastUpdated: "September 4, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: true,
		},
	},

	"groq/compound-mini": {
		name: "Compound Mini",
		matchingModel: "groq/compound-mini",
		provider: "groq",
		knowledgeCutoffDate: "September 4, 2025",
		releaseDate: "September 4, 2025",
		lastUpdated: "September 4, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: true,
		},
	},

	"meta-llama/llama-prompt-guard-2-22m": {
		name: "Llama Prompt Guard 2 22M",
		matchingModel: "meta-llama/llama-prompt-guard-2-22m",
		provider: "groq",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "October 1, 2024",
		lastUpdated: "October 1, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 512,
		maxTokens: 512,
		costPer1kInputTokens: 0.00003,
		costPer1kOutputTokens: 0.00003,
		reasoningConfig: {
			enabled: false,
		},
	},

	"meta-llama/llama-prompt-guard-2-86m": {
		name: "Llama Prompt Guard 2 86M",
		matchingModel: "meta-llama/llama-prompt-guard-2-86m",
		provider: "groq",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "October 1, 2024",
		lastUpdated: "October 1, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 512,
		maxTokens: 512,
		costPer1kInputTokens: 0.00004,
		costPer1kOutputTokens: 0.00004,
		reasoningConfig: {
			enabled: false,
		},
	},

	"openai/gpt-oss-safeguard-20b": {
		name: "Safety GPT OSS 20B",
		matchingModel: "openai/gpt-oss-safeguard-20b",
		provider: "groq",
		releaseDate: "March 5, 2025",
		lastUpdated: "March 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 65536,
		costPer1kInputTokens: 0.000075,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			enabled: true,
		},
	},

	"whisper-large-v3": {
		name: "Whisper Large V3",
		matchingModel: "whisper-large-v3",
		provider: "groq",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "September 1, 2023",
		lastUpdated: "September 5, 2025",
		modalities: {
			input: ["audio"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 448,
		maxTokens: 448,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"whisper-large-v3-turbo": {
		name: "Whisper Large v3 Turbo",
		matchingModel: "whisper-large-v3-turbo",
		provider: "groq",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "October 1, 2024",
		lastUpdated: "October 1, 2024",
		modalities: {
			input: ["audio"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 448,
		maxTokens: 448,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},
};
