import type { ModelConfig } from "~/types";

export const huggingfaceModelConfig: ModelConfig = {
	"deepseek-ai/DeepSeek-R1-0528": {
		name: "DeepSeek-R1-0528",
		matchingModel: "deepseek-ai/DeepSeek-R1-0528",
		provider: "huggingface",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "May 28, 2025",
		lastUpdated: "May 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.005,
		strengths: ["reasoning", "math", "analysis", "coding"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"deepseek-ai/Deepseek-V3-0324": {
		name: "DeepSeek-V3-0324",
		matchingModel: "deepseek-ai/Deepseek-V3-0324",
		provider: "huggingface",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "March 24, 2025",
		lastUpdated: "March 24, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 16384,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.00125,
		strengths: ["coding", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"moonshotai/Kimi-K2-Instruct": {
		name: "Kimi-K2-Instruct",
		matchingModel: "moonshotai/Kimi-K2-Instruct",
		provider: "huggingface",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 14, 2025",
		lastUpdated: "July 14, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.003,
		strengths: ["coding", "analysis", "multilingual", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"Qwen/Qwen3-Coder-480B-A35B-Instruct": {
		name: "Qwen3-Coder-480B-A35B-Instruct",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 66536,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.002,
		strengths: ["coding", "analysis", "reasoning"],
		contextComplexity: 5,
		reliability: 4,
		speed: 2,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"Qwen/Qwen3-235B-A22B-Thinking-2507": {
		name: "Qwen3-235B-A22B-Thinking-2507",
		matchingModel: "Qwen/Qwen3-235B-A22B-Thinking-2507",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 25, 2025",
		lastUpdated: "July 25, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.003,
		strengths: ["reasoning", "analysis", "multilingual"],
		contextComplexity: 5,
		reliability: 4,
		speed: 2,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"zai-org/GLM-4.5": {
		name: "GLM-4.5",
		matchingModel: "zai-org/GLM-4.5",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 98304,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
		strengths: ["reasoning", "analysis", "multilingual"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"zai-org/GLM-4.5-Air": {
		name: "GLM-4.5-Air",
		matchingModel: "zai-org/GLM-4.5-Air",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 96000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0011,
		strengths: ["reasoning", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"deepseek-ai/DeepSeek-V3.2": {
		name: "DeepSeek-V3.2",
		matchingModel: "deepseek-ai/DeepSeek-V3.2",
		provider: "huggingface",
		knowledgeCutoffDate: "July 2024",
		releaseDate: "December 1, 2025",
		lastUpdated: "December 1, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00028,
		costPer1kOutputTokens: 0.0004,
	},

	"MiniMaxAI/MiniMax-M2.1": {
		name: "MiniMax-M2.1",
		matchingModel: "MiniMaxAI/MiniMax-M2.1",
		provider: "huggingface",
		knowledgeCutoffDate: "October 2025",
		releaseDate: "December 23, 2025",
		lastUpdated: "December 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
	},

	"moonshotai/Kimi-K2-Instruct-0905": {
		name: "Kimi-K2-Instruct-0905",
		matchingModel: "moonshotai/Kimi-K2-Instruct-0905",
		provider: "huggingface",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "September 4, 2025",
		lastUpdated: "September 4, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.003,
	},

	"moonshotai/Kimi-K2-Thinking": {
		name: "Kimi-K2-Thinking",
		matchingModel: "moonshotai/Kimi-K2-Thinking",
		provider: "huggingface",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "November 6, 2025",
		lastUpdated: "November 6, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0025,
	},

	"moonshotai/Kimi-K2.5": {
		name: "Kimi-K2.5",
		matchingModel: "moonshotai/Kimi-K2.5",
		provider: "huggingface",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 1, 2026",
		lastUpdated: "January 1, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.003,
	},

	"Qwen/Qwen3-Embedding-4B": {
		name: "Qwen 3 Embedding 4B",
		matchingModel: "Qwen/Qwen3-Embedding-4B",
		provider: "huggingface",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "January 1, 2025",
		lastUpdated: "January 1, 2025",
		modalities: {
			input: ["text"],
			output: ["embedding"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 2048,
		costPer1kInputTokens: 0.00001,
		costPer1kOutputTokens: 0,
	},

	"Qwen/Qwen3-Embedding-8B": {
		name: "Qwen 3 Embedding 8B",
		matchingModel: "Qwen/Qwen3-Embedding-8B",
		provider: "huggingface",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "January 1, 2025",
		lastUpdated: "January 1, 2025",
		modalities: {
			input: ["text"],
			output: ["embedding"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.00001,
		costPer1kOutputTokens: 0,
	},

	"Qwen/Qwen3-Next-80B-A3B-Instruct": {
		name: "Qwen3-Next-80B-A3B-Instruct",
		matchingModel: "Qwen/Qwen3-Next-80B-A3B-Instruct",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 11, 2025",
		lastUpdated: "September 11, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 66536,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.001,
	},

	"Qwen/Qwen3-Next-80B-A3B-Thinking": {
		name: "Qwen3-Next-80B-A3B-Thinking",
		matchingModel: "Qwen/Qwen3-Next-80B-A3B-Thinking",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 11, 2025",
		lastUpdated: "September 11, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.002,
	},

	"XiaomiMiMo/MiMo-V2-Flash": {
		name: "MiMo-V2-Flash",
		matchingModel: "XiaomiMiMo/MiMo-V2-Flash",
		provider: "huggingface",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "December 16, 2025",
		lastUpdated: "December 16, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 4096,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0003,
	},

	"zai-org/GLM-4.7": {
		name: "GLM-4.7",
		matchingModel: "zai-org/GLM-4.7",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 22, 2025",
		lastUpdated: "December 22, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
	},

	"zai-org/GLM-4.7-Flash": {
		name: "GLM-4.7-Flash",
		matchingModel: "zai-org/GLM-4.7-Flash",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "August 8, 2025",
		lastUpdated: "August 8, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
	},

	"zai-org/GLM-5": {
		name: "GLM-5",
		matchingModel: "zai-org/GLM-5",
		provider: "huggingface",
		releaseDate: "February 11, 2026",
		lastUpdated: "February 11, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 131072,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.0032,
	},
	"deepseek-ai/DeepSeek-V4-Pro": {
		name: "DeepSeek V4 Pro",
		matchingModel: "deepseek-ai/DeepSeek-V4-Pro",
		provider: "huggingface",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 393216,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00348,
	},

	"MiniMaxAI/MiniMax-M2.5": {
		name: "MiniMax-M2.5",
		matchingModel: "MiniMaxAI/MiniMax-M2.5",
		provider: "huggingface",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
	},

	"MiniMaxAI/MiniMax-M2.7": {
		name: "MiniMax-M2.7",
		matchingModel: "MiniMaxAI/MiniMax-M2.7",
		provider: "huggingface",
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
	},

	"moonshotai/Kimi-K2.6": {
		name: "Kimi-K2.6",
		matchingModel: "moonshotai/Kimi-K2.6",
		provider: "huggingface",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "April 20, 2026",
		lastUpdated: "April 20, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
	},

	"Qwen/Qwen3-Coder-Next": {
		name: "Qwen3-Coder-Next",
		matchingModel: "Qwen/Qwen3-Coder-Next",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "February 3, 2026",
		lastUpdated: "February 3, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0015,
	},

	"Qwen/Qwen3.5-397B-A17B": {
		name: "Qwen3.5-397B-A17B",
		matchingModel: "Qwen/Qwen3.5-397B-A17B",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "February 1, 2026",
		lastUpdated: "February 1, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0036,
	},

	"zai-org/GLM-5.1": {
		name: "GLM-5.1",
		matchingModel: "zai-org/GLM-5.1",
		provider: "huggingface",
		releaseDate: "April 3, 2026",
		lastUpdated: "April 3, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 131072,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.0032,
	},
};
