import type { ModelConfig } from "~/types";

export const huggingfaceModelConfig: ModelConfig = {
	"deepseek-ai/DeepSeek-R1-0528": {
		name: "DeepSeek-R1-0528",
		matchingModel: "deepseek-ai/DeepSeek-R1-0528",
		provider: "huggingface",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "May 28, 2025",
		lastUpdated: "May 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.005,
		strengths: ["reasoning", "math", "analysis", "coding"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"deepseek-ai/Deepseek-V3-0324": {
		name: "DeepSeek-V3-0324",
		matchingModel: "deepseek-ai/Deepseek-V3-0324",
		provider: "huggingface",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "March 24, 2025",
		lastUpdated: "March 24, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 16384,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.00125,
		strengths: ["coding", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"moonshotai/Kimi-K2-Instruct": {
		name: "Kimi-K2-Instruct",
		matchingModel: "moonshotai/Kimi-K2-Instruct",
		provider: "huggingface",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 14, 2025",
		lastUpdated: "July 14, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.003,
		strengths: ["coding", "analysis", "multilingual", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"Qwen/Qwen3-Coder-480B-A35B-Instruct": {
		name: "Qwen3-Coder-480B-A35B-Instruct",
		matchingModel: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 66536,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.002,
		strengths: ["coding", "analysis", "reasoning"],
		contextComplexity: 5,
		reliability: 4,
		speed: 2,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"Qwen/Qwen3-235B-A22B-Thinking-2507": {
		name: "Qwen3-235B-A22B-Thinking-2507",
		matchingModel: "Qwen/Qwen3-235B-A22B-Thinking-2507",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 25, 2025",
		lastUpdated: "July 25, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.003,
		strengths: ["reasoning", "analysis", "multilingual"],
		contextComplexity: 5,
		reliability: 4,
		speed: 2,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"zai-org/GLM-4.5": {
		name: "GLM-4.5",
		matchingModel: "zai-org/GLM-4.5",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 98304,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
		strengths: ["reasoning", "analysis", "multilingual"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"zai-org/GLM-4.5-Air": {
		name: "GLM-4.5-Air",
		matchingModel: "zai-org/GLM-4.5-Air",
		provider: "huggingface",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 96000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0011,
		strengths: ["reasoning", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: false,
		supportsArtifacts: true,
	},
};
