import type { ModelConfig } from "~/types";
import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "inception";

export const inceptionModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("mercury-coder", PROVIDER, {
		name: "Mercury Coder",
		matchingModel: "mercury-coder",
		description:
			"Mercury Coder is a specialized model optimized for coding tasks with tool calling support and extensive context window.",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "February 26, 2025",
		lastUpdated: "July 31, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.001,
		strengths: ["coding", "analysis", "instruction", "tool_use"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		isFeatured: false,
		includedInRouter: true,
		supportsNextEdit: true,
		supportsApplyEdit: true,
		supportsFim: true,
		supportsArtifacts: true,
	}),

	createModelConfig("mercury", PROVIDER, {
		name: "Mercury",
		matchingModel: "mercury",
		description:
			"Mercury is a general-purpose model with strong capabilities in text generation, analysis, and tool calling.",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "June 26, 2025",
		lastUpdated: "July 31, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.001,
		strengths: ["chat", "general_knowledge", "analysis", "tool_use"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),
	createModelConfig("mercury-2", PROVIDER, {
		name: "Mercury 2",
		matchingModel: "mercury-2",
		knowledgeCutoffDate: "January 1, 2025",
		releaseDate: "February 24, 2026",
		lastUpdated: "February 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 50000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.00075,
	}),

	createModelConfig("mercury-edit-2", PROVIDER, {
		name: "Mercury Edit 2",
		matchingModel: "mercury-edit-2",
		releaseDate: "March 30, 2026",
		lastUpdated: "March 30, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.00075,
	}),
]);
