import type { ModelConfig } from "@ngriffin_uk/polychat-schemas";

import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "minimax";

export const minimaxModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("MiniMax-M2", PROVIDER, {
		name: "MiniMax M2",
		matchingModel: "MiniMax-M2",
		family: "minimax",
		openWeights: true,
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["coding", "agents", "tool_use"],
		releaseDate: "October 27, 2025",
		lastUpdated: "October 27, 2025",
		supportsAttachments: false,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 28.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),
	createModelConfig("MiniMax-M2.7", PROVIDER, {
		name: "MiniMax M2.7",
		matchingModel: "MiniMax-M2.7",
		family: "minimax",
		openWeights: true,
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["coding", "agents", "reasoning", "tool_use"],
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		supportsAttachments: false,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		contextComplexity: 4,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 38.1,
			codingIndex: 52.6,
			agenticIndex: 25.6,
			intelligenceIndexVersion: 4.1,
		},
	}),
	createModelConfig("MiniMax-M2.1", PROVIDER, {
		name: "MiniMax-M2.1",
		matchingModel: "MiniMax-M2.1",
		family: "minimax",
		openWeights: true,
		releaseDate: "December 23, 2025",
		lastUpdated: "December 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 31.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("MiniMax-M2.5", PROVIDER, {
		name: "MiniMax-M2.5",
		matchingModel: "MiniMax-M2.5",
		family: "minimax",
		openWeights: true,
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 33.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("MiniMax-M2.5-highspeed", PROVIDER, {
		name: "MiniMax-M2.5-highspeed",
		matchingModel: "MiniMax-M2.5-highspeed",
		family: "minimax",
		openWeights: true,
		releaseDate: "February 13, 2026",
		lastUpdated: "February 13, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0024,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("MiniMax-M2.7-highspeed", PROVIDER, {
		name: "MiniMax-M2.7-highspeed",
		matchingModel: "MiniMax-M2.7-highspeed",
		family: "minimax",
		openWeights: true,
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0024,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("MiniMax-M3", PROVIDER, {
		name: "MiniMax-M3",
		matchingModel: "MiniMax-M3",
		family: "minimax",
		openWeights: true,
		releaseDate: "June 1, 2026",
		lastUpdated: "June 25, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 512000,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 44.4,
			codingIndex: 58.6,
			agenticIndex: 35.4,
			intelligenceIndexVersion: 4.1,
		},
	}),
]);
