import type { ModelConfig } from "@ngriffin_uk/polychat-schemas";

import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "moonshot";

export const moonshotModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("kimi-k2-thinking", PROVIDER, {
		name: "Kimi K2 Thinking",
		matchingModel: "kimi-k2-thinking",
		family: "kimi-thinking",
		openWeights: true,
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["reasoning", "coding", "agents", "tool_use"],
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "thinking",
		},
		knowledgeCutoffDate: "August 2024",
		releaseDate: "November 6, 2025",
		lastUpdated: "November 6, 2025",
		supportsAttachments: false,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0025,
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 32.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),
	createModelConfig("kimi-k2.5", PROVIDER, {
		name: "Kimi K2.5",
		matchingModel: "kimi-k2.5",
		family: "kimi-k2",
		openWeights: true,
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["coding", "agents", "tool_use"],
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 2026",
		lastUpdated: "January 2026",
		supportsAttachments: false,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 29.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),
	createModelConfig("kimi-k2-0711-preview", PROVIDER, {
		name: "Kimi K2 0711",
		matchingModel: "kimi-k2-0711-preview",
		family: "kimi-k2",
		openWeights: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 14, 2025",
		lastUpdated: "July 14, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0025,
	}),

	createModelConfig("kimi-k2-0905-preview", PROVIDER, {
		name: "Kimi K2 0905",
		matchingModel: "kimi-k2-0905-preview",
		family: "kimi-k2",
		openWeights: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "September 5, 2025",
		lastUpdated: "September 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0025,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 23.5,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("kimi-k2-thinking-turbo", PROVIDER, {
		name: "Kimi K2 Thinking Turbo",
		matchingModel: "kimi-k2-thinking-turbo",
		family: "kimi-thinking",
		openWeights: true,
		knowledgeCutoffDate: "August 2024",
		releaseDate: "November 6, 2025",
		lastUpdated: "November 6, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00115,
		costPer1kOutputTokens: 0.008,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2-turbo-preview", PROVIDER, {
		name: "Kimi K2 Turbo",
		matchingModel: "kimi-k2-turbo-preview",
		family: "kimi-k2",
		openWeights: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "September 5, 2025",
		lastUpdated: "September 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0024,
		costPer1kOutputTokens: 0.01,
	}),

	createModelConfig("kimi-k2.6", PROVIDER, {
		name: "Kimi K2.6",
		matchingModel: "kimi-k2.6",
		family: "kimi-k2",
		openWeights: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "April 21, 2026",
		lastUpdated: "April 21, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 42.8,
			codingIndex: 56,
			agenticIndex: 30.3,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("kimi-k2.7-code", PROVIDER, {
		name: "Kimi K2.7 Code",
		matchingModel: "kimi-k2.7-code",
		family: "kimi-k2",
		openWeights: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 12, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use", "coding"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 41.9,
			codingIndex: 60.8,
			agenticIndex: 29.6,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("kimi-k2.7-code-highspeed", PROVIDER, {
		name: "Kimi K2.7 Code HighSpeed",
		matchingModel: "kimi-k2.7-code-highspeed",
		family: "kimi-k2",
		openWeights: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 12, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0019,
		costPer1kOutputTokens: 0.008,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k3", PROVIDER, {
		name: "Kimi K3",
		matchingModel: "kimi-k3",
		family: "kimi-k3",
		openWeights: true,
		releaseDate: "July 16, 2026",
		lastUpdated: "July 16, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 131072,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
]);
