import type { ModelConfig } from "@ngriffin_uk/polychat-schemas";

import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "ollama-cloud";

export const ollamaCloudModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("gpt-oss:120b", PROVIDER, {
		name: "GPT OSS 120B",
		matchingModel: "gpt-oss:120b",
		family: "gpt-oss",
		openWeights: true,
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["reasoning", "coding", "tool_use"],
		releaseDate: "August 5, 2025",
		lastUpdated: "January 19, 2026",
		supportsAttachments: false,
		contextWindow: 131072,
		maxTokens: 32768,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("gpt-oss:20b", PROVIDER, {
		name: "GPT OSS 20B",
		matchingModel: "gpt-oss:20b",
		family: "gpt-oss",
		openWeights: true,
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["reasoning", "coding", "tool_use"],
		releaseDate: "August 5, 2025",
		lastUpdated: "January 19, 2026",
		supportsAttachments: false,
		contextWindow: 131072,
		maxTokens: 32768,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("deepseek-v4-flash", PROVIDER, {
		name: "deepseek-v4-flash",
		matchingModel: "deepseek-v4-flash",
		family: "deepseek-flash",
		openWeights: true,
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("deepseek-v4-pro", PROVIDER, {
		name: "deepseek-v4-pro",
		matchingModel: "deepseek-v4-pro",
		family: "deepseek-thinking",
		openWeights: true,
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 1048576,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gemma4:31b", PROVIDER, {
		name: "gemma4:31b",
		matchingModel: "gemma4:31b",
		family: "gemma",
		openWeights: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "April 2, 2026",
		lastUpdated: "April 8, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.1", PROVIDER, {
		name: "glm-5.1",
		matchingModel: "glm-5.1",
		family: "glm",
		openWeights: true,
		releaseDate: "March 27, 2026",
		lastUpdated: "April 7, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 131072,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.2", PROVIDER, {
		name: "GLM-5.2",
		matchingModel: "glm-5.2",
		family: "glm",
		openWeights: true,
		releaseDate: "June 13, 2026",
		lastUpdated: "June 13, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 976000,
		maxTokens: 131072,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.3-flash", PROVIDER, {
		name: "GLM-5.3-Flash",
		matchingModel: "glm-5.3-flash",
		family: "glm",
		openWeights: true,
		releaseDate: "August 26, 2026",
		lastUpdated: "August 26, 2026",
		modalities: {
			input: ["text", "image", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 131072,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2.5", PROVIDER, {
		name: "kimi-k2.5",
		matchingModel: "kimi-k2.5",
		family: "kimi-k2",
		openWeights: true,
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2.6", PROVIDER, {
		name: "kimi-k2.6",
		matchingModel: "kimi-k2.6",
		family: "kimi-k2",
		openWeights: true,
		releaseDate: "April 20, 2026",
		lastUpdated: "April 20, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2.7-code", PROVIDER, {
		name: "kimi-k2.7-code",
		matchingModel: "kimi-k2.7-code",
		family: "kimi-k2",
		openWeights: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 12, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k3", PROVIDER, {
		name: "kimi-k3",
		matchingModel: "kimi-k3",
		family: "kimi-k3",
		openWeights: true,
		releaseDate: "July 16, 2026",
		lastUpdated: "July 27, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 131072,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m2.5", PROVIDER, {
		name: "minimax-m2.5",
		matchingModel: "minimax-m2.5",
		family: "minimax",
		openWeights: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m2.7", PROVIDER, {
		name: "minimax-m2.7",
		matchingModel: "minimax-m2.7",
		family: "minimax",
		openWeights: true,
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsToolCalls: true,
		contextWindow: 196608,
		maxTokens: 196608,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m3", PROVIDER, {
		name: "minimax-m3",
		matchingModel: "minimax-m3",
		family: "minimax-m3",
		openWeights: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 31, 2026",
		lastUpdated: "May 31, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 512000,
		maxTokens: 131072,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("mistral-large-3:675b", PROVIDER, {
		name: "mistral-large-3:675b",
		matchingModel: "mistral-large-3:675b",
		family: "mistral-large",
		openWeights: true,
		releaseDate: "December 2, 2025",
		lastUpdated: "January 19, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
	}),

	createModelConfig("nemotron-3-nano:30b", PROVIDER, {
		name: "nemotron-3-nano:30b",
		matchingModel: "nemotron-3-nano:30b",
		family: "nemotron",
		openWeights: true,
		releaseDate: "December 15, 2025",
		lastUpdated: "January 19, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 131072,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("nemotron-3-super", PROVIDER, {
		name: "nemotron-3-super",
		matchingModel: "nemotron-3-super",
		family: "nemotron",
		openWeights: true,
		releaseDate: "March 11, 2026",
		lastUpdated: "March 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("nemotron-3-ultra", PROVIDER, {
		name: "nemotron-3-ultra",
		matchingModel: "nemotron-3-ultra",
		family: "nemotron",
		openWeights: true,
		releaseDate: "June 4, 2026",
		lastUpdated: "June 4, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 128000,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.5:397b", PROVIDER, {
		name: "qwen3.5:397b",
		matchingModel: "qwen3.5:397b",
		family: "qwen",
		openWeights: true,
		releaseDate: "February 15, 2026",
		lastUpdated: "February 17, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
]);
