import type { ModelConfig } from "~/types";
import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "opencode-go";

export const opencodeGoModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("deepseek-v4-flash", PROVIDER, {
		name: "DeepSeek V4 Flash",
		matchingModel: "deepseek-v4-flash",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("deepseek-v4-pro", PROVIDER, {
		name: "DeepSeek V4 Pro",
		matchingModel: "deepseek-v4-pro",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00348,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5", PROVIDER, {
		name: "GLM-5",
		matchingModel: "glm-5",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "February 11, 2026",
		lastUpdated: "February 11, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 32768,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.0032,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.1", PROVIDER, {
		name: "GLM-5.1",
		matchingModel: "glm-5.1",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 7, 2026",
		lastUpdated: "April 7, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2.5", PROVIDER, {
		name: "Kimi K2.5",
		matchingModel: "kimi-k2.5",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2.6", PROVIDER, {
		name: "Kimi K2.6",
		matchingModel: "kimi-k2.6",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "April 21, 2026",
		lastUpdated: "April 21, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("mimo-v2.5", PROVIDER, {
		name: "MiMo V2.5",
		matchingModel: "mimo-v2.5",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "April 22, 2026",
		lastUpdated: "April 22, 2026",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("mimo-v2.5-pro", PROVIDER, {
		name: "MiMo V2.5 Pro",
		matchingModel: "mimo-v2.5-pro",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "April 22, 2026",
		lastUpdated: "April 22, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00348,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m2.5", PROVIDER, {
		name: "MiniMax M2.5",
		matchingModel: "minimax-m2.5",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m2.7", PROVIDER, {
		name: "MiniMax M2.7",
		matchingModel: "minimax-m2.7",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.6-plus", PROVIDER, {
		name: "Qwen3.6 Plus",
		matchingModel: "qwen3.6-plus",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2, 2026",
		lastUpdated: "April 2, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.7-max", PROVIDER, {
		name: "Qwen3.7 Max",
		matchingModel: "qwen3.7-max",
		releaseDate: "May 21, 2026",
		lastUpdated: "May 21, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.0075,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
]);
