import type { ModelConfig } from "@assistant/schemas";
import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "opencode";

export const opencodeModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("big-pickle", PROVIDER, {
		name: "Big Pickle",
		matchingModel: "big-pickle",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "October 17, 2025",
		lastUpdated: "October 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-haiku-4-5", PROVIDER, {
		name: "Claude Haiku 4.5",
		matchingModel: "claude-haiku-4-5",
		knowledgeCutoffDate: "February 28, 2025",
		releaseDate: "October 15, 2025",
		lastUpdated: "October 15, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.005,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus-4-1", PROVIDER, {
		name: "Claude Opus 4.1",
		matchingModel: "claude-opus-4-1",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus-4-5", PROVIDER, {
		name: "Claude Opus 4.5",
		matchingModel: "claude-opus-4-5",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "November 24, 2025",
		lastUpdated: "November 24, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus-4-6", PROVIDER, {
		name: "Claude Opus 4.6",
		matchingModel: "claude-opus-4-6",
		knowledgeCutoffDate: "May 31, 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "March 13, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus-4-7", PROVIDER, {
		name: "Claude Opus 4.7",
		matchingModel: "claude-opus-4-7",
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "April 16, 2026",
		lastUpdated: "April 16, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus-4-8", PROVIDER, {
		name: "Claude Opus 4.8",
		matchingModel: "claude-opus-4-8",
		releaseDate: "May 28, 2026",
		lastUpdated: "May 28, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-sonnet-4", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "claude-sonnet-4",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-sonnet-4-5", PROVIDER, {
		name: "Claude Sonnet 4.5",
		matchingModel: "claude-sonnet-4-5",
		knowledgeCutoffDate: "July 31, 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-sonnet-4-6", PROVIDER, {
		name: "Claude Sonnet 4.6",
		matchingModel: "claude-sonnet-4-6",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 17, 2026",
		lastUpdated: "February 17, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("deepseek-v4-flash-free", PROVIDER, {
		name: "DeepSeek V4 Flash Free",
		matchingModel: "deepseek-v4-flash-free",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gemini-3-flash", PROVIDER, {
		name: "Gemini 3 Flash",
		matchingModel: "gemini-3-flash",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "December 17, 2025",
		lastUpdated: "December 17, 2025",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gemini-3.1-pro", PROVIDER, {
		name: "Gemini 3.1 Pro Preview",
		matchingModel: "gemini-3.1-pro",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 19, 2026",
		lastUpdated: "February 19, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gemini-3.5-flash", PROVIDER, {
		name: "Gemini 3.5 Flash",
		matchingModel: "gemini-3.5-flash",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 19, 2026",
		lastUpdated: "May 19, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.009,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5", PROVIDER, {
		name: "GLM-5",
		matchingModel: "glm-5",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "February 11, 2026",
		lastUpdated: "February 11, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.0032,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.1", PROVIDER, {
		name: "GLM-5.1",
		matchingModel: "glm-5.1",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 7, 2026",
		lastUpdated: "April 7, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5", PROVIDER, {
		name: "GPT-5",
		matchingModel: "gpt-5",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00107,
		costPer1kOutputTokens: 0.0085,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5-codex", PROVIDER, {
		name: "GPT-5 Codex",
		matchingModel: "gpt-5-codex",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "September 15, 2025",
		lastUpdated: "September 15, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00107,
		costPer1kOutputTokens: 0.0085,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5-nano", PROVIDER, {
		name: "GPT-5 Nano",
		matchingModel: "gpt-5-nano",
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.1", PROVIDER, {
		name: "GPT-5.1",
		matchingModel: "gpt-5.1",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00107,
		costPer1kOutputTokens: 0.0085,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.1-codex", PROVIDER, {
		name: "GPT-5.1 Codex",
		matchingModel: "gpt-5.1-codex",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00107,
		costPer1kOutputTokens: 0.0085,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.1-codex-max", PROVIDER, {
		name: "GPT-5.1 Codex Max",
		matchingModel: "gpt-5.1-codex-max",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.1-codex-mini", PROVIDER, {
		name: "GPT-5.1 Codex Mini",
		matchingModel: "gpt-5.1-codex-mini",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.2", PROVIDER, {
		name: "GPT-5.2",
		matchingModel: "gpt-5.2",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.2-codex", PROVIDER, {
		name: "GPT-5.2 Codex",
		matchingModel: "gpt-5.2-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "January 14, 2026",
		lastUpdated: "January 14, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.3-codex", PROVIDER, {
		name: "GPT-5.3 Codex",
		matchingModel: "gpt-5.3-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 24, 2026",
		lastUpdated: "February 24, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.3-codex-spark", PROVIDER, {
		name: "GPT-5.3 Codex Spark",
		matchingModel: "gpt-5.3-codex-spark",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.4", PROVIDER, {
		name: "GPT-5.4",
		matchingModel: "gpt-5.4",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 5, 2026",
		lastUpdated: "March 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.4-mini", PROVIDER, {
		name: "GPT-5.4 Mini",
		matchingModel: "gpt-5.4-mini",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 17, 2026",
		lastUpdated: "March 17, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00075,
		costPer1kOutputTokens: 0.0045,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.4-nano", PROVIDER, {
		name: "GPT-5.4 Nano",
		matchingModel: "gpt-5.4-nano",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 17, 2026",
		lastUpdated: "March 17, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.00125,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.4-pro", PROVIDER, {
		name: "GPT-5.4 Pro",
		matchingModel: "gpt-5.4-pro",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 5, 2026",
		lastUpdated: "March 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: false,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.03,
		costPer1kOutputTokens: 0.18,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.5", PROVIDER, {
		name: "GPT-5.5",
		matchingModel: "gpt-5.5",
		knowledgeCutoffDate: "December 1, 2025",
		releaseDate: "April 23, 2026",
		lastUpdated: "April 23, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.03,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.5-pro", PROVIDER, {
		name: "GPT-5.5 Pro",
		matchingModel: "gpt-5.5-pro",
		knowledgeCutoffDate: "December 1, 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: false,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.03,
		costPer1kOutputTokens: 0.18,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("grok-build-0.1", PROVIDER, {
		name: "Grok Build 0.1",
		matchingModel: "grok-build-0.1",
		releaseDate: "May 20, 2026",
		lastUpdated: "May 20, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2.5", PROVIDER, {
		name: "Kimi K2.5",
		matchingModel: "kimi-k2.5",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2.6", PROVIDER, {
		name: "Kimi K2.6",
		matchingModel: "kimi-k2.6",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "April 21, 2026",
		lastUpdated: "April 21, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("mimo-v2.5-free", PROVIDER, {
		name: "MiMo V2.5 Free",
		matchingModel: "mimo-v2.5-free",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m2.5", PROVIDER, {
		name: "MiniMax M2.5",
		matchingModel: "minimax-m2.5",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("minimax-m2.7", PROVIDER, {
		name: "MiniMax M2.7",
		matchingModel: "minimax-m2.7",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.5-plus", PROVIDER, {
		name: "Qwen3.5 Plus",
		matchingModel: "qwen3.5-plus",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "February 16, 2026",
		lastUpdated: "February 16, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("qwen3.6-plus", PROVIDER, {
		name: "Qwen3.6 Plus",
		matchingModel: "qwen3.6-plus",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2, 2026",
		lastUpdated: "April 2, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("deepseek-v4-flash", PROVIDER, {
		name: "DeepSeek V4 Flash",
		matchingModel: "deepseek-v4-flash",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("nemotron-3-ultra-free", PROVIDER, {
		name: "Nemotron 3 Ultra Free",
		matchingModel: "nemotron-3-ultra-free",
		knowledgeCutoffDate: "February 2026",
		releaseDate: "June 4, 2026",
		lastUpdated: "June 4, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("north-mini-code-free", PROVIDER, {
		name: "North Mini Code Free",
		matchingModel: "north-mini-code-free",
		knowledgeCutoffDate: "September 23, 2025",
		releaseDate: "June 9, 2026",
		lastUpdated: "June 9, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 256000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("deepseek-v4-pro", PROVIDER, {
		name: "DeepSeek V4 Pro",
		matchingModel: "deepseek-v4-pro",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00384,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
]);
