import type { ModelConfig } from "@assistant/schemas";
import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "opencode-go";

export const opencodeGoModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("deepseek-v4-flash", PROVIDER, {
		name: "DeepSeek V4 Flash",
		matchingModel: "deepseek-v4-flash",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 28.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek-flash",
		openWeights: true,
	}),

	createModelConfig("deepseek-v4-pro", PROVIDER, {
		name: "DeepSeek V4 Pro",
		matchingModel: "deepseek-v4-pro",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00348,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 31.2,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek-thinking",
		openWeights: true,
	}),

	createModelConfig("glm-5.1", PROVIDER, {
		name: "GLM-5.1",
		matchingModel: "glm-5.1",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 7, 2026",
		lastUpdated: "April 7, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 202752,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 35.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	}),

	createModelConfig("kimi-k2.6", PROVIDER, {
		name: "Kimi K2.6",
		matchingModel: "kimi-k2.6",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "April 21, 2026",
		lastUpdated: "April 21, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 42.8,
			codingIndex: 56,
			agenticIndex: 30.3,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-k2",
		openWeights: true,
	}),

	createModelConfig("mimo-v2.5", PROVIDER, {
		name: "MiMo V2.5",
		matchingModel: "mimo-v2.5",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "April 22, 2026",
		lastUpdated: "April 22, 2026",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "audio", "video", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 40.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "mimo-v2.5",
		openWeights: true,
	}),

	createModelConfig("mimo-v2.5-pro", PROVIDER, {
		name: "MiMo V2.5 Pro",
		matchingModel: "mimo-v2.5-pro",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "April 22, 2026",
		lastUpdated: "April 22, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00348,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 42.2,
			codingIndex: 60.2,
			agenticIndex: 29.1,
			intelligenceIndexVersion: 4.1,
		},
		family: "mimo-v2.5-pro",
		openWeights: true,
	}),

	createModelConfig("minimax-m2.7", PROVIDER, {
		name: "MiniMax M2.7",
		matchingModel: "minimax-m2.7",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 38.1,
			codingIndex: 52.6,
			agenticIndex: 25.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax-m2.7",
		openWeights: true,
	}),

	createModelConfig("qwen3.6-plus", PROVIDER, {
		name: "Qwen3.6 Plus",
		matchingModel: "qwen3.6-plus",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2, 2026",
		lastUpdated: "April 2, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 39.6,
			codingIndex: 54.5,
			agenticIndex: 27.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen3.6",
		openWeights: false,
	}),

	createModelConfig("qwen3.7-max", PROVIDER, {
		name: "Qwen3.7 Max",
		matchingModel: "qwen3.7-max",
		releaseDate: "May 21, 2026",
		lastUpdated: "May 21, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.0075,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 46,
			codingIndex: 66,
			agenticIndex: 30.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen3.7-max",
		openWeights: false,
	}),
	createModelConfig("minimax-m3", PROVIDER, {
		name: "MiniMax M3",
		matchingModel: "minimax-m3",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 31, 2026",
		lastUpdated: "May 31, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 44.4,
			codingIndex: 58.6,
			agenticIndex: 35.4,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax-m3",
		openWeights: true,
	}),
	createModelConfig("qwen3.7-plus", PROVIDER, {
		name: "Qwen3.7 Plus",
		matchingModel: "qwen3.7-plus",
		releaseDate: "June 2, 2026",
		lastUpdated: "June 2, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 39,
			codingIndex: 55.9,
			agenticIndex: 20.8,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen3.7-plus",
		openWeights: false,
	}),
	createModelConfig("kimi-k2.7-code", PROVIDER, {
		name: "Kimi K2.7 Code",
		matchingModel: "kimi-k2.7-code",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 12, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 41.9,
			codingIndex: 60.8,
			agenticIndex: 29.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-k2",
		openWeights: true,
	}),
	createModelConfig("glm-5.2", PROVIDER, {
		name: "GLM-5.2",
		matchingModel: "glm-5.2",
		releaseDate: "June 13, 2026",
		lastUpdated: "June 13, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 51.1,
			codingIndex: 68.8,
			agenticIndex: 43.1,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	}),
]);
