import type { ModelConfig } from "@assistant/schemas";
import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "opencode";

export const opencodeModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("big-pickle", PROVIDER, {
		name: "Big Pickle",
		matchingModel: "big-pickle",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "October 17, 2025",
		lastUpdated: "October 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "big-pickle",
		openWeights: false,
	}),

	createModelConfig("claude-haiku-4-5", PROVIDER, {
		name: "Claude Haiku 4.5",
		matchingModel: "claude-haiku-4-5",
		knowledgeCutoffDate: "February 28, 2025",
		releaseDate: "October 15, 2025",
		lastUpdated: "October 15, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.005,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "claude-haiku",
		openWeights: false,
	}),

	createModelConfig("claude-opus-4-1", PROVIDER, {
		name: "Claude Opus 4.1",
		matchingModel: "claude-opus-4-1",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "claude-opus",
		openWeights: false,
	}),

	createModelConfig("claude-opus-4-5", PROVIDER, {
		name: "Claude Opus 4.5",
		matchingModel: "claude-opus-4-5",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "November 24, 2025",
		lastUpdated: "November 24, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 34.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-opus",
		openWeights: false,
	}),

	createModelConfig("claude-opus-4-6", PROVIDER, {
		name: "Claude Opus 4.6",
		matchingModel: "claude-opus-4-6",
		knowledgeCutoffDate: "May 31, 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "March 13, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 43.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-opus",
		openWeights: false,
	}),

	createModelConfig("claude-opus-4-7", PROVIDER, {
		name: "Claude Opus 4.7",
		matchingModel: "claude-opus-4-7",
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "April 16, 2026",
		lastUpdated: "April 16, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 53.5,
			codingIndex: 73.6,
			agenticIndex: 44.4,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-opus",
		openWeights: false,
	}),

	createModelConfig("claude-opus-4-8", PROVIDER, {
		name: "Claude Opus 4.8",
		matchingModel: "claude-opus-4-8",
		releaseDate: "May 28, 2026",
		lastUpdated: "May 28, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 55.7,
			codingIndex: 74.3,
			agenticIndex: 47.2,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "January 2026",
	}),

	createModelConfig("claude-sonnet-4", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "claude-sonnet-4",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "claude-sonnet",
		openWeights: false,
	}),

	createModelConfig("claude-sonnet-4-5", PROVIDER, {
		name: "Claude Sonnet 4.5",
		matchingModel: "claude-sonnet-4-5",
		knowledgeCutoffDate: "July 31, 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "claude-sonnet",
		openWeights: false,
	}),

	createModelConfig("claude-sonnet-4-6", PROVIDER, {
		name: "Claude Sonnet 4.6",
		matchingModel: "claude-sonnet-4-6",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 17, 2026",
		lastUpdated: "February 17, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 3,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 47.2,
			codingIndex: 63,
			agenticIndex: 40.8,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-sonnet",
		openWeights: false,
	}),

	createModelConfig("deepseek-v4-flash-free", PROVIDER, {
		name: "DeepSeek V4 Flash Free",
		matchingModel: "deepseek-v4-flash-free",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "deepseek-flash-free",
		openWeights: true,
	}),

	createModelConfig("gemini-3-flash", PROVIDER, {
		name: "Gemini 3 Flash",
		matchingModel: "gemini-3-flash",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "December 17, 2025",
		lastUpdated: "December 17, 2025",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 27.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		speed: 5,
		family: "gemini-flash",
		openWeights: false,
	}),

	createModelConfig("gemini-3.1-pro", PROVIDER, {
		name: "Gemini 3.1 Pro Preview",
		matchingModel: "gemini-3.1-pro",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 19, 2026",
		lastUpdated: "February 19, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 46.5,
			codingIndex: 68.8,
			agenticIndex: 21.4,
			intelligenceIndexVersion: 4.1,
		},
		family: "gemini-pro",
		openWeights: false,
	}),

	createModelConfig("gemini-3.5-flash", PROVIDER, {
		name: "Gemini 3.5 Flash",
		matchingModel: "gemini-3.5-flash",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 19, 2026",
		lastUpdated: "May 19, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.009,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 3,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 50.2,
			codingIndex: 70.1,
			agenticIndex: 37.4,
			intelligenceIndexVersion: 4.1,
		},
		family: "gemini-flash",
		openWeights: false,
	}),

	createModelConfig("glm-5", PROVIDER, {
		name: "GLM-5",
		matchingModel: "glm-5",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "February 11, 2026",
		lastUpdated: "February 11, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.0032,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 32.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	}),

	createModelConfig("glm-5.1", PROVIDER, {
		name: "GLM-5.1",
		matchingModel: "glm-5.1",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 7, 2026",
		lastUpdated: "April 7, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 35.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	}),

	createModelConfig("gpt-5", PROVIDER, {
		name: "GPT-5",
		matchingModel: "gpt-5",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00107,
		costPer1kOutputTokens: 0.0085,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 15.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("gpt-5-codex", PROVIDER, {
		name: "GPT-5 Codex",
		matchingModel: "gpt-5-codex",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "September 15, 2025",
		lastUpdated: "September 15, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00107,
		costPer1kOutputTokens: 0.0085,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 36.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("gpt-5-nano", PROVIDER, {
		name: "GPT-5 Nano",
		matchingModel: "gpt-5-nano",
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 19.9,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-nano",
		openWeights: false,
	}),

	createModelConfig("gpt-5.1", PROVIDER, {
		name: "GPT-5.1",
		matchingModel: "gpt-5.1",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00107,
		costPer1kOutputTokens: 0.0085,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 20.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("gpt-5.1-codex", PROVIDER, {
		name: "GPT-5.1 Codex",
		matchingModel: "gpt-5.1-codex",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00107,
		costPer1kOutputTokens: 0.0085,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 34.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("gpt-5.1-codex-max", PROVIDER, {
		name: "GPT-5.1 Codex Max",
		matchingModel: "gpt-5.1-codex-max",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("gpt-5.1-codex-mini", PROVIDER, {
		name: "GPT-5.1 Codex Mini",
		matchingModel: "gpt-5.1-codex-mini",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 30.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("gpt-5.2", PROVIDER, {
		name: "GPT-5.2",
		matchingModel: "gpt-5.2",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 26,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("gpt-5.2-codex", PROVIDER, {
		name: "GPT-5.2 Codex",
		matchingModel: "gpt-5.2-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "January 14, 2026",
		lastUpdated: "January 14, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 40.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("gpt-5.3-codex", PROVIDER, {
		name: "GPT-5.3 Codex",
		matchingModel: "gpt-5.3-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 24, 2026",
		lastUpdated: "February 24, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 44.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("gpt-5.3-codex-spark", PROVIDER, {
		name: "GPT-5.3 Codex Spark",
		matchingModel: "gpt-5.3-codex-spark",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gpt-codex-spark",
		openWeights: false,
	}),

	createModelConfig("gpt-5.4", PROVIDER, {
		name: "GPT-5.4",
		matchingModel: "gpt-5.4",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 5, 2026",
		lastUpdated: "March 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 27.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("gpt-5.4-mini", PROVIDER, {
		name: "GPT-5.4 Mini",
		matchingModel: "gpt-5.4-mini",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 17, 2026",
		lastUpdated: "March 17, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00075,
		costPer1kOutputTokens: 0.0045,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 16.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-mini",
		openWeights: false,
	}),

	createModelConfig("gpt-5.4-nano", PROVIDER, {
		name: "GPT-5.4 Nano",
		matchingModel: "gpt-5.4-nano",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 17, 2026",
		lastUpdated: "March 17, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.00125,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 17.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-nano",
		openWeights: false,
	}),

	createModelConfig("gpt-5.4-pro", PROVIDER, {
		name: "GPT-5.4 Pro",
		matchingModel: "gpt-5.4-pro",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 5, 2026",
		lastUpdated: "March 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: false,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.03,
		costPer1kOutputTokens: 0.18,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		artificialAnalysis: {
			intelligenceIndex: null,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-pro",
		openWeights: false,
	}),

	createModelConfig("gpt-5.5", PROVIDER, {
		name: "GPT-5.5",
		matchingModel: "gpt-5.5",
		knowledgeCutoffDate: "December 1, 2025",
		releaseDate: "April 23, 2026",
		lastUpdated: "April 23, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.03,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 35.4,
			codingIndex: 56.5,
			agenticIndex: 25.8,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("gpt-5.5-pro", PROVIDER, {
		name: "GPT-5.5 Pro",
		matchingModel: "gpt-5.5-pro",
		knowledgeCutoffDate: "December 1, 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: false,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.03,
		costPer1kOutputTokens: 0.18,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		artificialAnalysis: {
			intelligenceIndex: null,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-pro",
		openWeights: false,
	}),

	createModelConfig("grok-build-0.1", PROVIDER, {
		name: "Grok Build 0.1",
		matchingModel: "grok-build-0.1",
		releaseDate: "May 20, 2026",
		lastUpdated: "May 20, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 256000,
		maxTokens: 256000,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "grok-build",
		openWeights: false,
	}),

	createModelConfig("kimi-k2.5", PROVIDER, {
		name: "Kimi K2.5",
		matchingModel: "kimi-k2.5",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 29.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-k2",
		openWeights: true,
	}),

	createModelConfig("kimi-k2.6", PROVIDER, {
		name: "Kimi K2.6",
		matchingModel: "kimi-k2.6",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "April 21, 2026",
		lastUpdated: "April 21, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 42.8,
			codingIndex: 56,
			agenticIndex: 30.3,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-k2",
		openWeights: true,
	}),

	createModelConfig("mimo-v2.5-free", PROVIDER, {
		name: "MiMo V2.5 Free",
		matchingModel: "mimo-v2.5-free",
		knowledgeCutoffDate: "December 2024",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "mimo-v2.5-free",
		openWeights: true,
	}),

	createModelConfig("minimax-m2.5", PROVIDER, {
		name: "MiniMax M2.5",
		matchingModel: "minimax-m2.5",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 33.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
	}),

	createModelConfig("minimax-m2.7", PROVIDER, {
		name: "MiniMax M2.7",
		matchingModel: "minimax-m2.7",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 38.1,
			codingIndex: 52.6,
			agenticIndex: 25.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
	}),

	createModelConfig("qwen3.5-plus", PROVIDER, {
		name: "Qwen3.5 Plus",
		matchingModel: "qwen3.5-plus",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "February 16, 2026",
		lastUpdated: "February 16, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "qwen3.5",
		openWeights: false,
	}),

	createModelConfig("qwen3.6-plus", PROVIDER, {
		name: "Qwen3.6 Plus",
		matchingModel: "qwen3.6-plus",
		knowledgeCutoffDate: "April 2025",
		releaseDate: "April 2, 2026",
		lastUpdated: "April 2, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 39.6,
			codingIndex: 54.5,
			agenticIndex: 27.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen3.6",
		openWeights: false,
	}),
	createModelConfig("deepseek-v4-flash", PROVIDER, {
		name: "DeepSeek V4 Flash",
		matchingModel: "deepseek-v4-flash",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 28.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek-flash",
		openWeights: true,
	}),

	createModelConfig("nemotron-3-ultra-free", PROVIDER, {
		name: "Nemotron 3 Ultra Free",
		matchingModel: "nemotron-3-ultra-free",
		knowledgeCutoffDate: "February 2026",
		releaseDate: "June 4, 2026",
		lastUpdated: "June 4, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "nemotron-free",
		openWeights: true,
	}),
	createModelConfig("north-mini-code-free", PROVIDER, {
		name: "North Mini Code Free",
		matchingModel: "north-mini-code-free",
		knowledgeCutoffDate: "September 23, 2025",
		releaseDate: "June 9, 2026",
		lastUpdated: "June 9, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 256000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "north-free",
		openWeights: true,
	}),
	createModelConfig("deepseek-v4-pro", PROVIDER, {
		name: "DeepSeek V4 Pro",
		matchingModel: "deepseek-v4-pro",
		knowledgeCutoffDate: "May 2025",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00384,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 31.2,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek-thinking",
		openWeights: true,
	}),
	createModelConfig("glm-5.2", PROVIDER, {
		name: "GLM-5.2",
		matchingModel: "glm-5.2",
		releaseDate: "June 13, 2026",
		lastUpdated: "June 13, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		strengths: ["tool_use", "coding"],
		contextComplexity: 5,
		reliability: 3,
		speed: 4,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 51.1,
			codingIndex: 68.8,
			agenticIndex: 43.1,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	}),
	createModelConfig("claude-sonnet-5", PROVIDER, {
		name: "Claude Sonnet 5",
		matchingModel: "claude-sonnet-5",
		family: "claude-sonnet",
		openWeights: false,
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "June 30, 2026",
		lastUpdated: "June 30, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k2.7-code", PROVIDER, {
		name: "Kimi K2.7 Code",
		matchingModel: "kimi-k2.7-code",
		family: "kimi-k2",
		openWeights: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 12, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		strengths: ["vision", "video", "document", "tool_use", "coding"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 41.9,
			codingIndex: 60.8,
			agenticIndex: 29.6,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("minimax-m3", PROVIDER, {
		name: "MiniMax-M3",
		matchingModel: "minimax-m3",
		family: "minimax",
		openWeights: true,
		releaseDate: "June 1, 2026",
		lastUpdated: "June 1, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 512000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 44.4,
			codingIndex: 58.6,
			agenticIndex: 35.4,
			intelligenceIndexVersion: 4.1,
		},
	}),
	createModelConfig("claude-fable-5", PROVIDER, {
		name: "Claude Fable 5",
		matchingModel: "claude-fable-5",
		family: "claude-fable",
		openWeights: false,
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "June 9, 2026",
		lastUpdated: "June 9, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.05,
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 59.9,
			codingIndex: 76.5,
			agenticIndex: 52.8,
			intelligenceIndexVersion: 4.1,
		},
	}),
	createModelConfig("hy3-free", PROVIDER, {
		name: "Hy3 Free",
		matchingModel: "hy3-free",
		family: "hy3-free",
		openWeights: true,
		releaseDate: "June 26, 2026",
		lastUpdated: "June 26, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 190000,
		maxTokens: 64000,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("grok-4.5", PROVIDER, {
		name: "Grok 4.5",
		matchingModel: "grok-4.5",
		family: "grok",
		openWeights: false,
		releaseDate: "July 8, 2026",
		lastUpdated: "July 8, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 500000,
		maxTokens: 500000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.006,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("gpt-5.6-luna", PROVIDER, {
		name: "GPT-5.6 Luna",
		matchingModel: "gpt-5.6-luna",
		family: "gpt-nano",
		openWeights: false,
		knowledgeCutoffDate: "February 16, 2026",
		releaseDate: "July 9, 2026",
		lastUpdated: "July 9, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.006,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.6-sol", PROVIDER, {
		name: "GPT-5.6 Sol",
		matchingModel: "gpt-5.6-sol",
		family: "gpt",
		openWeights: false,
		knowledgeCutoffDate: "February 16, 2026",
		releaseDate: "July 9, 2026",
		lastUpdated: "July 9, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.03,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.6-terra", PROVIDER, {
		name: "GPT-5.6 Terra",
		matchingModel: "gpt-5.6-terra",
		family: "gpt-mini",
		openWeights: false,
		knowledgeCutoffDate: "February 16, 2026",
		releaseDate: "July 9, 2026",
		lastUpdated: "July 9, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
]);
