import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "openai";

export const openaiModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("o1", PROVIDER, {
		name: "OpenAI o1",
		matchingModel: "o1",
		description:
			"Advanced model with strong capabilities in coding, analysis, math, reasoning, and multilingual support. Predecessor to o3, features 200k context window. Surpassed by o3 in complex reasoning and tool use.",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "December 5, 2024",
		lastUpdated: "December 5, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/o1",
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.06,
		strengths: ["coding", "analysis", "math", "reasoning", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 1,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		timeout: 1000000,
		supportsTopP: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o3", PROVIDER, {
		name: "OpenAI o3",
		matchingModel: "o3",
		description:
			"OpenAI's most powerful reasoning model, pushing frontiers in coding, math, science, visual perception. Agentically uses tools (web search, Python, visual analysis, image generation).",
		knowledgeCutoffDate: "May 2024",
		releaseDate: "January 24, 2025",
		lastUpdated: "January 24, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
		strengths: ["coding", "math", "reasoning", "analysis", "multilingual"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		includedInRouter: false,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		timeout: 1000000,
		supportsTemperature: false,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o4-mini", PROVIDER, {
		name: "OpenAI o4 Mini",
		matchingModel: "o4-mini",
		description:
			"Smaller model optimized for fast, cost-efficient reasoning. Strong performance in math, coding, visual tasks, and data science. Agentically uses tools.",
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsTopP: false,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
		strengths: [
			"math",
			"coding",
			"reasoning",
			"analysis",
			"chat",
			"general_knowledge",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: false,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o3-mini", PROVIDER, {
		name: "OpenAI o3 Mini",
		matchingModel: "o3-mini",
		description:
			"Fast, flexible reasoning model, predecessor to o4-mini. Good reasoning capabilities.",
		knowledgeCutoffDate: "May 2024",
		releaseDate: "December 20, 2024",
		lastUpdated: "January 29, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsTopP: false,
		card: "https://www.prompthub.us/models/o3-mini",
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
		strengths: ["coding", "analysis", "math", "reasoning", "multilingual"],
		contextComplexity: 3,
		reliability: 3,
		speed: 3,
		multimodal: false,
		isFeatured: false,
		includedInRouter: false,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-4o", PROVIDER, {
		name: "OpenAI GPT-4o",
		matchingModel: "gpt-4o",
		description:
			"Enhanced GPT model with 128k context window, specialized in analysis, chat, coding, and multilingual tasks.",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "May 13, 2024",
		lastUpdated: "May 13, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		card: "https://www.prompthub.us/models/gpt-4o",
		contextWindow: 128000,
		maxTokens: 16484,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
		strengths: [
			"analysis",
			"chat",
			"coding",
			"multilingual",
			"general_knowledge",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
	}),

	createModelConfig("gpt-4o-search-preview", PROVIDER, {
		name: "OpenAI GPT-4o Search Preview",
		matchingModel: "gpt-4o-search-preview",
		description:
			"Enhanced GPT model with 128k context window, specialized in analysis, chat, coding, and multilingual tasks. With Search.",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "May 13, 2024",
		lastUpdated: "May 13, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		card: "https://www.prompthub.us/models/gpt-4o",
		contextWindow: 128000,
		maxTokens: 16484,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
		strengths: [
			"analysis",
			"chat",
			"coding",
			"multilingual",
			"general_knowledge",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
	}),

	createModelConfig("gpt-4o-mini", PROVIDER, {
		name: "OpenAI GPT-4o Mini",
		matchingModel: "gpt-4o-mini",
		description:
			"Efficient version of GPT-4o optimized for faster response times while maintaining core capabilities.",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		card: "https://www.prompthub.us/models/gpt-4o-mini",
		contextWindow: 128000,
		maxTokens: 16484,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: [
			"analysis",
			"chat",
			"coding",
			"multilingual",
			"general_knowledge",
		],
		contextComplexity: 3,
		reliability: 3,
		speed: 5,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
	}),

	createModelConfig("gpt-4o-mini-search", PROVIDER, {
		name: "OpenAI GPT-4o Mini Search Preview",
		matchingModel: "gpt-4o-mini-search-preview",
		description:
			"Efficient version of GPT-4o optimized for faster response times while maintaining core capabilities. With search.",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		card: "https://www.prompthub.us/models/gpt-4o-mini",
		contextWindow: 128000,
		maxTokens: 16484,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: [
			"analysis",
			"chat",
			"coding",
			"multilingual",
			"general_knowledge",
		],
		contextComplexity: 3,
		reliability: 3,
		speed: 5,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
	}),

	createModelConfig("gpt-4.5", PROVIDER, {
		name: "OpenAI GPT-4.5",
		matchingModel: "gpt-4.5-preview",
		description:
			"GPT-4.5 excels at tasks that benefit from creative, open-ended thinking and conversation, such as writing, learning, or exploring new ideas.",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "November 6, 2024",
		lastUpdated: "November 6, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		card: "https://platform.openai.com/docs/models/gpt-4.5-preview",
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.03,
		strengths: ["coding", "analysis", "reasoning", "multilingual"],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		timeout: 1000000,
	}),

	createModelConfig("gpt-4.1", PROVIDER, {
		name: "OpenAI GPT-4.1",
		matchingModel: "gpt-4.1",
		description:
			"OpenAI's advanced model optimized for coding and instruction-following with 1M token context window",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/gpt-4-1",
		supportsToolCalls: true,
		maxTokens: 1000000,
		contextWindow: 1000000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		strengths: ["coding", "academic", "reasoning", "instruction", "vision"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		supportsArtifacts: true,
		isFeatured: false,
		includedInRouter: true,
		timeout: 1000000,
	}),
	createModelConfig("gpt-4.1-mini", PROVIDER, {
		name: "OpenAI GPT-4.1 Mini",
		matchingModel: "gpt-4.1-mini",
		description:
			"Balanced version of GPT-4.1 with 1M token context window and lower cost",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/gpt-4-1-mini",
		supportsToolCalls: true,
		maxTokens: 1000000,
		contextWindow: 1000000,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
		strengths: ["coding", "academic", "instruction", "vision"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		supportsArtifacts: true,
		isFeatured: false,
		includedInRouter: true,
	}),
	createModelConfig("gpt-4.1-nano", PROVIDER, {
		name: "OpenAI GPT-4.1 Nano",
		matchingModel: "gpt-4.1-nano",
		description:
			"Fastest and most cost-effective version of GPT-4.1 with 1M token context window",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/gpt-4-1-nano",
		supportsToolCalls: true,
		maxTokens: 1000000,
		contextWindow: 1000000,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
		strengths: ["coding", "academic", "instruction"],
		contextComplexity: 3,
		reliability: 3,
		speed: 5,
		multimodal: true,
		supportsArtifacts: true,
		isFeatured: false,
		includedInRouter: true,
	}),

	createModelConfig("gpt-5", PROVIDER, {
		name: "OpenAI GPT 5",
		matchingModel: "gpt-5",
		description:
			"GPT-5 is OpenAI's flagship model for coding, reasoning, and agentic tasks across domains",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/gpt-5",
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		supportsTopP: false,
		strengths: ["coding", "reasoning", "analysis", "multilingual", "creative"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),
	createModelConfig("gpt-5-mini", PROVIDER, {
		name: "OpenAI GPT 5 Mini",
		matchingModel: "gpt-5-mini",
		description:
			"GPT-5 is OpenAI's flagship model for coding, reasoning, and agentic tasks across domains",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/gpt-5-mini",
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		supportsTopP: false,
		strengths: ["coding", "reasoning", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),
	createModelConfig("gpt-5-nano", PROVIDER, {
		name: "OpenAI GPT 5 Nano",
		matchingModel: "gpt-5-nano",
		description:
			"GPT-5 is OpenAI's flagship model for coding, reasoning, and agentic tasks across domains",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/gpt-5-nano",
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		supportsTopP: false,
		strengths: ["coding", "chat", "general_knowledge"],
		contextComplexity: 3,
		reliability: 4,
		speed: 5,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("gpt-5.1", PROVIDER, {
		name: "OpenAI GPT 5.2",
		matchingModel: "gpt-5.2",
		description:
			"GPT-5.1 is an improved version of OpenAI's flagship model for coding, reasoning, and agentic tasks across domains",
		knowledgeCutoffDate: "2025-08",
		releaseDate: "2025-12-11",
		lastUpdated: "2025-12-11",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		supportsTopP: false,
		strengths: ["coding", "reasoning", "analysis", "multilingual", "creative"],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		reasoningConfig: {
			enabled: true,
			supportedEffortLevels: ["none", "low", "medium", "high"],
			defaultEffort: "medium",
		},
		verbosityConfig: {
			supportedVerbosityLevels: ["low", "medium", "high"],
			defaultVerbosity: "medium",
		},
		includedInRouter: true,
		supportsArtifacts: true,
		isFeatured: true,
	}),
	createModelConfig("gpt-5.2-chat", PROVIDER, {
		name: "OpenAI GPT 5.2 Chat",
		matchingModel: "gpt-5.2-chat-latest",
		description:
			"A chat-optimized version of GPT-5.2, designed for dynamic and interactive conversations across various topics",
		knowledgeCutoffDate: "2025-08",
		releaseDate: "2025-12-11",
		lastUpdated: "2025-12-11",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		supportsTopP: false,
		strengths: [
			"chat",
			"creative",
			"analysis",
			"general_knowledge",
			"multilingual",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		reasoningConfig: {
			enabled: true,
			supportedEffortLevels: ["none", "low", "medium", "high"],
			defaultEffort: "medium",
		},
		verbosityConfig: {
			supportedVerbosityLevels: ["low", "medium", "high"],
			defaultVerbosity: "medium",
		},
		includedInRouter: true,
		supportsArtifacts: true,
		isFeatured: true,
	}),

	createModelConfig("gpt-5.1-codex", PROVIDER, {
		name: "OpenAI GPT 5.1 Codex",
		matchingModel: "gpt-5.1-codex",
		description:
			"GPT-5.1 Codex is a specialized version of GPT-5.1, fine-tuned for code generation and understanding tasks.",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		strengths: ["coding", "reasoning", "analysis"],
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/gpt-5.1",
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		supportsTopP: false,
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		reasoningConfig: {
			enabled: true,
			supportedEffortLevels: ["none", "low", "medium", "high"],
			defaultEffort: "medium",
		},
		verbosityConfig: {
			supportedVerbosityLevels: ["low", "medium", "high"],
			defaultVerbosity: "medium",
		},
		includedInRouter: true,
		supportsArtifacts: true,
		isFeatured: true,
	}),
	createModelConfig("gpt-5.1-codex-mini", PROVIDER, {
		name: "OpenAI GPT 5.1 Codex Mini",
		matchingModel: "gpt-5.1-codex-mini",
		description:
			"GPT-5.1 Codex Mini is a lightweight version of GPT-5.1 Codex, optimized for faster performance and lower resource usage.",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		strengths: ["coding", "reasoning", "analysis"],
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/gpt-5.1",
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		supportsTopP: false,
		contextComplexity: 4,
		reliability: 5,
		speed: 5,
		multimodal: true,
		reasoningConfig: {
			enabled: true,
			supportedEffortLevels: ["none", "low", "medium", "high"],
			defaultEffort: "medium",
		},
		verbosityConfig: {
			supportedVerbosityLevels: ["low", "medium", "high"],
			defaultVerbosity: "medium",
		},
		includedInRouter: true,
		supportsArtifacts: true,
		isFeatured: true,
	}),

	createModelConfig("gpt-image-1", PROVIDER, {
		name: "GPT Image Generation 1",
		matchingModel: "gpt-image-1",
		description: "OpenAI's model for image generation.",
		strengths: ["creative"],
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.001,
		contextComplexity: 3,
		reliability: 4,
		speed: 3,
		isFeatured: true,
		supportsImageEdits: true,
		timeout: 1000000,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	}),

	createModelConfig("gpt-image-1-mini", PROVIDER, {
		name: "GPT Image Generation 1 Mini",
		matchingModel: "gpt-image-1-mini",
		description: "OpenAI's model for image generation, but smaller / faster.",
		strengths: ["creative"],
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.001,
		contextComplexity: 2,
		reliability: 4,
		speed: 4,
		isFeatured: true,
		supportsImageEdits: true,
		timeout: 1000000,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	}),

	createModelConfig("gpt-image-1.5", PROVIDER, {
		name: "GPT Image Generation 1.5",
		matchingModel: "gpt-image-1.5",
		description:
			"OpenAI's latest and most advanced model for image generation, a natively multimodal language model.",
		strengths: ["creative"],
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.001,
		contextComplexity: 3,
		reliability: 4,
		speed: 3,
		isFeatured: true,
		supportsImageEdits: true,
		timeout: 1000000,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	}),
]);
