import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "openai";

export const openaiModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("o1", PROVIDER, {
		name: "o1",
		matchingModel: "o1",
		description:
			"Advanced model with strong capabilities in coding, analysis, math, reasoning, and multilingual support. Predecessor to o3, features 200k context window. Surpassed by o3 in complex reasoning and tool use.",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "December 5, 2024",
		lastUpdated: "December 5, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/o1",
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.06,
		strengths: ["coding", "analysis", "math", "reasoning", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 1,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		timeout: 1000000,
		supportsTopP: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o3", PROVIDER, {
		name: "o3",
		matchingModel: "o3",
		description:
			"OpenAI's most powerful reasoning model, pushing frontiers in coding, math, science, visual perception. Agentically uses tools (web search, Python, visual analysis, image generation).",
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		strengths: ["coding", "math", "reasoning", "analysis", "multilingual"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		includedInRouter: false,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		timeout: 1000000,
		supportsTemperature: false,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o4-mini", PROVIDER, {
		name: "o4-mini",
		matchingModel: "o4-mini",
		description:
			"Smaller model optimized for fast, cost-efficient reasoning. Strong performance in math, coding, visual tasks, and data science. Agentically uses tools.",
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsTopP: false,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
		strengths: [
			"math",
			"coding",
			"reasoning",
			"analysis",
			"chat",
			"general_knowledge",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: false,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o3-mini", PROVIDER, {
		name: "o3-mini",
		matchingModel: "o3-mini",
		description:
			"Fast, flexible reasoning model, predecessor to o4-mini. Good reasoning capabilities.",
		knowledgeCutoffDate: "May 2024",
		releaseDate: "December 20, 2024",
		lastUpdated: "January 29, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsTopP: false,
		card: "https://www.prompthub.us/models/o3-mini",
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
		strengths: ["coding", "analysis", "math", "reasoning", "multilingual"],
		contextComplexity: 3,
		reliability: 3,
		speed: 3,
		multimodal: false,
		isFeatured: false,
		includedInRouter: false,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		reasoningConfig: {
			enabled: true,
		},
		supportsToolCalls: true,
	}),

	createModelConfig("gpt-4o", PROVIDER, {
		name: "GPT-4o",
		matchingModel: "gpt-4o",
		description:
			"Enhanced GPT model with 128k context window, specialized in analysis, chat, coding, and multilingual tasks.",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "May 13, 2024",
		lastUpdated: "August 6, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		card: "https://www.prompthub.us/models/gpt-4o",
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
		strengths: [
			"analysis",
			"chat",
			"coding",
			"multilingual",
			"general_knowledge",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("gpt-4o-search-preview", PROVIDER, {
		name: "OpenAI GPT-4o Search Preview",
		matchingModel: "gpt-4o-search-preview",
		description:
			"Enhanced GPT model with 128k context window, specialized in analysis, chat, coding, and multilingual tasks. With Search.",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "May 13, 2024",
		lastUpdated: "May 13, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		card: "https://www.prompthub.us/models/gpt-4o",
		contextWindow: 128000,
		maxTokens: 16484,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
		strengths: [
			"analysis",
			"chat",
			"coding",
			"multilingual",
			"general_knowledge",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
	}),

	createModelConfig("gpt-4o-mini", PROVIDER, {
		name: "GPT-4o mini",
		matchingModel: "gpt-4o-mini",
		description:
			"Efficient version of GPT-4o optimized for faster response times while maintaining core capabilities.",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		card: "https://www.prompthub.us/models/gpt-4o-mini",
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: [
			"analysis",
			"chat",
			"coding",
			"multilingual",
			"general_knowledge",
		],
		contextComplexity: 3,
		reliability: 3,
		speed: 5,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("gpt-4o-mini-search", PROVIDER, {
		name: "OpenAI GPT-4o Mini Search Preview",
		matchingModel: "gpt-4o-mini-search-preview",
		description:
			"Efficient version of GPT-4o optimized for faster response times while maintaining core capabilities. With search.",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		card: "https://www.prompthub.us/models/gpt-4o-mini",
		contextWindow: 128000,
		maxTokens: 16484,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: [
			"analysis",
			"chat",
			"coding",
			"multilingual",
			"general_knowledge",
		],
		contextComplexity: 3,
		reliability: 3,
		speed: 5,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
	}),

	createModelConfig("gpt-4.5", PROVIDER, {
		name: "OpenAI GPT-4.5",
		matchingModel: "gpt-4.5-preview",
		description:
			"GPT-4.5 excels at tasks that benefit from creative, open-ended thinking and conversation, such as writing, learning, or exploring new ideas.",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "November 6, 2024",
		lastUpdated: "November 6, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		card: "https://platform.openai.com/docs/models/gpt-4.5-preview",
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.03,
		strengths: ["coding", "analysis", "reasoning", "multilingual"],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		supportsArtifacts: true,
		timeout: 1000000,
	}),

	createModelConfig("gpt-4.1", PROVIDER, {
		name: "GPT-4.1",
		matchingModel: "gpt-4.1",
		description:
			"OpenAI's advanced model optimized for coding and instruction-following with 1M token context window",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/gpt-4-1",
		supportsToolCalls: true,
		maxTokens: 32768,
		contextWindow: 1047576,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		strengths: ["coding", "academic", "reasoning", "instruction", "vision"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		supportsArtifacts: true,
		isFeatured: false,
		includedInRouter: true,
		timeout: 1000000,
		supportsResponseFormat: true,
		reasoningConfig: {
			enabled: false,
		},
	}),
	createModelConfig("gpt-4.1-mini", PROVIDER, {
		name: "GPT-4.1 mini",
		matchingModel: "gpt-4.1-mini",
		description:
			"Balanced version of GPT-4.1 with 1M token context window and lower cost",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/gpt-4-1-mini",
		supportsToolCalls: true,
		maxTokens: 32768,
		contextWindow: 1047576,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
		strengths: ["coding", "academic", "instruction", "vision"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		supportsArtifacts: true,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		reasoningConfig: {
			enabled: false,
		},
	}),
	createModelConfig("gpt-4.1-nano", PROVIDER, {
		name: "GPT-4.1 nano",
		matchingModel: "gpt-4.1-nano",
		description:
			"Fastest and most cost-effective version of GPT-4.1 with 1M token context window",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		card: "https://www.prompthub.us/models/gpt-4-1-nano",
		supportsToolCalls: true,
		maxTokens: 32768,
		contextWindow: 1047576,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
		strengths: ["coding", "academic", "instruction"],
		contextComplexity: 3,
		reliability: 3,
		speed: 5,
		multimodal: true,
		supportsArtifacts: true,
		isFeatured: false,
		includedInRouter: true,
		supportsResponseFormat: true,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("gpt-5", PROVIDER, {
		name: "GPT-5",
		matchingModel: "gpt-5",
		description:
			"GPT-5 is OpenAI's flagship model for coding, reasoning, and agentic tasks across domains",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/gpt-5",
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		supportsTopP: false,
		strengths: ["coding", "reasoning", "analysis", "multilingual", "creative"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsResponseFormat: true,
		reasoningConfig: {
			enabled: true,
		},
	}),
	createModelConfig("gpt-5-mini", PROVIDER, {
		name: "GPT-5 Mini",
		matchingModel: "gpt-5-mini",
		description:
			"GPT-5 is OpenAI's flagship model for coding, reasoning, and agentic tasks across domains",
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/gpt-5-mini",
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		supportsTopP: false,
		strengths: ["coding", "reasoning", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsResponseFormat: true,
		reasoningConfig: {
			enabled: true,
		},
	}),
	createModelConfig("gpt-5-nano", PROVIDER, {
		name: "GPT-5 Nano",
		matchingModel: "gpt-5-nano",
		description:
			"GPT-5 is OpenAI's flagship model for coding, reasoning, and agentic tasks across domains",
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/gpt-5-nano",
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0004,
		supportsTopP: false,
		strengths: ["coding", "chat", "general_knowledge"],
		contextComplexity: 3,
		reliability: 4,
		speed: 5,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsResponseFormat: true,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-5.2", PROVIDER, {
		name: "GPT-5.2",
		matchingModel: "gpt-5.2",
		description:
			"GPT-5.1 is an improved version of OpenAI's flagship model for coding, reasoning, and agentic tasks across domains",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		supportsTopP: false,
		strengths: ["coding", "reasoning", "analysis", "multilingual", "creative"],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		reasoningConfig: {
			enabled: true,
			supportedEffortLevels: ["none", "low", "medium", "high"],
			defaultEffort: "medium",
		},
		verbosityConfig: {
			supportedVerbosityLevels: ["low", "medium", "high"],
			defaultVerbosity: "medium",
		},
		includedInRouter: true,
		supportsArtifacts: true,
		isFeatured: true,
		supportsResponseFormat: true,
	}),
	createModelConfig("gpt-5.2-chat", PROVIDER, {
		name: "GPT-5.2 Chat",
		matchingModel: "gpt-5.2-chat-latest",
		description:
			"A chat-optimized version of GPT-5.2, designed for dynamic and interactive conversations across various topics",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		maxTokens: 16384,
		contextWindow: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		supportsTopP: false,
		strengths: [
			"chat",
			"creative",
			"analysis",
			"general_knowledge",
			"multilingual",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		reasoningConfig: {
			enabled: true,
			supportedEffortLevels: ["none", "low", "medium", "high"],
			defaultEffort: "medium",
		},
		verbosityConfig: {
			supportedVerbosityLevels: ["low", "medium", "high"],
			defaultVerbosity: "medium",
		},
		includedInRouter: true,
		supportsArtifacts: true,
		isFeatured: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("gpt-5.1-codex", PROVIDER, {
		name: "GPT-5.1 Codex",
		matchingModel: "gpt-5.1-codex",
		description:
			"GPT-5.1 Codex is a specialized version of GPT-5.1, fine-tuned for code generation and understanding tasks.",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		strengths: ["coding", "reasoning", "analysis"],
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/gpt-5.1",
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		supportsTopP: false,
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		multimodal: true,
		reasoningConfig: {
			enabled: true,
			supportedEffortLevels: ["none", "low", "medium", "high"],
			defaultEffort: "medium",
		},
		verbosityConfig: {
			supportedVerbosityLevels: ["low", "medium", "high"],
			defaultVerbosity: "medium",
		},
		includedInRouter: true,
		supportsArtifacts: true,
		isFeatured: true,
		supportsResponseFormat: true,
	}),
	createModelConfig("gpt-5.1-codex-mini", PROVIDER, {
		name: "GPT-5.1 Codex mini",
		matchingModel: "gpt-5.1-codex-mini",
		description:
			"GPT-5.1 Codex Mini is a lightweight version of GPT-5.1 Codex, optimized for faster performance and lower resource usage.",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		strengths: ["coding", "reasoning", "analysis"],
		supportsAttachments: true,
		supportsTemperature: false,
		card: "https://www.prompthub.us/models/gpt-5.1",
		supportsToolCalls: true,
		maxTokens: 128000,
		contextWindow: 400000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		supportsTopP: false,
		contextComplexity: 4,
		reliability: 5,
		speed: 5,
		multimodal: true,
		reasoningConfig: {
			enabled: true,
			supportedEffortLevels: ["none", "low", "medium", "high"],
			defaultEffort: "medium",
		},
		verbosityConfig: {
			supportedVerbosityLevels: ["low", "medium", "high"],
			defaultVerbosity: "medium",
		},
		includedInRouter: true,
		supportsArtifacts: true,
		isFeatured: true,
		supportsResponseFormat: true,
	}),

	createModelConfig("gpt-image-1", PROVIDER, {
		name: "GPT Image Generation 1",
		matchingModel: "gpt-image-1",
		description: "OpenAI's model for image generation.",
		strengths: ["creative"],
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.001,
		contextComplexity: 3,
		reliability: 4,
		speed: 3,
		isFeatured: false,
		supportsImageEdits: true,
		timeout: 1000000,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	}),

	createModelConfig("gpt-image-1-mini", PROVIDER, {
		name: "GPT Image Generation 1 Mini",
		matchingModel: "gpt-image-1-mini",
		description: "OpenAI's model for image generation, but smaller / faster.",
		strengths: ["creative"],
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.001,
		contextComplexity: 2,
		reliability: 4,
		speed: 4,
		isFeatured: true,
		supportsImageEdits: true,
		timeout: 1000000,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	}),

	createModelConfig("gpt-image-1.5", PROVIDER, {
		name: "GPT Image Generation 1.5",
		matchingModel: "gpt-image-1.5",
		description:
			"OpenAI's latest and most advanced model for image generation, a natively multimodal language model.",
		strengths: ["creative"],
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.001,
		contextComplexity: 3,
		reliability: 4,
		speed: 3,
		isFeatured: true,
		supportsImageEdits: true,
		timeout: 1000000,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	}),
	createModelConfig("codex-mini-latest", PROVIDER, {
		name: "Codex Mini",
		matchingModel: "codex-mini-latest",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "May 16, 2025",
		lastUpdated: "May 16, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.006,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-3.5-turbo", PROVIDER, {
		name: "GPT-3.5-turbo",
		matchingModel: "gpt-3.5-turbo",
		knowledgeCutoffDate: "September 1, 2021",
		releaseDate: "March 1, 2023",
		lastUpdated: "November 6, 2023",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: false,
		contextWindow: 16385,
		maxTokens: 4096,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.0015,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("gpt-4", PROVIDER, {
		name: "GPT-4",
		matchingModel: "gpt-4",
		knowledgeCutoffDate: "November 2023",
		releaseDate: "November 6, 2023",
		lastUpdated: "April 9, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: false,
		contextWindow: 8192,
		maxTokens: 8192,
		costPer1kInputTokens: 0.03,
		costPer1kOutputTokens: 0.06,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("gpt-4-turbo", PROVIDER, {
		name: "GPT-4 Turbo",
		matchingModel: "gpt-4-turbo",
		knowledgeCutoffDate: "December 2023",
		releaseDate: "November 6, 2023",
		lastUpdated: "April 9, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: false,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.03,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("gpt-4o-2024-05-13", PROVIDER, {
		name: "GPT-4o (2024-05-13)",
		matchingModel: "gpt-4o-2024-05-13",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "May 13, 2024",
		lastUpdated: "May 13, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("gpt-4o-2024-08-06", PROVIDER, {
		name: "GPT-4o (2024-08-06)",
		matchingModel: "gpt-4o-2024-08-06",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "August 6, 2024",
		lastUpdated: "August 6, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("gpt-4o-2024-11-20", PROVIDER, {
		name: "GPT-4o (2024-11-20)",
		matchingModel: "gpt-4o-2024-11-20",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "November 20, 2024",
		lastUpdated: "November 20, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("gpt-5-chat-latest", PROVIDER, {
		name: "GPT-5 Chat (latest)",
		matchingModel: "gpt-5-chat-latest",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-5-codex", PROVIDER, {
		name: "GPT-5-Codex",
		matchingModel: "gpt-5-codex",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "September 15, 2025",
		lastUpdated: "September 15, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-5-pro", PROVIDER, {
		name: "GPT-5 Pro",
		matchingModel: "gpt-5-pro",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "October 6, 2025",
		lastUpdated: "October 6, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 272000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.12,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-5.1", PROVIDER, {
		name: "GPT-5.1",
		matchingModel: "gpt-5.1",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-5.1-chat-latest", PROVIDER, {
		name: "GPT-5.1 Chat",
		matchingModel: "gpt-5.1-chat-latest",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-5.1-codex-max", PROVIDER, {
		name: "GPT-5.1 Codex Max",
		matchingModel: "gpt-5.1-codex-max",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-5.2-codex", PROVIDER, {
		name: "GPT-5.2 Codex",
		matchingModel: "gpt-5.2-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-5.2-pro", PROVIDER, {
		name: "GPT-5.2 Pro",
		matchingModel: "gpt-5.2-pro",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.021,
		costPer1kOutputTokens: 0.168,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-5.3-codex", PROVIDER, {
		name: "GPT-5.3 Codex",
		matchingModel: "gpt-5.3-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "February 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("gpt-5.3-codex-spark", PROVIDER, {
		name: "GPT-5.3 Codex Spark",
		matchingModel: "gpt-5.3-codex-spark",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "February 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o1-mini", PROVIDER, {
		name: "o1-mini",
		matchingModel: "o1-mini",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "September 12, 2024",
		lastUpdated: "September 12, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o1-preview", PROVIDER, {
		name: "o1-preview",
		matchingModel: "o1-preview",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "September 12, 2024",
		lastUpdated: "September 12, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.06,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o1-pro", PROVIDER, {
		name: "o1-pro",
		matchingModel: "o1-pro",
		knowledgeCutoffDate: "September 2023",
		releaseDate: "March 19, 2025",
		lastUpdated: "March 19, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.15,
		costPer1kOutputTokens: 0.6,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o3-deep-research", PROVIDER, {
		name: "o3-deep-research",
		matchingModel: "o3-deep-research",
		knowledgeCutoffDate: "May 2024",
		releaseDate: "June 26, 2024",
		lastUpdated: "June 26, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.04,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o3-pro", PROVIDER, {
		name: "o3-pro",
		matchingModel: "o3-pro",
		knowledgeCutoffDate: "May 2024",
		releaseDate: "June 10, 2025",
		lastUpdated: "June 10, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.02,
		costPer1kOutputTokens: 0.08,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("o4-mini-deep-research", PROVIDER, {
		name: "o4-mini-deep-research",
		matchingModel: "o4-mini-deep-research",
		knowledgeCutoffDate: "May 2024",
		releaseDate: "June 26, 2024",
		lastUpdated: "June 26, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("text-embedding-3-large", PROVIDER, {
		name: "text-embedding-3-large",
		matchingModel: "text-embedding-3-large",
		knowledgeCutoffDate: "January 2024",
		releaseDate: "January 25, 2024",
		lastUpdated: "January 25, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 8191,
		maxTokens: 3072,
		costPer1kInputTokens: 0.00013,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("text-embedding-3-small", PROVIDER, {
		name: "text-embedding-3-small",
		matchingModel: "text-embedding-3-small",
		knowledgeCutoffDate: "January 2024",
		releaseDate: "January 25, 2024",
		lastUpdated: "January 25, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 8191,
		maxTokens: 1536,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	}),

	createModelConfig("text-embedding-ada-002", PROVIDER, {
		name: "text-embedding-ada-002",
		matchingModel: "text-embedding-ada-002",
		knowledgeCutoffDate: "December 2022",
		releaseDate: "December 15, 2022",
		lastUpdated: "December 15, 2022",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: false,
		supportsToolCalls: false,
		contextWindow: 8192,
		maxTokens: 1536,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	}),
]);
