import type { ModelConfig } from "@ngriffin_uk/polychat-schemas";

import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "ovhcloud";

export const ovhCloudModelConfig: ModelConfig = createModelConfigObject([
  createModelConfig("gpt-oss-120b", PROVIDER, {
    name: "GPT OSS 120B",
    matchingModel: "gpt-oss-120b",
    modalities: { input: ["text"], output: ["text"] },
    supportsTemperature: true,
    supportsToolCalls: true,
  	openWeights: true,
  	releaseDate: "August 28, 2025",
  	lastUpdated: "August 28, 2025",
  	supportsAttachments: false,
  	supportsResponseFormat: true,
  	contextWindow: 131072,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.00009,
  	costPer1kOutputTokens: 0.00047,
  	reasoningConfig: {
  		supportedEffortLevels: ["low", "medium", "high"],
  		defaultEffort: "low",
  	},
  	strengths: ["tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	speed: 5,
  	artificialAnalysis: {
  		intelligenceIndex: 23.8,
  		codingIndex: 30.4,
  		agenticIndex: 13.2,
  		intelligenceIndexVersion: 4.1,
  	},
  }),
  createModelConfig("qwen3-32b", PROVIDER, {
    name: "Qwen3 32B",
    matchingModel: "qwen3-32b",
    modalities: { input: ["text"], output: ["text"] },
    supportsTemperature: true,
    supportsToolCalls: true,
  	openWeights: true,
  	releaseDate: "July 16, 2025",
  	lastUpdated: "July 16, 2025",
  	supportsAttachments: false,
  	supportsResponseFormat: true,
  	contextWindow: 32768,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.00009,
  	costPer1kOutputTokens: 0.00025,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["tool_use"],
  	contextComplexity: 3,
  	reliability: 1,
  	speed: 3,
  	artificialAnalysis: {
  		intelligenceIndex: 8.6,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),
  createModelConfig("gpt-oss-20b", PROVIDER, {
  	name: "gpt-oss-20b",
  	matchingModel: "gpt-oss-20b",
  	openWeights: true,
  	releaseDate: "August 28, 2025",
  	lastUpdated: "August 28, 2025",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 131072,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.00005,
  	costPer1kOutputTokens: 0.00018,
  	reasoningConfig: {
  		supportedEffortLevels: ["low", "medium", "high"],
  		defaultEffort: "low",
  	},
  	strengths: ["tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	speed: 5,
  	artificialAnalysis: {
  		intelligenceIndex: 14.9,
  		codingIndex: 20.7,
  		agenticIndex: 3.1,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("meta-llama-3_3-70b-instruct", PROVIDER, {
  	name: "Meta-Llama-3_3-70B-Instruct",
  	matchingModel: "meta-llama-3_3-70b-instruct",
  	openWeights: true,
  	releaseDate: "April 1, 2025",
  	lastUpdated: "April 1, 2025",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 131072,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.00074,
  	costPer1kOutputTokens: 0.00074,
  }),

  createModelConfig("mistral-7b-instruct-v0.3", PROVIDER, {
  	name: "Mistral-7B-Instruct-v0.3",
  	matchingModel: "mistral-7b-instruct-v0.3",
  	openWeights: true,
  	releaseDate: "April 1, 2025",
  	lastUpdated: "April 1, 2025",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 65536,
  	maxTokens: 65536,
  	costPer1kInputTokens: 0.00011,
  	costPer1kOutputTokens: 0.00011,
  }),

  createModelConfig("mistral-nemo-instruct-2407", PROVIDER, {
  	name: "Mistral-Nemo-Instruct-2407",
  	matchingModel: "mistral-nemo-instruct-2407",
  	openWeights: true,
  	releaseDate: "November 20, 2024",
  	lastUpdated: "November 20, 2024",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 65536,
  	maxTokens: 65536,
  	costPer1kInputTokens: 0.00014,
  	costPer1kOutputTokens: 0.00014,
  }),

  createModelConfig("mistral-small-3.2-24b-instruct-2506", PROVIDER, {
  	name: "Mistral-Small-3.2-24B-Instruct-2506",
  	matchingModel: "mistral-small-3.2-24b-instruct-2506",
  	openWeights: true,
  	releaseDate: "July 16, 2025",
  	lastUpdated: "July 16, 2025",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 131072,
  	maxTokens: 131072,
  	costPer1kInputTokens: 0.0001,
  	costPer1kOutputTokens: 0.00031,
  }),

  createModelConfig("qwen2.5-vl-72b-instruct", PROVIDER, {
  	name: "Qwen2.5-VL-72B-Instruct",
  	matchingModel: "qwen2.5-vl-72b-instruct",
  	openWeights: true,
  	releaseDate: "March 31, 2025",
  	lastUpdated: "March 31, 2025",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: false,
  	supportsResponseFormat: true,
  	contextWindow: 32768,
  	maxTokens: 32768,
  	costPer1kInputTokens: 0.00101,
  	costPer1kOutputTokens: 0.00101,
  }),

  createModelConfig("qwen3-coder-30b-a3b-instruct", PROVIDER, {
  	name: "Qwen3-Coder-30B-A3B-Instruct",
  	matchingModel: "qwen3-coder-30b-a3b-instruct",
  	openWeights: true,
  	releaseDate: "October 28, 2025",
  	lastUpdated: "October 28, 2025",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 262144,
  	costPer1kInputTokens: 0.00007,
  	costPer1kOutputTokens: 0.00026,
  	strengths: ["tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	speed: 4,
  	artificialAnalysis: {
  		intelligenceIndex: 13.6,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("qwen3.5-397b-a17b", PROVIDER, {
  	name: "Qwen3.5-397B-A17B",
  	matchingModel: "qwen3.5-397b-a17b",
  	openWeights: true,
  	releaseDate: "May 18, 2026",
  	lastUpdated: "May 18, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 262144,
  	costPer1kInputTokens: 0.00071,
  	costPer1kOutputTokens: 0.00425,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "low", "medium", "high"],
  		defaultEffort: "none",
  	},
  	strengths: ["vision", "document", "tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	speed: 2,
  	artificialAnalysis: {
  		intelligenceIndex: 32,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("qwen3.5-9b", PROVIDER, {
  	name: "Qwen3.5-9B",
  	matchingModel: "qwen3.5-9b",
  	openWeights: true,
  	releaseDate: "April 22, 2026",
  	lastUpdated: "April 22, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 262144,
  	costPer1kInputTokens: 0.00012,
  	costPer1kOutputTokens: 0.00018,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "low", "medium", "high"],
  		defaultEffort: "none",
  	},
  	strengths: ["vision", "document", "tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	artificialAnalysis: {
  		intelligenceIndex: 20.3,
  		codingIndex: 23.5,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("qwen3.6-27b", PROVIDER, {
  	name: "Qwen3.6-27B",
  	matchingModel: "qwen3.6-27b",
  	openWeights: true,
  	releaseDate: "June 1, 2026",
  	lastUpdated: "June 1, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 262144,
  	maxTokens: 262144,
  	costPer1kInputTokens: 0.00047,
  	costPer1kOutputTokens: 0.00319,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "minimal", "low", "medium", "high"],
  		defaultEffort: "none",
  	},
  	strengths: ["vision", "document", "tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	speed: 3,
  	artificialAnalysis: {
  		intelligenceIndex: 29.3,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("qwen3guard-gen-0.6b", PROVIDER, {
  	name: "Qwen3Guard-Gen-0.6B",
  	matchingModel: "qwen3guard-gen-0.6b",
  	openWeights: true,
  	releaseDate: "January 22, 2026",
  	lastUpdated: "January 22, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: false,
  	contextWindow: 32768,
  	maxTokens: 16384,
  }),

  createModelConfig("qwen3guard-gen-8b", PROVIDER, {
  	name: "Qwen3Guard-Gen-8B",
  	matchingModel: "qwen3guard-gen-8b",
  	openWeights: true,
  	releaseDate: "January 22, 2026",
  	lastUpdated: "January 22, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: false,
  	contextWindow: 32768,
  	maxTokens: 16384,
  }),
]);
