import type { ModelConfig } from "~/types";

export const perplexityModelConfig: ModelConfig = {
	"sonar-deep-research": {
		name: "Perplexity Sonar Deep Research",
		matchingModel: "sonar-deep-research",
		description:
			"Premier research offering with search grounding, supporting advanced queries and follow-ups.",
		provider: "perplexity-ai",
		strengths: [
			"search",
			"research",
			"analysis",
			"multilingual",
			"academic",
			"general_knowledge",
		],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		costPer1kInputTokens: 0.002,
		costPer1kReasoningTokens: 0.003,
		costPer1kOutputTokens: 0.008,
		costPer1kSearches: 0.005,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"sonar-reasoning-pro": {
		name: "Sonar Reasoning Pro",
		matchingModel: "sonar-reasoning-pro",
		description:
			"Premier reasoning offering powered by DeepSeek R1 with Chain of Thought (CoT).",
		provider: "perplexity-ai",
		strengths: [
			"reasoning",
			"multilingual",
			"coding",
			"analysis",
			"general_knowledge",
		],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		isFeatured: false,
		includedInRouter: true,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		costPer1kSearches: 0.005,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		knowledgeCutoffDate: "September 1, 2025",
		releaseDate: "January 1, 2024",
		lastUpdated: "September 1, 2025",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 4096,
		reasoningConfig: {
			enabled: true,
		},
	},
	"sonar-reasoning": {
		name: "Perplexity Sonar Reasoning",
		matchingModel: "sonar-reasoning",
		description:
			"Standard reasoning offering with Chain of Thought (CoT) capabilities.",
		provider: "perplexity-ai",
		strengths: [
			"reasoning",
			"multilingual",
			"coding",
			"analysis",
			"general_knowledge",
			"search",
		],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		isFeatured: false,
		includedInRouter: true,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.005,
		costPer1kSearches: 0.005,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"sonar-pro": {
		name: "Sonar Pro",
		matchingModel: "sonar-pro",
		description:
			"Premier search offering with search grounding, supporting advanced queries and follow-ups.",
		provider: "perplexity-ai",
		strengths: ["search", "analysis", "summarization", "general_knowledge"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		isFeatured: false,
		includedInRouter: true,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		costPer1kSearches: 0.005,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		knowledgeCutoffDate: "September 1, 2025",
		releaseDate: "January 1, 2024",
		lastUpdated: "September 1, 2025",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 200000,
		maxTokens: 8192,
		reasoningConfig: {
			enabled: false,
		},
	},
	sonar: {
		name: "Sonar",
		matchingModel: "sonar",
		description:
			"Lightweight offering with search grounding, quicker and cheaper than Sonar Pro.",
		provider: "perplexity-ai",
		strengths: ["search", "analysis", "summarization", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.001,
		costPer1kSearches: 0.005,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		knowledgeCutoffDate: "September 1, 2025",
		releaseDate: "January 1, 2024",
		lastUpdated: "September 1, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 4096,
		reasoningConfig: {
			enabled: false,
		},
	},
	"r1-1776": {
		name: "Perplexity R1 1776",
		matchingModel: "r1-1776",
		description:
			"R1-1776 is a version of the DeepSeek R1 model that has been post-trained to provide uncensored, unbiased, and factual information.",
		provider: "perplexity-ai",
		strengths: [
			"reasoning",
			"multilingual",
			"coding",
			"analysis",
			"general_knowledge",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
};
