import type { ModelConfig } from "@ngriffin_uk/polychat-schemas";

import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "regolo-ai";

export const regoloModelConfig: ModelConfig = createModelConfigObject([
  createModelConfig("gpt-oss-120b", PROVIDER, {
    name: "GPT OSS 120B",
    matchingModel: "gpt-oss-120b",
    modalities: { input: ["text"], output: ["text"] },
    supportsTemperature: true,
    supportsToolCalls: true,
  	family: "gpt-oss",
  	openWeights: false,
  	releaseDate: "August 5, 2025",
  	lastUpdated: "August 5, 2025",
  	supportsAttachments: false,
  	contextWindow: 128000,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.001,
  	costPer1kOutputTokens: 0.0042,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["tool_use"],
  	contextComplexity: 3,
  	reliability: 1,
  	speed: 5,
  	artificialAnalysis: {
  		intelligenceIndex: 23.8,
  		codingIndex: 30.4,
  		agenticIndex: 13.2,
  		intelligenceIndexVersion: 4.1,
  	},
  }),
  createModelConfig("qwen3-coder-next", PROVIDER, {
    name: "Qwen3 Coder Next",
    matchingModel: "qwen3-coder-next",
    modalities: { input: ["text"], output: ["text"] },
    supportsTemperature: true,
    supportsToolCalls: true,
  	family: "qwen",
  	openWeights: true,
  	releaseDate: "March 1, 2026",
  	lastUpdated: "March 1, 2026",
  	supportsAttachments: false,
  	contextWindow: 262144,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.0003,
  	costPer1kOutputTokens: 0.0012,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["tool_use"],
  	contextComplexity: 3,
  	reliability: 1,
  	speed: 4,
  	artificialAnalysis: {
  		intelligenceIndex: 21.2,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),
  createModelConfig("apertus-70b", PROVIDER, {
  	name: "Apertus 70B",
  	matchingModel: "apertus-70b",
  	openWeights: true,
  	knowledgeCutoffDate: "September 2025",
  	releaseDate: "September 2, 2025",
  	lastUpdated: "September 2, 2025",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 30000,
  	maxTokens: 30000,
  	costPer1kInputTokens: 0.00046,
  	costPer1kOutputTokens: 0.00242,
  }),

  createModelConfig("brick-complexity-pro", PROVIDER, {
  	name: "Brick Complexity Pro",
  	matchingModel: "brick-complexity-pro",
  	openWeights: false,
  	releaseDate: "February 6, 2026",
  	lastUpdated: "February 6, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 100000,
  	maxTokens: 15000,
  	costPer1kInputTokens: 0.00012,
  	costPer1kOutputTokens: 0.00046,
  }),

  createModelConfig("brick-v1-beta", PROVIDER, {
  	name: "Brick v1 Beta",
  	matchingModel: "brick-v1-beta",
  	family: "model-router",
  	status: "beta",
  	openWeights: false,
  	releaseDate: "February 6, 2026",
  	lastUpdated: "February 6, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 100000,
  	maxTokens: 15000,
  	costPer1kInputTokens: 0,
  	costPer1kOutputTokens: 0,
  }),

  createModelConfig("deepseek-ocr-2", PROVIDER, {
  	name: "DeepSeek OCR 2",
  	matchingModel: "deepseek-ocr-2",
  	openWeights: true,
  	releaseDate: "January 27, 2026",
  	lastUpdated: "January 27, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsToolCalls: false,
  	contextWindow: 4000,
  	maxTokens: 4000,
  	costPer1kInputTokens: 0,
  	costPer1kOutputTokens: 0,
  }),

  createModelConfig("faster-whisper-large-v3", PROVIDER, {
  	name: "Faster Whisper Large v3",
  	matchingModel: "faster-whisper-large-v3",
  	family: "whisper",
  	openWeights: true,
  	releaseDate: "October 1, 2024",
  	lastUpdated: "October 1, 2024",
  	modalities: {
  		input: ["audio"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsToolCalls: false,
  	contextWindow: 448,
  	maxTokens: 4096,
  	costPer1kInputTokens: 0,
  	costPer1kOutputTokens: 0,
  }),

  createModelConfig("gemma4-31b", PROVIDER, {
  	name: "Gemma 4 31B IT",
  	matchingModel: "gemma4-31b",
  	family: "gemma",
  	openWeights: true,
  	releaseDate: "April 2, 2026",
  	lastUpdated: "April 2, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 100000,
  	maxTokens: 100000,
  	costPer1kInputTokens: 0.00046,
  	costPer1kOutputTokens: 0.00242,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("glm5.2", PROVIDER, {
  	name: "GLM-5.2",
  	matchingModel: "glm5.2",
  	family: "glm",
  	openWeights: true,
  	releaseDate: "June 13, 2026",
  	lastUpdated: "June 13, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 96000,
  	maxTokens: 96000,
  	costPer1kInputTokens: 0.00231,
  	costPer1kOutputTokens: 0.006,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["coding", "tool_use"],
  	contextComplexity: 4,
  	reliability: 3,
  	speed: 4,
  	artificialAnalysis: {
  		intelligenceIndex: 51.1,
  		codingIndex: 68.8,
  		agenticIndex: 43.1,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("gpt-oss-20b", PROVIDER, {
  	name: "GPT-OSS-20B",
  	matchingModel: "gpt-oss-20b",
  	family: "gpt-oss",
  	openWeights: true,
  	releaseDate: "March 1, 2026",
  	lastUpdated: "March 1, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 128000,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.0004,
  	costPer1kOutputTokens: 0.0018,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["tool_use"],
  	contextComplexity: 3,
  	reliability: 1,
  	speed: 5,
  	artificialAnalysis: {
  		intelligenceIndex: 14.9,
  		codingIndex: 20.7,
  		agenticIndex: 3.1,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("llama-3.3-70b-instruct", PROVIDER, {
  	name: "Llama 3.3 70B Instruct",
  	matchingModel: "llama-3.3-70b-instruct",
  	family: "llama",
  	openWeights: false,
  	releaseDate: "April 28, 2025",
  	lastUpdated: "April 28, 2025",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 128000,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.0006,
  	costPer1kOutputTokens: 0.0027,
  }),

  createModelConfig("mistral-small-4-119b", PROVIDER, {
  	name: "Mistral Small 4 119B",
  	matchingModel: "mistral-small-4-119b",
  	family: "mistral-small",
  	openWeights: false,
  	releaseDate: "March 15, 2026",
  	lastUpdated: "March 15, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 256000,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.00075,
  	costPer1kOutputTokens: 0.003,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("qwen-image", PROVIDER, {
  	name: "Qwen-Image",
  	matchingModel: "qwen-image",
  	family: "qwen",
  	openWeights: false,
  	releaseDate: "March 1, 2026",
  	lastUpdated: "March 1, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["image"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: true,
  	supportsToolCalls: false,
  	contextWindow: 8192,
  	maxTokens: 4096,
  	costPer1kInputTokens: 0.0005,
  	costPer1kOutputTokens: 0.002,
  	strengths: ["image"],
  	contextComplexity: 1,
  	reliability: 3,
  	artificialAnalysis: {
  		intelligenceIndex: null,
  		codingIndex: null,
  		agenticIndex: null,
  		intelligenceIndexVersion: null,
  		mediaScores: [{
  			key: "text_to_imageElo",
  			label: "Text-to-image arena",
  			value: 1060,
  			min: 800,
  			max: 1400,
  			confidenceInterval95: 8,
  		}],
  	},
  }),

  createModelConfig("qwen3-embedding-8b", PROVIDER, {
  	name: "Qwen3-Embedding-8B",
  	matchingModel: "qwen3-embedding-8b",
  	family: "qwen",
  	openWeights: true,
  	releaseDate: "February 1, 2026",
  	lastUpdated: "February 1, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: false,
  	supportsToolCalls: false,
  	contextWindow: 32768,
  	maxTokens: 8192,
  	costPer1kInputTokens: 0.0001,
  	costPer1kOutputTokens: 0.0001,
  }),

  createModelConfig("qwen3-reranker-4b", PROVIDER, {
  	name: "Qwen3-Reranker-4B",
  	matchingModel: "qwen3-reranker-4b",
  	family: "qwen",
  	openWeights: true,
  	releaseDate: "February 1, 2026",
  	lastUpdated: "February 1, 2026",
  	modalities: {
  		input: ["text"],
  		output: ["text"],
  	},
  	supportsAttachments: false,
  	supportsTemperature: false,
  	supportsToolCalls: false,
  	contextWindow: 32768,
  	maxTokens: 8192,
  	costPer1kInputTokens: 0.00012,
  	costPer1kOutputTokens: 0.00012,
  }),

  createModelConfig("qwen3.5-122b", PROVIDER, {
  	name: "Qwen3.5-122B",
  	matchingModel: "qwen3.5-122b",
  	family: "qwen",
  	openWeights: true,
  	releaseDate: "February 1, 2026",
  	lastUpdated: "February 1, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 262144,
  	maxTokens: 16384,
  	costPer1kInputTokens: 0.0009,
  	costPer1kOutputTokens: 0.0036,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),

  createModelConfig("qwen3.5-9b", PROVIDER, {
  	name: "Qwen3.5-9B",
  	matchingModel: "qwen3.5-9b",
  	family: "qwen",
  	openWeights: true,
  	releaseDate: "February 1, 2026",
  	lastUpdated: "February 1, 2026",
  	modalities: {
  		input: ["text", "image"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	contextWindow: 262144,
  	maxTokens: 8192,
  	costPer1kInputTokens: 0.00015,
  	costPer1kOutputTokens: 0.0006,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  	strengths: ["vision", "document", "tool_use"],
  	contextComplexity: 4,
  	reliability: 1,
  	artificialAnalysis: {
  		intelligenceIndex: 20.3,
  		codingIndex: 23.5,
  		agenticIndex: null,
  		intelligenceIndexVersion: 4.1,
  	},
  }),

  createModelConfig("qwen3.8-27b", PROVIDER, {
  	name: "Qwen3.8 27B",
  	matchingModel: "qwen3.8-27b",
  	family: "qwen",
  	openWeights: true,
  	releaseDate: "August 14, 2026",
  	lastUpdated: "August 14, 2026",
  	modalities: {
  		input: ["text", "image", "video"],
  		output: ["text"],
  	},
  	supportsAttachments: true,
  	supportsTemperature: true,
  	supportsToolCalls: true,
  	supportsResponseFormat: true,
  	contextWindow: 120000,
  	maxTokens: 120000,
  	costPer1kInputTokens: 0.00058,
  	costPer1kOutputTokens: 0.00242,
  	reasoningConfig: {
  		supportedEffortLevels: ["none", "thinking"],
  		defaultEffort: "none",
  	},
  }),
]);
