import type { ModelConfig } from "@ngriffin_uk/polychat-schemas";
import { createModelConfig, createModelConfigObject } from "~/lib/providers/models/utils";

const PROVIDER = "requesty";

export const requestyModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("openai/gpt-4.1-mini", PROVIDER, {
		name: "GPT-4.1 Mini",
		matchingModel: "openai/gpt-4.1-mini",
		description:
			"Balanced version of GPT-4.1 with massive 1M+ token context window and lower cost.",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
		strengths: ["coding", "analysis", "instruction", "vision", "tool_use", "document"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		supportsArtifacts: true,
		artificialAnalysis: {
			intelligenceIndex: 16.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-mini",
		openWeights: false,
	}),

	createModelConfig("openai/o4-mini", PROVIDER, {
		name: "o4 Mini",
		matchingModel: "openai/o4-mini",
		description:
			"Smaller model optimized for fast, cost-efficient reasoning with strong performance in math, coding, and visual tasks.",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsParallelToolCalls: false,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
		strengths: ["reasoning", "math", "coding", "analysis", "vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		supportsArtifacts: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 25.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "o-mini",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-4o-mini", PROVIDER, {
		name: "GPT-4o Mini",
		matchingModel: "openai/gpt-4o-mini",
		description:
			"Efficient version of GPT-4o optimized for faster response times while maintaining core capabilities.",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: ["analysis", "chat", "coding", "multilingual", "vision", "document", "tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		supportsArtifacts: true,
		artificialAnalysis: {
			intelligenceIndex: 6.9,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-mini",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-4.1", PROVIDER, {
		name: "GPT-4.1",
		matchingModel: "openai/gpt-4.1",
		description:
			"OpenAI's advanced model optimized for coding and instruction-following with massive 1M+ token context window.",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		strengths: ["coding", "academic", "reasoning", "instruction", "vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		supportsArtifacts: true,
		artificialAnalysis: {
			intelligenceIndex: 19.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("anthropic/claude-4-sonnet-20250522", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "anthropic/claude-4-sonnet-20250522",
		description:
			"Claude's most advanced Sonnet model with enhanced reasoning capabilities and multimodal understanding.",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["reasoning", "analysis", "coding", "creative", "vision"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		supportsArtifacts: true,
	}),

	createModelConfig("anthropic/claude-3-7-sonnet", PROVIDER, {
		name: "Claude Sonnet 3.7",
		matchingModel: "anthropic/claude-3-7-sonnet",
		description:
			"Enhanced version of Claude 3.5 Sonnet with improved reasoning and analysis capabilities.",
		knowledgeCutoffDate: "January 2024",
		releaseDate: "February 19, 2025",
		lastUpdated: "February 19, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["reasoning", "analysis", "coding", "creative", "vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		supportsArtifacts: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 23.5,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-sonnet",
		openWeights: false,
	}),

	createModelConfig("anthropic/claude-opus-4", PROVIDER, {
		name: "Claude Opus 4",
		matchingModel: "anthropic/claude-opus-4",
		description: "Claude's flagship Opus model with exceptional performance across all domains.",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		strengths: ["reasoning", "analysis", "creative", "coding", "vision"],
		contextComplexity: 5,
		reliability: 5,
		speed: 2,
		multimodal: true,
		isFeatured: false,
		supportsArtifacts: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "claude-opus",
		openWeights: false,
	}),

	createModelConfig("google/gemini-2.5-flash", PROVIDER, {
		name: "Gemini 2.5 Flash",
		matchingModel: "google/gemini-2.5-flash",
		description:
			"Google's fast multimodal model with support for text, images, audio, video, and PDFs.",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		strengths: [
			"vision",
			"audio",
			"analysis",
			"reasoning",
			"tool_use",
			"document",
			"video",
			"image",
			"creative",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 5,
		multimodal: true,
		isFeatured: false,
		supportsArtifacts: true,
		supportsAudio: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: null,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: null,
			mediaScores: [
				{
					key: "text_to_imageElo",
					label: "Text-to-image arena",
					value: 1159,
					min: 800,
					max: 1400,
					confidenceInterval95: 8,
				},
			],
		},
		family: "gemini-flash",
		openWeights: false,
	}),

	createModelConfig("google/gemini-2.5-pro", PROVIDER, {
		name: "Gemini 2.5 Pro",
		matchingModel: "google/gemini-2.5-pro",
		description:
			"Google's advanced multimodal model with extensive capabilities across text, images, audio, video, and PDFs.",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		strengths: [
			"vision",
			"audio",
			"analysis",
			"reasoning",
			"tool_use",
			"coding",
			"document",
			"video",
		],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		supportsArtifacts: true,
		supportsAudio: true,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 27,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gemini-pro",
		openWeights: false,
	}),
	createModelConfig("anthropic/claude-haiku-4-5", PROVIDER, {
		name: "Claude Haiku 4.5",
		matchingModel: "anthropic/claude-haiku-4-5",
		knowledgeCutoffDate: "February 1, 2025",
		releaseDate: "October 15, 2025",
		lastUpdated: "October 15, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 62000,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.005,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "claude-haiku",
		openWeights: false,
	}),

	createModelConfig("anthropic/claude-opus-4-1", PROVIDER, {
		name: "Claude Opus 4.1",
		matchingModel: "anthropic/claude-opus-4-1",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "claude-opus",
		openWeights: false,
	}),

	createModelConfig("anthropic/claude-opus-4-5", PROVIDER, {
		name: "Claude Opus 4.5",
		matchingModel: "anthropic/claude-opus-4-5",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "November 24, 2025",
		lastUpdated: "November 24, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 34.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-opus",
		openWeights: false,
	}),

	createModelConfig("anthropic/claude-sonnet-4", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "anthropic/claude-sonnet-4",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "claude-sonnet",
		openWeights: false,
	}),

	createModelConfig("anthropic/claude-sonnet-4-5", PROVIDER, {
		name: "Claude Sonnet 4.5",
		matchingModel: "anthropic/claude-sonnet-4-5",
		knowledgeCutoffDate: "July 31, 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "claude-sonnet",
		openWeights: false,
	}),

	createModelConfig("google/gemini-3-flash-preview", PROVIDER, {
		name: "Gemini 3 Flash",
		matchingModel: "google/gemini-3-flash-preview",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "December 17, 2025",
		lastUpdated: "December 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 27.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		speed: 5,
		openWeights: false,
	}),

	createModelConfig("google/gemini-3-pro-preview", PROVIDER, {
		name: "Gemini 3 Pro",
		matchingModel: "google/gemini-3-pro-preview",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "November 18, 2025",
		lastUpdated: "November 18, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		artificialAnalysis: {
			intelligenceIndex: 39.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gemini-pro",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5", PROVIDER, {
		name: "GPT-5",
		matchingModel: "openai/gpt-5",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "audio", "image", "video"],
			output: ["text", "audio", "image"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "audio", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 15.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5-mini", PROVIDER, {
		name: "GPT-5 Mini",
		matchingModel: "openai/gpt-5-mini",
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 33,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-mini",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5-nano", PROVIDER, {
		name: "GPT-5 Nano",
		matchingModel: "openai/gpt-5-nano",
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 16000,
		maxTokens: 4000,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["document", "tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 19.9,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-nano",
		openWeights: false,
	}),

	createModelConfig("xai/grok-4", PROVIDER, {
		name: "Grok 4",
		matchingModel: "xai/grok-4",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "September 9, 2025",
		lastUpdated: "September 9, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 33.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "grok",
		openWeights: false,
	}),

	createModelConfig("xai/grok-4-fast", PROVIDER, {
		name: "Grok 4 Fast",
		matchingModel: "xai/grok-4-fast",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "September 19, 2025",
		lastUpdated: "September 19, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 2000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 16.5,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "grok",
		openWeights: false,
	}),
	createModelConfig("anthropic/claude-opus-4-6", PROVIDER, {
		name: "Claude Opus 4.6",
		matchingModel: "anthropic/claude-opus-4-6",
		knowledgeCutoffDate: "May 31, 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "February 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 43.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-opus",
		openWeights: false,
	}),

	createModelConfig("anthropic/claude-sonnet-4-6", PROVIDER, {
		name: "Claude Sonnet 4.6",
		matchingModel: "anthropic/claude-sonnet-4-6",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 17, 2026",
		lastUpdated: "February 17, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 47.2,
			codingIndex: 63,
			agenticIndex: 40.8,
			intelligenceIndexVersion: 4.1,
		},
		family: "claude-sonnet",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5-chat", PROVIDER, {
		name: "GPT-5 Chat",
		matchingModel: "openai/gpt-5-chat",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5-codex", PROVIDER, {
		name: "GPT-5 Codex",
		matchingModel: "openai/gpt-5-codex",
		knowledgeCutoffDate: "October 1, 2024",
		releaseDate: "September 15, 2025",
		lastUpdated: "September 15, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 36.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5-image", PROVIDER, {
		name: "GPT-5 Image",
		matchingModel: "openai/gpt-5-image",
		knowledgeCutoffDate: "October 1, 2024",
		releaseDate: "October 14, 2025",
		lastUpdated: "October 14, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text", "image"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5-pro", PROVIDER, {
		name: "GPT-5 Pro",
		matchingModel: "openai/gpt-5-pro",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "October 6, 2025",
		lastUpdated: "October 6, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 272000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.12,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gpt-pro",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.1", PROVIDER, {
		name: "GPT-5.1",
		matchingModel: "openai/gpt-5.1",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 20.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.1-chat", PROVIDER, {
		name: "GPT-5.1 Chat",
		matchingModel: "openai/gpt-5.1-chat",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.1-codex", PROVIDER, {
		name: "GPT-5.1-Codex",
		matchingModel: "openai/gpt-5.1-codex",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 34.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.1-codex-max", PROVIDER, {
		name: "GPT-5.1-Codex-Max",
		matchingModel: "openai/gpt-5.1-codex-max",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.009,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.1-codex-mini", PROVIDER, {
		name: "GPT-5.1-Codex-Mini",
		matchingModel: "openai/gpt-5.1-codex-mini",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 30.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.2", PROVIDER, {
		name: "GPT-5.2",
		matchingModel: "openai/gpt-5.2",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 26,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.2-chat", PROVIDER, {
		name: "GPT-5.2 Chat",
		matchingModel: "openai/gpt-5.2-chat",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.2-codex", PROVIDER, {
		name: "GPT-5.2-Codex",
		matchingModel: "openai/gpt-5.2-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "January 14, 2026",
		lastUpdated: "January 14, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 40.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.2-pro", PROVIDER, {
		name: "GPT-5.2 Pro",
		matchingModel: "openai/gpt-5.2-pro",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "December 11, 2025",
		lastUpdated: "December 11, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.021,
		costPer1kOutputTokens: 0.168,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gpt-pro",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.3-codex", PROVIDER, {
		name: "GPT-5.3-Codex",
		matchingModel: "openai/gpt-5.3-codex",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 24, 2026",
		lastUpdated: "February 24, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00175,
		costPer1kOutputTokens: 0.014,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 44.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-codex",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.4", PROVIDER, {
		name: "GPT-5.4",
		matchingModel: "openai/gpt-5.4",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 5, 2026",
		lastUpdated: "March 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 27.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt",
		openWeights: false,
	}),

	createModelConfig("openai/gpt-5.4-pro", PROVIDER, {
		name: "GPT-5.4 Pro",
		matchingModel: "openai/gpt-5.4-pro",
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 5, 2026",
		lastUpdated: "March 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: false,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.03,
		costPer1kOutputTokens: 0.18,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		artificialAnalysis: {
			intelligenceIndex: null,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-pro",
		openWeights: false,
	}),
	createModelConfig("claude-fable-5", PROVIDER, {
		name: "Claude Fable 5",
		matchingModel: "claude-fable-5",
		family: "claude-fable",
		openWeights: false,
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "June 9, 2026",
		lastUpdated: "June 9, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.05,
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 59.9,
			codingIndex: 76.5,
			agenticIndex: 52.8,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-haiku-4-5", PROVIDER, {
		name: "Claude Haiku 4.5 (latest)",
		matchingModel: "claude-haiku-4-5",
		family: "claude-haiku",
		openWeights: false,
		knowledgeCutoffDate: "February 28, 2025",
		releaseDate: "October 15, 2025",
		lastUpdated: "October 15, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.005,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-haiku-4-5@eu", PROVIDER, {
		name: "Claude Haiku 4.5 (latest) (EU)",
		matchingModel: "claude-haiku-4-5@eu",
		family: "claude-haiku",
		openWeights: false,
		knowledgeCutoffDate: "February 28, 2025",
		releaseDate: "October 15, 2025",
		lastUpdated: "October 15, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0055,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus-4-1", PROVIDER, {
		name: "Claude Opus 4.1 (latest)",
		matchingModel: "claude-opus-4-1",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus-4-5", PROVIDER, {
		name: "Claude Opus 4.5 (latest)",
		matchingModel: "claude-opus-4-5",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "May 2025",
		releaseDate: "November 24, 2025",
		lastUpdated: "November 24, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 34.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-opus-4-5@eu", PROVIDER, {
		name: "Claude Opus 4.5 (latest) (EU)",
		matchingModel: "claude-opus-4-5@eu",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "May 2025",
		releaseDate: "November 24, 2025",
		lastUpdated: "November 24, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.0055,
		costPer1kOutputTokens: 0.0275,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 34.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-opus-4-6", PROVIDER, {
		name: "Claude Opus 4.6",
		matchingModel: "claude-opus-4-6",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "May 31, 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "March 13, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 2,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 43.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-opus-4-6@eu", PROVIDER, {
		name: "Claude Opus 4.6 (EU)",
		matchingModel: "claude-opus-4-6@eu",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "May 31, 2025",
		releaseDate: "February 5, 2026",
		lastUpdated: "March 13, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0055,
		costPer1kOutputTokens: 0.0275,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 2,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 43.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-opus-4-7", PROVIDER, {
		name: "Claude Opus 4.7",
		matchingModel: "claude-opus-4-7",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "April 16, 2026",
		lastUpdated: "April 16, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 53.5,
			codingIndex: 73.6,
			agenticIndex: 44.4,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-opus-4-7@eu", PROVIDER, {
		name: "Claude Opus 4.7 (EU)",
		matchingModel: "claude-opus-4-7@eu",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "April 16, 2026",
		lastUpdated: "April 16, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0055,
		costPer1kOutputTokens: 0.0275,
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 53.5,
			codingIndex: 73.6,
			agenticIndex: 44.4,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-opus-4-8", PROVIDER, {
		name: "Claude Opus 4.8",
		matchingModel: "claude-opus-4-8",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "January 2026",
		releaseDate: "May 28, 2026",
		lastUpdated: "May 28, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 55.7,
			codingIndex: 74.3,
			agenticIndex: 47.2,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-opus-4-8@eu", PROVIDER, {
		name: "Claude Opus 4.8 (EU)",
		matchingModel: "claude-opus-4-8@eu",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "January 2026",
		releaseDate: "May 28, 2026",
		lastUpdated: "May 28, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0055,
		costPer1kOutputTokens: 0.0275,
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 55.7,
			codingIndex: 74.3,
			agenticIndex: 47.2,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-opus-5", PROVIDER, {
		name: "Claude Opus 5",
		matchingModel: "claude-opus-5",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "May 2026",
		releaseDate: "July 24, 2026",
		lastUpdated: "July 24, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-opus-5@eu", PROVIDER, {
		name: "Claude Opus 5 (EU)",
		matchingModel: "claude-opus-5@eu",
		family: "claude-opus",
		openWeights: false,
		knowledgeCutoffDate: "May 2026",
		releaseDate: "July 24, 2026",
		lastUpdated: "July 24, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0055,
		costPer1kOutputTokens: 0.0275,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-sonnet-4-5", PROVIDER, {
		name: "Claude Sonnet 4.5 (latest)",
		matchingModel: "claude-sonnet-4-5",
		family: "claude-sonnet",
		openWeights: false,
		knowledgeCutoffDate: "July 31, 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-sonnet-4-5@eu", PROVIDER, {
		name: "Claude Sonnet 4.5 (latest) (EU)",
		matchingModel: "claude-sonnet-4-5@eu",
		family: "claude-sonnet",
		openWeights: false,
		knowledgeCutoffDate: "July 31, 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.0033,
		costPer1kOutputTokens: 0.0165,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-sonnet-4-6", PROVIDER, {
		name: "Claude Sonnet 4.6",
		matchingModel: "claude-sonnet-4-6",
		family: "claude-sonnet",
		openWeights: false,
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 17, 2026",
		lastUpdated: "March 13, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 2,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 47.2,
			codingIndex: 63,
			agenticIndex: 40.8,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-sonnet-4-6@eu", PROVIDER, {
		name: "Claude Sonnet 4.6 (EU)",
		matchingModel: "claude-sonnet-4-6@eu",
		family: "claude-sonnet",
		openWeights: false,
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "February 17, 2026",
		lastUpdated: "March 13, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.0033,
		costPer1kOutputTokens: 0.0165,
		strengths: ["coding", "vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 3,
		speed: 2,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 47.2,
			codingIndex: 63,
			agenticIndex: 40.8,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("claude-sonnet-4@eu", PROVIDER, {
		name: "Claude Sonnet 4 (latest) (EU)",
		matchingModel: "claude-sonnet-4@eu",
		family: "claude-sonnet",
		openWeights: false,
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-sonnet-5", PROVIDER, {
		name: "Claude Sonnet 5",
		matchingModel: "claude-sonnet-5",
		family: "claude-sonnet",
		openWeights: false,
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "June 30, 2026",
		lastUpdated: "June 30, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("claude-sonnet-5@eu", PROVIDER, {
		name: "Claude Sonnet 5 (EU)",
		matchingModel: "claude-sonnet-5@eu",
		family: "claude-sonnet",
		openWeights: false,
		knowledgeCutoffDate: "January 31, 2026",
		releaseDate: "June 30, 2026",
		lastUpdated: "June 30, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0022,
		costPer1kOutputTokens: 0.011,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("deepseek-v4-flash-0731", PROVIDER, {
		name: "DeepSeek V4 Flash 0731",
		matchingModel: "deepseek-v4-flash-0731",
		family: "deepseek-flash",
		openWeights: true,
		knowledgeCutoffDate: "May 2025",
		releaseDate: "July 31, 2026",
		lastUpdated: "July 31, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("deepseek-v4-flash-0731@eu", PROVIDER, {
		name: "DeepSeek V4 Flash 0731 (EU)",
		matchingModel: "deepseek-v4-flash-0731@eu",
		family: "deepseek-flash",
		openWeights: true,
		knowledgeCutoffDate: "May 2025",
		releaseDate: "July 31, 2026",
		lastUpdated: "July 31, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00028,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gemini-2.5-flash@eu", PROVIDER, {
		name: "Gemini 2.5 Flash (EU)",
		matchingModel: "gemini-2.5-flash@eu",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65535,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		strengths: ["vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 5,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 14.1,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gemini-3.1-flash-lite@eu", PROVIDER, {
		name: "Gemini 3.1 Flash Lite (EU)",
		matchingModel: "gemini-3.1-flash-lite@eu",
		family: "gemini-flash-lite",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 7, 2026",
		lastUpdated: "May 7, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65535,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.0015,
		strengths: ["vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 25,
			codingIndex: 34.7,
			agenticIndex: 6.2,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gemini-3.5-flash-lite", PROVIDER, {
		name: "Gemini 3.5 Flash Lite",
		matchingModel: "gemini-3.5-flash-lite",
		family: "gemini-flash-lite",
		openWeights: false,
		knowledgeCutoffDate: "March 2026",
		releaseDate: "July 21, 2026",
		lastUpdated: "July 21, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65535,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gemini-3.5-flash@eu", PROVIDER, {
		name: "Gemini 3.5 Flash (EU)",
		matchingModel: "gemini-3.5-flash@eu",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "May 19, 2026",
		lastUpdated: "May 19, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65535,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.009,
		strengths: ["coding", "vision", "document", "audio", "video", "tool_use"],
		contextComplexity: 4,
		reliability: 3,
		speed: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 50.2,
			codingIndex: 70.1,
			agenticIndex: 37.4,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gemini-3.6-flash", PROVIDER, {
		name: "Gemini 3.6 Flash",
		matchingModel: "gemini-3.6-flash",
		family: "gemini-flash",
		openWeights: false,
		knowledgeCutoffDate: "March 2026",
		releaseDate: "July 21, 2026",
		lastUpdated: "July 21, 2026",
		modalities: {
			input: ["text", "image", "video", "audio", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 65535,
		costPer1kInputTokens: 0.0015,
		costPer1kOutputTokens: 0.007,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.2", PROVIDER, {
		name: "GLM-5.2",
		matchingModel: "glm-5.2",
		family: "glm",
		openWeights: true,
		releaseDate: "June 13, 2026",
		lastUpdated: "June 13, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0012,
		costPer1kOutputTokens: 0.0042,
		strengths: ["coding", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 4,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 51.1,
			codingIndex: 68.8,
			agenticIndex: 43.1,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("glm-5.2@eu", PROVIDER, {
		name: "GLM-5.2 (EU)",
		matchingModel: "glm-5.2@eu",
		family: "glm",
		openWeights: true,
		releaseDate: "June 13, 2026",
		lastUpdated: "June 13, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0012,
		costPer1kOutputTokens: 0.0042,
		strengths: ["coding", "tool_use"],
		contextComplexity: 5,
		reliability: 3,
		speed: 4,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 51.1,
			codingIndex: 68.8,
			agenticIndex: 43.1,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-4.1-mini@eu", PROVIDER, {
		name: "GPT-4.1 mini (EU)",
		matchingModel: "gpt-4.1-mini@eu",
		family: "gpt-mini",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00044,
		costPer1kOutputTokens: 0.00176,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 16.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-4.1-nano@eu", PROVIDER, {
		name: "GPT-4.1 nano (EU)",
		matchingModel: "gpt-4.1-nano@eu",
		family: "gpt-nano",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00011,
		costPer1kOutputTokens: 0.00044,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 7.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-4.1@eu", PROVIDER, {
		name: "GPT-4.1 (EU)",
		matchingModel: "gpt-4.1@eu",
		family: "gpt",
		openWeights: false,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0022,
		costPer1kOutputTokens: 0.0088,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 19.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-4o-mini@eu", PROVIDER, {
		name: "GPT-4o mini (EU)",
		matchingModel: "gpt-4o-mini@eu",
		family: "gpt-mini",
		openWeights: false,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 128000,
		maxTokens: 16000,
		costPer1kInputTokens: 0.000165,
		costPer1kOutputTokens: 0.00066,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 3,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 6.9,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-5-mini@eu", PROVIDER, {
		name: "GPT-5 Mini (EU)",
		matchingModel: "gpt-5-mini@eu",
		family: "gpt-mini",
		openWeights: false,
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.000275,
		costPer1kOutputTokens: 0.0022,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 2,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 33,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-5-nano@eu", PROVIDER, {
		name: "GPT-5 Nano (EU)",
		matchingModel: "gpt-5-nano@eu",
		family: "gpt-nano",
		openWeights: false,
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.000055,
		costPer1kOutputTokens: 0.00044,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 19.9,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-5.1@eu", PROVIDER, {
		name: "GPT-5.1 (EU)",
		matchingModel: "gpt-5.1@eu",
		family: "gpt",
		openWeights: false,
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.001375,
		costPer1kOutputTokens: 0.011,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 20.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-5.4@eu", PROVIDER, {
		name: "GPT-5.4 (EU)",
		matchingModel: "gpt-5.4@eu",
		family: "gpt",
		openWeights: false,
		knowledgeCutoffDate: "August 31, 2025",
		releaseDate: "March 5, 2026",
		lastUpdated: "March 5, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.015,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 1,
		speed: 4,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 27.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-5.5@eu", PROVIDER, {
		name: "GPT-5.5 (EU)",
		matchingModel: "gpt-5.5@eu",
		family: "gpt",
		openWeights: false,
		knowledgeCutoffDate: "December 1, 2025",
		releaseDate: "April 23, 2026",
		lastUpdated: "April 23, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.03,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 35.4,
			codingIndex: 56.5,
			agenticIndex: 25.8,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("gpt-5.6-luna@eu", PROVIDER, {
		name: "GPT-5.6 Luna (EU)",
		matchingModel: "gpt-5.6-luna@eu",
		family: "gpt-luna",
		openWeights: false,
		knowledgeCutoffDate: "February 16, 2026",
		releaseDate: "July 9, 2026",
		lastUpdated: "July 9, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00022,
		costPer1kOutputTokens: 0.00132,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.6-sol@eu", PROVIDER, {
		name: "GPT-5.6 Sol (EU)",
		matchingModel: "gpt-5.6-sol@eu",
		family: "gpt-sol",
		openWeights: false,
		knowledgeCutoffDate: "February 16, 2026",
		releaseDate: "July 9, 2026",
		lastUpdated: "July 9, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0055,
		costPer1kOutputTokens: 0.033,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5.6-terra@eu", PROVIDER, {
		name: "GPT-5.6 Terra (EU)",
		matchingModel: "gpt-5.6-terra@eu",
		family: "gpt-terra",
		openWeights: false,
		knowledgeCutoffDate: "February 16, 2026",
		releaseDate: "July 9, 2026",
		lastUpdated: "July 9, 2026",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1050000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0022,
		costPer1kOutputTokens: 0.0132,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("gpt-5@eu", PROVIDER, {
		name: "GPT-5 (EU)",
		matchingModel: "gpt-5@eu",
		family: "gpt",
		openWeights: false,
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.001375,
		costPer1kOutputTokens: 0.011,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 15.3,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),

	createModelConfig("grok-4.5", PROVIDER, {
		name: "Grok 4.5",
		matchingModel: "grok-4.5",
		family: "grok",
		openWeights: false,
		releaseDate: "July 8, 2026",
		lastUpdated: "July 8, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 500000,
		maxTokens: 500000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.006,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k3", PROVIDER, {
		name: "Kimi K3",
		matchingModel: "kimi-k3",
		family: "kimi-k3",
		openWeights: true,
		releaseDate: "July 16, 2026",
		lastUpdated: "July 16, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00225,
		costPer1kOutputTokens: 0.01125,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("kimi-k3@eu", PROVIDER, {
		name: "Kimi K3 (EU)",
		matchingModel: "kimi-k3@eu",
		family: "kimi-k3",
		openWeights: true,
		releaseDate: "July 16, 2026",
		lastUpdated: "July 16, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1048576,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00225,
		costPer1kOutputTokens: 0.01125,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("o4-mini@eu", PROVIDER, {
		name: "o4-mini (EU)",
		matchingModel: "o4-mini@eu",
		family: "o-mini",
		openWeights: false,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.00121,
		costPer1kOutputTokens: 0.00484,
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 25.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	}),
]);
