import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "requesty";

export const requestyModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("openai/gpt-4.1-mini", PROVIDER, {
		name: "GPT-4.1 Mini",
		matchingModel: "openai/gpt-4.1-mini",
		description:
			"Balanced version of GPT-4.1 with massive 1M+ token context window and lower cost.",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
		strengths: ["coding", "analysis", "instruction", "vision", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("openai/o4-mini", PROVIDER, {
		name: "o4 Mini",
		matchingModel: "openai/o4-mini",
		description:
			"Smaller model optimized for fast, cost-efficient reasoning with strong performance in math, coding, and visual tasks.",
		knowledgeCutoffDate: "June 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
		strengths: ["reasoning", "math", "coding", "analysis", "vision"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("openai/gpt-4o-mini", PROVIDER, {
		name: "GPT-4o Mini",
		matchingModel: "openai/gpt-4o-mini",
		description:
			"Efficient version of GPT-4o optimized for faster response times while maintaining core capabilities.",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: ["analysis", "chat", "coding", "multilingual", "vision"],
		contextComplexity: 3,
		reliability: 3,
		speed: 5,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("openai/gpt-4.1", PROVIDER, {
		name: "GPT-4.1",
		matchingModel: "openai/gpt-4.1",
		description:
			"OpenAI's advanced model optimized for coding and instruction-following with massive 1M+ token context window.",
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		strengths: ["coding", "academic", "reasoning", "instruction", "vision"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("anthropic/claude-4-sonnet-20250522", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "anthropic/claude-4-sonnet-20250522",
		description:
			"Claude's most advanced Sonnet model with enhanced reasoning capabilities and multimodal understanding.",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["reasoning", "analysis", "coding", "creative", "vision"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("anthropic/claude-3-7-sonnet", PROVIDER, {
		name: "Claude Sonnet 3.7",
		matchingModel: "anthropic/claude-3-7-sonnet",
		description:
			"Enhanced version of Claude 3.5 Sonnet with improved reasoning and analysis capabilities.",
		knowledgeCutoffDate: "January 2024",
		releaseDate: "February 19, 2025",
		lastUpdated: "February 19, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["reasoning", "analysis", "coding", "creative", "vision"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("anthropic/claude-opus-4-1-20250805", PROVIDER, {
		name: "Claude Opus 4.1",
		matchingModel: "anthropic/claude-opus-4-1-20250805",
		description:
			"Claude's most powerful model with exceptional reasoning, analysis, and creative capabilities.",
		knowledgeCutoffDate: "March 2025",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		strengths: ["reasoning", "analysis", "creative", "coding", "vision"],
		contextComplexity: 5,
		reliability: 5,
		speed: 2,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("anthropic/claude-opus-4", PROVIDER, {
		name: "Claude Opus 4",
		matchingModel: "anthropic/claude-opus-4",
		description:
			"Claude's flagship Opus model with exceptional performance across all domains.",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		strengths: ["reasoning", "analysis", "creative", "coding", "vision"],
		contextComplexity: 5,
		reliability: 5,
		speed: 2,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
	}),

	createModelConfig("google/gemini-2.5-flash", PROVIDER, {
		name: "Gemini 2.5 Flash",
		matchingModel: "google/gemini-2.5-flash",
		description:
			"Google's fast multimodal model with support for text, images, audio, video, and PDFs.",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		strengths: ["vision", "audio", "analysis", "reasoning", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 5,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsAudio: true,
	}),

	createModelConfig("google/gemini-2.5-pro", PROVIDER, {
		name: "Gemini 2.5 Pro",
		matchingModel: "google/gemini-2.5-pro",
		description:
			"Google's advanced multimodal model with extensive capabilities across text, images, audio, video, and PDFs.",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "June 17, 2025",
		lastUpdated: "June 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		strengths: [
			"vision",
			"audio",
			"analysis",
			"reasoning",
			"tool_use",
			"coding",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: false,
		includedInRouter: true,
		supportsArtifacts: true,
		supportsAudio: true,
	}),
	createModelConfig("anthropic/claude-haiku-4-5", PROVIDER, {
		name: "Claude Haiku 4.5",
		matchingModel: "anthropic/claude-haiku-4-5",
		knowledgeCutoffDate: "February 1, 2025",
		releaseDate: "October 15, 2025",
		lastUpdated: "October 15, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 62000,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.005,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("anthropic/claude-opus-4-1", PROVIDER, {
		name: "Claude Opus 4.1",
		matchingModel: "anthropic/claude-opus-4-1",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("anthropic/claude-opus-4-5", PROVIDER, {
		name: "Claude Opus 4.5",
		matchingModel: "anthropic/claude-opus-4-5",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "November 24, 2025",
		lastUpdated: "November 24, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("anthropic/claude-sonnet-4", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "anthropic/claude-sonnet-4",
		knowledgeCutoffDate: "March 31, 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("anthropic/claude-sonnet-4-5", PROVIDER, {
		name: "Claude Sonnet 4.5",
		matchingModel: "anthropic/claude-sonnet-4-5",
		knowledgeCutoffDate: "July 31, 2025",
		releaseDate: "September 29, 2025",
		lastUpdated: "September 29, 2025",
		modalities: {
			input: ["text", "image", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("google/gemini-3-flash-preview", PROVIDER, {
		name: "Gemini 3 Flash",
		matchingModel: "google/gemini-3-flash-preview",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "December 17, 2025",
		lastUpdated: "December 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("google/gemini-3-pro-preview", PROVIDER, {
		name: "Gemini 3 Pro",
		matchingModel: "google/gemini-3-pro-preview",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "November 18, 2025",
		lastUpdated: "November 18, 2025",
		modalities: {
			input: ["text", "image", "audio", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.012,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5", PROVIDER, {
		name: "GPT-5",
		matchingModel: "openai/gpt-5",
		knowledgeCutoffDate: "September 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "audio", "image", "video"],
			output: ["text", "audio", "image"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5-mini", PROVIDER, {
		name: "GPT-5 Mini",
		matchingModel: "openai/gpt-5-mini",
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("openai/gpt-5-nano", PROVIDER, {
		name: "GPT-5 Nano",
		matchingModel: "openai/gpt-5-nano",
		knowledgeCutoffDate: "May 30, 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: false,
		supportsToolCalls: true,
		contextWindow: 16000,
		maxTokens: 4000,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("xai/grok-4", PROVIDER, {
		name: "Grok 4",
		matchingModel: "xai/grok-4",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "September 9, 2025",
		lastUpdated: "September 9, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			enabled: true,
		},
	}),

	createModelConfig("xai/grok-4-fast", PROVIDER, {
		name: "Grok 4 Fast",
		matchingModel: "xai/grok-4-fast",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "September 19, 2025",
		lastUpdated: "September 19, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 2000000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			enabled: true,
		},
	}),
]);
