import type { ModelConfig } from "@assistant/schemas";

export const togetherAiModelConfig: ModelConfig = {
	"meta-llama/Llama-3.3-70B-Instruct-Turbo": {
		name: "Llama 3.3 70B",
		description:
			"The Meta Llama 3.3 multilingual large language model (LLM) is a pretrained and instruction tuned generative model in 70B (text in/text out). The Llama 3.3 instruction tuned text only model is optimized for multilingual dialogue use cases and outperform many of the available open source and closed chat models on common industry benchmarks.",
		matchingModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
		provider: "together-ai",
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kOutputTokens: 0.00104,
		costPer1kInputTokens: 0.00104,
		strengths: ["chat", "general_knowledge", "analysis", "creative", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		knowledgeCutoffDate: "December 2023",
		releaseDate: "December 6, 2024",
		lastUpdated: "July 2, 2026",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		family: "llama",
		openWeights: true,
	},
	"meta-llama/Llama-3.3-70B-Instruct-Turbo-Free": {
		name: "Meta Llama 3.3 70B Instruct Turbo Free",
		description:
			"The Meta Llama 3.3 multilingual large language model (LLM) is a pretrained and instruction tuned generative model in 70B (text in/text out). The Llama 3.3 instruction tuned text only model is optimized for multilingual dialogue use cases and outperform many of the available open source and closed chat models on common industry benchmarks.",
		matchingModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free",
		provider: "together-ai",
		contextWindow: 8192,
		maxTokens: 4096,
		isFree: true,
		strengths: ["chat", "general_knowledge", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 3,
		speed: 3,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo": {
		name: "Meta Llama 3.2 90B Vision Instruct Turbo",
		description:
			"Llama 3.2 is an auto-regressive language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.",
		matchingModel: "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo",
		provider: "together-ai",
		multimodal: true,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kOutputTokens: 0.0012,
		costPer1kInputTokens: 0.0012,
		strengths: ["vision", "analysis", "chat", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
	},
	"meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo": {
		name: "Meta Llama 3.2 11B Vision Instruct Turbo",
		description:
			"Llama 3.2 is an auto-regressive language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.",
		matchingModel: "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo",
		provider: "together-ai",
		multimodal: true,
		contextWindow: 32768,
		maxTokens: 4096,
		costPer1kOutputTokens: 0.00018,
		costPer1kInputTokens: 0.00018,
		strengths: ["vision", "chat", "general_knowledge"],
		contextComplexity: 3,
		reliability: 3,
		speed: 4,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
	},
	"meta-llama/Llama-Vision-Free": {
		name: "Meta Llama Vision Free",
		description:
			"Llama 3.2 is an auto-regressive language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.",
		matchingModel: "meta-llama/Llama-Vision-Free",
		provider: "together-ai",
		isFree: true,
		multimodal: true,
		contextWindow: 32768,
		maxTokens: 4096,
		strengths: ["vision", "chat"],
		contextComplexity: 3,
		reliability: 3,
		speed: 3,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
	},
	"meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo": {
		name: "Meta Llama 3.1 405B Instruct Turbo",
		description:
			"Llama 3.1 is an auto-regressive language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.",
		matchingModel: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
		provider: "together-ai",
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kOutputTokens: 0.0035,
		costPer1kInputTokens: 0.0035,
		strengths: ["chat", "general_knowledge", "analysis", "creative", "multilingual"],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		isFeatured: false,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
	},
	"deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free": {
		name: "DeepSeek R1 Distill Llama 70B Free",
		description:
			"DeepSeek-R1-Distill-Qwen-32B outperforms OpenAI-o1-mini across various benchmarks, achieving new state-of-the-art results for dense models.",
		matchingModel: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free",
		provider: "together-ai",
		isFree: true,
		contextWindow: 128000,
		maxTokens: 16384,
		strengths: ["reasoning", "analysis", "creative"],
		contextComplexity: 4,
		reliability: 3,
		speed: 3,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"llama-4-maverick-instruct": {
		name: "Llama 4 Maverick Instruct",
		description:
			"Llama 4 Maverick is a large language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.",
		matchingModel: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
		provider: "together-ai",
		strengths: ["chat", "general_knowledge", "analysis", "creative", "multilingual", "coding"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		contextWindow: 1000000,
		maxTokens: 16384,
		isFeatured: false,
		multimodal: true,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"Refuel-Llm-V2": {
		name: "Refuel LLM V2",
		matchingModel: "togethercomputer/Refuel-Llm-V2",
		description:
			"47B model optimized for data tasks such as classification, structured data extraction, and more.",
		contextWindow: 16000,
		provider: "together-ai",
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"Refuel-Llm-V2-Small": {
		name: "Refuel LLM V2 Small",
		matchingModel: "togethercomputer/Refuel-Llm-V2-Small",
		description:
			"8B model optimized for data tasks such as classification, structured data extraction, and more.",
		contextWindow: 8000,
		provider: "together-ai",
		contextComplexity: 3,
		reliability: 3,
		speed: 4,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"essentialai/Rnj-1-Instruct": {
		name: "Rnj-1 Instruct",
		matchingModel: "essentialai/Rnj-1-Instruct",
		provider: "together-ai",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "December 5, 2025",
		lastUpdated: "December 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.00015,
		family: "rnj",
		openWeights: true,
	},

	"moonshotai/Kimi-K2-Instruct": {
		name: "Kimi K2 Instruct",
		matchingModel: "moonshotai/Kimi-K2-Instruct",
		provider: "together-ai",
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 14, 2025",
		lastUpdated: "July 14, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.003,
	},

	"moonshotai/Kimi-K2-Instruct-0905": {
		name: "Kimi K2 Instruct-0905",
		matchingModel: "moonshotai/Kimi-K2-Instruct-0905",
		provider: "together-ai",
		knowledgeCutoffDate: "September 2025",
		releaseDate: "September 5, 2025",
		lastUpdated: "September 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.003,
	},

	"moonshotai/Kimi-K2-Thinking": {
		name: "Kimi K2 Thinking",
		matchingModel: "moonshotai/Kimi-K2-Thinking",
		provider: "together-ai",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "November 6, 2025",
		lastUpdated: "November 6, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0012,
		costPer1kOutputTokens: 0.004,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 32.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"openai/gpt-oss-120b": {
		name: "GPT OSS 120B",
		matchingModel: "openai/gpt-oss-120b",
		provider: "together-ai",
		knowledgeCutoffDate: "August 2025",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 23.8,
			codingIndex: 30.4,
			agenticIndex: 13.2,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-oss",
		openWeights: true,
	},

	"Qwen/Qwen3-235B-A22B-Instruct-2507-tput": {
		name: "Qwen3 235B A22B Instruct 2507 FP8",
		matchingModel: "Qwen/Qwen3-235B-A22B-Instruct-2507-tput",
		provider: "together-ai",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "July 25, 2025",
		lastUpdated: "July 25, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0006,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "qwen",
		openWeights: true,
	},

	"Qwen/Qwen3-Next-80B-A3B-Instruct": {
		name: "Qwen3-Next-80B-A3B-Instruct",
		matchingModel: "Qwen/Qwen3-Next-80B-A3B-Instruct",
		provider: "together-ai",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "July 25, 2025",
		lastUpdated: "July 25, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 262144,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0015,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 13.7,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"zai-org/GLM-4.6": {
		name: "GLM 4.6",
		matchingModel: "zai-org/GLM-4.6",
		provider: "together-ai",
		knowledgeCutoffDate: "September 2025",
		releaseDate: "September 30, 2025",
		lastUpdated: "September 30, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 23,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},

	"zai-org/GLM-4.7": {
		name: "GLM-4.7",
		matchingModel: "zai-org/GLM-4.7",
		provider: "together-ai",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "July 25, 2025",
		lastUpdated: "July 25, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 200000,
		costPer1kInputTokens: 0.00045,
		costPer1kOutputTokens: 0.002,
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 26.6,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
	},
	"deepseek-ai/DeepSeek-V4-Pro": {
		name: "DeepSeek V4 Pro",
		matchingModel: "deepseek-ai/DeepSeek-V4-Pro",
		provider: "together-ai",
		releaseDate: "April 24, 2026",
		lastUpdated: "April 24, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 512000,
		maxTokens: 384000,
		costPer1kInputTokens: 0.00174,
		costPer1kOutputTokens: 0.00348,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 31.2,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "deepseek",
		openWeights: true,
	},

	"google/gemma-4-31B-it": {
		name: "Gemma 4 31B Instruct",
		matchingModel: "google/gemma-4-31B-it",
		provider: "together-ai",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "April 7, 2026",
		lastUpdated: "April 7, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00039,
		costPer1kOutputTokens: 0.00097,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		supportsResponseFormat: true,
		family: "gemma",
		openWeights: true,
	},

	"MiniMaxAI/MiniMax-M2.7": {
		name: "MiniMax-M2.7",
		matchingModel: "MiniMaxAI/MiniMax-M2.7",
		provider: "together-ai",
		releaseDate: "March 18, 2026",
		lastUpdated: "March 18, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 38.1,
			codingIndex: 52.6,
			agenticIndex: 25.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
	},

	"moonshotai/Kimi-K2.6": {
		name: "Kimi K2.6",
		matchingModel: "moonshotai/Kimi-K2.6",
		provider: "together-ai",
		knowledgeCutoffDate: "January 2025",
		releaseDate: "April 21, 2026",
		lastUpdated: "April 21, 2026",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 131000,
		costPer1kInputTokens: 0.0012,
		costPer1kOutputTokens: 0.0045,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "video", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 42.8,
			codingIndex: 56,
			agenticIndex: 30.3,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-k2",
		openWeights: true,
	},

	"Qwen/Qwen3.5-397B-A17B": {
		name: "Qwen3.5 397B A17B",
		matchingModel: "Qwen/Qwen3.5-397B-A17B",
		provider: "together-ai",
		releaseDate: "February 16, 2026",
		lastUpdated: "June 15, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 130000,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0036,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 2,
		artificialAnalysis: {
			intelligenceIndex: 32,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
	},

	"Qwen/Qwen3.6-Plus": {
		name: "Qwen3.6 Plus",
		matchingModel: "Qwen/Qwen3.6-Plus",
		provider: "together-ai",
		releaseDate: "April 30, 2026",
		lastUpdated: "April 30, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 500000,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.003,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 39.6,
			codingIndex: 54.5,
			agenticIndex: 27.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
	},

	"zai-org/GLM-5.1": {
		name: "GLM-5.1",
		matchingModel: "zai-org/GLM-5.1",
		provider: "together-ai",
		knowledgeCutoffDate: "November 2025",
		releaseDate: "April 7, 2026",
		lastUpdated: "July 2, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 35.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	},
	"Qwen/Qwen3.7-Max": {
		name: "Qwen3.7 Max",
		matchingModel: "Qwen/Qwen3.7-Max",
		provider: "together-ai",
		releaseDate: "May 21, 2026",
		lastUpdated: "July 2, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 1000000,
		maxTokens: 500000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.00375,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "tool_use"],
		contextComplexity: 5,
		reliability: 2,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 46,
			codingIndex: 66,
			agenticIndex: 30.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: false,
	},
	"nvidia/nemotron-3-ultra-550b-a55b": {
		name: "Nemotron 3 Ultra 550B A55B",
		matchingModel: "nvidia/nemotron-3-ultra-550b-a55b",
		provider: "together-ai",
		releaseDate: "June 4, 2026",
		lastUpdated: "June 4, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 512300,
		maxTokens: 512300,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0036,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 37.8,
			codingIndex: 49.3,
			agenticIndex: 27.4,
			intelligenceIndexVersion: 4.1,
		},
		family: "nemotron",
		openWeights: true,
	},
	"deepcogito/cogito-v2-1-671b": {
		name: "Cogito v2.1 671B",
		matchingModel: "deepcogito/cogito-v2-1-671b",
		provider: "together-ai",
		releaseDate: "November 13, 2025",
		lastUpdated: "November 13, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.00125,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "cogito",
		openWeights: false,
	},

	"google/gemma-3n-E4B-it": {
		name: "Gemma 3N E4B Instruct",
		matchingModel: "google/gemma-3n-E4B-it",
		provider: "together-ai",
		releaseDate: "May 20, 2025",
		lastUpdated: "May 20, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		supportsResponseFormat: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00006,
		costPer1kOutputTokens: 0.00012,
		contextComplexity: 3,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 1.2,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "gemma",
		openWeights: true,
	},

	"LiquidAI/LFM2-24B-A2B": {
		name: "LFM2-24B-A2B",
		matchingModel: "LiquidAI/LFM2-24B-A2B",
		provider: "together-ai",
		releaseDate: "February 25, 2026",
		lastUpdated: "February 25, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00003,
		costPer1kOutputTokens: 0.00012,
		contextComplexity: 3,
		reliability: 1,
		speed: 4,
		artificialAnalysis: {
			intelligenceIndex: 4.9,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "liquid",
		openWeights: true,
	},

	"meta-llama/Meta-Llama-3-8B-Instruct-Lite": {
		name: "Meta Llama 3 8B Instruct Lite",
		matchingModel: "meta-llama/Meta-Llama-3-8B-Instruct-Lite",
		provider: "together-ai",
		releaseDate: "April 18, 2024",
		lastUpdated: "April 18, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 8192,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00014,
		costPer1kOutputTokens: 0.00014,
		family: "llama",
		openWeights: true,
	},

	"openai/gpt-oss-20b": {
		name: "GPT OSS 20B",
		matchingModel: "openai/gpt-oss-20b",
		provider: "together-ai",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0002,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 5,
		artificialAnalysis: {
			intelligenceIndex: 14.9,
			codingIndex: 20.7,
			agenticIndex: 3.1,
			intelligenceIndexVersion: 4.1,
		},
		family: "gpt-oss",
		openWeights: true,
	},

	"pearl-ai/gemma-4-31b-it": {
		name: "Pearl AI Gemma 4 31B Instruct",
		matchingModel: "pearl-ai/gemma-4-31b-it",
		provider: "together-ai",
		releaseDate: "April 7, 2026",
		lastUpdated: "April 7, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.00028,
		costPer1kOutputTokens: 0.00086,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		family: "gemma",
		openWeights: false,
	},

	"Qwen/Qwen2.5-7B-Instruct-Turbo": {
		name: "Qwen 2.5 7B Instruct Turbo",
		matchingModel: "Qwen/Qwen2.5-7B-Instruct-Turbo",
		provider: "together-ai",
		releaseDate: "September 19, 2024",
		lastUpdated: "September 19, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0003,
		family: "qwen",
		openWeights: true,
	},

	"Qwen/Qwen3.5-9B": {
		name: "Qwen3.5 9B",
		matchingModel: "Qwen/Qwen3.5-9B",
		provider: "together-ai",
		releaseDate: "March 3, 2026",
		lastUpdated: "March 3, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00017,
		costPer1kOutputTokens: 0.00025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 1,
		artificialAnalysis: {
			intelligenceIndex: 20.3,
			codingIndex: 23.5,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "qwen",
		openWeights: true,
	},

	"zai-org/GLM-5": {
		name: "GLM-5",
		matchingModel: "zai-org/GLM-5",
		provider: "together-ai",
		releaseDate: "February 11, 2026",
		lastUpdated: "February 11, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 202752,
		maxTokens: 131072,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.0032,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["tool_use"],
		contextComplexity: 4,
		reliability: 1,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 32.4,
			codingIndex: null,
			agenticIndex: null,
			intelligenceIndexVersion: 4.1,
		},
		family: "glm",
		openWeights: true,
	},
	"MiniMaxAI/MiniMax-M3": {
		name: "MiniMax-M3",
		matchingModel: "MiniMaxAI/MiniMax-M3",
		provider: "together-ai",
		releaseDate: "June 12, 2026",
		lastUpdated: "June 12, 2026",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 524288,
		maxTokens: 250000,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0012,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["vision", "document", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 44.4,
			codingIndex: 58.6,
			agenticIndex: 35.4,
			intelligenceIndexVersion: 4.1,
		},
		family: "minimax",
		openWeights: true,
	},
	"moonshotai/Kimi-K2.7-Code": {
		name: "Kimi K2.7 Code",
		matchingModel: "moonshotai/Kimi-K2.7-Code",
		provider: "together-ai",
		releaseDate: "June 14, 2026",
		lastUpdated: "June 14, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		strengths: ["coding", "tool_use"],
		contextComplexity: 4,
		reliability: 2,
		speed: 3,
		artificialAnalysis: {
			intelligenceIndex: 41.9,
			codingIndex: 60.8,
			agenticIndex: 29.6,
			intelligenceIndexVersion: 4.1,
		},
		family: "kimi-k2",
		openWeights: true,
	},
	"zai-org/GLM-5.2": {
		name: "GLM-5.2",
		matchingModel: "zai-org/GLM-5.2",
		provider: "together-ai",
		family: "glm",
		openWeights: true,
		releaseDate: "June 16, 2026",
		lastUpdated: "June 16, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 262144,
		maxTokens: 164000,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		strengths: ["coding", "tool_use"],
		contextComplexity: 4,
		reliability: 3,
		speed: 4,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
		artificialAnalysis: {
			intelligenceIndex: 51.1,
			codingIndex: 68.8,
			agenticIndex: 43.1,
			intelligenceIndexVersion: 4.1,
		},
	},
	"thinkingmachines/Inkling": {
		name: "Inkling",
		matchingModel: "thinkingmachines/Inkling",
		provider: "together-ai",
		family: "ling",
		openWeights: true,
		releaseDate: "July 15, 2026",
		lastUpdated: "July 15, 2026",
		modalities: {
			input: ["text", "image", "audio"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 524288,
		maxTokens: 131072,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.00405,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	},
};
