import type { ModelConfig } from "~/types";

export const togetherAiModelConfig: ModelConfig = {
	"meta-llama/Llama-3.3-70B-Instruct-Turbo": {
		name: "Meta Llama 3.3 70B Instruct Turbo",
		description:
			"The Meta Llama 3.3 multilingual large language model (LLM) is a pretrained and instruction tuned generative model in 70B (text in/text out). The Llama 3.3 instruction tuned text only model is optimized for multilingual dialogue use cases and outperform many of the available open source and closed chat models on common industry benchmarks.",
		matchingModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
		provider: "together-ai",
		contextWindow: 8192,
		maxTokens: 4096,
		costPer1kOutputTokens: 0.00088,
		costPer1kInputTokens: 0.00088,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"creative",
			"multilingual",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"meta-llama/Llama-3.3-70B-Instruct-Turbo-Free": {
		name: "Meta Llama 3.3 70B Instruct Turbo Free",
		description:
			"The Meta Llama 3.3 multilingual large language model (LLM) is a pretrained and instruction tuned generative model in 70B (text in/text out). The Llama 3.3 instruction tuned text only model is optimized for multilingual dialogue use cases and outperform many of the available open source and closed chat models on common industry benchmarks.",
		matchingModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free",
		provider: "together-ai",
		contextWindow: 8192,
		maxTokens: 4096,
		isFree: true,
		strengths: ["chat", "general_knowledge", "analysis", "multilingual"],
		contextComplexity: 4,
		reliability: 3,
		speed: 3,
		includedInRouter: true,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo": {
		name: "Meta Llama 3.2 90B Vision Instruct Turbo",
		description:
			"Llama 3.2 is an auto-regressive language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.",
		matchingModel: "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo",
		provider: "together-ai",
		multimodal: true,
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kOutputTokens: 0.0012,
		costPer1kInputTokens: 0.0012,
		strengths: ["vision", "analysis", "chat", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
	},
	"meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo": {
		name: "Meta Llama 3.2 11B Vision Instruct Turbo",
		description:
			"Llama 3.2 is an auto-regressive language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.",
		matchingModel: "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo",
		provider: "together-ai",
		multimodal: true,
		contextWindow: 32768,
		maxTokens: 4096,
		costPer1kOutputTokens: 0.00018,
		costPer1kInputTokens: 0.00018,
		strengths: ["vision", "chat", "general_knowledge"],
		contextComplexity: 3,
		reliability: 3,
		speed: 4,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
	},
	"meta-llama/Llama-Vision-Free": {
		name: "Meta Llama Vision Free",
		description:
			"Llama 3.2 is an auto-regressive language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.",
		matchingModel: "meta-llama/Llama-Vision-Free",
		provider: "together-ai",
		isFree: true,
		multimodal: true,
		contextWindow: 32768,
		maxTokens: 4096,
		strengths: ["vision", "chat"],
		contextComplexity: 3,
		reliability: 3,
		speed: 3,
		includedInRouter: true,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
	},
	"meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo": {
		name: "Meta Llama 3.1 405B Instruct Turbo",
		description:
			"Llama 3.1 is an auto-regressive language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.",
		matchingModel: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
		provider: "together-ai",
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kOutputTokens: 0.0035,
		costPer1kInputTokens: 0.0035,
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"creative",
			"multilingual",
		],
		contextComplexity: 5,
		reliability: 5,
		speed: 4,
		isFeatured: true,
		includedInRouter: true,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
	},
	"deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free": {
		name: "DeepSeek R1 Distill Llama 70B Free",
		description:
			"DeepSeek-R1-Distill-Qwen-32B outperforms OpenAI-o1-mini across various benchmarks, achieving new state-of-the-art results for dense models.",
		matchingModel: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free",
		provider: "together-ai",
		isFree: true,
		contextWindow: 128000,
		maxTokens: 16384,
		strengths: ["reasoning", "analysis", "creative"],
		contextComplexity: 4,
		reliability: 3,
		speed: 3,
		includedInRouter: true,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"llama-4-maverick-instruct": {
		name: "Llama 4 Maverick Instruct",
		description:
			"Llama 4 Maverick is a large language model that uses an optimized transformer architecture. The tuned versions use supervised fine-tuning (SFT) and reinforcement learning with human feedback (RLHF) to align with human preferences for helpfulness and safety.",
		matchingModel: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
		provider: "together-ai",
		strengths: [
			"chat",
			"general_knowledge",
			"analysis",
			"creative",
			"multilingual",
			"coding",
		],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		contextWindow: 1000000,
		maxTokens: 16384,
		isFeatured: true,
		includedInRouter: true,
		multimodal: true,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"Refuel-Llm-V2": {
		name: "Refuel LLM V2",
		matchingModel: "togethercomputer/Refuel-Llm-V2",
		description:
			"47B model optimized for data tasks such as classification, structured data extraction, and more.",
		contextWindow: 16000,
		provider: "together-ai",
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"Refuel-Llm-V2-Small": {
		name: "Refuel LLM V2 Small",
		matchingModel: "togethercomputer/Refuel-Llm-V2-Small",
		description:
			"8B model optimized for data tasks such as classification, structured data extraction, and more.",
		contextWindow: 8000,
		provider: "together-ai",
		contextComplexity: 3,
		reliability: 3,
		speed: 4,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
};
