import type { ModelConfig } from "~/types";

export const v0ModelConfig: ModelConfig = {
	"v0-1.0-md": {
		name: "v0-1.0-md",
		description:
			"The v0 model is designed for building modern web applications with text and image inputs and optimized for frontend and full stack web development.",
		matchingModel: "v0-1.0-md",
		provider: "v0",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["coding", "analysis", "vision"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: true,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"v0-1.5-md": {
		name: "v0-1.5-md",
		description:
			"Enhanced v0 model with improved capabilities for building modern web applications with better understanding of design patterns and frameworks.",
		matchingModel: "v0-1.5-md",
		provider: "v0",
		releaseDate: "June 9, 2025",
		lastUpdated: "June 9, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["coding", "analysis", "vision", "creative"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		isFeatured: true,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"v0-1.5-lg": {
		name: "v0-1.5-lg",
		description:
			"Large v0 model with extensive context window and advanced capabilities for complex web application development and comprehensive code generation.",
		matchingModel: "v0-1.5-lg",
		provider: "v0",
		releaseDate: "June 9, 2025",
		lastUpdated: "June 9, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 512000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		strengths: ["coding", "analysis", "vision", "reasoning", "creative"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: true,
		includedInRouter: false,
		supportsArtifacts: true,
	},
};
