import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "vercel";

export const vercelModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("openai/o3", PROVIDER, {
		name: "o3",
		matchingModel: "openai/o3",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
	}),

	createModelConfig("openai/gpt-4o", PROVIDER, {
		name: "GPT-4o",
		matchingModel: "openai/gpt-4o",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "May 13, 2024",
		lastUpdated: "May 13, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0025,
		costPer1kOutputTokens: 0.01,
	}),

	createModelConfig("openai/gpt-5-mini", PROVIDER, {
		name: "GPT-5 Mini",
		matchingModel: "openai/gpt-5-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
	}),

	createModelConfig("openai/gpt-4.1", PROVIDER, {
		name: "GPT-4.1",
		matchingModel: "openai/gpt-4.1",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
	}),

	createModelConfig("openai/gpt-5", PROVIDER, {
		name: "GPT-5",
		matchingModel: "openai/gpt-5",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
	}),

	createModelConfig("openai/o1", PROVIDER, {
		name: "o1",
		matchingModel: "openai/o1",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "December 5, 2024",
		lastUpdated: "December 5, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.06,
	}),

	createModelConfig("openai/o3-mini", PROVIDER, {
		name: "o3-mini",
		matchingModel: "openai/o3-mini",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "December 20, 2024",
		lastUpdated: "January 29, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
	}),

	createModelConfig("openai/gpt-4-turbo", PROVIDER, {
		name: "GPT-4 Turbo",
		matchingModel: "openai/gpt-4-turbo",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "December 2023",
		releaseDate: "November 6, 2023",
		lastUpdated: "April 9, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.01,
		costPer1kOutputTokens: 0.03,
	}),

	createModelConfig("openai/gpt-4o-mini", PROVIDER, {
		name: "GPT-4o mini",
		matchingModel: "openai/gpt-4o-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2023",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
	}),

	createModelConfig("openai/gpt-4.1-nano", PROVIDER, {
		name: "GPT-4.1 nano",
		matchingModel: "openai/gpt-4.1-nano",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0004,
	}),

	createModelConfig("openai/gpt-5-nano", PROVIDER, {
		name: "GPT-5 Nano",
		matchingModel: "openai/gpt-5-nano",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0004,
	}),

	createModelConfig("openai/o4-mini", PROVIDER, {
		name: "o4-mini",
		matchingModel: "openai/o4-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: false,
		supportsToolCalls: true,
		knowledgeCutoffDate: "May 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
	}),

	createModelConfig("openai/gpt-4.1-mini", PROVIDER, {
		name: "GPT-4.1 mini",
		matchingModel: "openai/gpt-4.1-mini",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
	}),

	createModelConfig("deepseek/deepseek-r1-distill-llama-70b", PROVIDER, {
		name: "DeepSeek R1 Distill Llama 70B",
		matchingModel: "deepseek/deepseek-r1-distill-llama-70b",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "July 2024",
		releaseDate: "January 20, 2025",
		lastUpdated: "January 20, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00075,
		costPer1kOutputTokens: 0.00099,
	}),

	createModelConfig("deepseek/deepseek-r1", PROVIDER, {
		name: "DeepSeek-R1",
		matchingModel: "deepseek/deepseek-r1",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "July 2024",
		releaseDate: "January 20, 2025",
		lastUpdated: "May 29, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00135,
		costPer1kOutputTokens: 0.0054,
	}),

	createModelConfig("anthropic/claude-4-1-opus", PROVIDER, {
		name: "Claude Opus 4",
		matchingModel: "anthropic/claude-4-1-opus",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
	}),

	createModelConfig("anthropic/claude-3-opus", PROVIDER, {
		name: "Claude Opus 3",
		matchingModel: "anthropic/claude-3-opus",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "August 2023",
		releaseDate: "February 29, 2024",
		lastUpdated: "February 29, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
	}),

	createModelConfig("anthropic/claude-3-haiku", PROVIDER, {
		name: "Claude Haiku 3",
		matchingModel: "anthropic/claude-3-haiku",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "August 2023",
		releaseDate: "March 13, 2024",
		lastUpdated: "March 13, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.00125,
	}),

	createModelConfig("anthropic/claude-3.7-sonnet", PROVIDER, {
		name: "Claude Sonnet 3.7",
		matchingModel: "anthropic/claude-3.7-sonnet",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "February 19, 2025",
		lastUpdated: "February 19, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
	}),

	createModelConfig("anthropic/claude-3-5-haiku", PROVIDER, {
		name: "Claude Haiku 3.5",
		matchingModel: "anthropic/claude-3-5-haiku",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "July 2024",
		releaseDate: "October 22, 2024",
		lastUpdated: "October 22, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0008,
		costPer1kOutputTokens: 0.004,
	}),

	createModelConfig("anthropic/claude-4-sonnet", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "anthropic/claude-4-sonnet",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
	}),

	createModelConfig("anthropic/claude-3.5-sonnet", PROVIDER, {
		name: "Claude Sonnet 3.5 v2",
		matchingModel: "anthropic/claude-3.5-sonnet",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "October 22, 2024",
		lastUpdated: "October 22, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
	}),

	createModelConfig("anthropic/claude-4-opus", PROVIDER, {
		name: "Claude Opus 4",
		matchingModel: "anthropic/claude-4-opus",
		supportsAttachments: true,
		reasoningConfig: { enabled: true },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
	}),

	createModelConfig("amazon/nova-micro", PROVIDER, {
		name: "Nova Micro",
		matchingModel: "amazon/nova-micro",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "December 3, 2024",
		lastUpdated: "December 3, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.000035,
		costPer1kOutputTokens: 0.00014,
	}),

	createModelConfig("amazon/nova-pro", PROVIDER, {
		name: "Nova Pro",
		matchingModel: "amazon/nova-pro",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "December 3, 2024",
		lastUpdated: "December 3, 2024",
		modalities: { input: ["text", "image", "video"], output: ["text"] },
		contextWindow: 300000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0008,
		costPer1kOutputTokens: 0.0032,
	}),

	createModelConfig("amazon/nova-lite", PROVIDER, {
		name: "Nova Lite",
		matchingModel: "amazon/nova-lite",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "December 3, 2024",
		lastUpdated: "December 3, 2024",
		modalities: { input: ["text", "image", "video"], output: ["text"] },
		contextWindow: 300000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.00006,
		costPer1kOutputTokens: 0.00024,
	}),

	createModelConfig("mistral/ministral-8b", PROVIDER, {
		name: "Ministral 8B",
		matchingModel: "mistral/ministral-8b",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "October 1, 2024",
		lastUpdated: "October 4, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0001,
	}),

	createModelConfig("mistral/magistral-medium", PROVIDER, {
		name: "Magistral Medium",
		matchingModel: "mistral/magistral-medium",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "June 2025",
		releaseDate: "March 17, 2025",
		lastUpdated: "March 20, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.005,
	}),

	createModelConfig("mistral/codestral", PROVIDER, {
		name: "Codestral",
		matchingModel: "mistral/codestral",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "May 29, 2024",
		lastUpdated: "January 4, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 256000,
		maxTokens: 4096,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0009,
	}),

	createModelConfig("mistral/pixtral-large", PROVIDER, {
		name: "Pixtral Large",
		matchingModel: "mistral/pixtral-large",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "November 2024",
		releaseDate: "November 1, 2024",
		lastUpdated: "November 4, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.006,
	}),

	createModelConfig("mistral/pixtral-12b", PROVIDER, {
		name: "Pixtral 12B",
		matchingModel: "mistral/pixtral-12b",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "September 2024",
		releaseDate: "September 1, 2024",
		lastUpdated: "September 1, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.00015,
	}),

	createModelConfig("mistral/ministral-3b", PROVIDER, {
		name: "Ministral 3B",
		matchingModel: "mistral/ministral-3b",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "October 1, 2024",
		lastUpdated: "October 4, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00004,
		costPer1kOutputTokens: 0.00004,
	}),

	createModelConfig("mistral/mistral-small", PROVIDER, {
		name: "Mistral Small",
		matchingModel: "mistral/mistral-small",
		supportsAttachments: true,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "March 2025",
		releaseDate: "September 1, 2024",
		lastUpdated: "September 4, 2024",
		modalities: { input: ["text", "image"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0003,
	}),

	createModelConfig("mistral/mixtral-8x22b-instruct", PROVIDER, {
		name: "Mixtral 8x22B",
		matchingModel: "mistral/mixtral-8x22b-instruct",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 17, 2024",
		lastUpdated: "April 17, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 64000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.006,
	}),

	createModelConfig("mistral/magistral-small", PROVIDER, {
		name: "Magistral Small",
		matchingModel: "mistral/magistral-small",
		supportsAttachments: false,
		reasoningConfig: { enabled: true },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "June 2025",
		releaseDate: "March 17, 2025",
		lastUpdated: "March 17, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.0015,
	}),

	createModelConfig("mistral/mistral-large", PROVIDER, {
		name: "Mistral Large",
		matchingModel: "mistral/mistral-large",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "November 2024",
		releaseDate: "November 1, 2024",
		lastUpdated: "November 4, 2024",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.006,
	}),

	createModelConfig("moonshotai/kimi-k2", PROVIDER, {
		name: "Kimi K2 Instruct",
		matchingModel: "moonshotai/kimi-k2",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 14, 2025",
		lastUpdated: "July 14, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 131072,
		maxTokens: 16384,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.003,
	}),

	createModelConfig("cerebras/qwen3-coder", PROVIDER, {
		name: "Qwen 3 Coder 480B",
		matchingModel: "cerebras/qwen3-coder",
		supportsAttachments: false,
		reasoningConfig: { enabled: false },
		supportsTemperature: true,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: { input: ["text"], output: ["text"] },
		contextWindow: 131000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.002,
	}),
]);
