import type { ModelConfig } from "~/types";

export const xaiModelConfig: ModelConfig = {
	"grok-3-mini-fast-latest": {
		name: "Grok 3 Mini Fast Latest",
		matchingModel: "grok-3-mini-fast-latest",
		provider: "grok",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.004,
		strengths: ["reasoning", "analysis", "chat"],
		contextComplexity: 3,
		reliability: 4,
		speed: 5,
		includedInRouter: true,
		supportsArtifacts: true,
		costPer1kReasoningTokens: 0.004,
	},

	"grok-2-vision-latest": {
		name: "Grok 2 Vision Latest",
		matchingModel: "grok-2-vision-latest",
		provider: "grok",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "August 20, 2024",
		lastUpdated: "December 12, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 8192,
		maxTokens: 4096,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.01,
		strengths: ["vision", "analysis", "chat"],
		contextComplexity: 3,
		reliability: 4,
		speed: 4,
		multimodal: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"grok-2-latest": {
		name: "Grok 2 Latest",
		matchingModel: "grok-2-latest",
		provider: "grok",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "August 20, 2024",
		lastUpdated: "December 12, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.01,
		strengths: ["reasoning", "analysis", "chat", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"grok-3-mini": {
		name: "Grok 3 Mini",
		matchingModel: "grok-3-mini",
		description:
			"A lightweight model that thinks before responding. Fast, smart, and great for logic-based tasks that do not require deep domain knowledge.",
		provider: "grok",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0005,
		strengths: ["reasoning", "analysis", "chat"],
		contextComplexity: 3,
		reliability: 4,
		speed: 4,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
		costPer1kReasoningTokens: 0.0005,
	},

	"grok-3-fast-latest": {
		name: "Grok 3 Fast Latest",
		matchingModel: "grok-3-fast-latest",
		provider: "grok",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		strengths: ["reasoning", "analysis", "chat", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		speed: 5,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"grok-3": {
		name: "Grok 3",
		matchingModel: "grok-3",
		description:
			"Excels at enterprise use cases like data extraction, coding, and text summarization. Possesses deep domain knowledge in finance, healthcare, law, and science.",
		provider: "grok",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["reasoning", "analysis", "chat", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		isFeatured: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"grok-3-mini-latest": {
		name: "Grok 3 Mini Latest",
		matchingModel: "grok-3-mini-latest",
		provider: "grok",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0005,
		strengths: ["reasoning", "analysis", "chat"],
		contextComplexity: 3,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
		costPer1kReasoningTokens: 0.0005,
	},

	"grok-3-mini-fast": {
		name: "Grok 3 Mini Fast",
		matchingModel: "grok-3-mini-fast",
		provider: "grok",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.004,
		strengths: ["reasoning", "analysis", "chat"],
		contextComplexity: 3,
		reliability: 4,
		speed: 5,
		includedInRouter: true,
		supportsArtifacts: true,
		costPer1kReasoningTokens: 0.004,
	},

	"grok-3-latest": {
		name: "Grok 3 Latest",
		matchingModel: "grok-3-latest",
		provider: "grok",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["reasoning", "analysis", "chat", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"grok-4": {
		name: "Grok 4",
		matchingModel: "grok-4",
		description:
			"Flagship Grok model with 256k context window, advanced reasoning, structured outputs, and function calling. Excels at natural language, math, and logic.",
		provider: "grok",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "July 9, 2025",
		lastUpdated: "July 9, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: true },
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["reasoning", "analysis", "math", "coding"],
		contextComplexity: 5,
		reliability: 5,
		speed: 2,
		isFeatured: true,
		includedInRouter: false,
		supportsArtifacts: true,
		supportsPresencePenalty: false,
		costPer1kReasoningTokens: 0.015,
	},

	"grok-vision-beta": {
		name: "Grok Vision Beta",
		matchingModel: "grok-vision-beta",
		provider: "grok",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "November 1, 2024",
		lastUpdated: "November 1, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 8192,
		maxTokens: 4096,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.015,
		strengths: ["vision", "analysis", "chat"],
		contextComplexity: 3,
		reliability: 3,
		speed: 3,
		multimodal: true,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"grok-2": {
		name: "Grok 2",
		matchingModel: "grok-2",
		provider: "grok",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "August 20, 2024",
		lastUpdated: "August 20, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.01,
		strengths: ["reasoning", "analysis", "chat", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"grok-3-fast": {
		name: "Grok 3 Fast",
		matchingModel: "grok-3-fast",
		provider: "grok",
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		reasoningConfig: { enabled: false },
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.025,
		strengths: ["reasoning", "analysis", "chat", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		speed: 5,
		includedInRouter: false,
		supportsArtifacts: true,
	},
	"grok-2-1212": {
		name: "Grok 2 (1212)",
		matchingModel: "grok-2-1212",
		provider: "grok",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "December 12, 2024",
		lastUpdated: "December 12, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: false,
		},
	},

	"grok-2-vision": {
		name: "Grok 2 Vision",
		matchingModel: "grok-2-vision",
		provider: "grok",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "August 20, 2024",
		lastUpdated: "August 20, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 8192,
		maxTokens: 4096,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: false,
		},
	},

	"grok-2-vision-1212": {
		name: "Grok 2 Vision (1212)",
		matchingModel: "grok-2-vision-1212",
		provider: "grok",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "August 20, 2024",
		lastUpdated: "December 12, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 8192,
		maxTokens: 4096,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.01,
		reasoningConfig: {
			enabled: false,
		},
	},

	"grok-4-1-fast": {
		name: "Grok 4.1 Fast",
		matchingModel: "grok-4-1-fast",
		provider: "grok",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "November 19, 2025",
		lastUpdated: "November 19, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 2000000,
		maxTokens: 30000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			enabled: true,
		},
	},

	"grok-4-1-fast-non-reasoning": {
		name: "Grok 4.1 Fast (Non-Reasoning)",
		matchingModel: "grok-4-1-fast-non-reasoning",
		provider: "grok",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "November 19, 2025",
		lastUpdated: "November 19, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 2000000,
		maxTokens: 30000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			enabled: false,
		},
	},

	"grok-4-fast": {
		name: "Grok 4 Fast",
		matchingModel: "grok-4-fast",
		provider: "grok",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "September 19, 2025",
		lastUpdated: "September 19, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 2000000,
		maxTokens: 30000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			enabled: true,
		},
	},

	"grok-4-fast-non-reasoning": {
		name: "Grok 4 Fast (Non-Reasoning)",
		matchingModel: "grok-4-fast-non-reasoning",
		provider: "grok",
		knowledgeCutoffDate: "July 2025",
		releaseDate: "September 19, 2025",
		lastUpdated: "September 19, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 2000000,
		maxTokens: 30000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0005,
		reasoningConfig: {
			enabled: false,
		},
	},

	"grok-beta": {
		name: "Grok Beta",
		matchingModel: "grok-beta",
		provider: "grok",
		knowledgeCutoffDate: "August 2024",
		releaseDate: "November 1, 2024",
		lastUpdated: "November 1, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 4096,
		costPer1kInputTokens: 0.005,
		costPer1kOutputTokens: 0.015,
		reasoningConfig: {
			enabled: false,
		},
	},

	"grok-code-fast-1": {
		name: "Grok Code Fast 1",
		matchingModel: "grok-code-fast-1",
		provider: "grok",
		knowledgeCutoffDate: "October 2023",
		releaseDate: "August 28, 2025",
		lastUpdated: "August 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 256000,
		maxTokens: 10000,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0015,
		reasoningConfig: {
			enabled: true,
		},
	},
};
