import type { ModelConfig } from "@ngriffin_uk/polychat-schemas";

import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "zai";

export const zaiModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("glm-4.7", PROVIDER, {
		name: "GLM 4.7",
		matchingModel: "glm-4.7",
		family: "glm",
		openWeights: true,
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["coding", "reasoning", "agents", "tool_use"],
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 22, 2025",
		lastUpdated: "December 22, 2025",
		supportsAttachments: false,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("glm-5", PROVIDER, {
		name: "GLM 5",
		matchingModel: "glm-5",
		family: "glm",
		openWeights: true,
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		strengths: ["coding", "reasoning", "agents", "tool_use"],
		releaseDate: "February 12, 2026",
		lastUpdated: "February 12, 2026",
		supportsAttachments: false,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.001,
		costPer1kOutputTokens: 0.0032,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
	createModelConfig("glm-4.5", PROVIDER, {
		name: "GLM-4.5",
		matchingModel: "glm-4.5",
		family: "glm",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 98304,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.5-air", PROVIDER, {
		name: "GLM-4.5-Air",
		matchingModel: "glm-4.5-air",
		family: "glm-air",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 98304,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0011,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.5-flash", PROVIDER, {
		name: "GLM-4.5-Flash",
		matchingModel: "glm-4.5-flash",
		family: "glm-flash",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 28, 2025",
		lastUpdated: "July 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 98304,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.5v", PROVIDER, {
		name: "GLM-4.5V",
		matchingModel: "glm-4.5v",
		family: "glm",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "August 11, 2025",
		lastUpdated: "August 11, 2025",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 64000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0018,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.6", PROVIDER, {
		name: "GLM-4.6",
		matchingModel: "glm-4.6",
		family: "glm",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "September 30, 2025",
		lastUpdated: "September 30, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 204800,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.0022,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.6v", PROVIDER, {
		name: "GLM-4.6V",
		matchingModel: "glm-4.6v",
		family: "glm",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "December 8, 2025",
		lastUpdated: "December 8, 2025",
		modalities: {
			input: ["text", "image", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0009,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.7-flash", PROVIDER, {
		name: "GLM-4.7-Flash",
		matchingModel: "glm-4.7-flash",
		family: "glm-flash",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "January 19, 2026",
		lastUpdated: "January 19, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 131072,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-4.7-flashx", PROVIDER, {
		name: "GLM-4.7-FlashX",
		matchingModel: "glm-4.7-flashx",
		family: "glm-flash",
		openWeights: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "January 19, 2026",
		lastUpdated: "January 19, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.00007,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5-turbo", PROVIDER, {
		name: "GLM-5-Turbo",
		matchingModel: "glm-5-turbo",
		family: "glm",
		openWeights: false,
		releaseDate: "March 16, 2026",
		lastUpdated: "March 16, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0012,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.1", PROVIDER, {
		name: "GLM-5.1",
		matchingModel: "glm-5.1",
		family: "glm",
		openWeights: true,
		releaseDate: "April 7, 2026",
		lastUpdated: "April 7, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 200000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.2", PROVIDER, {
		name: "GLM-5.2",
		matchingModel: "glm-5.2",
		family: "glm",
		openWeights: true,
		releaseDate: "June 13, 2026",
		lastUpdated: "June 13, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.3", PROVIDER, {
		name: "GLM-5.3",
		matchingModel: "glm-5.3",
		family: "glm",
		openWeights: false,
		releaseDate: "August 14, 2026",
		lastUpdated: "August 14, 2026",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0014,
		costPer1kOutputTokens: 0.0044,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5.3-flash", PROVIDER, {
		name: "GLM-5.3-Flash",
		matchingModel: "glm-5.3-flash",
		family: "glm",
		openWeights: false,
		releaseDate: "August 26, 2026",
		lastUpdated: "August 26, 2026",
		modalities: {
			input: ["text", "image", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		contextWindow: 1000000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.000075,
		costPer1kOutputTokens: 0.00025,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),

	createModelConfig("glm-5v-turbo", PROVIDER, {
		name: "GLM-5V-Turbo",
		matchingModel: "glm-5v-turbo",
		family: "glm",
		openWeights: false,
		releaseDate: "April 1, 2026",
		lastUpdated: "April 1, 2026",
		modalities: {
			input: ["text", "image", "video", "pdf"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0012,
		costPer1kOutputTokens: 0.004,
		reasoningConfig: {
			supportedEffortLevels: ["none", "thinking"],
			defaultEffort: "none",
		},
	}),
]);
