import type { ModelConfig } from "~/types";

export const oldWorkersAiModelConfig: ModelConfig = {
	"whisper-tiny": {
		name: "OpenAI Whisper",
		matchingModel: "@cf/openai/whisper-tiny-en",
		provider: "workers-ai",
		strengths: ["audio"],
		speed: 3,
		reliability: 2,
		contextComplexity: 2,
		modalities: {
			input: ["text"],
			output: ["speech"],
		},
	},
	whisper: {
		name: "OpenAI Whisper",
		matchingModel: "@cf/openai/whisper",
		provider: "workers-ai",
		strengths: ["audio"],
		speed: 3,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["speech"],
		},
	},
	"whisper-large-v3-turbo": {
		name: "OpenAI Whisper Large v3 Turbo",
		description:
			"A faster, more accurate speech-to-text model when compared to the base Whisper model.",
		matchingModel: "@cf/openai/whisper-large-v3-turbo",
		provider: "workers-ai",
		strengths: ["audio"],
		speed: 4,
		reliability: 5,
		contextComplexity: 4,
		modalities: {
			input: ["text"],
			output: ["speech"],
		},
	},
	melotts: {
		name: "MyShell MeloTTS",
		matchingModel: "@cf/myshell-ai/melotts",
		description:
			"Melotts is a text-to-speech model that can generate high-quality speech from text.",
		provider: "workers-ai",
		strengths: ["audio"],
		speed: 4,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["audio"],
		},
		releaseDate: "November 14, 2025",
		lastUpdated: "November 14, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},
	"@cf/moonshotai/kimi-k2.5": {
		name: "Moonshot Kimi K2.5",
		matchingModel: "@cf/moonshotai/kimi-k2.5",
		description:
			"Kimi K2.5 is a frontier-scale open-source model with a 256k context window, multi-turn tool calling, vision inputs, and structured outputs for agentic workloads.",
		provider: "workers-ai",
		supportsToolCalls: true,
		supportsAttachments: true,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		reasoningConfig: {
			enabled: true,
		},
		contextWindow: 256000,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 27, 2026",
		lastUpdated: "January 27, 2026",
		supportsTemperature: true,
		supportsResponseFormat: true,
		maxTokens: 256000,
		costPer1kInputTokens: 0.0006,
		costPer1kOutputTokens: 0.003,
	},
	"@cf/moonshotai/kimi-k2.6": {
		name: "Moonshot Kimi K2.6",
		matchingModel: "@cf/moonshotai/kimi-k2.6",
		description:
			"Kimi K2.6 is a frontier-scale open-source 1T parameter model with a 262.1k context window, multi-turn tool calling, vision inputs, and structured outputs for agentic workloads.",
		provider: "workers-ai",
		supportsToolCalls: true,
		supportsAttachments: true,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		reasoningConfig: {
			enabled: true,
		},
		contextWindow: 262144,
		supportsTemperature: true,
		supportsResponseFormat: true,
		maxTokens: 256000,
		isFeatured: true,
		knowledgeCutoffDate: "January 2025",
		releaseDate: "April 20, 2026",
		lastUpdated: "April 20, 2026",
		costPer1kInputTokens: 0.00095,
		costPer1kOutputTokens: 0.004,
	},
	"llama-3.3-70b-instruct": {
		name: "Llama 3.3 70B Instruct FP8 Fast",
		matchingModel: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
		description:
			"Meta's new 70B model that claims to have the same performance as the 450B model but more cost effective.",
		provider: "workers-ai",
		supportsResponseFormat: false,
		strengths: ["instruction", "general_knowledge", "coding", "reasoning", "multilingual"],
		speed: 4,
		reliability: 5,
		contextComplexity: 5,
		supportsToolCalls: true,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		releaseDate: "December 6, 2024",
		lastUpdated: "December 6, 2024",
		supportsAttachments: false,
		supportsTemperature: true,
		contextWindow: 24000,
		maxTokens: 24000,
		costPer1kInputTokens: 0.000293,
		costPer1kOutputTokens: 0.002253,
		reasoningConfig: {
			enabled: false,
		},
	},
	"llama-3.2-1b-instruct": {
		name: "Llama 3.2 1B Instruct",
		matchingModel: "@cf/meta/llama-3.2-1b-instruct",
		description:
			"The Llama 3.2 instruction-tuned text only models are optimized for multilingual dialogue use cases, including agentic retrieval and summarization tasks.",
		provider: "workers-ai",
		strengths: ["instruction", "summarization", "multilingual"],
		speed: 5,
		reliability: 3,
		contextComplexity: 2,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		releaseDate: "September 25, 2024",
		lastUpdated: "September 25, 2024",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 60000,
		maxTokens: 60000,
		costPer1kInputTokens: 0.000027,
		costPer1kOutputTokens: 0.000201,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},
	"llama-3.2-3b-instruct": {
		name: "Llama 3.2 3B Instruct",
		matchingModel: "@cf/meta/llama-3.2-3b-instruct",
		description:
			"The Llama 3.2 instruction-tuned text only models are optimized for multilingual dialogue use cases, including agentic retrieval and summarization tasks.",
		provider: "workers-ai",
		strengths: ["instruction", "summarization", "multilingual"],
		speed: 4,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		releaseDate: "September 25, 2024",
		lastUpdated: "September 25, 2024",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 80000,
		maxTokens: 80000,
		costPer1kInputTokens: 0.0000509,
		costPer1kOutputTokens: 0.000335,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},
	"llama-3.1-70b-instruct": {
		name: "Meta Llama 3.1 70B Instruct",
		matchingModel: "@cf/meta/llama-3.1-70b-instruct",
		description:
			"The Meta Llama 3.1 collection of multilingual large language models (LLMs) is a collection of pretrained and instruction tuned generative models. The Llama 3.1 instruction tuned text only models are optimized for multilingual dialogue use cases and outperform many of the available open source and closed chat models on common industry benchmarks.",
		provider: "workers-ai",
		supportsResponseFormat: true,
		strengths: ["instruction", "reasoning", "multilingual", "general_knowledge"],
		speed: 3,
		reliability: 5,
		contextComplexity: 5,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"llama-4-scout-17b": {
		name: "Llama 4 Scout 17B 16E Instruct",
		matchingModel: "@cf/meta/llama-4-scout-17b-16e-instruct",
		description:
			"Meta's Llama 4 Scout is a 17 billion parameter model with 16 experts that is natively multimodal. These models leverage a mixture-of-experts architecture to offer industry-leading performance in text and image understanding.",
		provider: "workers-ai",
		supportsToolCalls: true,
		isFeatured: true,
		multimodal: true,
		strengths: ["vision", "reasoning", "instruction", "general_knowledge", "chat"],
		speed: 4,
		reliability: 5,
		contextComplexity: 5,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		supportsAttachments: true,
		supportsTemperature: true,
		contextWindow: 131000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00027,
		costPer1kOutputTokens: 0.00085,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},
	"hermes-2-pro-mistral-7b": {
		name: "Hermes 2 Pro Mistral 7B",
		matchingModel: "@hf/nousresearch/hermes-2-pro-mistral-7b",
		description:
			"An upgraded, retrained version of Nous Hermes 2, consisting of an updated and cleaned version of the OpenHermes 2.5 Dataset, as well as a newly introduced Function Calling and JSON Mode dataset developed in-house.",
		provider: "workers-ai",
		supportsToolCalls: true,
		isFree: true,
		isFeatured: true,
		supportsResponseFormat: true,
		contextWindow: 24000,
		maxTokens: 1024,
		strengths: ["instruction", "coding", "reasoning", "chat"],
		speed: 4,
		reliability: 4,
		contextComplexity: 4,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	llava: {
		name: "HuggingFace Llava 1.5 7B",
		matchingModel: "@cf/llava-hf/llava-1.5-7b-hf",
		provider: "workers-ai",
		strengths: ["vision"],
		speed: 3,
		reliability: 4,
		contextComplexity: 3,
		multimodal: true,
		modalities: {
			input: ["image"],
			output: ["text"],
		},
	},
	"uform-gen2-qwen-500m": {
		name: "UForm Gen2 Qwen 500M",
		matchingModel: "@cf/unum/uform-gen2-qwen-500m",
		description: "Generative vision-language model for captioning and VQA.",
		provider: "workers-ai",
		strengths: ["vision"],
		speed: 4,
		reliability: 3,
		contextComplexity: 3,
		multimodal: true,
		modalities: {
			input: ["image"],
			output: ["text"],
		},
	},
	flux: {
		name: "Black Forest Labs Flux 1 Schnell",
		matchingModel: "@cf/black-forest-labs/flux-1-schnell",
		description:
			"FLUX.1 [schnell] is a 12 billion parameter rectified flow transformer capable of generating images from text descriptions.",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 4,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	},
	"flux-2-dev": {
		name: "Black Forest Labs Flux 2 Dev",
		matchingModel: "@cf/black-forest-labs/flux-2-dev",
		description:
			"Flux 2 is an image generation and editing model by Black Forest Labs. It creates high-quality images from text prompts and can edit existing images using natural language instructions.",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 4,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	},
	"@cf/black-forest-labs/flux-2-klein-4b": {
		name: "Black Forest Labs Flux 2 Klein 4B",
		matchingModel: "@cf/black-forest-labs/flux-2-klein-4b",
		description: "",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 4,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	},
	"@cf/black-forest-labs/flux-2-klein-9b": {
		name: "Black Forest Labs Flux 2 Klein 9B",
		matchingModel: "@cf/black-forest-labs/flux-2-klein-9b",
		description: "",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 4,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	},
	"stable-diffusion-1.5-img2img": {
		name: "Stable Diffusion 1.5 Img2Img",
		matchingModel: "@cf/runwayml/stable-diffusion-v1-5-img2img",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 3,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["image"],
			output: ["image"],
		},
	},
	"stable-diffusion-1.5-inpainting": {
		name: "Stable Diffusion 1.5 Inpainting",
		matchingModel: "@cf/runwayml/stable-diffusion-v1-5-inpainting",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 3,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["image"],
			output: ["image"],
		},
	},
	"stable-diffusion-xl-base-1.0": {
		name: "Stable Diffusion XL Base 1.0",
		matchingModel: "@cf/stabilityai/stable-diffusion-xl-base-1.0",
		description:
			"Diffusion-based text-to-image generative model by Stability AI. Generates and modify images based on text prompts.",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 3,
		reliability: 4,
		contextComplexity: 4,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	},
	"dreamshaper-8-lcm": {
		name: "Dreamshaper 8 LCM",
		description:
			"Stable Diffusion model that has been fine-tuned to be better at photorealism without sacrificing range.",
		matchingModel: "@cf/lykon/dreamshaper-8-lcm",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 5,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	},
	"stable-diffusion-xl-lightning": {
		name: "Stable Diffusion XL Lightning",
		matchingModel: "@cf/bytedance/stable-diffusion-xl-lightning",
		description:
			"SDXL-Lightning is a lightning-fast text-to-image generation model. It can generate high-quality 1024px images in a few steps.",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 5,
		reliability: 4,
		contextComplexity: 4,
		modalities: {
			input: ["text"],
			output: ["image"],
		},
	},
	sqlcoder: {
		name: "SQLCoder 7B",
		matchingModel: "@cf/defog/sqlcoder-7b-2",
		description:
			"SQLCoder is a model trained on SQL queries and their corresponding natural language descriptions. It can generate SQL queries from natural language descriptions and vice versa.",
		provider: "workers-ai",
		isFree: true,
		strengths: ["coding"],
		speed: 4,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"bge-base-en-v1.5": {
		name: "BGE Base EN v1.5",
		matchingModel: "@cf/baai/bge-base-en-v1.5",
		provider: "workers-ai",
		strengths: ["search"],
		speed: 5,
		reliability: 5,
		contextComplexity: 3,
		modalities: {
			input: ["embedding"],
			output: ["embedding"],
		},
		releaseDate: "April 3, 2025",
		lastUpdated: "April 3, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.000067,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},
	"bge-large-en-v1.5": {
		name: "BGE Large EN v1.5",
		matchingModel: "@cf/baai/bge-large-en-v1.5",
		provider: "workers-ai",
		strengths: ["search"],
		speed: 5,
		reliability: 5,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["embedding"],
		},
		releaseDate: "April 3, 2025",
		lastUpdated: "April 3, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},
	"bge-m3": {
		name: "BGE M3",
		description:
			"A multi-lingual embeddings model that supports over 100 languages. It can also simultaneously perform dense retrieval, multi-vector retrieval, and sparse retrieval, with the ability to process inputs of different granularities.",
		matchingModel: "@cf/baai/bge-m3",
		provider: "workers-ai",
		strengths: ["search", "multilingual"],
		speed: 4,
		reliability: 5,
		contextComplexity: 4,
		modalities: {
			input: ["text"],
			output: ["embedding"],
		},
		releaseDate: "April 3, 2025",
		lastUpdated: "April 3, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.000012,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},
	"bge-reranker-base": {
		name: "BGE Reranker Base",
		description:
			"For use after the initial vector search to find the most relevant documents to return to a user by reranking the outputs.",
		matchingModel: "@cf/baai/bge-reranker-base",
		provider: "workers-ai",
		strengths: ["search"],
		speed: 4,
		reliability: 5,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["embedding"],
		},
		releaseDate: "April 9, 2025",
		lastUpdated: "April 9, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0000031,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},
	"gemma-3-12b-it": {
		name: "Gemma 3 12B IT",
		matchingModel: "@cf/google/gemma-3-12b-it",
		description:
			"Gemma 3 models are well-suited for a variety of text generation and image understanding tasks, including question answering, summarization, and reasoning. Gemma 3 models are multimodal, handling text and image input and generating text output, with a large, 128K context window, multilingual support in over 140 languages.",
		provider: "workers-ai",
		includedInRouter: true,
		strengths: ["instruction", "reasoning", "multilingual", "summarization", "vision"],
		speed: 4,
		reliability: 4,
		contextComplexity: 4,
		multimodal: true,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		releaseDate: "March 18, 2025",
		lastUpdated: "March 18, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 80000,
		maxTokens: 80000,
		costPer1kInputTokens: 0.000345,
		costPer1kOutputTokens: 0.000556,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},
	"gemma-4-26b-a4b-it": {
		name: "Gemma 4 26B A4B IT",
		matchingModel: "@cf/google/gemma-4-26b-a4b-it",
		description:
			"Gemma 4 is Google's most intelligent family of open models, built from Gemini 3 research to maximize intelligence-per-parameter.",
		provider: "workers-ai",
		contextWindow: 256000,
		maxTokens: 16384,
		multimodal: true,
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		releaseDate: "December 15, 2025",
		lastUpdated: "December 15, 2025",
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: true,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			enabled: true,
		},
		supportsResponseFormat: true,
	},
	"qwq-32b": {
		name: "QwQ 32B",
		matchingModel: "@cf/qwen/qwq-32b",
		description:
			"QwQ is the reasoning model of the Qwen series. Compared with conventional instruction-tuned models, QwQ, which is capable of thinking and reasoning, can achieve significantly enhanced performance in downstream tasks, especially hard problems.",
		provider: "workers-ai",
		includedInRouter: true,
		strengths: ["reasoning", "math", "analysis"],
		speed: 3,
		reliability: 5,
		contextComplexity: 5,
		reasoningConfig: { enabled: true },
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		releaseDate: "March 5, 2025",
		lastUpdated: "March 5, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 24000,
		maxTokens: 24000,
		costPer1kInputTokens: 0.00066,
		costPer1kOutputTokens: 0.001,
		supportsResponseFormat: false,
	},
	"qwen2.5-coder-32b": {
		name: "Qwen 2.5 Coder 32B Instruct",
		matchingModel: "@cf/qwen/qwen2.5-coder-32b-instruct",
		description:
			"Qwen2.5-Coder is the latest series of Code-Specific Qwen large language models. As of now, Qwen2.5-Coder has covered six mainstream model sizes, 0.5, 1.5, 3, 7, 14, 32 billion parameters, to meet the needs of different developers.",
		provider: "workers-ai",
		includedInRouter: true,
		strengths: ["coding"],
		speed: 3,
		reliability: 5,
		contextComplexity: 5,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		releaseDate: "February 27, 2025",
		lastUpdated: "February 27, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00066,
		costPer1kOutputTokens: 0.001,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},
	"@cf/meta/llama-guard-3-8b": {
		name: "Llama Guard 3 8B",
		matchingModel: "@cf/meta/llama-guard-3-8b",
		provider: "workers-ai",
		isFree: true,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		releaseDate: "January 22, 2025",
		lastUpdated: "January 22, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.000484,
		costPer1kOutputTokens: 0.00003,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},
	"lucid-origin": {
		name: "Leonardo Lucid Origin",
		matchingModel: "@cf/leonardo/lucid-origin",
		description:
			"Leonardo.AI's most adaptable and prompt-responsive model to date. Whether you're generating images with sharp graphic design, stunning full-HD renders, or highly specific creative direction, it adheres closely to your prompts, renders text with accuracy, and supports a wide array of visual styles and aesthetics.",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 4,
		reliability: 4,
		contextComplexity: 4,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"phoenix-1.0": {
		name: "Leonardo Phoenix 1.0",
		matchingModel: "@cf/leonardo/phoenix-1.0",
		description:
			"Phoenix 1.0 is a model by Leonardo.Ai that generates images with exceptional prompt adherence and coherent text.",
		provider: "workers-ai",
		strengths: ["creative"],
		speed: 4,
		reliability: 4,
		contextComplexity: 4,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
	},
	"aura-1": {
		name: "Deepgram Aura 1",
		matchingModel: "@cf/deepgram/aura-1",
		description:
			"Aura is a context-aware text-to-speech (TTS) model that applies natural pacing, expressiveness, and fillers based on the context of the provided text. The quality of your text input directly impacts the naturalness of the audio output.",
		provider: "workers-ai",
		strengths: ["audio"],
		speed: 4,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["speech"],
		},
	},
	"nova-3": {
		name: "Deepgram Nova 3",
		matchingModel: "@cf/deepgram/nova-3",
		description:
			"Transcribe audio using Deepgram's speech-to-text model with advanced features like language detection, speaker diarization, and sentiment analysis.",
		provider: "workers-ai",
		strengths: ["audio"],
		speed: 4,
		reliability: 5,
		contextComplexity: 4,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		releaseDate: "November 14, 2025",
		lastUpdated: "November 14, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},
	"smart-turn-v2": {
		name: "Pipecat Smart Turn v2",
		matchingModel: "@cf/pipecat-ai/smart-turn-v2",
		description:
			"An open source, community-driven, native audio turn detection model that detects end-of-turn in audio streams to determine when someone has finished speaking.",
		provider: "workers-ai",
		strengths: ["audio"],
		speed: 4,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		releaseDate: "November 14, 2025",
		lastUpdated: "November 14, 2025",
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},
	"embeddinggemma-300m": {
		name: "EmbeddingGemma 300M",
		matchingModel: "@cf/google/embeddinggemma-300m",
		provider: "workers-ai",
		strengths: ["search"],
		speed: 4,
		reliability: 4,
		contextComplexity: 3,
		modalities: {
			input: ["text"],
			output: ["embedding"],
		},
	},
	"@cf/ai4bharat/indictrans2-en-indic-1B": {
		name: "IndicTrans2 EN-Indic 1B",
		matchingModel: "@cf/ai4bharat/indictrans2-en-indic-1B",
		provider: "workers-ai",
		releaseDate: "September 25, 2025",
		lastUpdated: "September 25, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00034,
		costPer1kOutputTokens: 0.00034,
		reasoningConfig: {
			enabled: false,
		},
	},

	"@cf/aisingapore/gemma-sea-lion-v4-27b-it": {
		name: "Gemma SEA-LION v4 27B IT",
		matchingModel: "@cf/aisingapore/gemma-sea-lion-v4-27b-it",
		provider: "workers-ai",
		releaseDate: "September 23, 2025",
		lastUpdated: "September 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000351,
		costPer1kOutputTokens: 0.000555,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/baai/bge-small-en-v1.5": {
		name: "BGE Small EN v1.5",
		matchingModel: "@cf/baai/bge-small-en-v1.5",
		provider: "workers-ai",
		releaseDate: "April 3, 2025",
		lastUpdated: "April 3, 2025",
		modalities: {
			input: ["text"],
			output: ["embedding"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00002,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"@cf/deepgram/aura-2-en": {
		name: "Deepgram Aura 2 (EN)",
		matchingModel: "@cf/deepgram/aura-2-en",
		provider: "workers-ai",
		releaseDate: "November 14, 2025",
		lastUpdated: "November 14, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"@cf/deepgram/aura-2-es": {
		name: "Deepgram Aura 2 (ES)",
		matchingModel: "@cf/deepgram/aura-2-es",
		provider: "workers-ai",
		releaseDate: "November 14, 2025",
		lastUpdated: "November 14, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"@cf/deepseek-ai/deepseek-r1-distill-qwen-32b": {
		name: "DeepSeek R1 Distill Qwen 32B",
		matchingModel: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
		provider: "workers-ai",
		releaseDate: "January 22, 2025",
		lastUpdated: "January 22, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 80000,
		maxTokens: 80000,
		costPer1kInputTokens: 0.000497,
		costPer1kOutputTokens: 0.004881,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/facebook/bart-large-cnn": {
		name: "BART Large CNN",
		matchingModel: "@cf/facebook/bart-large-cnn",
		provider: "workers-ai",
		releaseDate: "April 9, 2025",
		lastUpdated: "April 9, 2025",
		modalities: {
			input: ["text"],
			output: ["embedding"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"@cf/huggingface/distilbert-sst-2-int8": {
		name: "DistilBERT SST-2 INT8",
		matchingModel: "@cf/huggingface/distilbert-sst-2-int8",
		provider: "workers-ai",
		releaseDate: "April 3, 2025",
		lastUpdated: "April 3, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.000026,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"@cf/ibm-granite/granite-4.0-h-micro": {
		name: "IBM Granite 4.0 H Micro",
		matchingModel: "@cf/ibm-granite/granite-4.0-h-micro",
		provider: "workers-ai",
		releaseDate: "October 7, 2025",
		lastUpdated: "October 7, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 131000,
		maxTokens: 131000,
		costPer1kInputTokens: 0.000017,
		costPer1kOutputTokens: 0.000112,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/meta/llama-2-7b-chat-fp16": {
		name: "Llama 2 7B Chat FP16",
		matchingModel: "@cf/meta/llama-2-7b-chat-fp16",
		provider: "workers-ai",
		releaseDate: "November 7, 2023",
		lastUpdated: "November 7, 2023",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 4096,
		maxTokens: 4096,
		costPer1kInputTokens: 0.000556,
		costPer1kOutputTokens: 0.006667,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/meta/llama-3-8b-instruct": {
		name: "Llama 3 8B Instruct",
		matchingModel: "@cf/meta/llama-3-8b-instruct",
		provider: "workers-ai",
		releaseDate: "April 18, 2024",
		lastUpdated: "April 18, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 7968,
		maxTokens: 7968,
		costPer1kInputTokens: 0.000282,
		costPer1kOutputTokens: 0.000827,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/meta/llama-3-8b-instruct-awq": {
		name: "Llama 3 8B Instruct AWQ",
		matchingModel: "@cf/meta/llama-3-8b-instruct-awq",
		provider: "workers-ai",
		releaseDate: "May 9, 2024",
		lastUpdated: "May 9, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 8192,
		maxTokens: 8192,
		costPer1kInputTokens: 0.000123,
		costPer1kOutputTokens: 0.000266,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/meta/llama-3.1-8b-instruct": {
		name: "Llama 3.1 8B Instruct",
		matchingModel: "@cf/meta/llama-3.1-8b-instruct",
		provider: "workers-ai",
		releaseDate: "April 3, 2025",
		lastUpdated: "April 3, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00028,
		costPer1kOutputTokens: 0.00083,
		reasoningConfig: {
			enabled: false,
		},
	},

	"@cf/meta/llama-3.1-8b-instruct-awq": {
		name: "Llama 3.1 8B Instruct AWQ",
		matchingModel: "@cf/meta/llama-3.1-8b-instruct-awq",
		provider: "workers-ai",
		releaseDate: "July 25, 2024",
		lastUpdated: "July 25, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 8192,
		maxTokens: 8192,
		costPer1kInputTokens: 0.000123,
		costPer1kOutputTokens: 0.000266,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/meta/llama-3.1-8b-instruct-fp8": {
		name: "Llama 3.1 8B Instruct FP8",
		matchingModel: "@cf/meta/llama-3.1-8b-instruct-fp8",
		provider: "workers-ai",
		releaseDate: "July 25, 2024",
		lastUpdated: "July 25, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 32000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.000152,
		costPer1kOutputTokens: 0.000287,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/meta/llama-3.2-11b-vision-instruct": {
		name: "Llama 3.2 11B Vision Instruct",
		matchingModel: "@cf/meta/llama-3.2-11b-vision-instruct",
		provider: "workers-ai",
		releaseDate: "September 25, 2024",
		lastUpdated: "September 25, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.0000485,
		costPer1kOutputTokens: 0.000676,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/meta/m2m100-1.2b": {
		name: "M2M100 1.2B",
		matchingModel: "@cf/meta/m2m100-1.2b",
		provider: "workers-ai",
		releaseDate: "April 3, 2025",
		lastUpdated: "April 3, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00034,
		costPer1kOutputTokens: 0.00034,
		reasoningConfig: {
			enabled: false,
		},
	},

	"@cf/mistral/mistral-7b-instruct-v0.1": {
		name: "Mistral 7B Instruct v0.1",
		matchingModel: "@cf/mistral/mistral-7b-instruct-v0.1",
		provider: "workers-ai",
		releaseDate: "November 7, 2023",
		lastUpdated: "November 7, 2023",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 2824,
		maxTokens: 2824,
		costPer1kInputTokens: 0.00011,
		costPer1kOutputTokens: 0.00019,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/mistralai/mistral-small-3.1-24b-instruct": {
		name: "Mistral Small 3.1 24B Instruct",
		matchingModel: "@cf/mistralai/mistral-small-3.1-24b-instruct",
		provider: "workers-ai",
		releaseDate: "March 18, 2025",
		lastUpdated: "March 18, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.000351,
		costPer1kOutputTokens: 0.000555,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/nvidia/nemotron-3-120b-a12b": {
		name: "Nemotron 3 Super",
		description:
			"NVIDIA Nemotron 3 Super is a hybrid MoE model with leading accuracy for multi-agent applications and specialized agentic AI systems.",
		matchingModel: "@cf/nvidia/nemotron-3-120b-a12b",
		provider: "workers-ai",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		contextWindow: 256000,
		supportsToolCalls: true,
		releaseDate: "March 11, 2026",
		lastUpdated: "March 11, 2026",
		supportsAttachments: false,
		supportsTemperature: true,
		maxTokens: 256000,
		costPer1kInputTokens: 0.0005,
		costPer1kOutputTokens: 0.0015,
		reasoningConfig: {
			enabled: true,
		},
		supportsResponseFormat: true,
	},

	"@cf/zai-org/glm-4.7-flash": {
		name: "GLM 4.7 Flash",
		description:
			"GLM-4.7-Flash is a fast and efficient multilingual text generation model with a 131,072 token context window. Optimized for dialogue, instruction-following, and multi-turn tool calling across 100+ languages.",
		matchingModel: "@cf/zai-org/glm-4.7-flash",
		provider: "workers-ai",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		contextWindow: 131072,
		supportsToolCalls: true,
		knowledgeCutoffDate: "April 2025",
		releaseDate: "January 19, 2026",
		lastUpdated: "January 19, 2026",
		supportsAttachments: false,
		supportsTemperature: true,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0000605,
		costPer1kOutputTokens: 0.0004,
		reasoningConfig: {
			enabled: true,
		},
		supportsResponseFormat: true,
	},

	"@cf/openai/gpt-oss-120b": {
		name: "GPT OSS 120B",
		matchingModel: "@cf/openai/gpt-oss-120b",
		provider: "workers-ai",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00035,
		costPer1kOutputTokens: 0.00075,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: true,
	},

	"@cf/openai/gpt-oss-20b": {
		name: "GPT OSS 20B",
		matchingModel: "@cf/openai/gpt-oss-20b",
		provider: "workers-ai",
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.0002,
		costPer1kOutputTokens: 0.0003,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: true,
	},

	"@cf/pfnet/plamo-embedding-1b": {
		name: "PLaMo Embedding 1B",
		matchingModel: "@cf/pfnet/plamo-embedding-1b",
		provider: "workers-ai",
		releaseDate: "September 25, 2025",
		lastUpdated: "September 25, 2025",
		modalities: {
			input: ["text"],
			output: ["embedding"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.000019,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},

	"@cf/qwen/qwen3-30b-a3b-fp8": {
		name: "Qwen3 30B A3B FP8",
		matchingModel: "@cf/qwen/qwen3-30b-a3b-fp8",
		provider: "workers-ai",
		releaseDate: "April 30, 2025",
		lastUpdated: "April 30, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: true,
		contextWindow: 32768,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0000509,
		costPer1kOutputTokens: 0.000335,
		reasoningConfig: {
			enabled: false,
		},
		supportsResponseFormat: false,
	},

	"@cf/qwen/qwen3-embedding-0.6b": {
		name: "Qwen3 Embedding 0.6B",
		matchingModel: "@cf/qwen/qwen3-embedding-0.6b",
		provider: "workers-ai",
		releaseDate: "November 14, 2025",
		lastUpdated: "November 14, 2025",
		modalities: {
			input: ["text"],
			output: ["embedding"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsToolCalls: false,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.000012,
		costPer1kOutputTokens: 0,
		reasoningConfig: {
			enabled: false,
		},
	},
};
