import type { ModelConfig } from "~/types";
import {
	createModelConfig,
	createModelConfigObject,
} from "~/lib/providers/models/utils";

const PROVIDER = "workers-ai";

export const workersAiModelConfig: ModelConfig = createModelConfigObject([
	createModelConfig("workers-ai-anthropic-claude-opus-4-7", PROVIDER, {
		name: "Claude Opus 4.7",
		matchingModel: "anthropic/claude-opus-4.7",
		modalities: { input: ["text"], output: ["text"] },
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-anthropic-claude-haiku-4-5", PROVIDER, {
		name: "Claude Haiku 4.5",
		matchingModel: "anthropic/claude-haiku-4.5",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-anthropic-claude-sonnet-4", PROVIDER, {
		name: "Claude Sonnet 4",
		matchingModel: "anthropic/claude-sonnet-4",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-anthropic-claude-sonnet-4-5", PROVIDER, {
		name: "Claude Sonnet 4.5",
		matchingModel: "anthropic/claude-sonnet-4.5",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-anthropic-claude-sonnet-4-6", PROVIDER, {
		name: "Claude Sonnet 4.6",
		matchingModel: "anthropic/claude-sonnet-4.6",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-anthropic-claude-opus-4-6", PROVIDER, {
		name: "Claude Opus 4.6",
		matchingModel: "anthropic/claude-opus-4.6",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-alibaba-qwen3-5-397b-a17b", PROVIDER, {
		name: "Qwen3.5 397B A17B",
		matchingModel: "alibaba/qwen3.5-397b-a17b",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
		supportsTopP: true,
	}),
	createModelConfig("workers-ai-alibaba-qwen3-max", PROVIDER, {
		name: "Qwen3 Max",
		matchingModel: "alibaba/qwen3-max",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
		supportsTopP: true,
	}),
	createModelConfig("workers-ai-minimax-m2-7", PROVIDER, {
		name: "MiniMax M2.7",
		matchingModel: "minimax/m2.7",
		modalities: { input: ["text", "image"], output: ["text"] },
		multimodal: true,
		supportsAttachments: true,
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
		supportsTopP: true,
	}),
	createModelConfig("workers-ai-google-gemini-3-flash", PROVIDER, {
		name: "Gemini 3 Flash",
		matchingModel: "google/gemini-3-flash",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-google-gemini-3-1-flash-lite", PROVIDER, {
		name: "Gemini 3.1 Flash Lite",
		matchingModel: "google/gemini-3.1-flash-lite",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-google-gemini-3-1-pro", PROVIDER, {
		name: "Gemini 3.1 Pro",
		matchingModel: "google/gemini-3.1-pro",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-openai-o4-mini", PROVIDER, {
		name: "o4-mini",
		matchingModel: "openai/o4-mini",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		reasoningConfig: { enabled: true },
	}),
	createModelConfig("workers-ai-openai-gpt-4-1", PROVIDER, {
		name: "GPT-4.1",
		matchingModel: "openai/gpt-4.1",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-openai-gpt-4-1-mini", PROVIDER, {
		name: "GPT-4.1 Mini",
		matchingModel: "openai/gpt-4.1-mini",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		supportsTemperature: true,
	}),
	createModelConfig("workers-ai-openai-gpt-5", PROVIDER, {
		name: "GPT-5",
		matchingModel: "openai/gpt-5",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		reasoningConfig: { enabled: true },
	}),
	createModelConfig("workers-ai-openai-gpt-5-4", PROVIDER, {
		name: "GPT-5.4",
		matchingModel: "openai/gpt-5.4",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		reasoningConfig: { enabled: true },
	}),
	createModelConfig("workers-ai-openai-gpt-5-4-mini", PROVIDER, {
		name: "GPT-5.4 Mini",
		matchingModel: "openai/gpt-5.4-mini",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		reasoningConfig: { enabled: true },
	}),
	createModelConfig("workers-ai-openai-gpt-5-4-nano", PROVIDER, {
		name: "GPT-5.4 Nano",
		matchingModel: "openai/gpt-5.4-nano",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsResponseFormat: true,
		reasoningConfig: { enabled: true },
	}),
	createModelConfig("workers-ai-moonshotai-kimi-k2-5", PROVIDER, {
		name: "Kimi K2.5",
		matchingModel: "moonshotai/kimi-k2.5",
		modalities: { input: ["text"], output: ["text"] },
		supportsToolCalls: true,
		supportsAttachments: true,
		supportsResponseFormat: true,
	}),
]);
