import type { IconType } from "./icon-type";

type IconModule = { default: IconType };

/**
 * Static import map so bundlers can code-split each icon. A dynamic specifier would leave the
 * published package unable to resolve its own icons.
 */
export const ICON_LOADERS: Record<string, () => Promise<IconModule>> = {
	adobe: () => import("./Icons/adobe"),
	"adobe-firefly": () => import("./Icons/adobe-firefly"),
	ai21: () => import("./Icons/ai21"),
	"amazon-nova": () => import("./Icons/amazon-nova"),
	anthropic: () => import("./Icons/anthropic"),
	aws: () => import("./Icons/aws"),
	azure: () => import("./Icons/azure"),
	baai: () => import("./Icons/baai"),
	bedrock: () => import("./Icons/bedrock"),
	bytedance: () => import("./Icons/bytedance"),
	cerebras: () => import("./Icons/cerebras"),
	claude: () => import("./Icons/claude"),
	cloudflare: () => import("./Icons/cloudflare"),
	cohere: () => import("./Icons/cohere"),
	"command-a": () => import("./Icons/command-a"),
	deepai: () => import("./Icons/deepai"),
	deepinfra: () => import("./Icons/deepinfra"),
	deepseek: () => import("./Icons/deepseek"),
	dolphin: () => import("./Icons/dolphin"),
	elevenlabs: () => import("./Icons/elevenlabs"),
	exa: () => import("./Icons/exa"),
	fal: () => import("./Icons/fal"),
	fireworks: () => import("./Icons/fireworks"),
	flux: () => import("./Icons/flux"),
	gemini: () => import("./Icons/gemini"),
	gemma: () => import("./Icons/gemma"),
	github: () => import("./Icons/github"),
	"github-copilot": () => import("./Icons/github-copilot"),
	google: () => import("./Icons/google"),
	grok: () => import("./Icons/grok"),
	groq: () => import("./Icons/groq"),
	huggingface: () => import("./Icons/huggingface"),
	hunyuan: () => import("./Icons/hunyuan"),
	hyperbolic: () => import("./Icons/hyperbolic"),
	ideogram: () => import("./Icons/ideogram"),
	inception: () => import("./Icons/inception"),
	inference: () => import("./Icons/inference"),
	kimi: () => import("./Icons/kimi"),
	llava: () => import("./Icons/llava"),
	"lm-studio": () => import("./Icons/lm-studio"),
	mcp: () => import("./Icons/mcp"),
	meta: () => import("./Icons/meta"),
	midjourney: () => import("./Icons/midjourney"),
	minimax: () => import("./Icons/minimax"),
	mistral: () => import("./Icons/mistral"),
	moonshot: () => import("./Icons/moonshot"),
	morph: () => import("./Icons/morph"),
	"nous-research": () => import("./Icons/nous-research"),
	nova: () => import("./Icons/nova"),
	nvidia: () => import("./Icons/nvidia"),
	ollama: () => import("./Icons/ollama"),
	openai: () => import("./Icons/openai"),
	openclaw: () => import("./Icons/openclaw"),
	opencode: () => import("./Icons/opencode"),
	openrouter: () => import("./Icons/openrouter"),
	perplexity: () => import("./Icons/perplexity"),
	qcoder: () => import("./Icons/qcoder"),
	qwen: () => import("./Icons/qwen"),
	replicate: () => import("./Icons/replicate"),
	sora: () => import("./Icons/sora"),
	stability: () => import("./Icons/stability"),
	tavily: () => import("./Icons/tavily"),
	"together-ai": () => import("./Icons/together-ai"),
	upstage: () => import("./Icons/upstage"),
	v0: () => import("./Icons/v0"),
	vercel: () => import("./Icons/vercel"),
	"workers-ai": () => import("./Icons/workers-ai"),
	xai: () => import("./Icons/xai"),
	zai: () => import("./Icons/zai"),
};
