export const MODEL_ICONS: Record<string, string> = {
	claude: "claude",
	command: "command-a",
	"amazon-nova": "amazon-nova",
	llava: "llava",
	gemini: "gemini",
	gemma: "gemma",
	mistral: "mistral",
	codestral: "mistral",
	voxtral: "mistral",
	devstral: "mistral",
	magistral: "mistral",
	ministral: "mistral",
	qwen: "qwen",
	"gpt-": "openai",
	o1: "openai",
	o3: "openai",
	flux: "flux",
	grok: "grok",
	together: "together-ai",
	perplexity: "perplexity",
	"lm-studio": "lm-studio",
	ai21: "ai21",
	jamba: "ai21",
	baai: "baai",
	bytedance: "bytedance",
	hunyuan: "hunyuan",
	midjourney: "midjourney",
	meta: "meta",
	stability: "stability",
	sonar: "perplexity",
	"Titan Text": "bedrock",
	moonshot: "moonshot",
	kimi: "kimi",
	nvidia: "nvidia",
	zai: "zai",
	glm: "zai",
	"gpt oss": "openai",
	llama: "meta",
	minimax: "minimax",
	"stable diffusion": "stability",
	whisper: "openai",
	google: "google",
	deepseek: "deepseek",
};

export const PROVIDER_ICONS: Record<string, string> = {
	openai: "openai",
	anthropic: "anthropic",
	google: "google",
	"google-ai-studio": "google",
	googleai: "google",
	mistral: "mistral",
	groq: "groq",
	"perplexity-ai": "perplexity",
	deepseek: "deepseek",
	bedrock: "bedrock",
	"together-ai": "together-ai",
	grok: "grok",
	replicate: "replicate",
	huggingface: "huggingface",
	cohere: "cohere",
	ollama: "ollama",
	"github-models": "github",
	github: "github",
	xai: "xai",
	openrouter: "openrouter",
	"workers-ai": "workers-ai",
	cloudflare: "cloudflare",
	fireworks: "fireworks",
	hyperbolic: "hyperbolic",
	v0: "v0",
	exa: "exa",
	sagemaker: "sagemaker",
	opencode: "opencode",
	"opencode-go": "opencode",
	openclaw: "openclaw",
	zai: "zai",
};
