// Generated by scripts/sync-composio-toolkits.mjs. Do not edit by hand.
import type { UnparsedComposioToolkitCatalogue } from "../schema.js";
import toolkit0 from "./toolkits/_1password.json" with { type: "json" };
import toolkit1 from "./toolkits/agent_mail.json" with { type: "json" };
import toolkit2 from "./toolkits/airtable.json" with { type: "json" };
import toolkit3 from "./toolkits/algolia.json" with { type: "json" };
import toolkit4 from "./toolkits/alpaca.json" with { type: "json" };
import toolkit5 from "./toolkits/apollo.json" with { type: "json" };
import toolkit6 from "./toolkits/artificial_analysis.json" with { type: "json" };
import toolkit7 from "./toolkits/asana.json" with { type: "json" };
import toolkit8 from "./toolkits/attio.json" with { type: "json" };
import toolkit9 from "./toolkits/basecamp.json" with { type: "json" };
import toolkit10 from "./toolkits/better_proposals.json" with { type: "json" };
import toolkit11 from "./toolkits/bitbucket.json" with { type: "json" };
import toolkit12 from "./toolkits/box.json" with { type: "json" };
import toolkit13 from "./toolkits/browserbase_tool.json" with { type: "json" };
import toolkit14 from "./toolkits/cal.json" with { type: "json" };
import toolkit15 from "./toolkits/calendly.json" with { type: "json" };
import toolkit16 from "./toolkits/canva.json" with { type: "json" };
import toolkit17 from "./toolkits/clickhouse.json" with { type: "json" };
import toolkit18 from "./toolkits/clickup.json" with { type: "json" };
import toolkit19 from "./toolkits/cloudflare.json" with { type: "json" };
import toolkit20 from "./toolkits/cloudflare_api_key.json" with { type: "json" };
import toolkit21 from "./toolkits/cloudflare_browser_rendering.json" with { type: "json" };
import toolkit22 from "./toolkits/coinbase.json" with { type: "json" };
import toolkit23 from "./toolkits/confluence.json" with { type: "json" };
import toolkit24 from "./toolkits/contentful.json" with { type: "json" };
import toolkit25 from "./toolkits/convex.json" with { type: "json" };
import toolkit26 from "./toolkits/crawlbase.json" with { type: "json" };
import toolkit27 from "./toolkits/cursor.json" with { type: "json" };
import toolkit28 from "./toolkits/databricks.json" with { type: "json" };
import toolkit29 from "./toolkits/datadog.json" with { type: "json" };
import toolkit30 from "./toolkits/devto.json" with { type: "json" };
import toolkit31 from "./toolkits/digital_ocean.json" with { type: "json" };
import toolkit32 from "./toolkits/discord.json" with { type: "json" };
import toolkit33 from "./toolkits/discordbot.json" with { type: "json" };
import toolkit34 from "./toolkits/docker_hub.json" with { type: "json" };
import toolkit35 from "./toolkits/dropbox.json" with { type: "json" };
import toolkit36 from "./toolkits/dropbox_sign.json" with { type: "json" };
import toolkit37 from "./toolkits/dynamics365.json" with { type: "json" };
import toolkit38 from "./toolkits/eventbrite.json" with { type: "json" };
import toolkit39 from "./toolkits/excel.json" with { type: "json" };
import toolkit40 from "./toolkits/facebook.json" with { type: "json" };
import toolkit41 from "./toolkits/fathom.json" with { type: "json" };
import toolkit42 from "./toolkits/figma.json" with { type: "json" };
import toolkit43 from "./toolkits/firecrawl.json" with { type: "json" };
import toolkit44 from "./toolkits/fireflies.json" with { type: "json" };
import toolkit45 from "./toolkits/fly.json" with { type: "json" };
import toolkit46 from "./toolkits/foursquare.json" with { type: "json" };
import toolkit47 from "./toolkits/freshbooks.json" with { type: "json" };
import toolkit48 from "./toolkits/freshdesk.json" with { type: "json" };
import toolkit49 from "./toolkits/gamma.json" with { type: "json" };
import toolkit50 from "./toolkits/giphy.json" with { type: "json" };
import toolkit51 from "./toolkits/gist.json" with { type: "json" };
import toolkit52 from "./toolkits/gitea.json" with { type: "json" };
import toolkit53 from "./toolkits/github.json" with { type: "json" };
import toolkit54 from "./toolkits/gitlab.json" with { type: "json" };
import toolkit55 from "./toolkits/gmail.json" with { type: "json" };
import toolkit56 from "./toolkits/google_analytics.json" with { type: "json" };
import toolkit57 from "./toolkits/google_maps.json" with { type: "json" };
import toolkit58 from "./toolkits/google_search_console.json" with { type: "json" };
import toolkit59 from "./toolkits/googleads.json" with { type: "json" };
import toolkit60 from "./toolkits/googlebigquery.json" with { type: "json" };
import toolkit61 from "./toolkits/googlecalendar.json" with { type: "json" };
import toolkit62 from "./toolkits/googledocs.json" with { type: "json" };
import toolkit63 from "./toolkits/googledrive.json" with { type: "json" };
import toolkit64 from "./toolkits/googlemeet.json" with { type: "json" };
import toolkit65 from "./toolkits/googlephotos.json" with { type: "json" };
import toolkit66 from "./toolkits/googlesheets.json" with { type: "json" };
import toolkit67 from "./toolkits/googleslides.json" with { type: "json" };
import toolkit68 from "./toolkits/googlesuper.json" with { type: "json" };
import toolkit69 from "./toolkits/googletasks.json" with { type: "json" };
import toolkit70 from "./toolkits/grafana.json" with { type: "json" };
import toolkit71 from "./toolkits/gumroad.json" with { type: "json" };
import toolkit72 from "./toolkits/harvest.json" with { type: "json" };
import toolkit73 from "./toolkits/heygen.json" with { type: "json" };
import toolkit74 from "./toolkits/hostinger.json" with { type: "json" };
import toolkit75 from "./toolkits/hubspot.json" with { type: "json" };
import toolkit76 from "./toolkits/hugging_face.json" with { type: "json" };
import toolkit77 from "./toolkits/hyperbrowser.json" with { type: "json" };
import toolkit78 from "./toolkits/incident_io.json" with { type: "json" };
import toolkit79 from "./toolkits/instagram.json" with { type: "json" };
import toolkit80 from "./toolkits/intercom.json" with { type: "json" };
import toolkit81 from "./toolkits/jira.json" with { type: "json" };
import toolkit82 from "./toolkits/kibana.json" with { type: "json" };
import toolkit83 from "./toolkits/klaviyo.json" with { type: "json" };
import toolkit84 from "./toolkits/launch_darkly.json" with { type: "json" };
import toolkit85 from "./toolkits/line.json" with { type: "json" };
import toolkit86 from "./toolkits/linear.json" with { type: "json" };
import toolkit87 from "./toolkits/linkedin.json" with { type: "json" };
import toolkit88 from "./toolkits/mailchimp.json" with { type: "json" };
import toolkit89 from "./toolkits/metabase.json" with { type: "json" };
import toolkit90 from "./toolkits/microsoft_clarity.json" with { type: "json" };
import toolkit91 from "./toolkits/microsoft_teams.json" with { type: "json" };
import toolkit92 from "./toolkits/miro.json" with { type: "json" };
import toolkit93 from "./toolkits/mixpanel.json" with { type: "json" };
import toolkit94 from "./toolkits/monday.json" with { type: "json" };
import toolkit95 from "./toolkits/nasa.json" with { type: "json" };
import toolkit96 from "./toolkits/nasdaq.json" with { type: "json" };
import toolkit97 from "./toolkits/neon.json" with { type: "json" };
import toolkit98 from "./toolkits/new_relic.json" with { type: "json" };
import toolkit99 from "./toolkits/ngrok.json" with { type: "json" };
import toolkit100 from "./toolkits/notion.json" with { type: "json" };
import toolkit101 from "./toolkits/npm.json" with { type: "json" };
import toolkit102 from "./toolkits/one_drive.json" with { type: "json" };
import toolkit103 from "./toolkits/openweather_api.json" with { type: "json" };
import toolkit104 from "./toolkits/outlook.json" with { type: "json" };
import toolkit105 from "./toolkits/pagerduty.json" with { type: "json" };
import toolkit106 from "./toolkits/pandadoc.json" with { type: "json" };
import toolkit107 from "./toolkits/plausible_analytics.json" with { type: "json" };
import toolkit108 from "./toolkits/polymarket_us.json" with { type: "json" };
import toolkit109 from "./toolkits/posthog.json" with { type: "json" };
import toolkit110 from "./toolkits/postman.json" with { type: "json" };
import toolkit111 from "./toolkits/postmark.json" with { type: "json" };
import toolkit112 from "./toolkits/railway.json" with { type: "json" };
import toolkit113 from "./toolkits/reddit.json" with { type: "json" };
import toolkit114 from "./toolkits/resend.json" with { type: "json" };
import toolkit115 from "./toolkits/salesforce.json" with { type: "json" };
import toolkit116 from "./toolkits/semrush.json" with { type: "json" };
import toolkit117 from "./toolkits/sendgrid.json" with { type: "json" };
import toolkit118 from "./toolkits/sentry.json" with { type: "json" };
import toolkit119 from "./toolkits/serpapi.json" with { type: "json" };
import toolkit120 from "./toolkits/share_point.json" with { type: "json" };
import toolkit121 from "./toolkits/shortcut.json" with { type: "json" };
import toolkit122 from "./toolkits/slack.json" with { type: "json" };
import toolkit123 from "./toolkits/slackbot.json" with { type: "json" };
import toolkit124 from "./toolkits/smugmug.json" with { type: "json" };
import toolkit125 from "./toolkits/square.json" with { type: "json" };
import toolkit126 from "./toolkits/stack_exchange.json" with { type: "json" };
import toolkit127 from "./toolkits/strava.json" with { type: "json" };
import toolkit128 from "./toolkits/stripe.json" with { type: "json" };
import toolkit129 from "./toolkits/supabase.json" with { type: "json" };
import toolkit130 from "./toolkits/ticketmaster.json" with { type: "json" };
import toolkit131 from "./toolkits/ticktick.json" with { type: "json" };
import toolkit132 from "./toolkits/todoist.json" with { type: "json" };
import toolkit133 from "./toolkits/toneden.json" with { type: "json" };
import toolkit134 from "./toolkits/trello.json" with { type: "json" };
import toolkit135 from "./toolkits/tripadvisor.json" with { type: "json" };
import toolkit136 from "./toolkits/typeform.json" with { type: "json" };
import toolkit137 from "./toolkits/vercel.json" with { type: "json" };
import toolkit138 from "./toolkits/wakatime.json" with { type: "json" };
import toolkit139 from "./toolkits/webex.json" with { type: "json" };
import toolkit140 from "./toolkits/webflow.json" with { type: "json" };
import toolkit141 from "./toolkits/whatsapp.json" with { type: "json" };
import toolkit142 from "./toolkits/wolfram_alpha_api.json" with { type: "json" };
import toolkit143 from "./toolkits/wrike.json" with { type: "json" };
import toolkit144 from "./toolkits/yandex.json" with { type: "json" };
import toolkit145 from "./toolkits/youtube.json" with { type: "json" };
import toolkit146 from "./toolkits/zendesk.json" with { type: "json" };
import toolkit147 from "./toolkits/zeplin.json" with { type: "json" };
import toolkit148 from "./toolkits/zoho.json" with { type: "json" };
import toolkit149 from "./toolkits/zoom.json" with { type: "json" };

const catalogue: UnparsedComposioToolkitCatalogue = {
  toolkits: {
    "_1password": toolkit0,
    "agent_mail": toolkit1,
    "airtable": toolkit2,
    "algolia": toolkit3,
    "alpaca": toolkit4,
    "apollo": toolkit5,
    "artificial_analysis": toolkit6,
    "asana": toolkit7,
    "attio": toolkit8,
    "basecamp": toolkit9,
    "better_proposals": toolkit10,
    "bitbucket": toolkit11,
    "box": toolkit12,
    "browserbase_tool": toolkit13,
    "cal": toolkit14,
    "calendly": toolkit15,
    "canva": toolkit16,
    "clickhouse": toolkit17,
    "clickup": toolkit18,
    "cloudflare": toolkit19,
    "cloudflare_api_key": toolkit20,
    "cloudflare_browser_rendering": toolkit21,
    "coinbase": toolkit22,
    "confluence": toolkit23,
    "contentful": toolkit24,
    "convex": toolkit25,
    "crawlbase": toolkit26,
    "cursor": toolkit27,
    "databricks": toolkit28,
    "datadog": toolkit29,
    "devto": toolkit30,
    "digital_ocean": toolkit31,
    "discord": toolkit32,
    "discordbot": toolkit33,
    "docker_hub": toolkit34,
    "dropbox": toolkit35,
    "dropbox_sign": toolkit36,
    "dynamics365": toolkit37,
    "eventbrite": toolkit38,
    "excel": toolkit39,
    "facebook": toolkit40,
    "fathom": toolkit41,
    "figma": toolkit42,
    "firecrawl": toolkit43,
    "fireflies": toolkit44,
    "fly": toolkit45,
    "foursquare": toolkit46,
    "freshbooks": toolkit47,
    "freshdesk": toolkit48,
    "gamma": toolkit49,
    "giphy": toolkit50,
    "gist": toolkit51,
    "gitea": toolkit52,
    "github": toolkit53,
    "gitlab": toolkit54,
    "gmail": toolkit55,
    "google_analytics": toolkit56,
    "google_maps": toolkit57,
    "google_search_console": toolkit58,
    "googleads": toolkit59,
    "googlebigquery": toolkit60,
    "googlecalendar": toolkit61,
    "googledocs": toolkit62,
    "googledrive": toolkit63,
    "googlemeet": toolkit64,
    "googlephotos": toolkit65,
    "googlesheets": toolkit66,
    "googleslides": toolkit67,
    "googlesuper": toolkit68,
    "googletasks": toolkit69,
    "grafana": toolkit70,
    "gumroad": toolkit71,
    "harvest": toolkit72,
    "heygen": toolkit73,
    "hostinger": toolkit74,
    "hubspot": toolkit75,
    "hugging_face": toolkit76,
    "hyperbrowser": toolkit77,
    "incident_io": toolkit78,
    "instagram": toolkit79,
    "intercom": toolkit80,
    "jira": toolkit81,
    "kibana": toolkit82,
    "klaviyo": toolkit83,
    "launch_darkly": toolkit84,
    "line": toolkit85,
    "linear": toolkit86,
    "linkedin": toolkit87,
    "mailchimp": toolkit88,
    "metabase": toolkit89,
    "microsoft_clarity": toolkit90,
    "microsoft_teams": toolkit91,
    "miro": toolkit92,
    "mixpanel": toolkit93,
    "monday": toolkit94,
    "nasa": toolkit95,
    "nasdaq": toolkit96,
    "neon": toolkit97,
    "new_relic": toolkit98,
    "ngrok": toolkit99,
    "notion": toolkit100,
    "npm": toolkit101,
    "one_drive": toolkit102,
    "openweather_api": toolkit103,
    "outlook": toolkit104,
    "pagerduty": toolkit105,
    "pandadoc": toolkit106,
    "plausible_analytics": toolkit107,
    "polymarket_us": toolkit108,
    "posthog": toolkit109,
    "postman": toolkit110,
    "postmark": toolkit111,
    "railway": toolkit112,
    "reddit": toolkit113,
    "resend": toolkit114,
    "salesforce": toolkit115,
    "semrush": toolkit116,
    "sendgrid": toolkit117,
    "sentry": toolkit118,
    "serpapi": toolkit119,
    "share_point": toolkit120,
    "shortcut": toolkit121,
    "slack": toolkit122,
    "slackbot": toolkit123,
    "smugmug": toolkit124,
    "square": toolkit125,
    "stack_exchange": toolkit126,
    "strava": toolkit127,
    "stripe": toolkit128,
    "supabase": toolkit129,
    "ticketmaster": toolkit130,
    "ticktick": toolkit131,
    "todoist": toolkit132,
    "toneden": toolkit133,
    "trello": toolkit134,
    "tripadvisor": toolkit135,
    "typeform": toolkit136,
    "vercel": toolkit137,
    "wakatime": toolkit138,
    "webex": toolkit139,
    "webflow": toolkit140,
    "whatsapp": toolkit141,
    "wolfram_alpha_api": toolkit142,
    "wrike": toolkit143,
    "yandex": toolkit144,
    "youtube": toolkit145,
    "zendesk": toolkit146,
    "zeplin": toolkit147,
    "zoho": toolkit148,
    "zoom": toolkit149,
  },
};

export default catalogue;
