import {
	createToolCallActionHandler,
	executeAgentLoop,
	type AgentLoopState,
} from "@assistant/agent-core";
import type { ConversationManager } from "~/lib/conversationManager";
import {
	buildContinuationInstruction,
	buildInitialPlan,
	getAgentCompletionRequirements,
	shouldRequireToolChoice,
	withRequiredToolChoice,
} from "~/lib/chat/agent/completionRequirements";
import {
	createAgentProviderIO,
	type AgentModelResponse,
	type AgentModelToolCall,
} from "~/lib/chat/agent/provider-io";
import {
	DEFAULT_AGENT_MAX_STEPS,
	resolveAgentStepBudgetExtension,
} from "~/lib/chat/agent/stepBudget";
import { getAIResponse } from "~/lib/chat/responses";
import { handleToolCalls } from "~/lib/chat/tools";
import type { IRequest, Message } from "~/types";
import { AssistantError, ErrorType } from "~/utils/errors";
import { hasEnabledToolNames } from "~/utils/toolNames";

const AGENT_MAX_RECOVERY_REPLANS = 2;
const AGENT_MAX_DECISION_FAILURES = 2;

interface ApiAgentLoopState extends AgentLoopState {
	commandCount: number;
}

interface ApiAgentSharedContext {
	completionId: string;
	conversationManager: ConversationManager;
	toolRequestContext: IRequest;
}

export type ModelToolCall = AgentModelToolCall;
export type ModelResponse = AgentModelResponse;

export interface AgentLoopExecutionParams {
	requestParams: Parameters<typeof getAIResponse>[0];
	completionId: string;
	conversationManager: ConversationManager;
	toolRequestContext: IRequest;
	maxSteps?: number;
}

export interface AgentLoopExecutionResult {
	response: ModelResponse;
	toolResponses: Message[];
}

export async function runAgentLoop(
	params: AgentLoopExecutionParams,
): Promise<AgentLoopExecutionResult> {
	const providerIO = createAgentProviderIO();
	const runtimeMessages = providerIO.initialMessages(params.requestParams.messages);
	const completionRequirements = getAgentCompletionRequirements(params.requestParams);
	if (
		completionRequirements.minToolCalls > 0 &&
		!hasEnabledToolNames(params.requestParams.enabled_tools)
	) {
		throw new AssistantError(
			"Agent completion requires tool calls but no tools are enabled",
			ErrorType.PARAMS_ERROR,
		);
	}
	const state: ApiAgentLoopState = {
		commandCount: 0,
	};
	const toolResponses: Message[] = [];
	let finalResponse: ModelResponse | null = null;

	await executeAgentLoop<ApiAgentSharedContext, ApiAgentLoopState>({
		initialMessages: runtimeMessages,
		initialPlan: buildInitialPlan(completionRequirements),
		shared: {
			completionId: params.completionId,
			conversationManager: params.conversationManager,
			toolRequestContext: params.toolRequestContext,
		},
		state,
		config: {
			maxSteps: params.maxSteps || DEFAULT_AGENT_MAX_STEPS,
			maxConsecutiveDecisionFailures: AGENT_MAX_DECISION_FAILURES,
			maxRecoveryReplans: AGENT_MAX_RECOVERY_REPLANS,
		},
		getCommandCount: (runtimeState) => runtimeState.commandCount,
		onStepBudgetExceeded: ({ messages, state: runtimeState }) =>
			resolveAgentStepBudgetExtension({
				enabledTools: params.requestParams.enabled_tools,
				requirements: completionRequirements,
				commandCount: runtimeState.commandCount,
				messages,
			}),
		resolveDecision: async ({ messages }) => {
			const requestParams = withRequiredToolChoice(
				params.requestParams,
				shouldRequireToolChoice({
					requirements: completionRequirements,
					commandCount: state.commandCount,
					requestParams: params.requestParams,
				}),
			);
			const providerResponse = await getAIResponse({
				...requestParams,
				messages: providerIO.providerMessages(messages),
				stream: false,
			});

			if (providerResponse instanceof ReadableStream) {
				throw new AssistantError(
					"Agent mode expected non-streaming model response",
					ErrorType.PROVIDER_ERROR,
				);
			}

			const modelResponse = providerIO.modelResponse(providerResponse);
			if (!modelResponse.response && !modelResponse.tool_calls?.length) {
				throw new AssistantError("No response generated by the model", ErrorType.PARAMS_ERROR);
			}

			if (modelResponse.tool_calls?.length) {
				const toolCalls = providerIO.toolCallInvocations(modelResponse.tool_calls);
				return {
					decision: {
						action: "tool_calls",
						toolCalls,
						responseText: typeof modelResponse.response === "string" ? modelResponse.response : "",
					},
					assistantMessage: {
						role: "assistant",
						content: modelResponse.response || "",
						tool_calls: modelResponse.tool_calls,
					},
				};
			}

			if (completionRequirements.minToolCalls > state.commandCount) {
				return {
					decision: {
						action: "continue",
						instruction: buildContinuationInstruction({
							requirements: completionRequirements,
							commandCount: state.commandCount,
						}),
						reasoning: "Agent completion requirements were not met before the model returned text.",
					},
					assistantMessage: {
						role: "assistant",
						content: modelResponse.response || "",
					},
				};
			}

			finalResponse = modelResponse;
			return {
				decision: {
					action: "finish",
					summary:
						typeof modelResponse.response === "string"
							? modelResponse.response
							: JSON.stringify(modelResponse.response ?? ""),
				},
				assistantMessage: {
					role: "assistant",
					content: modelResponse.response || "",
				},
			};
		},
		handlers: [
			createToolCallActionHandler<ApiAgentSharedContext, ApiAgentLoopState>({
				onToolCalls: async (decision, context) => {
					const providerToolCalls = providerIO.providerToolCalls(decision.toolCalls);
					const toolResults = await handleToolCalls(
						context.shared.completionId,
						{
							response: decision.responseText || "",
							tool_calls: providerToolCalls,
						},
						context.shared.conversationManager,
						context.shared.toolRequestContext,
					);

					context.state.commandCount += providerToolCalls.length;
					toolResponses.push(...toolResults);
					context.messages.push(...toolResults);
				},
			}),
		],
	});

	if (!finalResponse) {
		throw new AssistantError(
			"Agent loop finished without a final response",
			ErrorType.PROVIDER_ERROR,
		);
	}

	return {
		response: finalResponse,
		toolResponses,
	};
}
