import type { TurnOutput } from "~/lib/chat/agent/assistant-turn";
import { createAgentProviderIO } from "~/lib/chat/agent/provider-io";
import { consumeProviderStream } from "~/lib/chat/agent/provider-stream";
import type { ChatEventSink } from "~/lib/chat/streaming/emitter";
import { getAIResponse } from "~/lib/chat/streaming/responses";
import type { ServiceContext } from "~/lib/context/serviceContext";
import { extractUsagePayload } from "~/lib/usage/extractUsage";
import { normaliseTokenUsage } from "~/lib/usage/tokenUsage";
import type { ChatCompletionParameters, IEnv, ToolCall } from "~/types";
import { AssistantError, ErrorType } from "~/utils/errors";

export interface TurnTransportContext {
  env: IEnv;
  completionId: string;
  model: string;
  provider: string;
  userId?: number;
  serviceContext?: ServiceContext;
  shouldStop?: () => boolean;
}

export interface ChatTurnTransport {
  readonly streams: boolean;
  runTurn(params: {
    request: ChatCompletionParameters;
    sink: ChatEventSink;
    context: TurnTransportContext;
  }): Promise<TurnOutput & { error?: unknown }>;
}

export function createBufferedTurnTransport(): ChatTurnTransport {
  const providerIO = createAgentProviderIO();

  return {
    streams: false,
    async runTurn({ request }) {
      const providerResponse = await getAIResponse({ ...request, stream: false });

      if (providerResponse instanceof ReadableStream) {
        throw new AssistantError(
          "Buffered turn expected a non-streaming model response",
          ErrorType.PROVIDER_ERROR,
        );
      }

      const modelResponse = providerIO.modelResponse(providerResponse);

      if (!modelResponse.response && !modelResponse.tool_calls?.length) {
        throw new AssistantError("No response generated by the model", ErrorType.PROVIDER_ERROR);
      }

      return {
        content: modelResponse.response ?? "",
        thinking: modelResponse.thinking,
        parts: modelResponse.parts,
        toolCalls: (modelResponse.tool_calls ?? []) as ToolCall[],
        citations: modelResponse.citations ?? [],
        usage: normaliseTokenUsage(extractUsagePayload(providerResponse)),
        structuredData: modelResponse.data,
        refusal: modelResponse.refusal ?? null,
        annotations: modelResponse.annotations ?? null,
        status: modelResponse.status,
        logId: modelResponse.log_id,
      };
    },
  };
}

export function createStreamingTurnTransport(): ChatTurnTransport {
  return {
    streams: true,
    async runTurn({ request, sink, context }) {
      const providerResponse = await getAIResponse({ ...request, stream: true });

      if (!(providerResponse instanceof ReadableStream)) {
        throw new AssistantError(
          "Streaming turn expected a provider stream",
          ErrorType.PROVIDER_ERROR,
        );
      }

      const streamed = await consumeProviderStream(providerResponse, sink, {
        env: context.env,
        model: context.model,
        provider: context.provider,
        completionId: context.completionId,
        userId: context.userId,
        serviceContext: context.serviceContext,
        shouldStop: context.shouldStop,
      });

      if (
        !streamed.content &&
        streamed.toolCalls.length === 0 &&
        streamed.parts.length === 0 &&
        !streamed.error &&
        !streamed.stopped
      ) {
        throw new AssistantError("No response generated by the model", ErrorType.PROVIDER_ERROR);
      }

      return {
        content: streamed.content,
        thinking: streamed.thinking,
        signature: streamed.signature,
        toolCalls: streamed.interrupted ? [] : streamed.toolCalls,
        citations: streamed.citations,
        usage: streamed.usage,
        structuredData: streamed.structuredData,
        refusal: streamed.refusal,
        annotations: streamed.annotations,
        parts: streamed.parts,
        error: streamed.error,
        status: streamed.interrupted ? "incomplete" : undefined,
        stopped: streamed.stopped,
      };
    },
  };
}
