import type { Hono } from "hono";

import activity from "~/modules/activity/api/routes";
import admin from "~/modules/admin/api/routes";
import apps from "~/modules/apps/api";
import { registerSandboxCredentialBrokerRoutes } from "~/modules/apps/api/sandbox/credential-broker";
import { registerSandboxPreviewAuthorisationRoute } from "~/modules/apps/api/sandbox/preview-authorisation";
import audio from "~/modules/audio/api/routes";
import auth from "~/modules/auth/api";
import capabilities from "~/modules/capabilities/api/routes";
import channels from "~/modules/channels/api/routes";
import chat from "~/modules/conversations/api/routes";
import decisions from "~/modules/decisions/api/routes";
import desktop from "~/modules/desktop-releases/api/routes";
import flags from "~/modules/experiments/api/routes";
import machines from "~/modules/machines/api/routes";
import memoryDocuments from "~/modules/memory-documents/api/routes";
import models from "~/modules/models/api/routes";
import outputs from "~/modules/outputs/api/routes";
import plans from "~/modules/plans/api/routes";
import notifications from "~/modules/project-tasks/api/notifications";
import realtime from "~/modules/realtime/api/routes";
import savedMessages from "~/modules/saved-messages/api/routes";
import search from "~/modules/search/api/routes";
import sites from "~/modules/sites/api/routes";
import skills from "~/modules/skills/api/routes";
import sources from "~/modules/sources/api/routes";
import stripe from "~/modules/subscription/api/routes";
import sync from "~/modules/sync/api/routes";
import tasks from "~/modules/tasks/api/routes";
import teammates from "~/modules/teammates/api";
import templates from "~/modules/templates/api/routes";
import tools from "~/modules/tools/api/routes";
import training from "~/modules/training/api/routes";
import uploads from "~/modules/uploads/api/routes";
import user from "~/modules/user/api";
import webhook from "~/modules/webhooks/api";
import workspaceInvitations from "~/modules/workspaces/api/invitations";
import projects from "~/modules/workspaces/api/projects";
import workspaces from "~/modules/workspaces/api/routes";
import type { IEnv } from "~/types";

type ApiApp = Hono<{ Bindings: IEnv }>;

export function registerApiRoutes(app: ApiApp): void {
  registerSandboxCredentialBrokerRoutes(app);
  registerSandboxPreviewAuthorisationRoute(app);
  app.route("/auth", auth);
  app.route("/activity", activity);
  app.route("/chat", chat);
  app.route("/apps", apps);
  app.route("/desktop", desktop);
  app.route("/machines", machines);
  app.route("/models", models);
  app.route("/notifications", notifications);
  app.route("/outputs", outputs);
  app.route("/tasks", tasks);
  app.route("/templates", templates);
  app.route("/tools", tools);
  app.route("/audio", audio);
  app.route("/capabilities", capabilities);
  app.route("/uploads", uploads);
  app.route("/user", user);
  app.route("/plans", plans);
  app.route("/flags", flags);
  app.route("/stripe", stripe);
  app.route("/skills", skills);
  app.route("/sources", sources);
  app.route("/realtime", realtime);
  app.route("/sync", sync);
  app.route("/search", search);
  app.route("/decisions", decisions);
  app.route("/sites", sites);
  app.route("/memory/documents", memoryDocuments);
  app.route("/chat/saved-messages", savedMessages);
  app.route("/channels", channels);
  app.route("/teammates", teammates);
  app.route("/admin", admin);
  app.route("/webhooks", webhook);
  app.route("/training", training);
  app.route("/workspaces", workspaces);
  app.route("/projects", projects);
  app.route("/workspace-invitations", workspaceInvitations);
}
