import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/model-tools.ts",
    "src/verbosity.ts",
    "src/attachments.ts",
    "src/compaction-command.ts",
    "src/goal-command.ts",
    "src/message-goal-status.ts",
    "src/conversation-storage-policy.ts",
    "src/conversation-types.ts",
    "src/message-parts.ts",
    "src/message-speech.ts",
    "src/messages.ts",
    "src/provider-messages.ts",
    "src/composer-commands.ts",
    "src/tool-results.ts",
    "src/weather.ts",
    "src/message-utils.ts",
    "src/markdown-editor.ts",
    "src/agent-trace.ts",
    "src/agent-trace-display.ts",
    "src/run-activity.ts",
    "src/textarea-selection-position.ts",
    "src/opinion.ts",
    "src/branching.ts",
    "src/message-compaction-status.ts",
    "src/conversations.ts",
    "src/model-selection.ts",
    "src/request-options.ts",
    "src/response-stats.ts",
    "src/turn-activity.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
});
