import {
  extractPredictionMetricsPayload,
  readServiceTier,
  extractUsagePayload,
  extractImpactPayload,
  normaliseTokenUsage,
} from "@ngriffin_uk/polychat-ai-telemetry";
import { AssistantError, ErrorType } from "@ngriffin_uk/polychat-utility-server/errors";

import type { ServiceContext } from "~/infrastructure/context/serviceContext";
import type { TurnOutput } from "~/modules/chat/application/agent/assistant-turn";
import { createAgentProviderIO } from "~/modules/chat/application/agent/provider-io";
import { consumeProviderStream } from "~/modules/chat/application/agent/provider-stream";
import type { ChatEventSink } from "~/modules/chat/application/streaming/emitter";
import { getAIResponse } from "~/modules/chat/application/streaming/responses";
import {
  runProviderCallWithRetry,
  type ProviderRetryExecutionOptions,
} from "~/modules/chat/domain/provider-retry";
import type { ChatCompletionParameters, IEnv, ToolCall } from "~/types";

export interface TurnTransportContext {
  env: IEnv;
  completionId: string;
  model: string;
  provider: string;
  userId?: number;
  serviceContext?: ServiceContext;
  shouldStop?: () => boolean;
  retry?: ProviderRetryExecutionOptions;
  step?: number;
}

async function requestProviderResponse(
  request: ChatCompletionParameters,
  context: TurnTransportContext,
) {
  const operation = () => getAIResponse(request);

  return context.retry ? runProviderCallWithRetry(operation, context.retry) : operation();
}

export interface ChatTurnTransport {
  readonly streams: boolean;
  runTurn(params: {
    request: ChatCompletionParameters;
    sink: ChatEventSink;
    context: TurnTransportContext;
  }): Promise<TurnOutput & { error?: unknown }>;
}

function formatBufferedTurn(providerResponse: unknown): TurnOutput {
  const modelResponse = createAgentProviderIO().modelResponse(providerResponse);

  if (!modelResponse.response && !modelResponse.tool_calls?.length) {
    throw new AssistantError("No response generated by the model", ErrorType.PROVIDER_ERROR);
  }

  return {
    content: modelResponse.response ?? "",
    thinking: modelResponse.thinking,
    parts: modelResponse.parts,
    toolCalls: (modelResponse.tool_calls ?? []) as ToolCall[],
    citations: modelResponse.citations ?? [],
    usage: normaliseTokenUsage(extractUsagePayload(providerResponse)),
    rawUsage:
      extractUsagePayload(providerResponse) ??
      extractPredictionMetricsPayload(providerResponse) ??
      undefined,
    impact: extractImpactPayload(providerResponse),
    serviceTier: readServiceTier(providerResponse),
    structuredData: modelResponse.data,
    refusal: modelResponse.refusal ?? null,
    annotations: modelResponse.annotations ?? null,
    status: modelResponse.status,
    logId: modelResponse.log_id,
  };
}

export function createBufferedTurnTransport(): ChatTurnTransport {
  return {
    streams: false,
    async runTurn({ request, context }) {
      const providerResponse = await requestProviderResponse(
        { ...request, stream: false },
        context,
      );

      if (providerResponse instanceof ReadableStream) {
        throw new AssistantError(
          "Buffered turn expected a non-streaming model response",
          ErrorType.PROVIDER_ERROR,
        );
      }

      return formatBufferedTurn(providerResponse);
    },
  };
}

export function createStreamingTurnTransport(): ChatTurnTransport {
  return {
    streams: true,
    async runTurn({ request, sink, context }) {
      const providerResponse = await requestProviderResponse({ ...request, stream: true }, context);

      if (!(providerResponse instanceof ReadableStream)) {
        return formatBufferedTurn(providerResponse);
      }

      const streamed = await consumeProviderStream(providerResponse, sink, {
        env: context.env,
        model: context.model,
        provider: context.provider,
        completionId: context.completionId,
        userId: context.userId,
        serviceContext: context.serviceContext,
        shouldStop: context.shouldStop,
        step: context.step,
      });

      if (
        !streamed.content &&
        streamed.toolCalls.length === 0 &&
        streamed.parts.length === 0 &&
        !streamed.error &&
        !streamed.stopped &&
        !streamed.interrupted
      ) {
        throw new AssistantError("No response generated by the model", ErrorType.PROVIDER_ERROR);
      }

      return {
        content: streamed.content,
        thinking: streamed.thinking,
        signature: streamed.signature,
        toolCalls: streamed.interrupted ? [] : streamed.toolCalls,
        citations: streamed.citations,
        usage: streamed.usage,
        rawUsage: streamed.rawUsage,
        impact: streamed.impact,
        serviceTier: streamed.serviceTier,
        structuredData: streamed.structuredData,
        refusal: streamed.refusal,
        annotations: streamed.annotations,
        parts: streamed.parts,
        error: streamed.error,
        status: streamed.interrupted ? "incomplete" : undefined,
        stopped: streamed.stopped,
        activityStreamed: true,
      };
    },
  };
}
