import { listSitePages, type SiteFile, type SiteProject } from "@ngriffin_uk/polychat-schemas";

import type { SiteComponentType } from "../catalog.js";
import { buildSiteGoogleFontsUrl, renderSiteThemeCss } from "../theme.js";
import { renderPageFile } from "./page.js";
import { renderIconModule, renderUiModule, renderUtilsModule } from "./support-files.js";
import { SITE_COMPONENT_TEMPLATES } from "./templates.js";

const PACKAGE_JSON = {
  private: true,
  scripts: { dev: "next dev", build: "next build", start: "next start" },
  dependencies: {
    clsx: "^2.1.1",
    "lucide-react": "^1.45.0",
    next: "^16.2.0",
    react: "^19.3.0",
    "react-dom": "^19.3.0",
    "tailwind-merge": "^3.4.0",
  },
  devDependencies: {
    "@tailwindcss/postcss": "^4.3.0",
    "@types/node": "^26.0.0",
    "@types/react": "^19.3.0",
    "@types/react-dom": "^19.3.0",
    tailwindcss: "^4.3.0",
    typescript: "^6.0.0",
  },
};

const TSCONFIG = {
  compilerOptions: {
    target: "ES2022",
    lib: ["dom", "dom.iterable", "esnext"],
    allowJs: true,
    skipLibCheck: true,
    strict: true,
    noEmit: true,
    esModuleInterop: true,
    module: "esnext",
    moduleResolution: "bundler",
    resolveJsonModule: true,
    isolatedModules: true,
    jsx: "preserve",
    incremental: true,
    plugins: [{ name: "next" }],
    paths: { "@/*": ["./*"] },
  },
  include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  exclude: ["node_modules"],
};

function renderGlobalsCss(project: SiteProject): string {
  return `@import "tailwindcss";

@custom-variant dark (&:is(.dark *));

${renderSiteThemeCss(project.theme)}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
  --font-sans: var(--font-sans);
  --font-heading: var(--font-heading);
}

@layer base {
  :where(*), ::before, ::after {
    @apply border-border outline-ring/50;
  }

  body {
    @apply bg-background text-foreground font-sans antialiased;
  }
}
`;
}

function renderLayout(project: SiteProject): string {
  const description = project.description ?? project.title;
  const dark = project.theme.mode === "dark";

  return `import type { Metadata } from "next";
import type { ReactNode } from "react";

import "./globals.css";

export const metadata: Metadata = {
  title: { default: ${JSON.stringify(project.title)}, template: ${JSON.stringify(`%s · ${project.title}`)} },
  description: ${JSON.stringify(description)},
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en"${dark ? ' className="dark"' : ""}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="stylesheet" href=${JSON.stringify(buildSiteGoogleFontsUrl(project.theme.font))} />
      </head>
      <body>{children}</body>
    </html>
  );
}
`;
}

function renderReadme(project: SiteProject, components: SiteComponentType[]): string {
  const pages = listSitePages(project)
    .map(({ page }) => `- \`${page.path}\` — ${page.title}`)
    .join("\n");

  return `# ${project.title}

${project.description ?? ""}

Generated by Polychat Sites as a Next.js app with Tailwind CSS v4. Every page composes the components in \`components/site\`, which follow shadcn/ui conventions and depend only on Tailwind, \`lucide-react\`, \`clsx\` and \`tailwind-merge\`.

## Run

\`\`\`sh
npm install
npm run dev
\`\`\`

## Pages

${pages}

## Components

${components.map((component) => `- \`components/site/${component}.tsx\``).join("\n")}

Theme tokens live in \`app/globals.css\`. Swap the palette by editing the CSS variables on \`:root\` and \`.dark\`.
`;
}

export interface GeneratedSiteFiles {
  files: SiteFile[];
  components: SiteComponentType[];
}

export function generateSiteFiles(project: SiteProject): GeneratedSiteFiles {
  const pages = listSitePages(project);
  const used = new Set<SiteComponentType>();
  const pageFiles: SiteFile[] = [];

  for (const { page } of pages) {
    const rendered = renderPageFile(page);

    pageFiles.push({ path: rendered.path, content: rendered.content });

    for (const component of rendered.components) {
      used.add(component);
    }
  }

  const components = [...used].sort();
  const componentFiles = components.map((component) => ({
    path: `components/site/${component}.tsx`,
    content: SITE_COMPONENT_TEMPLATES[component],
  }));
  const files: SiteFile[] = [
    { path: "README.md", content: renderReadme(project, components) },
    { path: "package.json", content: `${JSON.stringify(PACKAGE_JSON, null, 2)}\n` },
    { path: "tsconfig.json", content: `${JSON.stringify(TSCONFIG, null, 2)}\n` },
    {
      path: "next.config.ts",
      content:
        'import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n',
    },
    {
      path: "postcss.config.mjs",
      content: 'export default { plugins: { "@tailwindcss/postcss": {} } };\n',
    },
    { path: "app/globals.css", content: renderGlobalsCss(project) },
    { path: "app/layout.tsx", content: renderLayout(project) },
    ...pageFiles,
    { path: "lib/utils.ts", content: renderUtilsModule() },
    { path: "components/site/icon.tsx", content: renderIconModule() },
    { path: "components/site/ui.tsx", content: renderUiModule() },
    ...componentFiles,
  ];

  return { files, components };
}
