import type { MemoryDocumentRow } from "~/infrastructure/database/schema";
import type { IUser, IUserSettings } from "~/types";

export const nativeMemoryUser: IUser = {
  id: 1,
  plan_id: "pro",
  name: null,
  avatar_url: null,
  email: "fixture@example.test",
  github_username: null,
  company: null,
  site: null,
  location: null,
  bio: null,
  twitter_username: null,
  created_at: "2026-10-04",
  updated_at: "2026-10-04",
  setup_at: null,
  terms_accepted_at: null,
};

export const nativeMemorySettings: IUserSettings = {
  guardrails_enabled: false,
  guardrails_provider: "bedrock",
  bedrock_guardrail_id: null,
  bedrock_guardrail_version: null,
  embedding_provider: "cloudflare",
  bedrock_knowledge_base_id: null,
  bedrock_knowledge_base_custom_data_source_id: null,
  s3vectors_bucket_name: null,
  s3vectors_index_name: null,
  s3vectors_region: null,
  nickname: null,
  job_role: null,
  traits: null,
  preferences: null,
  memories_save_enabled: true,
  memories_chat_history_enabled: false,
  temporary_chats_default: false,
  memory_provider: "documents",
  transcription_provider: "cloudflare",
  transcription_model: "test-model",
  speech_provider: null,
  speech_model: null,
  search_provider: null,
  tracking_enabled: false,
  advertise_machines: false,
  sandbox_model: null,
  default_model_tier: null,
  default_model_id: null,
  default_compute_site: null,
  pet_source: null,
  pet_id: null,
  pet_travel_enabled: false,
  pet_animation_enabled: false,
  pet_model_overrides: { states: {}, families: {}, providers: {}, makers: {} },
  onboarding_seen: [],
};

export function memoryDocumentFixture(
  overrides: Partial<MemoryDocumentRow> = {},
): MemoryDocumentRow {
  return {
    id: "memory",
    name: "working-memory",
    kind: "teammate_context",
    content: "Prefer concise answers",
    tier: "core",
    summary: "Answer preferences",
    revision: 1,
    scope_type: "personal",
    scope_id: "1",
    created_by: 1,
    deleted_at: null,
    created_at: "2026-10-04",
    updated_at: "2026-10-04",
    ...overrides,
  };
}
