import { createSequentialProjectFlow, type ChatRun } from "@ngriffin_uk/polychat-schemas";

import { projectTaskFixture } from "./project-task-fixtures";

export const task = projectTaskFixture({
  id: "task-1",
  projectId: "project-1",
  workspaceId: "workspace-1",
  objective: "Ship the report",
  acceptanceCriteria: [{ id: "criterion-1", text: "Report exists" }],
  expectedOutput: null,
  context: null,
  constraints: null,
  dependsOnTaskIds: [],
  requireApprovalFor: [],
  status: "blocked",
  source: "user",
  blockedReason: "run_failed",
  blockedDetail: "Provider failed",
  runId: "run-2",
  dispatchTaskId: null,
  nodeId: "build",
  flowSnapshot: createSequentialProjectFlow([
    {
      id: "build",
      name: "Build",
      instructions: null,
      teammateId: null,
      skillIds: [],
      mode: null,
      requiresApprovalFor: [],
    },
  ]),
  flowExecution: {
    epoch: 1,
    nodeId: "build",
    steps: 1,
    iterations: {},
    values: {},
    waitId: "wait",
  },
  flowRevision: 1,
  runner: null,
  createdByUserId: 7,
  assigneeUserId: null,
  runnerIdentityUserId: 7,
  conversationId: "conversation-run-2",
  goalId: "goal-2",
  completions: [
    {
      id: "completion-1",
      nodeId: "plan",
      conversationId: "conversation-1",
      goalId: "goal-1",
      runId: "run-1",
      output: "Plan ready",
      evidence: [],
      approval: {
        mode: "automated",
        status: "approved",
        reviewedByUserId: null,
        reviewWaitId: null,
        reviewedAt: "2026-09-05T10:01:00.000Z",
      },
      createdAt: "2026-09-05T10:01:00.000Z",
    },
  ],
  position: 1000,
  tokenBudget: 1000,
  tokensSpent: 100,
  createdAt: "2026-09-05T09:00:00.000Z",
  updatedAt: "2026-09-05T10:01:00.000Z",
  startedAt: "2026-09-05T10:00:00.000Z",
  completedAt: null,
});

export function projectTaskEvidenceRun(
  id: string,
  nodeId: string,
  status: ChatRun["status"],
  attempt = 1,
): ChatRun {
  return {
    protocolVersion: 1,
    id,
    conversationId: `conversation-${id}`,
    projectId: "project-1",
    projectTaskId: "task-1",
    nodeId,
    initiatorUserId: 7,
    trigger: "user",
    status,
    attempt,
    createdAt: "2026-09-05T10:00:00.000Z",
    updatedAt: "2026-09-05T10:01:00.000Z",
    startedAt: "2026-09-05T10:00:00.000Z",
    completedAt: "2026-09-05T10:01:00.000Z",
    terminalReason: status === "failed" ? "Provider failed" : null,
    lastMessageId: null,
    context: null,
    retry: null,
  };
}
