name: Test

on:
  pull_request:
    branches:
      - canary
      - "*.x"
      - 'main'
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run checks
        run: pnpm check
      - name: Build schemas
        run: pnpm --filter @assistant/schemas build
      - name: Run typechecks
        run: pnpm typecheck
      - name: Run test
        run: pnpm test
      - name: Run coverage
        run: pnpm coverage
      - name: Coverage comment
        if: github.event_name == 'pull_request'
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: ./coverage/coverage-summary.json
          json-final-path: ./coverage/coverage-final.json
      - name: Coverage summary
        if: always()
        run: |
          echo "## 📊 Coverage Report" >> $GITHUB_STEP_SUMMARY
          if [ -f "./coverage/coverage-summary.json" ]; then
            echo "### Overall Coverage" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat ./coverage/coverage-summary.json >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "### Workspace Coverage" >> $GITHUB_STEP_SUMMARY
          for app in apps/*/; do
            if [ -f "${app}coverage/coverage-summary.json" ]; then
              echo "#### $(basename $app)" >> $GITHUB_STEP_SUMMARY
              echo '```json' >> $GITHUB_STEP_SUMMARY
              cat "${app}coverage/coverage-summary.json" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
            fi
          done
