import { createModelConfig, createModelConfigObject } from "~/lib/models/utils";
import type { ModelConfig } from "~/types";

const PROVIDER = "anthropic";

export const anthropicModelConfig: ModelConfig = createModelConfigObject([
  createModelConfig("claude-4-sonnet", PROVIDER, {
    name: "Claude 4 Sonnet",
    matchingModel: "claude-sonnet-4-0",
    description:
      "Combined with state-of-the-art coding, vision, and writing skills, you can use this model for a variety of use cases.",
    type: ["text"],
    card: "https://www.prompthub.us/models/claude-3-7-sonnet",
    contextWindow: 200000,
    maxTokens: 64000,
    costPer1kInputTokens: 0.003,
    costPer1kOutputTokens: 0.015,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "coding",
      "reasoning",
      "creative",
    ],
    contextComplexity: 5,
    reliability: 5,
    speed: 4,
    multimodal: true,
    hasThinking: false,
    isFeatured: true,
    includedInRouter: true,
    supportsArtifacts: true,
    supportsFunctions: true,
    supportsDocuments: true,
  }),

  createModelConfig("claude-4-sonnet-thinking", PROVIDER, {
    name: "Claude 4 Sonnet Thinking",
    matchingModel: "claude-sonnet-4-20250514",
    description:
      "Combined with state-of-the-art coding, vision, and writing skills, you can use this model for a variety of use cases.",
    type: ["text"],
    card: "https://www.prompthub.us/models/claude-3-7-sonnet",
    contextWindow: 200000,
    maxTokens: 64000,
    costPer1kInputTokens: 0.003,
    costPer1kOutputTokens: 0.015,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "coding",
      "reasoning",
      "creative",
    ],
    contextComplexity: 5,
    reliability: 5,
    speed: 4,
    multimodal: true,
    hasThinking: true,
    isFeatured: true,
    includedInRouter: true,
    supportsArtifacts: true,
    supportsFunctions: true,
    supportsDocuments: true,
  }),

  createModelConfig("claude-3.5-haiku", PROVIDER, {
    name: "Claude 3.5 Haiku",
    matchingModel: "claude-3-5-haiku-latest",
    description:
      "With fast speeds, improved instruction following, and more accurate tool use, Claude 3.5 Haiku is well suited for user-facing products, specialized sub-agent tasks, and generating personalized experiences from huge volumes of data.",
    type: ["text"],
    card: "https://www.prompthub.us/models/claude-3-5-haiku",
    contextWindow: 80000,
    maxTokens: 8192,
    costPer1kInputTokens: 0.001,
    costPer1kOutputTokens: 0.005,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "reasoning",
      "creative",
    ],
    contextComplexity: 3,
    reliability: 3,
    speed: 5,
    isFeatured: false,
    multimodal: true,
    supportsArtifacts: true,
    supportsFunctions: true,
    includedInRouter: true,
  }),

  createModelConfig("claude-4-opus", PROVIDER, {
    name: "Claude 4 Opus",
    matchingModel: "claude-opus-4-20250514",
    description:
      "The Claude 4 Opus is an advanced AI model by Anthropic designed for enterprise-level applications. It offers unmatched performance in handling complex tasks, making it an ideal solution for businesses requiring high-level data processing and analysis.",
    type: ["text"],
    card: "https://www.prompthub.us/models/claude-4-opus",
    contextWindow: 200000,
    maxTokens: 32000,
    costPer1kInputTokens: 0.015,
    costPer1kOutputTokens: 0.075,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "reasoning",
      "creative",
    ],
    contextComplexity: 5,
    reliability: 5,
    speed: 3,
    multimodal: true,
    isFeatured: false,
    supportsFunctions: true,
    supportsDocuments: true,
  }),
]);
