import type { ModelConfig } from "~/types";
import { createModelConfig, createModelConfigObject } from "./utils";

const PROVIDER = "bedrock";

// TODO: Cohere need a different input to nova, need to check others as well.
export const bedrockModelConfig: ModelConfig = createModelConfigObject([
  createModelConfig("nova-lite", PROVIDER, {
    name: "Amazon Nova Lite",
    matchingModel: "amazon.nova-lite-v1:0",
    description:
      "Amazon Nova Lite is a very low-cost multimodal model that is lightning fast for processing image, video, and text inputs. Amazon Nova Lite's accuracy across a breadth of tasks, coupled with its lightning-fast speed, makes it suitable for a wide range of interactive and high-volume applications where cost is a key consideration.",
    type: ["text", "image-to-text"],
    knowledgeCutoffDate: "October 2024",
    releaseDate: "December 3, 2024",
    lastUpdated: "December 3, 2024",
    modalities: {
      input: ["text", "image", "video"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    contextWindow: 300000,
    maxTokens: 5000,
    costPer1kInputTokens: 0.0008,
    costPer1kOutputTokens: 0.0016,
    strengths: ["analysis", "multilingual", "vision"],
    contextComplexity: 3,
    reliability: 3,
    speed: 4,
    multimodal: true,
    includedInRouter: true,
    supportsDocuments: true,
    supportsToolCalls: true,
  }),

  createModelConfig("nova-micro", PROVIDER, {
    name: "Amazon Nova Micro",
    matchingModel: "amazon.nova-micro-v1:0",
    description:
      "Amazon Nova Micro is a text only model that delivers the lowest latency responses at very low cost. It is highly performant at language understanding, translation, reasoning, code completion, brainstorming, and mathematical problem-solving. With its generation speed of over 200 tokens per second, Amazon Nova Micro is ideal for applications that require fast responses.",
    type: ["text", "coding"],
    knowledgeCutoffDate: "October 2024",
    releaseDate: "December 3, 2024",
    lastUpdated: "December 3, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 5000,
    costPer1kInputTokens: 0.0001,
    costPer1kOutputTokens: 0.0002,
    strengths: ["coding", "analysis", "multilingual"],
    contextComplexity: 2,
    reliability: 3,
    speed: 5,
    multimodal: false,
    includedInRouter: true,
    supportsToolCalls: true,
  }),

  createModelConfig("nova-pro", PROVIDER, {
    name: "Amazon Nova Pro",
    matchingModel: "amazon.nova-pro-v1:0",
    description:
      "Amazon Nova Pro is a highly capable multimodal model with the best combination of accuracy, speed, and cost for a wide range of tasks.  Amazon Nova Pro's capabilities, coupled with its industry-leading speed and cost efficiency, makes it a compelling model for almost any task, including video summarization, Q&A, mathematical reasoning, software development, and AI agents that can execute multi-step workflows.",
    type: ["text", "image-to-text"],
    knowledgeCutoffDate: "October 2024",
    releaseDate: "December 3, 2024",
    lastUpdated: "December 3, 2024",
    modalities: {
      input: ["text", "image", "video"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    contextWindow: 300000,
    maxTokens: 5000,
    costPer1kInputTokens: 0.0015,
    costPer1kOutputTokens: 0.006,
    strengths: ["coding", "analysis", "math", "reasoning", "vision"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    multimodal: true,
    supportsDocuments: true,
    supportsToolCalls: true,
  }),

  createModelConfig("nova-canvas", PROVIDER, {
    name: "Amazon Nova Canvas",
    matchingModel: "amazon.nova-canvas-v1:0",
    description:
      "Amazon Nova Canvas is a state-of-the-art image generation model that creates professional grade images from text or images provided in prompts. Amazon Nova Canvas also provides features that make it easy to edit images using text inputs, controls for adjusting color scheme and layout, and built-in controls to support safe and responsible use of AI.",
    type: ["text-to-image", "image-to-image"],
    beta: true,
    costPer1kInputTokens: 0.002,
    contextWindow: 1024,
    maxTokens: 1024,
    multimodal: true,
  }),

  createModelConfig("nova-reel", PROVIDER, {
    name: "Amazon Nova Reel",
    matchingModel: "amazon.nova-reel-v1:0",
    description:
      "Amazon Nova Reel is a state-of-the-art video generation model that allows customers to easily create high quality video from text and images. Amazon Nova Reel supports use of natural language prompts to control visual style and pacing, including camera motion control, and built-in controls to support safe and responsible use of AI.",
    type: ["text-to-video", "image-to-video"],
    beta: true,
    contextWindow: 512,
    maxTokens: 512,
    multimodal: true,
  }),

  createModelConfig("anthropic.claude-sonnet-4", PROVIDER, {
    name: "Claude 4 Sonnet (Bedrock US)",
    matchingModel: "us.anthropic.claude-sonnet-4-20250514-v1:0",
    description:
      "Combined with state-of-the-art coding, vision, and writing skills, you can use this model for a variety of use cases.",
    type: ["text"],
    knowledgeCutoffDate: "March 2025",
    releaseDate: "May 22, 2025",
    lastUpdated: "May 22, 2025",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    card: "https://www.prompthub.us/models/claude-4-sonnet",
    contextWindow: 200000,
    maxTokens: 64000,
    costPer1kInputTokens: 0.003,
    costPer1kOutputTokens: 0.015,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "coding",
      "reasoning",
      "creative",
    ],
    contextComplexity: 5,
    reliability: 5,
    speed: 4,
    multimodal: true,
    supportsReasoning: false,
    isFeatured: true,
    includedInRouter: true,
    supportsArtifacts: true,
    supportsToolCalls: true,
    supportsSearchGrounding: true,
    supportsCodeExecution: true,
    supportsDocuments: true,
  }),

  createModelConfig("anthropic.claude-3-5-haiku", PROVIDER, {
    name: "Claude 3.5 Haiku (Bedrock US)",
    matchingModel: "us.anthropic.claude-3-5-haiku-20241022-v1:0",
    description:
      "With fast speeds, improved instruction following, and more accurate tool use, Claude 3.5 Haiku is well suited for user-facing products, specialized sub-agent tasks, and generating personalized experiences from huge volumes of data.",
    type: ["text"],
    knowledgeCutoffDate: "July 2024",
    releaseDate: "October 22, 2024",
    lastUpdated: "October 22, 2024",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    card: "https://www.prompthub.us/models/claude-3-5-haiku",
    contextWindow: 80000,
    maxTokens: 8192,
    costPer1kInputTokens: 0.001,
    costPer1kOutputTokens: 0.005,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "reasoning",
      "creative",
    ],
    contextComplexity: 3,
    reliability: 3,
    speed: 5,
    isFeatured: false,
    multimodal: true,
    supportsArtifacts: true,
    supportsToolCalls: true,
    supportsSearchGrounding: true,
    supportsCodeExecution: true,
    includedInRouter: true,
    supportsTokenCounting: true,
  }),

  createModelConfig("anthropic.claude-opus-4", PROVIDER, {
    name: "Claude 4 Opus (Bedrock US)",
    matchingModel: "us.anthropic.claude-opus-4-20250514-v1:0",
    description:
      "The Claude 4 Opus is an advanced AI model by Anthropic designed for enterprise-level applications. It offers unmatched performance in handling complex tasks, making it an ideal solution for businesses requiring high-level data processing and analysis.",
    type: ["text"],
    knowledgeCutoffDate: "March 2025",
    releaseDate: "May 22, 2025",
    lastUpdated: "May 22, 2025",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    card: "https://www.prompthub.us/models/claude-4-opus",
    contextWindow: 200000,
    maxTokens: 32000,
    costPer1kInputTokens: 0.015,
    costPer1kOutputTokens: 0.075,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "reasoning",
      "creative",
    ],
    contextComplexity: 5,
    reliability: 5,
    speed: 3,
    multimodal: true,
    supportsToolCalls: true,
    supportsSearchGrounding: true,
    supportsCodeExecution: true,
    supportsDocuments: true,
    supportsTokenCounting: true,
    isFeatured: false,
  }),

  createModelConfig("anthropic.claude-opus-4-1", PROVIDER, {
    name: "Claude 4.1 Opus (Bedrock US)",
    matchingModel: "us.anthropic.claude-opus-4-1-20250805-v1:0",
    description:
      "Enhanced Claude 4 Opus with improved reasoning and analysis capabilities.",
    type: ["text"],
    knowledgeCutoffDate: "March 2025",
    releaseDate: "August 5, 2025",
    lastUpdated: "August 5, 2025",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    card: "https://www.prompthub.us/models/claude-4-opus",
    contextWindow: 200000,
    maxTokens: 32000,
    costPer1kInputTokens: 0.015,
    costPer1kOutputTokens: 0.075,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "reasoning",
      "creative",
    ],
    contextComplexity: 5,
    reliability: 5,
    speed: 3,
    multimodal: true,
    supportsReasoning: true,
    supportsArtifacts: true,
    supportsToolCalls: true,
    isFeatured: true,
  }),

  createModelConfig("anthropic.claude-3-7-sonnet", PROVIDER, {
    name: "Claude 3.7 Sonnet (Bedrock US)",
    matchingModel: "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
    description:
      "Advanced reasoning model with enhanced capabilities for complex analytical tasks.",
    type: ["text"],
    knowledgeCutoffDate: "October 2024",
    releaseDate: "February 19, 2025",
    lastUpdated: "February 19, 2025",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    card: "https://www.prompthub.us/models/claude-3-7-sonnet",
    contextWindow: 200000,
    maxTokens: 64000,
    costPer1kInputTokens: 0.003,
    costPer1kOutputTokens: 0.015,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "coding",
      "reasoning",
      "creative",
    ],
    contextComplexity: 5,
    reliability: 5,
    speed: 3,
    multimodal: true,
    supportsReasoning: true,
    supportsArtifacts: true,
    supportsToolCalls: true,
    supportsTokenCounting: true,
    isFeatured: true,
  }),

  createModelConfig("embed-english", PROVIDER, {
    name: "Cohere Embed English",
    matchingModel: "cohere.embed-english-v3",
    type: ["embedding"],
    costPer1kInputTokens: 0.0001,
  }),

  createModelConfig("embed-multilingual", PROVIDER, {
    name: "Cohere Embed Multilingual",
    matchingModel: "cohere.embed-multilingual-v3",
    type: ["embedding"],
    costPer1kInputTokens: 0.0001,
  }),

  createModelConfig("command-r", PROVIDER, {
    name: "Cohere Command R",
    matchingModel: "cohere.command-r-v1:0",
    description:
      "Command R is an instruction-following conversational model that performs language tasks at a higher quality, more reliably, and with a longer context than previous models. It can be used for complex workflows like code generation, retrieval augmented generation (RAG), tool use, and agents.",
    type: ["text"],
    knowledgeCutoffDate: "April 2024",
    releaseDate: "March 11, 2024",
    lastUpdated: "March 11, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 4096,
    costPer1kInputTokens: 0.0005,
    costPer1kOutputTokens: 0.0015,
    strengths: ["summarization", "analysis"],
    contextComplexity: 3,
    reliability: 3,
    speed: 3,
  }),

  createModelConfig("command-r-plus", PROVIDER, {
    name: "Cohere Command R+",
    matchingModel: "cohere.command-r-plus-v1:0",
    description:
      "Command R+ is an instruction-following conversational model that performs language tasks at a higher quality, more reliably, and with a longer context than previous models. It is best suited for complex RAG workflows and multi-step tool use.",
    type: ["text"],
    knowledgeCutoffDate: "April 2024",
    releaseDate: "April 4, 2024",
    lastUpdated: "April 4, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 4096,
    costPer1kInputTokens: 0.003,
    costPer1kOutputTokens: 0.015,
    strengths: ["summarization", "analysis", "reasoning"],
    contextComplexity: 4,
    reliability: 4,
    speed: 2,
  }),

  createModelConfig("jamba-large", PROVIDER, {
    name: "AI21 Jamba 1.5 Large",
    matchingModel: "ai21.jamba-1-5-large-v1:0",
    description:
      "Jamba 1.5 Large (94B active/398B total) is built for superior long context handling, speed, and quality. They mark the first time a non-Transformer model has been successfully scaled to the quality and strength of the market's leading models.",
    type: ["text", "instruct"],
    knowledgeCutoffDate: "August 2024",
    releaseDate: "August 15, 2024",
    lastUpdated: "August 15, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 8000,
    costPer1kInputTokens: 0.002,
    costPer1kOutputTokens: 0.008,
    strengths: ["analysis", "reasoning"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
  }),

  createModelConfig("jamba-mini", PROVIDER, {
    name: "AI21 Jamba 1.5 Mini",
    matchingModel: "ai21.jamba-1-5-mini-v1:0",
    description:
      "Jamba 1.5 Mini (12B active/52B total) is built for superior long context handling, speed, and quality. They mark the first time a non-Transformer model has been successfully scaled to the quality and strength of the market's leading models.",
    type: ["text", "instruct"],
    knowledgeCutoffDate: "August 2024",
    releaseDate: "August 15, 2024",
    lastUpdated: "August 15, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 8000,
    costPer1kInputTokens: 0.0002,
    costPer1kOutputTokens: 0.0004,
    strengths: ["analysis"],
    contextComplexity: 3,
    reliability: 3,
    speed: 4,
  }),

  createModelConfig("jambda-instruct", PROVIDER, {
    name: "AI21 Jambda Instruct",
    matchingModel: "ai21.jamba-instruct-v1:0",
    description:
      "Jambda Instruct is an aligned version of Jamba with additional training, chat capabilities, and safety guardrails to make it suitable for immediate and secure enterprise use.",
    type: ["text", "instruct"],
    knowledgeCutoffDate: "August 2024",
    releaseDate: "August 15, 2024",
    lastUpdated: "August 15, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 8000,
    costPer1kInputTokens: 0.0005,
    costPer1kOutputTokens: 0.0007,
    strengths: ["summarization", "analysis"],
    contextComplexity: 3,
    reliability: 4,
    speed: 3,
  }),

  createModelConfig("nova-premier", PROVIDER, {
    name: "Amazon Nova Premier",
    matchingModel: "amazon.nova-premier-v1:0",
    description:
      "Amazon Nova Premier is the most capable multimodal model in the Nova family with advanced reasoning capabilities.",
    type: ["text", "image-to-text"],
    knowledgeCutoffDate: "October 2024",
    releaseDate: "December 3, 2024",
    lastUpdated: "December 3, 2024",
    modalities: {
      input: ["text", "image", "video"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    contextWindow: 1000000,
    maxTokens: 16384,
    costPer1kInputTokens: 0.0025,
    costPer1kOutputTokens: 0.0125,
    strengths: ["coding", "analysis", "math", "reasoning", "vision"],
    contextComplexity: 5,
    reliability: 5,
    speed: 2,
    multimodal: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    supportsDocuments: true,
  }),

  createModelConfig("llama-3-2-90b-bedrock", PROVIDER, {
    name: "Llama 3.2 90B Instruct",
    matchingModel: "meta.llama3-2-90b-instruct-v1:0",
    description:
      "Large multimodal model with 90B parameters offering strong vision and language capabilities.",
    type: ["text", "image-to-text"],
    knowledgeCutoffDate: "December 2023",
    releaseDate: "September 25, 2024",
    lastUpdated: "September 25, 2024",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 4096,
    costPer1kInputTokens: 0.00072,
    costPer1kOutputTokens: 0.00072,
    strengths: ["analysis", "reasoning", "vision"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    multimodal: true,
    supportsToolCalls: true,
  }),

  createModelConfig("llama-3-1-70b-bedrock", PROVIDER, {
    name: "Llama 3.1 70B Instruct",
    matchingModel: "meta.llama3-1-70b-instruct-v1:0",
    description:
      "Large language model with 70B parameters offering strong performance across various tasks.",
    type: ["text"],
    knowledgeCutoffDate: "December 2023",
    releaseDate: "July 23, 2024",
    lastUpdated: "July 23, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 4096,
    costPer1kInputTokens: 0.00072,
    costPer1kOutputTokens: 0.00072,
    strengths: ["analysis", "reasoning", "coding"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    supportsToolCalls: true,
  }),

  createModelConfig("deepseek-r1-bedrock", PROVIDER, {
    name: "DeepSeek-R1",
    matchingModel: "deepseek.r1-v1:0",
    description:
      "Advanced reasoning model with strong performance in mathematical and logical tasks.",
    type: ["text"],
    knowledgeCutoffDate: "July 2024",
    releaseDate: "January 20, 2025",
    lastUpdated: "May 29, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 32768,
    costPer1kInputTokens: 0.00135,
    costPer1kOutputTokens: 0.0054,
    strengths: ["math", "reasoning", "analysis"],
    contextComplexity: 5,
    reliability: 4,
    speed: 3,
    supportsReasoning: true,
    supportsToolCalls: true,
  }),

  createModelConfig("marengo-embed", PROVIDER, {
    name: "Twelve Labs Marengo Embed",
    matchingModel: "twelvelabs.marengo-embed-2-7-v1:0",
    description:
      "Advanced multimodal embedding model that generates vector representations from text, image, speech, and video inputs for semantic search and retrieval applications.",
    type: ["embedding"],
    knowledgeCutoffDate: "2024",
    releaseDate: "2024",
    lastUpdated: "2024",
    modalities: {
      input: ["text", "image", "audio", "video"],
      output: ["embedding"],
    },
    supportsAttachments: true,
    supportsTemperature: false,
    contextWindow: 8192,
    maxTokens: 512,
    costPer1kInputTokens: 0.0001,
    costPer1kOutputTokens: 0.0001,
    strengths: ["vision", "search", "analysis"],
    contextComplexity: 3,
    reliability: 4,
    speed: 4,
    multimodal: true,
    includedInRouter: false,
  }),

  createModelConfig("pegasus-video", PROVIDER, {
    name: "Twelve Labs Pegasus",
    matchingModel: "twelvelabs.pegasus-1-2-v1:0",
    description:
      "Advanced video understanding model that analyzes video content and generates detailed text responses, perfect for video summarization, content analysis, and multimodal question answering.",
    type: ["text"],
    knowledgeCutoffDate: "2024",
    releaseDate: "2024",
    lastUpdated: "2024",
    modalities: {
      input: ["text", "video"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    contextWindow: 16384,
    maxTokens: 4096,
    costPer1kInputTokens: 0.003,
    costPer1kOutputTokens: 0.006,
    strengths: ["vision", "analysis", "summarization"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    multimodal: true,
    supportsStreaming: true,
    includedInRouter: false,
    supportsDocuments: false,
  }),
]);
