export const availableCapabilities = [
  "research",
  "coding",
  "math",
  "creative",
  "analysis",
  "chat",
  "search",
  "multilingual",
  "reasoning",
  "vision",
  "summarization",
  "audio",
  "academic",
  "instruction",
  "general_knowledge",
  "image_generation",
  "agents",
  "tool_use",
  "video_generation",
  "text-to-audio",
  "ocr",
] as const;

export const availableModelTypes = [
  "text",
  "coding",
  "speech",
  "text-to-speech",
  "text-to-audio",
  "audio-to-text",
  "image-to-text",
  "image-to-image",
  "text-to-image",
  "embedding",
  "reranking",
  "instruct",
  "text-to-video",
  "image-to-video",
  "guardrails",
  "code-edits",
  "function-calling",
  "voice-activity-detection",
  "ocr",
  "video-to-video",
  "audio-to-video",
] as const;

export const defaultModel = "mistral-medium";
export const defaultProvider = "mistral";
