import type { ModelConfig } from "~/types";

export const fireworksModelConfig: ModelConfig = {
  "gpt-oss-120b-fireworks": {
    name: "GPT OSS 120B",
    matchingModel: "accounts/fireworks/gpt-oss-120b",
    description:
      "Large 120B parameter open-source GPT model optimized for reasoning and complex tasks.",
    provider: "fireworks",
    type: ["text"],
    releaseDate: "August 5, 2025",
    lastUpdated: "August 5, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 131072,
    maxTokens: 32768,
    costPer1kInputTokens: 0.00015,
    costPer1kOutputTokens: 0.0006,
    strengths: ["reasoning", "analysis", "coding", "multilingual"],
    contextComplexity: 5,
    reliability: 4,
    speed: 2,
    includedInRouter: true,
    supportsArtifacts: true,
  },

  "gpt-oss-20b-fireworks": {
    name: "GPT OSS 20B",
    matchingModel: "accounts/fireworks/gpt-oss-20b",
    description:
      "Efficient 20B parameter open-source GPT model for fast reasoning and general tasks.",
    provider: "fireworks",
    type: ["text"],
    releaseDate: "August 5, 2025",
    lastUpdated: "August 5, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 131072,
    maxTokens: 32768,
    costPer1kInputTokens: 0.00005,
    costPer1kOutputTokens: 0.0002,
    strengths: ["reasoning", "analysis", "coding"],
    contextComplexity: 4,
    reliability: 4,
    speed: 4,
    includedInRouter: true,
    supportsArtifacts: true,
  },

  "deepseek-r1-fireworks": {
    name: "DeepSeek R1 (Fireworks)",
    matchingModel: "accounts/fireworks/models/deepseek-r1-0528",
    description:
      "Advanced DeepSeek R1 reasoning model hosted on Fireworks with enhanced mathematical and logical capabilities.",
    provider: "fireworks",
    type: ["text"],
    knowledgeCutoffDate: "May 2025",
    releaseDate: "May 28, 2025",
    lastUpdated: "May 28, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 160000,
    maxTokens: 16384,
    costPer1kInputTokens: 0.003,
    costPer1kOutputTokens: 0.008,
    strengths: ["reasoning", "math", "analysis", "coding"],
    contextComplexity: 5,
    reliability: 5,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "qwen3-235b-fireworks": {
    name: "Qwen3 235B-A22B",
    matchingModel: "accounts/fireworks/models/qwen3-235b-a22b",
    description:
      "Large-scale Qwen3 model with 235B parameters, offering strong reasoning and language understanding.",
    provider: "fireworks",
    type: ["text"],
    knowledgeCutoffDate: "April 2025",
    releaseDate: "April 29, 2025",
    lastUpdated: "April 29, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 16384,
    costPer1kInputTokens: 0.00022,
    costPer1kOutputTokens: 0.00088,
    strengths: ["reasoning", "analysis", "multilingual", "coding"],
    contextComplexity: 5,
    reliability: 4,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "deepseek-v3-fireworks": {
    name: "DeepSeek V3 (Fireworks)",
    matchingModel: "accounts/fireworks/models/deepseek-v3-0324",
    description:
      "DeepSeek V3 model hosted on Fireworks, optimized for coding and analytical tasks.",
    provider: "fireworks",
    type: ["text"],
    knowledgeCutoffDate: "October 2024",
    releaseDate: "March 24, 2025",
    lastUpdated: "March 24, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    contextWindow: 160000,
    maxTokens: 16384,
    costPer1kInputTokens: 0.0009,
    costPer1kOutputTokens: 0.0009,
    strengths: ["coding", "analysis", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "kimi-k2-fireworks": {
    name: "Kimi K2 Instruct",
    matchingModel: "accounts/fireworks/models/kimi-k2-instruct",
    description:
      "Kimi K2 instruction-following model optimized for conversational AI and task completion.",
    provider: "fireworks",
    type: ["text"],
    knowledgeCutoffDate: "October 2024",
    releaseDate: "July 11, 2025",
    lastUpdated: "July 11, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 16384,
    costPer1kInputTokens: 0.001,
    costPer1kOutputTokens: 0.003,
    strengths: ["chat", "analysis", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },
};
