import type { ModelConfig } from "~/types";

export const githubModelsConfig: ModelConfig = {
  "Phi-4": {
    name: "Phi 4",
    matchingModel: "Phi-4",
    provider: "github-models",
    type: ["text"],
    hasThinking: true,
    strengths: ["reasoning", "chat", "general_knowledge"],
    contextWindow: 16000,
    maxTokens: 16000,
  },
  "Phi-4-Reasoning": {
    name: "Phi 4 Reasoning",
    matchingModel: "Phi-4-reasoning",
    provider: "github-models",
    type: ["text"],
    hasThinking: true,
    strengths: ["reasoning", "chat", "general_knowledge"],
    contextWindow: 16000,
    maxTokens: 16000,
  },
  "Phi-4-mini-Reasoning": {
    name: "Phi 4 Mini Reasoning",
    matchingModel: "Phi-4-mini-reasoning",
    provider: "github-models",
    type: ["text"],
    hasThinking: true,
    strengths: ["reasoning", "chat", "general_knowledge"],
    contextWindow: 16000,
    maxTokens: 16000,
  },
  "Phi-4-mini-instruct": {
    name: "Phi 4 Mini Instruct",
    matchingModel: "Phi-4-mini-instruct",
    provider: "github-models",
    type: ["text"],
    strengths: ["reasoning", "multilingual", "chat", "general_knowledge"],
    contextWindow: 1280000,
    maxTokens: 4000,
    supportsArtifacts: true,
  },
  "Phi-4-multimodal-instruct": {
    name: "Phi 4 Multimodal Instruct",
    matchingModel: "Phi-4-multimodal-instruct",
    provider: "github-models",
    type: ["text", "image-to-text"],
    strengths: [
      "vision",
      "audio",
      "summarization",
      "chat",
      "general_knowledge",
    ],
    contextWindow: 1280000,
    maxTokens: 4000,
    supportsArtifacts: true,
  },
  "gh-grok-3": {
    name: "Grok 3",
    matchingModel: "grok-3",
    description:
      "Grok 3 is xAI's debut model, pretrained by Colossus at supermassive scale to excel in specialized domains like finance, healthcare, and the law.",
    provider: "github-models",
    type: ["text"],
    contextWindow: 131000,
    maxTokens: 4096,
  },
  "gh-grok-3-mini": {
    name: "Grok 3 Mini",
    matchingModel: "grok-3-mini",
    description:
      "A lightweight model that thinks before responding. Fast, smart, and great for logic-based tasks that do not require deep domain knowledge. The raw thinking traces are accessible.",
    provider: "github-models",
    type: ["text"],
    contextWindow: 131000,
    maxTokens: 4096,
  },
};
