import type { ModelConfig } from "~/types";

export const githubModelsConfig: ModelConfig = {
  "jamba-1-5-mini-gh": {
    name: "AI21 Jamba 1.5 Mini (GitHub)",
    matchingModel: "ai21-labs/ai21-jamba-1.5-mini",
    description:
      "Efficient hybrid architecture model combining Transformer and Mamba layers for speed and context handling.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "March 2024",
    releaseDate: "August 29, 2024",
    lastUpdated: "August 29, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 256000,
    maxTokens: 4096,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["analysis", "reasoning", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    speed: 4,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "jamba-1-5-large-gh": {
    name: "AI21 Jamba 1.5 Large (GitHub)",
    matchingModel: "ai21-labs/ai21-jamba-1.5-large",
    description:
      "Large-scale hybrid architecture model for complex reasoning and analysis tasks.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "March 2024",
    releaseDate: "August 29, 2024",
    lastUpdated: "August 29, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 256000,
    maxTokens: 4096,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["analysis", "reasoning", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "gpt-4-1-mini-gh": {
    name: "GPT-4.1 Mini (GitHub)",
    matchingModel: "openai/gpt-4.1-mini",
    description:
      "Advanced GPT model with improved instruction following and 1M context window.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "April 2024",
    releaseDate: "April 14, 2025",
    lastUpdated: "April 14, 2025",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 16384,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["coding", "analysis", "chat", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    speed: 4,
    multimodal: true,
    includedInRouter: true,
    supportsArtifacts: true,
  },

  "o4-mini-gh": {
    name: "OpenAI o4-mini (GitHub)",
    matchingModel: "openai/o4-mini",
    description:
      "Reasoning model optimized for complex problem-solving with enhanced mathematical capabilities.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "April 2024",
    releaseDate: "January 31, 2025",
    lastUpdated: "January 31, 2025",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: false,
    supportsReasoning: true,
    supportsToolCalls: false,
    contextWindow: 200000,
    maxTokens: 100000,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "math", "analysis", "coding"],
    contextComplexity: 5,
    reliability: 5,
    speed: 3,
    multimodal: true,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "o1-mini-gh": {
    name: "OpenAI o1-mini (GitHub)",
    matchingModel: "openai/o1-mini",
    description:
      "Compact reasoning model for mathematical and logical problem-solving.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "October 2023",
    releaseDate: "September 12, 2024",
    lastUpdated: "December 17, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: false,
    supportsReasoning: true,
    supportsToolCalls: false,
    contextWindow: 128000,
    maxTokens: 65536,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "math", "analysis"],
    contextComplexity: 4,
    reliability: 4,
    speed: 4,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "gpt-4o-mini-gh": {
    name: "GPT-4o Mini (GitHub)",
    matchingModel: "openai/gpt-4o-mini",
    description:
      "Efficient multimodal model with support for text, image, and audio inputs.",
    provider: "github-models",
    type: ["text", "image-to-text"],
    knowledgeCutoffDate: "October 2023",
    releaseDate: "July 18, 2024",
    lastUpdated: "July 18, 2024",
    modalities: {
      input: ["text", "image", "audio"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 16384,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["chat", "analysis", "vision", "audio"],
    contextComplexity: 3,
    reliability: 4,
    speed: 5,
    multimodal: true,
    includedInRouter: true,
    supportsArtifacts: true,
  },

  "gpt-4o-gh": {
    name: "GPT-4o (GitHub)",
    matchingModel: "openai/gpt-4o",
    description:
      "Advanced multimodal GPT model with enhanced vision and audio capabilities.",
    provider: "github-models",
    type: ["text", "image-to-text"],
    knowledgeCutoffDate: "October 2023",
    releaseDate: "May 13, 2024",
    lastUpdated: "May 13, 2024",
    modalities: {
      input: ["text", "image", "audio"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 16384,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["chat", "analysis", "vision", "audio", "coding"],
    contextComplexity: 4,
    reliability: 4,
    speed: 4,
    multimodal: true,
    includedInRouter: true,
    supportsArtifacts: true,
  },

  "o3-mini-gh": {
    name: "OpenAI o3-mini (GitHub)",
    matchingModel: "openai/o3-mini",
    description:
      "Latest compact reasoning model with enhanced problem-solving capabilities.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "April 2024",
    releaseDate: "January 31, 2025",
    lastUpdated: "January 31, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: false,
    supportsReasoning: true,
    supportsToolCalls: false,
    contextWindow: 200000,
    maxTokens: 100000,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "math", "analysis", "coding"],
    contextComplexity: 5,
    reliability: 5,
    speed: 4,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "o1-gh": {
    name: "OpenAI o1 (GitHub)",
    matchingModel: "openai/o1",
    description:
      "Advanced reasoning model with multimodal capabilities and enhanced logical thinking.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "October 2023",
    releaseDate: "September 12, 2024",
    lastUpdated: "December 17, 2024",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: false,
    supportsReasoning: true,
    supportsToolCalls: false,
    contextWindow: 200000,
    maxTokens: 100000,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "math", "analysis", "coding"],
    contextComplexity: 5,
    reliability: 5,
    speed: 2,
    multimodal: true,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "phi-4-gh": {
    name: "Phi-4 (GitHub)",
    matchingModel: "microsoft/phi-4",
    description:
      "Microsoft's latest small language model optimized for reasoning and code generation.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "October 2023",
    releaseDate: "December 11, 2024",
    lastUpdated: "December 11, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 16000,
    maxTokens: 4096,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "coding", "analysis", "math"],
    contextComplexity: 4,
    reliability: 4,
    speed: 4,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "phi-4-multimodal-gh": {
    name: "Phi-4 Multimodal (GitHub)",
    matchingModel: "microsoft/phi-4-multimodal-instruct",
    description:
      "Multimodal version of Phi-4 with vision and audio capabilities.",
    provider: "github-models",
    type: ["text", "image-to-text"],
    knowledgeCutoffDate: "October 2023",
    releaseDate: "December 11, 2024",
    lastUpdated: "December 11, 2024",
    modalities: {
      input: ["text", "image", "audio"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 4096,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "vision", "audio", "analysis"],
    contextComplexity: 4,
    reliability: 4,
    speed: 4,
    multimodal: true,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "phi-4-reasoning-gh": {
    name: "Phi-4 Reasoning (GitHub)",
    matchingModel: "microsoft/phi-4-reasoning",
    description:
      "Specialized version of Phi-4 optimized for complex reasoning tasks.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "October 2023",
    releaseDate: "December 11, 2024",
    lastUpdated: "December 11, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 4096,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "math", "analysis", "coding"],
    contextComplexity: 5,
    reliability: 4,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "phi-3-5-vision-gh": {
    name: "Phi-3.5 Vision (GitHub)",
    matchingModel: "microsoft/phi-3.5-vision-instruct",
    description:
      "Vision-enabled Phi model for image understanding and analysis.",
    provider: "github-models",
    type: ["text", "image-to-text"],
    knowledgeCutoffDate: "October 2023",
    releaseDate: "August 20, 2024",
    lastUpdated: "August 20, 2024",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 4096,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["vision", "reasoning", "analysis"],
    contextComplexity: 4,
    reliability: 4,
    speed: 4,
    multimodal: true,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "llama-3-2-90b-vision-gh": {
    name: "Llama 3.2 90B Vision (GitHub)",
    matchingModel: "meta/llama-3.2-90b-vision-instruct",
    description:
      "Large multimodal Llama model with vision and audio capabilities.",
    provider: "github-models",
    type: ["text", "image-to-text"],
    knowledgeCutoffDate: "December 2023",
    releaseDate: "September 25, 2024",
    lastUpdated: "September 25, 2024",
    modalities: {
      input: ["text", "image", "audio"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 8192,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "vision", "audio", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    multimodal: true,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "llama-3-1-405b-gh": {
    name: "Meta Llama 3.1 405B (GitHub)",
    matchingModel: "meta/meta-llama-3.1-405b-instruct",
    description:
      "Largest open-source language model with exceptional reasoning capabilities.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "December 2023",
    releaseDate: "July 23, 2024",
    lastUpdated: "July 23, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 32768,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "analysis", "coding", "multilingual"],
    contextComplexity: 5,
    reliability: 5,
    speed: 1,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "deepseek-r1-gh": {
    name: "DeepSeek-R1 (GitHub)",
    matchingModel: "deepseek/deepseek-r1",
    description:
      "Advanced reasoning model with strong mathematical and logical capabilities.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "June 2024",
    releaseDate: "January 20, 2025",
    lastUpdated: "January 20, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 65536,
    maxTokens: 8192,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "math", "analysis", "coding"],
    contextComplexity: 5,
    reliability: 4,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "mistral-large-2411-gh": {
    name: "Mistral Large 24.11 (GitHub)",
    matchingModel: "mistral-ai/mistral-large-2411",
    description:
      "Latest Mistral model with enhanced reasoning and multilingual capabilities.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "September 2024",
    releaseDate: "November 1, 2024",
    lastUpdated: "November 1, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 32768,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "analysis", "multilingual", "coding"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "codestral-2501-gh": {
    name: "Codestral 25.01 (GitHub)",
    matchingModel: "mistral-ai/codestral-2501",
    description:
      "Specialized Mistral model optimized for code generation and programming tasks.",
    provider: "github-models",
    type: ["text", "coding"],
    knowledgeCutoffDate: "March 2024",
    releaseDate: "January 1, 2025",
    lastUpdated: "January 1, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 32000,
    maxTokens: 8192,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["coding", "analysis", "reasoning"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "grok-3-gh": {
    name: "Grok 3 (GitHub)",
    matchingModel: "xai/grok-3",
    description:
      "xAI's flagship model with strong reasoning capabilities and real-time knowledge.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "October 2024",
    releaseDate: "December 9, 2024",
    lastUpdated: "December 9, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 8192,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "analysis", "chat", "general_knowledge"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "grok-3-mini-gh": {
    name: "Grok 3 Mini (GitHub)",
    matchingModel: "xai/grok-3-mini",
    description:
      "Efficient version of Grok 3 optimized for speed while maintaining reasoning capabilities.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "October 2024",
    releaseDate: "December 9, 2024",
    lastUpdated: "December 9, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 8192,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["reasoning", "analysis", "chat"],
    contextComplexity: 3,
    reliability: 4,
    speed: 4,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "command-r-gh": {
    name: "Cohere Command R (GitHub)",
    matchingModel: "cohere/cohere-command-r",
    description:
      "Cohere's conversational model optimized for RAG and tool use.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "March 2024",
    releaseDate: "March 11, 2024",
    lastUpdated: "August 1, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 4096,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["analysis", "summarization", "reasoning"],
    contextComplexity: 3,
    reliability: 4,
    speed: 3,
    includedInRouter: false,
    supportsArtifacts: true,
  },

  "command-r-plus-gh": {
    name: "Cohere Command R+ (GitHub)",
    matchingModel: "cohere/cohere-command-r-plus",
    description:
      "Enhanced version of Command R with improved capabilities for complex workflows.",
    provider: "github-models",
    type: ["text"],
    knowledgeCutoffDate: "March 2024",
    releaseDate: "April 4, 2024",
    lastUpdated: "August 1, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 128000,
    maxTokens: 4096,
    costPer1kInputTokens: 0,
    costPer1kOutputTokens: 0,
    strengths: ["analysis", "reasoning", "summarization"],
    contextComplexity: 4,
    reliability: 4,
    speed: 2,
    includedInRouter: false,
    supportsArtifacts: true,
  },
};
