import type { ModelConfig } from "~/types";

export const googleAiStudioModelConfig: ModelConfig = {
  "gemini-2.5-pro": {
    name: "Gemini 2.5 Pro",
    matchingModel: "gemini-2.5-pro",
    description:
      "Gemini 2.5 Pro is our state-of-the-art thinking model, capable of reasoning over complex problems in code, math, and STEM, as well as analyzing large datasets, codebases, and documents using long context.",
    provider: "google-ai-studio",
    type: ["text"],
    card: "https://www.prompthub.us/models/gemini-2-5-pro",
    strengths: ["coding", "analysis", "math", "multilingual"],
    multimodal: true,
    supportsToolCalls: true,
    supportsSearchGrounding: true,
    supportsCodeExecution: true,
    supportsReasoning: true,
    supportsAttachments: true,
    supportsTemperature: true,
    modalities: {
      input: ["text", "image", "audio", "video", "pdf"],
      output: ["text"],
    },
    knowledgeCutoffDate: "January 2025",
    releaseDate: "March 20, 2025",
    lastUpdated: "June 5, 2025",
    contextWindow: 1048576,
    maxTokens: 65536,
    costPer1kInputTokens: 0.00125,
    costPer1kOutputTokens: 0.01,
    supportsArtifacts: true,
    isFeatured: true,
    isFree: true,
    includedInRouter: true,
    contextComplexity: 5,
    reliability: 5,
    speed: 3,
  },
  "gemini-2.5-flash": {
    name: "Gemini 2.5 Flash",
    matchingModel: "gemini-2.5-flash",
    description:
      "Gemini 2.5 Flash delivers next-gen features and improved capabilities, including superior speed, native tool use, multimodal generation, and a 1M token context window.",
    provider: "google-ai-studio",
    type: ["text"],
    card: "https://www.prompthub.us/models/gemini-2-5-flash",
    strengths: ["coding", "analysis", "math", "multilingual"],
    modalities: {
      input: ["text", "image", "audio", "video", "pdf"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsToolCalls: true,
    supportsCodeExecution: true,
    supportsSearchGrounding: true,
    supportsReasoning: true,
    supportsTemperature: true,
    multimodal: true,
    knowledgeCutoffDate: "January 2025",
    releaseDate: "March 20, 2025",
    lastUpdated: "June 5, 2025",
    contextWindow: 1048576,
    maxTokens: 65536,
    costPer1kInputTokens: 0.0003,
    costPer1kOutputTokens: 0.0025,
    isFeatured: true,
    includedInRouter: true,
    supportsArtifacts: true,
    isFree: true,
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
  },
  "gemini-2.5-flash-lite": {
    name: "Gemini 2.5 Flash Lite",
    matchingModel: "gemini-2.5-flash-lite",
    description:
      "A Gemini 2.5 Flash model optimized for cost efficiency and low latency.",
    provider: "google-ai-studio",
    type: ["text"],
    card: "https://www.prompthub.us/models/gemini-2-5-flash-lite",
    strengths: ["coding", "analysis", "math", "multilingual"],
    modalities: {
      input: ["text", "image", "audio", "video", "pdf"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsToolCalls: true,
    supportsTemperature: true,
    multimodal: true,
    knowledgeCutoffDate: "June 2024",
    releaseDate: "December 11, 2024",
    lastUpdated: "December 11, 2024",
    contextWindow: 1048576,
    maxTokens: 8192,
    costPer1kInputTokens: 0.000075,
    costPer1kOutputTokens: 0.0003,
    supportsArtifacts: true,
    isFree: true,
    contextComplexity: 3,
    reliability: 3,
    speed: 2,
  },
};
