import type { ModelConfig } from "~/types";

export const googleAiStudioModelConfig: ModelConfig = {
  "gemini-2.5-pro": {
    name: "Gemini 2.5 Pro",
    matchingModel: "gemini-2.5-pro",
    description:
      "Gemini 2.5 Pro is our state-of-the-art thinking model, capable of reasoning over complex problems in code, math, and STEM, as well as analyzing large datasets, codebases, and documents using long context.",
    provider: "google-ai-studio",
    type: ["text"],
    card: "https://www.prompthub.us/models/gemini-2-5-pro",
    strengths: ["coding", "analysis", "math", "multilingual"],
    multimodal: false,
    supportsToolCalls: true,
    supportsSearchGrounding: true,
    supportsCodeExecution: true,
    supportsReasoning: true,
    contextWindow: 1000000,
    maxTokens: 65000,
    supportsArtifacts: true,
    isFeatured: true,
    isFree: true,
    includedInRouter: true,
    contextComplexity: 5,
    reliability: 5,
    speed: 3,
  },
  "gemini-2.5-flash": {
    name: "Gemini 2.5 Flash",
    matchingModel: "gemini-2.5-flash",
    description:
      "Gemini 2.5 Flash delivers next-gen features and improved capabilities, including superior speed, native tool use, multimodal generation, and a 1M token context window.",
    provider: "google-ai-studio",
    type: ["text"],
    card: "https://www.prompthub.us/models/gemini-2-5-flash",
    contextWindow: 1048576,
    maxTokens: 63536,
    strengths: ["coding", "analysis", "math", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    speed: 3,
    supportsToolCalls: true,
    supportsCodeExecution: true,
    multimodal: false,
    isFeatured: true,
    includedInRouter: true,
    supportsArtifacts: true,
    supportsSearchGrounding: true,
    isFree: true,
  },
  "gemini-2.5-flash-lite": {
    name: "Gemini 2.5 Flash Lite",
    matchingModel: "gemini-2.5-flash-lite",
    description:
      "A Gemini 2.5 Flash model optimized for cost efficiency and low latency.",
    provider: "google-ai-studio",
    type: ["text"],
    card: "https://www.prompthub.us/models/gemini-2-5-flash-lite",
    strengths: ["coding", "analysis", "math", "multilingual"],
    contextWindow: 1000000,
    maxTokens: 6400,
    supportsToolCalls: true,
    supportsArtifacts: true,
    isFree: true,
    contextComplexity: 3,
    reliability: 3,
    speed: 2,
  },
};
