import type { ModelConfig } from "~/types";

export const groqModelConfig: ModelConfig = {
  "gemma2-9b-it": {
    name: "Groq Gemma 2 9B IT",
    matchingModel: "gemma2-9b-it",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "June 2024",
    releaseDate: "June 27, 2024",
    lastUpdated: "June 27, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    contextWindow: 8192,
    maxTokens: 8192,
    card: "https://huggingface.co/google/gemma-2-9b-it",
    includedInRouter: true,
    costPer1kInputTokens: 0.0002,
    costPer1kOutputTokens: 0.0002,
    speed: 5,
    strengths: ["chat", "general_knowledge"],
    contextComplexity: 3,
    reliability: 3,
    supportsArtifacts: true,
  },
  "qwen-qwq-32b": {
    name: "Groq Qwen QWQ 32B",
    matchingModel: "qwen-qwq-32b",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "September 2024",
    releaseDate: "November 27, 2024",
    lastUpdated: "November 27, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 131072,
    maxTokens: 16384,
    card: "https://huggingface.co/Qwen/QwQ-32B",
    includedInRouter: true,
    costPer1kInputTokens: 0.00029,
    costPer1kOutputTokens: 0.00039,
    speed: 5,
    strengths: ["reasoning", "analysis", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    supportsArtifacts: true,
  },
  "deepseek-r1-distill-qwen-32b": {
    name: "Groq DeepSeek R1 Distill Qwen 32B",
    matchingModel: "deepseek-r1-distill-qwen-32b",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "July 2024",
    releaseDate: "January 20, 2025",
    lastUpdated: "January 20, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 16384,
    card: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
    supportsReasoning: true,
    includedInRouter: true,
    costPer1kInputTokens: 0.0002,
    costPer1kOutputTokens: 0.0003,
    speed: 4,
    strengths: ["reasoning", "analysis"],
    contextComplexity: 4,
    reliability: 4,
    supportsArtifacts: true,
    supportsToolCalls: true,
  },
  "deepseek-r1-distill-llama-70b": {
    name: "Groq DeepSeek R1 Distill Llama 70B",
    matchingModel: "deepseek-r1-distill-llama-70b",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "July 2024",
    releaseDate: "January 20, 2025",
    lastUpdated: "January 20, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 16384,
    card: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    supportsReasoning: true,
    includedInRouter: true,
    costPer1kInputTokens: 0.0002,
    costPer1kOutputTokens: 0.0004,
    speed: 4,
    strengths: ["reasoning", "analysis", "creative"],
    contextComplexity: 4,
    reliability: 4,
    supportsArtifacts: true,
    supportsToolCalls: true,
  },
  "deepseek-r1-distill-llama-70b-specdec": {
    name: "Groq DeepSeek R1 Distill Llama 70B SpecDec",
    matchingModel: "deepseek-r1-distill-llama-70b-specdec",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "July 2024",
    releaseDate: "January 20, 2025",
    lastUpdated: "January 20, 2025",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 128000,
    maxTokens: 16384,
    card: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    supportsReasoning: true,
    includedInRouter: true,
    costPer1kInputTokens: 0.0002,
    costPer1kOutputTokens: 0.0004,
    speed: 4,
    strengths: ["reasoning", "analysis"],
    contextComplexity: 4,
    reliability: 4,
    supportsArtifacts: true,
    supportsToolCalls: true,
  },
  "llama3-70b": {
    name: "Groq Llama 3 70B",
    matchingModel: "llama3-70b-8192-tool-use-preview",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "December 2023",
    releaseDate: "April 18, 2024",
    lastUpdated: "April 18, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    includedInRouter: true,
    contextWindow: 8192,
    maxTokens: 8192,
    costPer1kInputTokens: 0.0003,
    costPer1kOutputTokens: 0.0006,
    speed: 5,
    strengths: ["chat", "analysis", "creative", "general_knowledge"],
    contextComplexity: 4,
    reliability: 4,
    supportsArtifacts: true,
  },
  "llama3-8b": {
    name: "Groq Llama 3 8B",
    matchingModel: "llama3-8b-8192-tool-use-preview",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "December 2023",
    releaseDate: "April 18, 2024",
    lastUpdated: "April 18, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    includedInRouter: true,
    contextWindow: 8192,
    maxTokens: 8192,
    costPer1kInputTokens: 0.00015,
    costPer1kOutputTokens: 0.0003,
    speed: 5,
    strengths: ["chat", "general_knowledge"],
    contextComplexity: 3,
    reliability: 3,
    supportsArtifacts: true,
  },
  "llama-3.3-70b-versatile": {
    name: "Groq Llama 3.3 70B Versatile",
    matchingModel: "llama-3.3-70b-versatile",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "December 2024",
    releaseDate: "December 6, 2024",
    lastUpdated: "December 6, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    card: "https://www.prompthub.us/models/llama-3-3-70b",
    contextWindow: 128000,
    maxTokens: 2048,
    costPer1kInputTokens: 0.00023,
    costPer1kOutputTokens: 0.0004,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "creative",
      "multilingual",
    ],
    contextComplexity: 4,
    reliability: 4,
    speed: 5,
    isFeatured: true,
    includedInRouter: true,
    supportsArtifacts: true,
  },
  "meta-llama/llama-guard-4-12b": {
    name: "Groq Llama Guard 4 12B",
    matchingModel: "meta-llama/llama-guard-4-12b",
    provider: "groq",
    type: ["guardrails"],
    knowledgeCutoffDate: "December 2023",
    releaseDate: "November 27, 2024",
    lastUpdated: "November 27, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    contextWindow: 131072,
    maxTokens: 1024,
    costPer1kInputTokens: 0.00004,
    costPer1kOutputTokens: 0.00004,
    speed: 5,
    contextComplexity: 3,
    reliability: 3,
  },
  "groq-llama-4-scout-17b": {
    name: "Groq Llama 4 Scout 17B",
    matchingModel: "meta-llama/llama-4-scout-17b-16e-instruct",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "December 2024",
    releaseDate: "January 31, 2025",
    lastUpdated: "January 31, 2025",
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    supportsAttachments: true,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    isFeatured: true,
    includedInRouter: true,
    multimodal: true,
    contextWindow: 128000,
    maxTokens: 16384,
    costPer1kInputTokens: 0.0002,
    costPer1kOutputTokens: 0.0004,
    strengths: [
      "chat",
      "general_knowledge",
      "analysis",
      "creative",
      "multilingual",
      "coding",
      "vision",
    ],
    contextComplexity: 4,
    reliability: 4,
    speed: 5,
    supportsArtifacts: true,
  },
  "kimi-k2": {
    name: "Groq Kimi K2",
    matchingModel: "moonshotai/kimi-k2-instruct",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "September 2024",
    releaseDate: "November 27, 2024",
    lastUpdated: "November 27, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    contextWindow: 131072,
    maxTokens: 16384,
    supportsToolCalls: true,
    costPer1kInputTokens: 0.001,
    costPer1kOutputTokens: 0.003,
    includedInRouter: true,
    speed: 4,
    strengths: ["coding", "analysis", "tool_use", "reasoning", "multilingual"],
    contextComplexity: 5,
    reliability: 4,
    description:
      "Kimi K2 is Moonshot AI's state-of-the-art Mixture-of-Experts (MoE) language model with 1 trillion total parameters and 32 billion activated parameters. Designed for agentic intelligence, it excels at tool use, coding, and autonomous problem-solving across diverse domains.",
    supportsReasoning: true,
    supportsArtifacts: true,
    isFeatured: true,
  },
  "llama-3.1-8b-instant": {
    name: "Llama 3.1 8B Instant",
    matchingModel: "llama-3.1-8b-instant",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "December 2023",
    releaseDate: "July 23, 2024",
    lastUpdated: "July 23, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    contextWindow: 131072,
    maxTokens: 8192,
    costPer1kInputTokens: 0.00005,
    costPer1kOutputTokens: 0.00008,
    speed: 5,
    strengths: ["chat", "general_knowledge", "multilingual"],
    contextComplexity: 3,
    reliability: 3,
    includedInRouter: true,
    supportsArtifacts: true,
  },
  "llama-guard-3-8b": {
    name: "Llama Guard 3 8B",
    matchingModel: "llama-guard-3-8b",
    provider: "groq",
    type: ["guardrails"],
    knowledgeCutoffDate: "December 2023",
    releaseDate: "August 1, 2024",
    lastUpdated: "August 1, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: false,
    supportsReasoning: false,
    supportsToolCalls: false,
    contextWindow: 8192,
    maxTokens: 8192,
    costPer1kInputTokens: 0.0001,
    costPer1kOutputTokens: 0.0001,
    speed: 5,
    strengths: ["analysis"],
    contextComplexity: 2,
    reliability: 4,
    includedInRouter: false,
    supportsArtifacts: false,
  },
  "mistral-saba-24b": {
    name: "Mistral SABA 24B",
    matchingModel: "mistral-saba-24b",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "October 2024",
    releaseDate: "December 11, 2024",
    lastUpdated: "December 11, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 32768,
    maxTokens: 8192,
    costPer1kInputTokens: 0.0002,
    costPer1kOutputTokens: 0.0006,
    speed: 4,
    strengths: ["reasoning", "analysis", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    includedInRouter: true,
    supportsArtifacts: true,
  },
  "mixtral-8x7b-32768": {
    name: "Mixtral 8x7B Instruct",
    matchingModel: "mixtral-8x7b-32768",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "September 2023",
    releaseDate: "December 11, 2023",
    lastUpdated: "December 11, 2023",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 32768,
    maxTokens: 32768,
    costPer1kInputTokens: 0.00024,
    costPer1kOutputTokens: 0.00024,
    speed: 4,
    strengths: ["reasoning", "analysis", "multilingual", "coding"],
    contextComplexity: 4,
    reliability: 4,
    includedInRouter: true,
    supportsArtifacts: true,
  },
  "gemma-2-2b-it": {
    name: "Gemma 2 2B IT",
    matchingModel: "gemma-2-2b-it",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "June 2024",
    releaseDate: "June 27, 2024",
    lastUpdated: "June 27, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: false,
    supportsToolCalls: true,
    contextWindow: 8192,
    maxTokens: 8192,
    costPer1kInputTokens: 0.0001,
    costPer1kOutputTokens: 0.0001,
    speed: 5,
    strengths: ["chat", "general_knowledge"],
    contextComplexity: 2,
    reliability: 3,
    includedInRouter: true,
    supportsArtifacts: true,
  },
  "gemma-2-27b-it": {
    name: "Gemma 2 27B IT",
    matchingModel: "gemma-2-27b-it",
    provider: "groq",
    type: ["text"],
    knowledgeCutoffDate: "June 2024",
    releaseDate: "June 27, 2024",
    lastUpdated: "June 27, 2024",
    modalities: {
      input: ["text"],
      output: ["text"],
    },
    supportsAttachments: false,
    supportsTemperature: true,
    supportsReasoning: true,
    supportsToolCalls: true,
    contextWindow: 8192,
    maxTokens: 8192,
    costPer1kInputTokens: 0.0002,
    costPer1kOutputTokens: 0.0002,
    speed: 4,
    strengths: ["reasoning", "analysis", "multilingual"],
    contextComplexity: 3,
    reliability: 4,
    includedInRouter: true,
    supportsArtifacts: true,
  },
};
