import type { ModelConfig } from "../../types";

export const groqModelConfig: ModelConfig = {
  "gemma2-9b-it": {
    name: "Groq Gemma 2 9B IT",
    matchingModel: "gemma2-9b-it",
    provider: "groq",
    type: ["text"],
    contextWindow: 8192,
    card: "https://huggingface.co/google/gemma-2-9b-it",
  },
  "qwen-qwq-32b": {
    name: "Groq Qwen QWQ 32B",
    matchingModel: "qwen-qwq-32b",
    provider: "groq",
    type: ["text"],
    contextWindow: 128000,
    card: "https://huggingface.co/Qwen/QwQ-32B",
  },
  "deepseek-r1-distill-qwen-32b": {
    name: "Groq DeepSeek R1 Distill Qwen 32B",
    matchingModel: "deepseek-r1-distill-qwen-32b",
    provider: "groq",
    type: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    card: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
    hasThinking: true,
  },
  "deepseek-r1-distill-llama-70b": {
    name: "Groq DeepSeek R1 Distill Llama 70B",
    matchingModel: "deepseek-r1-distill-llama-70b",
    provider: "groq",
    type: ["text"],
    contextWindow: 128000,
    card: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    hasThinking: true,
  },
  "deepseek-r1-distill-llama-70b-specdec": {
    name: "Groq DeepSeek R1 Distill Llama 70B SpecDec",
    matchingModel: "deepseek-r1-distill-llama-70b-specdec",
    provider: "groq",
    type: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    card: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    hasThinking: true,
  },
  "llama3-groq-70b": {
    name: "Groq Llama 3 70B",
    matchingModel: "llama3-groq-70b-8192-tool-use-preview",
    provider: "groq",
    type: ["text"],
    supportsFunctions: true,
  },
  "llama3-groq-8b": {
    name: "Groq Llama 3 8B",
    matchingModel: "llama3-groq-8b-8192-tool-use-preview",
    provider: "groq",
    type: ["text"],
    supportsFunctions: true,
  },
  "llama-3.3-70b-versatile": {
    name: "Groq Llama 3.3 70B Versatile",
    matchingModel: "llama-3.3-70b-versatile",
    provider: "groq",
    type: ["text"],
    card: "https://www.prompthub.us/models/llama-3-3-70b",
    contextWindow: 128000,
    maxTokens: 2048,
    costPer1kInputTokens: 0.00023,
    costPer1kOutputTokens: 0.0004,
    strengths: ["chat", "analysis", "creative", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    speed: 4,
    isFeatured: true,
    includedInRouter: true,
  },
  "llama-3.3-70b-specdec": {
    name: "Groq Llama 3.3 70B SpecDec",
    matchingModel: "llama-3.3-70b-specdec",
    provider: "groq",
    type: ["text"],
    card: "https://www.prompthub.us/models/llama-3-3-70b",
    contextWindow: 128000,
    maxTokens: 2048,
    costPer1kInputTokens: 0.00023,
    costPer1kOutputTokens: 0.0004,
    strengths: ["chat", "analysis", "creative", "multilingual"],
    contextComplexity: 4,
    reliability: 4,
    speed: 5,
    isFeatured: true,
    includedInRouter: true,
  },
  "llama-guard-3-8b": {
    name: "Groq Llama Guard 3 8B",
    matchingModel: "llama-guard-3-8b",
    provider: "groq",
    type: ["guardrails"],
  },
  "groq-llama-4-scout-17b": {
    name: "Groq Llama 4 Scout 17B",
    matchingModel: "meta-llama/llama-4-scout-17b-16e-instruct",
    provider: "groq",
    type: ["text"],
    isFeatured: true,
    includedInRouter: true,
    multimodal: true,
    contextWindow: 10000000,
    strengths: ["chat", "analysis", "creative", "multilingual", "coding"],
    contextComplexity: 4,
    reliability: 4,
    speed: 5,
  },
};
