import type { ModelConfig } from "~/types";

export const openrouterModelConfig: ModelConfig = {
	"openai/gpt-oss-120b": {
		name: "GPT OSS 120B",
		matchingModel: "openai/gpt-oss-120b",
		provider: "openrouter",
		type: ["text"],
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: ["reasoning", "analysis", "coding", "multilingual"],
		contextComplexity: 5,
		reliability: 4,
		speed: 2,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"openai/gpt-4.1-mini": {
		name: "GPT-4.1 Mini",
		matchingModel: "openai/gpt-4.1-mini",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: false,
		supportsToolCalls: true,
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.0004,
		costPer1kOutputTokens: 0.0016,
		strengths: ["coding", "analysis", "chat", "vision", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"openai/o4-mini": {
		name: "o4 Mini",
		matchingModel: "openai/o4-mini",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "June 2024",
		releaseDate: "April 16, 2025",
		lastUpdated: "April 16, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 100000,
		costPer1kInputTokens: 0.0011,
		costPer1kOutputTokens: 0.0044,
		strengths: ["reasoning", "math", "analysis", "coding"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"openai/gpt-5-nano": {
		name: "GPT-5 Nano",
		matchingModel: "openai/gpt-5-nano",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "October 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0004,
		strengths: ["reasoning", "coding", "analysis", "vision"],
		contextComplexity: 4,
		reliability: 4,
		speed: 5,
		multimodal: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"openai/gpt-4o-mini-openrouter": {
		name: "GPT-4o Mini (OpenRouter)",
		matchingModel: "openai/gpt-4o-mini",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 18, 2024",
		lastUpdated: "July 18, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: false,
		supportsToolCalls: true,
		contextWindow: 128000,
		maxTokens: 16384,
		costPer1kInputTokens: 0.00015,
		costPer1kOutputTokens: 0.0006,
		strengths: ["chat", "analysis", "vision", "coding"],
		contextComplexity: 3,
		reliability: 4,
		speed: 5,
		multimodal: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"openai/gpt-5": {
		name: "GPT-5",
		matchingModel: "openai/gpt-5",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "October 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		strengths: ["reasoning", "coding", "analysis", "creative", "vision"],
		contextComplexity: 5,
		reliability: 5,
		speed: 2,
		multimodal: true,
		isFeatured: true,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"openai/gpt-oss-20b": {
		name: "GPT OSS 20B",
		matchingModel: "openai/gpt-oss-20b",
		provider: "openrouter",
		type: ["text"],
		releaseDate: "August 5, 2025",
		lastUpdated: "August 5, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00005,
		costPer1kOutputTokens: 0.0002,
		strengths: ["reasoning", "analysis", "coding"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"openai/gpt-4.1": {
		name: "GPT-4.1",
		matchingModel: "openai/gpt-4.1",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "April 2024",
		releaseDate: "April 14, 2025",
		lastUpdated: "April 14, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: false,
		supportsToolCalls: true,
		contextWindow: 1047576,
		maxTokens: 32768,
		costPer1kInputTokens: 0.002,
		costPer1kOutputTokens: 0.008,
		strengths: ["coding", "analysis", "creative", "vision", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		multimodal: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"openai/gpt-5-mini": {
		name: "GPT-5 Mini",
		matchingModel: "openai/gpt-5-mini",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "October 2024",
		releaseDate: "August 7, 2025",
		lastUpdated: "August 7, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 400000,
		maxTokens: 128000,
		costPer1kInputTokens: 0.00025,
		costPer1kOutputTokens: 0.002,
		strengths: ["reasoning", "coding", "analysis", "vision"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"deepseek/deepseek-r1-free": {
		name: "DeepSeek R1 (free)",
		matchingModel: "deepseek/deepseek-r1:free",
		provider: "openrouter",
		type: ["text"],
		knowledgeCutoffDate: "January 2025",
		releaseDate: "January 20, 2025",
		lastUpdated: "January 20, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		strengths: ["reasoning", "math", "analysis", "coding"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		isFree: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"deepseek/deepseek-r1-0528-free": {
		name: "DeepSeek R1 0528 (free)",
		matchingModel: "deepseek/deepseek-r1-0528:free",
		provider: "openrouter",
		type: ["text"],
		knowledgeCutoffDate: "May 2025",
		releaseDate: "May 28, 2025",
		lastUpdated: "May 28, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 163840,
		maxTokens: 163840,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		strengths: ["reasoning", "math", "analysis", "coding"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		isFree: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"anthropic/claude-sonnet-4": {
		name: "Claude Sonnet 4",
		matchingModel: "anthropic/claude-4-sonnet-20250522",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["reasoning", "analysis", "creative", "vision", "coding"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		isFeatured: true,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"anthropic/claude-opus-4": {
		name: "Claude Opus 4",
		matchingModel: "anthropic/claude-opus-4",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "March 2025",
		releaseDate: "May 22, 2025",
		lastUpdated: "May 22, 2025",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 32000,
		costPer1kInputTokens: 0.015,
		costPer1kOutputTokens: 0.075,
		strengths: ["reasoning", "analysis", "creative", "vision", "coding"],
		contextComplexity: 5,
		reliability: 5,
		speed: 2,
		multimodal: true,
		isFeatured: true,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"anthropic/claude-haiku-3.5": {
		name: "Claude Haiku 3.5",
		matchingModel: "anthropic/claude-3.5-haiku",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "July 2024",
		releaseDate: "October 22, 2024",
		lastUpdated: "October 22, 2024",
		modalities: {
			input: ["text", "image"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: false,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0008,
		costPer1kOutputTokens: 0.004,
		strengths: ["chat", "analysis", "vision"],
		contextComplexity: 3,
		reliability: 4,
		speed: 5,
		multimodal: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"x-ai/grok-3": {
		name: "Grok 3",
		matchingModel: "x-ai/grok-3",
		provider: "openrouter",
		type: ["text"],
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsReasoning: false,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.003,
		costPer1kOutputTokens: 0.015,
		strengths: ["reasoning", "analysis", "chat", "general_knowledge"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"x-ai/grok-3-mini": {
		name: "Grok 3 Mini",
		matchingModel: "x-ai/grok-3-mini",
		provider: "openrouter",
		type: ["text"],
		knowledgeCutoffDate: "November 2024",
		releaseDate: "February 17, 2025",
		lastUpdated: "February 17, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 8192,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0005,
		strengths: ["reasoning", "analysis", "chat"],
		contextComplexity: 3,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"moonshotai/kimi-k2-openrouter": {
		name: "Kimi K2 (OpenRouter)",
		matchingModel: "moonshotai/kimi-k2",
		provider: "openrouter",
		type: ["text"],
		knowledgeCutoffDate: "October 2024",
		releaseDate: "July 11, 2025",
		lastUpdated: "July 11, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsReasoning: false,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 32768,
		costPer1kInputTokens: 0.00055,
		costPer1kOutputTokens: 0.0022,
		strengths: ["coding", "analysis", "multilingual", "tool_use"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		includedInRouter: true,
		supportsArtifacts: true,
		description:
			"Kimi K2 is Moonshot AI's state-of-the-art Mixture-of-Experts (MoE) language model with 1 trillion total parameters and 32 billion activated parameters.",
	},

	"google/gemini-2.5-pro": {
		name: "Gemini 2.5 Pro",
		matchingModel: "google/gemini-2.5-pro",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "January 2025",
		releaseDate: "March 20, 2025",
		lastUpdated: "June 5, 2025",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.00125,
		costPer1kOutputTokens: 0.01,
		strengths: ["reasoning", "analysis", "vision", "audio", "multilingual"],
		contextComplexity: 5,
		reliability: 5,
		speed: 3,
		multimodal: true,
		includedInRouter: false,
		supportsArtifacts: true,
	},

	"google/gemini-2.5-flash": {
		name: "Gemini 2.5 Flash",
		matchingModel: "google/gemini-2.5-flash",
		provider: "openrouter",
		type: ["text", "image-to-text"],
		knowledgeCutoffDate: "January 2025",
		releaseDate: "July 17, 2025",
		lastUpdated: "July 17, 2025",
		modalities: {
			input: ["text", "image", "audio", "video"],
			output: ["text"],
		},
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 1048576,
		maxTokens: 65536,
		costPer1kInputTokens: 0.0003,
		costPer1kOutputTokens: 0.0025,
		strengths: ["reasoning", "analysis", "vision", "audio", "multilingual"],
		contextComplexity: 4,
		reliability: 4,
		speed: 4,
		multimodal: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"meta-llama/llama-3.3-70b-free": {
		name: "Llama 3.3 70B Instruct (free)",
		matchingModel: "meta-llama/llama-3.3-70b-instruct:free",
		provider: "openrouter",
		type: ["text"],
		knowledgeCutoffDate: "December 2024",
		releaseDate: "December 6, 2024",
		lastUpdated: "December 6, 2024",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsReasoning: false,
		supportsToolCalls: true,
		contextWindow: 65536,
		maxTokens: 65536,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		strengths: ["chat", "general_knowledge", "analysis", "multilingual"],
		contextComplexity: 3,
		reliability: 4,
		speed: 4,
		isFree: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"qwen/qwen3-coder-free": {
		name: "Qwen3 Coder 480B A35B (free)",
		matchingModel: "qwen/qwen3-coder:free",
		provider: "openrouter",
		type: ["text", "coding"],
		knowledgeCutoffDate: "April 2025",
		releaseDate: "July 23, 2025",
		lastUpdated: "July 23, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsReasoning: false,
		supportsToolCalls: true,
		contextWindow: 262144,
		maxTokens: 66536,
		costPer1kInputTokens: 0,
		costPer1kOutputTokens: 0,
		strengths: ["coding", "analysis", "reasoning"],
		contextComplexity: 5,
		reliability: 4,
		speed: 3,
		isFree: true,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	"mistralai/devstral-small": {
		name: "Devstral Small 1.1",
		matchingModel: "mistralai/devstral-small-2507",
		provider: "openrouter",
		type: ["text", "coding"],
		knowledgeCutoffDate: "May 2025",
		releaseDate: "July 10, 2025",
		lastUpdated: "July 10, 2025",
		modalities: {
			input: ["text"],
			output: ["text"],
		},
		supportsAttachments: false,
		supportsTemperature: true,
		supportsReasoning: false,
		supportsToolCalls: true,
		contextWindow: 131072,
		maxTokens: 131072,
		costPer1kInputTokens: 0.0001,
		costPer1kOutputTokens: 0.0003,
		strengths: ["coding", "analysis", "agents"],
		contextComplexity: 3,
		reliability: 4,
		speed: 4,
		includedInRouter: true,
		supportsArtifacts: true,
	},

	auto: {
		name: "OpenRouter Auto",
		description:
			"OpenRouter's auto model, will select the best model for the task.",
		matchingModel: "openrouter/auto",
		provider: "openrouter",
		type: ["text"],
		supportsAttachments: true,
		supportsTemperature: true,
		supportsReasoning: true,
		supportsToolCalls: true,
		contextWindow: 200000,
		maxTokens: 64000,
		strengths: ["general_knowledge", "analysis", "reasoning"],
		contextComplexity: 4,
		reliability: 4,
		speed: 3,
		includedInRouter: true,
	},
};
